### ISSUE TITLE
Any plans to add https://github.com/NVIDIA/DALI support?

### ISSUE THREAD

**Issue by dkozlov** [albumentations-team/albumentations#100]
Hi, any plans to add https://github.com/NVIDIA/DALI support?

**Comment by BloodAxe** [comment]
From my perspective, most probably not. DALI has they own augmentation pipeline which is not compatible with albumentations API. Therefore support of DALI would require to introduce breaking changes in albumentations with doubtful outcome.

**Comment by Data-drone** [comment]
any progress @albu

**Comment by albu** [comment]
sorry, no progress here

**Comment by vfdev-5** [comment]
We have some interesting code to port in data augs libs like albumentations

https://github.com/pytorch/ignite/blob/f02a91a28153e08092dbb625472e0211f642923d/ignite/contrib/engines/dali.py#L27

and 

https://github.com/pytorch/ignite/pull/493#issuecomment-581778218

Maybe we can try to build something like that here:
- `ComposeOps`
- generalized `TransformPipeline`

Certainly it wont support all your augs, only DALI ones, but this could help user to avoid copying common stuff. 
 
@albu @ternaus what do you think ?

**Comment by dnola** [comment]
I have an additional example of the usage here - it really brings DALI usage inline with Albumentations/PyTorch Compose usage, so would be very cool to have integrated

Usability wise this code is a super handy way of dropping GPU acceleration as a nearly 'drop in' replacement to existing PyTorch/Albumentations workloads - we just need to find a home for it.

Take a look! Here is another Colab:

https://colab.research.google.com/drive/1XDRzDeIeteTPyzYbZp2XWjKtUWMLXqcg

**Comment by ternaus** [comment]
No plans to support DALI
