### ISSUE TITLE
Undefined behaviour of albumentations.Perspective()

### ISSUE THREAD

**Issue by enaskopelja** [albumentations-team/albumentations#1001]
## 🐛 Bug

It happens on rare occasions that `albumentations.Perspective()` returns a completely distorted image.
The bug in the example code is caught because the keypoints get transformed outside the image plane (despite the `fit_output` argument being set), I suspect that that is not the only time such behaviour arises.  

## To Reproduce

Run the following code:
__Edited__: added random seeding as instructed in #1000

```python
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import albumentations as A
import cv2
import random

random.seed(42)
np.random.seed(42)


perspective = A.Compose([
    A.Perspective(
        pad_mode=cv2.BORDER_CONSTANT,
        fit_output=True,
        always_apply=True
    )
], keypoint_params=A.KeypointParams(format='xy')
)


def apply(
        image: np.ndarray,
        keypoints: np.ndarray,
):
    augmented = perspective(
        image=image,
        keypoints=keypoints
    )

    return augmented['image'], augmented['keypoints']


def plot(
        title: str,
        image: np.ndarray,
        keypoints: np.ndarray,
):
    plt.title(title)
    plt.imshow(image)
    plt.scatter(*zip(*keypoints))
    plt.xticks([])
    plt.yticks([])
    plt.savefig(f"{title}.png")
    plt.cla()


if __name__ == '__main__':
    image = np.ones((126, 224, 3))
    keypoints = np.array(
        [
            [11, 8],
            [14, 115],
            [196, 114],
            [201, 13]
        ]
    )

    plot(
        title="Input",
        image=image,
        keypoints=keypoints,
    )

    # Run until distortion  
    for _ in tqdm(range(315505)):
        augmented_image, augmented_keypoints = apply(
            image=image,
            keypoints=keypoints
        )

    plot(
        title="Result",
        image=augmented_image,
        keypoints=augmented_keypoints,
    )
```

## Example outputs for different random seeds:
Otherwise, see my [example input](https://drive.google.com/uc?id=1BC62XGGcjXJB1C6uVgmE0zTQ-n42AWj5), [expected](https://drive.google.com/uc?id=1j5qIRGECYBCtgkfe_P8XTbdOmuGiWRGS) (and most common) output and two examples of distorted output: [(1)](https://drive.google.com/uc?id=1Iu_DjpWXFTZuWu1hXeoxr-K3uNCPPNCF), [(2)](https://drive.google.com/uc?id=1dq46LuUcV2u-3o6556EgKRvWJePQOuXr). 

## Expected behaviour:
Something like [this](https://drive.google.com/uc?id=1j5qIRGECYBCtgkfe_P8XTbdOmuGiWRGS). 

## Environment:
Albumentations version: `1.0.3`
Python version: `3.9.6`
OS (e.g., Linux): `macOS Big Sur 11.4`
How you installed albumentations: `pip`

**Comment by Dipet** [comment]
It is because `Perspective` uses `np.random`. This behavior will be changed in the future.
At this time, you must also set `np.random.seed(seed)` for reproducibility.

**Comment by eugen-vusak** [comment]
Any progress on this?
