### ISSUE TITLE
How to use 'RandomScale()'

### ISSUE THREAD

**Issue by likyoo** [albumentations-team/albumentations#1002]
When I use "RandomScale" for multi-scale training, I get different image_size within one batch (,it doesn't work)... How do I use "RandomScale" correctly ?

**Comment by Dipet** [comment]
RandomScale resizes an image by a randomly selected factor.
To get a batch of images with the same image shapes try to add after `RandomScale` `Resize` transform or some crop transform.

**Comment by likyoo** [comment]
RandomScale + Resize == NoOp ?
RandomScale + Crop == RandomResizedCrop ?

**Comment by Dipet** [comment]
`RandomScale + Resize == NoOp ?` - nope, it's more like [Downscale](https://albumentations.ai/docs/api_reference/full_reference/#albumentations.augmentations.transforms.Downscale)
`RandomScale + Crop == RandomResizedCrop ?` - yes, looks the same.

**Comment by likyoo** [comment]
thx!
