### ISSUE TITLE
AssertionError: RandomCropNearBBox requires ['cropping_bbox'] When using RandomCropNearBBox

### ISSUE THREAD

**Issue by JingyuWu-ZJU** [albumentations-team/albumentations#1007]
## To Reproduce

1.When i use RandomCropNearBBox, the error comes. if there is any way to solve the problem? Would you please give me an example to use RandomCropNearBBox?

transform = A.Compose([
        A.RandomCropNearBBox()],
        bbox_params=A.BboxParams(format='coco', label_fields=['category_ids']),
    )   
transformed = transform(image=img, category_ids=category,bboxes = bbox)
## Environment

 - Albumentations version (e.g., 0.1.8)
 - Python version (e.g., 3.7): 3.7
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip 
 - Any other relevant information:

**Comment by Dipet** [comment]
Try this example:
```python
import random
import numpy as np
import albumentations as A

img = np.random.randint(0, 256, [100, 100, 3], dtype=np.uint8)
bboxes = [
    [0, 0, 10, 10, 0],
    [30, 30, 40, 40, 0],
    [70, 70, 99, 99, 0]
]

transforms = A.Compose([A.RandomCropNearBBox()], bbox_params=A.BboxParams("pascal_voc"))
res = transforms(image=img, bboxes=bboxes, cropping_bbox=random.choice(bboxes))
print(res["image"].shape, bboxes)
```
