### ISSUE TITLE
PiecewiseAffine generate wrong bounding boxes.

### ISSUE THREAD

**Issue by MichaelMonashev** [albumentations-team/albumentations#1009]
## 🐛 Bug

Transform generate wrong bounding boxes.

## To Reproduce

PiecewiseAffine(p=1.0, scale=(0.03, 0.05), nb_rows=4, nb_cols=4, interpolation=3, cval=0, mode='constant')

## Expected behavior

Bboxes cover whole objects.
But after PiecewiseAffine trasform some parts of objects staing out of bounding boxes.

## Environment

 - albumentations 1.0.3
 - Python 3.8.10
 - Ubuntu 20.04
 - pip3 install -U albumentations

## Additional context

https://opendatascience.slack.com/archives/CGHGA0DQC/p1631195117041600

**Comment by ternaus** [comment]
FIxed: https://explore.albumentations.ai/transform/PiecewiseAffine
