### ISSUE TITLE
Imagefolder with albumentations

### ISSUE THREAD

**Issue by abaqusstudent** [albumentations-team/albumentations#1010]
## 🐛 Bug

I am trying to use pytorch inbuilt image folder with albumentations, but I cant seem to get it to work.
I see a related issue here: https://github.com/albumentations-team/albumentations/issues/879 and I am trying to use the same style, but it seems to error out.

## To Reproduce

So, I have this from the issue pointed above:

```
class Transforms:
    def __init__(self, transforms: A.Compose):
        self.transforms = transforms

    def __call__(self, img, *args, **kwargs):
        return self.transforms(image=np.array(img))
```

then, I do in pytorch:

```
traindir=/some/dir/with/images'
trainset = datasets.ImageFolder(traindir,transform=Transforms(transforms=[A.Resize(32 , 32)]))
```

and I get thrown:

```
    return self.transforms(image=np.array(img))
TypeError: 'list' object is not callable
```

Obviously, I am not getting it! 
A working example would be REALLY useful.

## Expected behavior

Should work with imagefolder from pytorch.

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

## Additional context

PS: using a custom dataloader is NOT an option in my case. I need to work with ImageFolder only :(

**Comment by abaqusstudent** [comment]
Just as a follow up, when I use:

```
traindir=/some/dir/with/images'
trainset = datasets.ImageFolder(traindir,transform=Transforms(transforms=A.Resize(32 , 32)))
```

I get:

```
RuntimeError: Given groups=1, weight of size [16, 3, 3, 3], expected input[1024, 32, 32, 3] to have 3 channels, but got 32 channels instead
```

**Comment by Dipet** [comment]
Just add a `albumentations.ToTensorV2` as the last transform into your pipeline to switch channel shape.
https://albumentations.ai/docs/api_reference/pytorch/transforms/#albumentations.pytorch.transforms.ToTensorV2

**Comment by espiriki** [comment]
> A.Resize(32 , 32)]

Hello!

I was having the same error as the OP with the same code, and from Google I've got here

But I'm having a different error in my code (I do have the ToTensorV2 in my pipeline):

`TypeError: forward() got an unexpected keyword argument 'image'`

PyTorch version: 1.12.1
Albumentation version: 1.3.0

Sample code:
`base_augmentations = [
    A.Rotate(
        crop_border=True, p=1.0),
    keep_aspect_ratio.PadToMaintainAR(aspect_ratio=AR_INPUT),
    A.Resize(height=HEIGHT, width=WIDTH, interpolation=cv2.INTER_CUBIC),
    A.Flip(p=1.0),
    A.RandomBrightnessContrast(p=1.0),
    A.Perspective(p=1.0),
    A.Sharpen(p=1.0),
    album_pytorch.transforms.ToTensorV2()]


class Transforms:
    def __init__(self, transforms: A.Compose):
        self.transforms = transforms

    def __call__(self, img, *args, **kwargs):
        return self.transforms(image=np.array(img))


train_data = torchvision.datasets.ImageFolder(
    root=TRAIN_DATA_PATH, transform=Transforms(transforms=A.Compose(base_augmentations)))`

**Comment by espiriki** [comment]
> Just add a `albumentations.ToTensorV2` as the last transform into your pipeline to switch channel shape. https://albumentations.ai/docs/api_reference/pytorch/transforms/#albumentations.pytorch.transforms.ToTensorV2

Hello!

I was having the same error as the OP with the same code, and from Google I've got here

But I'm having a different error in my code (I do have the ToTensorV2 in my pipeline):

TypeError: forward() got an unexpected keyword argument 'image'

PyTorch version: 1.12.1
Albumentation version: 1.3.0

Sample code:
`base_augmentations = [
A.Rotate(
crop_border=True, p=1.0),
keep_aspect_ratio.PadToMaintainAR(aspect_ratio=AR_INPUT),
A.Resize(height=HEIGHT, width=WIDTH, interpolation=cv2.INTER_CUBIC),
A.Flip(p=1.0),
A.RandomBrightnessContrast(p=1.0),
A.Perspective(p=1.0),
A.Sharpen(p=1.0),
album_pytorch.transforms.ToTensorV2()]

class Transforms:
def init(self, transforms: A.Compose):
self.transforms = transforms

def __call__(self, img, *args, **kwargs):
    return self.transforms(image=np.array(img))
train_data = torchvision.datasets.ImageFolder(
root=TRAIN_DATA_PATH, transform=Transforms(transforms=A.Compose(base_augmentations)))`
