### ISSUE TITLE
Affine transformation handles `scale` tuple incorrectly

### ISSUE THREAD

**Issue by stefanistrate** [albumentations-team/albumentations#1011]
## 🐛 Bug

I'd like to use the [`Affine` transformation](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.Affine) for a random zoom-in/zoom-out behaviour. According to the documentation, when passing a tuple to the `scale` argument, the scaling factor should be the same across the `x` and `y` axes:

> If a tuple (a, b), then a value will be uniformly sampled per image from the interval [a, b]. That value will be used identically for both x- and y-axis.

However, that's not the case:

<img width="1233" alt="Screenshot 2021-09-13 at 08 50 53" src="https://user-images.githubusercontent.com/3457859/133046593-2426178b-d2dc-4010-b370-ae1ab7d7a3c1.png">

## To Reproduce

1. Run an image through the following transformation:
```
albumentations.Affine(scale=(0.5, 2), p=1)
```

## Expected behavior

The sampled scaling factor should be the same for the `x` and `y` axes. As you can see in the image above, that's not the case.

I believe the cause of this bug comes from [this line](https://github.com/albumentations-team/albumentations/blob/162dc0657c065a64cd0cc795583598df88b6441b/albumentations/augmentations/geometric/transforms.py#L548). That function doesn't seem to handle `Sequence[float]` at all.

## Environment

 - Albumentations version (e.g., 0.1.8): 1.0.3
 - Python version (e.g., 3.7): 3.9.7
 - OS (e.g., Linux): macOS
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

**Comment by Dipet** [comment]
No, this line works correctly.
This is a documentation problem.
In this case we need to change description into this ` That **the same range** will be used for both x- and y-axis.`
And I think we need to add the `keep_ratio` argument to keep the aspect ratio of the image.
