### ISSUE TITLE
Augmenting keypoints w/o image

### ISSUE THREAD

**Issue by AvivSham** [albumentations-team/albumentations#1021]
Sorry in advance if this is not the right place/tag to task this.
I'm working on the problem in which the input is pose keypoints without the image. Is it possible to augment the keypoints only? according to the API we need to pass both image and keypoints. 
i.e.
`transformed = transform(image=image, keypoints=keypoints)`

thanks in advance!

**Comment by Dipet** [comment]
The library is designed to augment images, for this reason, an image is necessary 
You can try calling `transform.apply_to_keypoints` directly, providing the keypoitns in albumentations format, but you also need to generate all needed params before the call. You can see how to get all needed params [there](https://github.com/albumentations-team/albumentations/blob/master/albumentations/core/transforms_interface.py#L81).

**Comment by AvivSham** [comment]
Hi @Dipet thank you for your response.
Can you be more specific on what should be passed to `transform.apply_to_keypoints` please?

I tried to define transformation as follow:
```
transform = A.Compose(
    [A.HorizontalFlip(p=1)], 
    keypoint_params=A.KeypointParams(format='xy')
)
```
and then tried to call `transform.apply_to_keypoints' but it turns out that the object does not have this method.

**Comment by Dipet** [comment]
Oh, no, library has too many logical bindings to `np.ndarray` to work correctly with all augs without an image.

But you can work with simple augs like this:
```python
import random
import albumentations as A

image_height = 100
image_width = 100
image_size = image_height, image_width
keypoints = [
    [0, 0, 0, 0],
    [10, 10, 0, 0]
]

augs = [
    A.HorizontalFlip(p=1),
]

for aug in augs:
    if random.random() > aug.p:
        continue
    keypoints = aug.apply_to_keypoints(keypoints, rows=image_height, cols=image_width)
print(keypoints)
```

**Comment by AvivSham** [comment]
ohhhh I see. so I can't use `Compose` obj directly!

**Comment by BloodAxe** [comment]
You can use Compose directly but you have to pass an image (even if it's dummy one). 
The flip operation from your example does not make sense without an image, since it needs to know the dimensions of an image, and it assumes keypoint coordinates are given in pixel space. E,g keypoint with coordinates `(1,2)`  on the image of `(512, 512)` pixels after flip will have coordinates `(512 - 1, 2)`.  Hope this clarifies why we need image to be present.

**Comment by AvivSham** [comment]
@BloodAxe I'm sorry but still it does not make sense to me. let's say I have a model which acts on the pose keypoints space instead of the image space and I want to apply augmentation to it. I want to be able to compose augmentations and apply them on the keypoints without passing dummy image (as it will be more computationally costing).
So in my case (which is without passing a dummy image) I need to iterate over list of augmentation objects and apply them on the keypoints.

I think this could be a useful feature.

**Comment by AvivSham** [comment]
BTW @Dipet is it possible to pass the keypoints as `(x,y)` format, from what I see you pass them as `(x,y,angle,scale)` if that is not possible I guess that for 2D pose estimation I can manually pad the keypoints with zeros for the scale and angle.

**Comment by BloodAxe** [comment]
Image is a first-class citizen in Albumentations and all transformation that supports additional targets like keypoints or boxes assuming they are in the pixel-space. While you're trying to work on `pose keypoints space` instead, I don't see a fit here.

Mind sharing how the original keypoints look like, what augmentations you plan to use and how expected augmented keypoints should look like?

**Comment by AvivSham** [comment]
@BloodAxe I'm sure you do not understand me correctly. 
Take as example the dog keypoints you provide [here](https://albumentations.ai/docs/examples/example_keypoints/) and I want to apply Horizontal / Vertical augmentation. I guess that if I pass dummy image some operations occur on this image which are redundant since it's a dummy one and I won't use it.

I think that @Dipet understood what I mean.
