### ISSUE TITLE
Ensure input image for A.Compose is continuous 

### ISSUE THREAD

**Issue by BloodAxe** [albumentations-team/albumentations#1025]
## Enhancement

A discussion in #614 revealed a good place for improvement - we should ensure that input image is continuous upon start of the augmentation pipeline. This could be implemented by adding `image = np.ascontiguousarray(image)` to image and mask targets.

A proposed place to add this call - somewhere at the beginning of `A.Compose.__call__`.

**Comment by Dipet** [comment]
I think we need to call `np.ascontiguousarray` at the beginning of `A.Compose.__call__` and after each call of `apply_with_params`, to be sure that we get the valid image after each transform. Because we have non contiguousarray array after channel shuffle.

**Comment by ternaus** [comment]
Fixed
