### ISSUE TITLE
[FR] Grayscale to RGB

### ISSUE THREAD

**Issue by hoangtnm** [albumentations-team/albumentations#1032]
Hi, I'm using `albumentations` for my project, but my image is GrayScale with shape `[H, W]` but I need to use RGB image (3 channels or `[H, W, 3]`) for training neural networks. Does the library provides any transformation to `convert grayscale to RGB`, which is similar to ` tf.image.grayscale_to_rgb`? thank you

**Comment by BloodAxe** [comment]
A combination of `[A.Normalize(), A.ToTensorV2()] shoud do the job. Please refer to this [notebook](https://github.com/albumentations-team/albumentations_examples/blob/24f3bf740ffda010dd5ceda743d4cb41899b7d22/notebooks/migrating_from_torchvision_to_albumentations.ipynb) for an example.

**Comment by hoangtnm** [comment]
Hi @BloodAxe, as I understand [RGBShift](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.RGBShift) is used for RGB image with shape [H, W, 3], does `albumentations` has the equivalent transform for Grayscale image with shape [H, W]?

**Comment by amin-nejad** [comment]
+1 for a `ToRGB` transformation in the same vein as `ToGray`

**Comment by Beluuuuuuga** [comment]
Is this Issue still ongoing? Can I take it?

**Comment by domef** [comment]
A tranformation `A.ToRGB` would be very usefull.

**Comment by Dipet** [comment]
ToRGB added in #1323
