### ISSUE TITLE
Support of a special Pad operation

### ISSUE THREAD

**Issue by rose-jinyang** [albumentations-team/albumentations#1039]
Hello
How are you?
Thanks for contributing to this project.
I am going to implement an operation for center-padding along with the shortest side while keeping the longest side.
There is the operation named "CenterPadToSquare" in "imgaug" library (https://github.com/aleju/imgaug). 
![image](https://user-images.githubusercontent.com/47862419/137576102-13a980e6-6be8-47a6-a7be-252df00b2e02.png)

But I can NOT find/implement such an operation/combination in this library.

Could u help me?

**Comment by rose-jinyang** [comment]
I found there is NOT an operation such as "CenterCropToAspectRatio" in "imgaug" library (https://github.com/aleju/imgaug).

**Comment by Dipet** [comment]
In most cases, algorithms work with known image height and width.
For this reason, a combination of [`CenterCrop`](https://albumentations.ai/docs/api_reference/full_reference/#albumentations.augmentations.crops.transforms.CenterCrop) and [`PadIfNeeded`]() is enough.
If you need this transformation, you can implement it and add it to the library, we'd love to see you contribute to the library.
