### ISSUE TITLE
opencv-python-headless gets installed when no-binary is specified

### ISSUE THREAD

**Issue by helena-intel** [albumentations-team/albumentations#1043]
## 📚 Documentation

I followed instructions on https://albumentations.ai/docs/getting_started/installation/#note-on-opencv-dependencies to install albumentations without opencv-python-headless and installed with `pip install -U albumentations --no-binary imgaug,albumentations` 

According to the documentation, this should preven opencv-python-headless from getting installed if opencv-python is already installed. This is not the case however: it still gets installed, even though `opencv-python` is also installed. They are both the same version, `pip freeze | grep opencv` gives:

```
opencv-python==4.5.3.56
opencv-python-headless==4.5.3.56
```

I tried this in a clean environment, both with first installing other requirements and then installing albumentations with the `--no-binary` flag, and with including albumentatoins and the `--no-binary` flag in requirements.txt.

I notice that the documentation says _In future versions, we plan to get rid of imgaug as a dependency, and Albumentations will require only opencv-python-headless as its dependency._  It seems that this is outdated, because imgaug is already optional. But now it is not clear to me how to prevent albumentations from installing opencv-python-headless when opencv-python is already installed or also in requirements.txt.

The cause of the issue seems to be the qudida requirement:

```
$ pip show opencv-python-headless
Name: opencv-python-headless
Version: 4.5.3.56
Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/skvark/opencv-python
Author: 
Author-email: 
License: MIT
Location: ---
Requires: numpy
Required-by: qudida
```

Which according to https://github.com/arsenyinfo/qudida/blob/main/requirements.txt requires opencv-python, but where the PyPI package requires opencv-python-headless https://libraries.io/pypi/qudida

**Comment by mrgiba** [comment]
I am also having the same issue, where my environment already has `opencv-contrib-python` and `pip install -U albumentations --no-binary imgaug,albumentations` is installing `opencv-python-headless`

**Comment by hsuanguo** [comment]
I have encountered the same issue, `opencv-python-headless` is installed even though I already have `opencv-python`

**Comment by creafz** [comment]
Hi. Sorry for the outdated docs. I have updated them. 

The correct way is now to use the `--no-binary qudida,albumentations` argument, e.g. `pip install -U albumentations --no-binary qudida,albumentations`

**Comment by Dipet** [comment]
On a clean env and python3.8 with opencv-python installed all works fine and `opencv-python-headless` doesn't get installed.
```
Requirement already satisfied: opencv-python>=4.1.1 in ./test_venv/lib/python3.8/site-packages (from albumentations) (4.6.0.66)
````

**Comment by gitgitgithut** [comment]
@Dipet @ai4prod Silly me, by simply updating pip to the latest version `pip install -U albumentations --no-binary qudida,albumentations` now functions correctly.

**Comment by PetrDvoracek** [comment]
Again facing this issue in docker container `nvcr.io/nvidia/pytorch:24.01-py3`. After running `pip install --upgrade pip` followed by `pip install -r requirements.txt`, following content is in `requirements.txt`:

```
timm==0.9.12
hydra-core==1.3.2
wandb==0.16.2
lightning==2.1.4
scikit-image==0.22.0
black==24.1.1
albumentations==1.3.1 --no-binary qudida,albumentations
```

Following versions are installed:

```
$ pip list | grep opencv
opencv                    4.7.0
opencv-python-headless    4.9.0.80
```

**Comment by ternaus** [comment]
```python
import re

from pkg_resources import DistributionNotFound, get_distribution
from setuptools import setup, find_packages

INSTALL_REQUIRES = [
    "numpy>=1.24.4",
    "scipy>=1.10.0",
    "PyYAML",
    "typing-extensions>=4.9.0; python_version<'3.10'",
    "pydantic>=2.9.2",
    "albucore==0.0.23",
    "eval-type-backport; python_version<'3.10'",
]

MIN_OPENCV_VERSION = "4.9.0.80"

CHOOSE_INSTALL_REQUIRES = [
    (
        (f"opencv-python>={MIN_OPENCV_VERSION}", f"opencv-contrib-python>={MIN_OPENCV_VERSION}", f"opencv-contrib-python-headless>={MIN_OPENCV_VERSION}"),
        f"opencv-python-headless>={MIN_OPENCV_VERSION}",
    ),
]

def choose_requirement(mains: tuple[str, ...], secondary: str) -> str:
    chosen = secondary
    for main in mains:
        try:
            name = re.split(r"[!<>=]", main)[0]
            get_distribution(name)
            chosen = main
            break
        except DistributionNotFound:
            pass
    return chosen

def get_install_requirements(install_requires: list[str], choose_install_requires: list[tuple[tuple[str, ...], str]]) -> list[str]:
    for mains, secondary in choose_install_requires:
        install_requires.append(choose_requirement(mains, secondary))
    return install_requires

setup(
    packages=find_packages(exclude=["tests", "tools", "benchmark"], include=['albumentations*']),
    install_requires=get_install_requirements(INSTALL_REQUIRES, CHOOSE_INSTALL_REQUIRES),
)

```

Right now dynamic dependencies are handled this way.

If one knows how to make the choice of dependencies to work better - would be happy to update the code.
