### ISSUE TITLE
The border generated in FDA mask seems not in line with the paper.

### ISSUE THREAD

**Issue by themurtazanazir** [albumentations-team/albumentations#1046]
## 🐛 Bug
The `border` in FDA is taken as `min(height, width)*beta` which is not in line with the paper.

To quote the paper:

> As we can see from Eq. (3), $\beta = 0$ will render $x^{s→t}$ the same as the original source image $x^s$. On the other hand, **when $\beta = 1.0$, the amplitude of $x^s$ will be replaced by that of $x^t$.**

But while setting the beta=1, we get almost the original source image back. Also, setting beta=1 should replace _all_ amplitude not just along the smaller axis.

## To Reproduce

```python
betas = [0.001, 0.1, 0.5, 0.8, 0.9, 1.0]

f, axes = plt.subplots(3, 2, figsize=(30, 20))

for beta, ax  in zip(betas, axes.ravel()):
    ax.imshow(A.fourier_domain_adaptation(src,  cv2.resize(tar, dsize=(src.shape[1], src.shape[0])), beta=beta))
    ax.set_title(f"beta: {beta}")
    ax.set_axis_off()
    
f.tight_layout()
```

## Output
![FDA bug in album](https://user-images.githubusercontent.com/34167018/138074690-45c02316-65f9-42e8-910e-bbdbb7ed63e6.jpg)

## Expected behavior
The "augmentation" should be maximum at beta=1 not at beta=0.5.

## Environment

 - Albumentations version (e.g., 0.1.8): 1.1.0
 - Python version (e.g., 3.7): 3.8.8
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed albumentations (`conda`, `pip`, source): source
 - Any other relevant information:

**Comment by Dipet** [comment]
It is strange that the results are different from the paper, because we took implementation from the original repo https://github.com/YanchaoYang/FDA/blob/master/utils/__init__.py#L64.
