### ISSUE TITLE
Feature request: Extend Blur to anisotropic kernels and generalised normal distribution.  

### ISSUE THREAD

**Issue by zakajd** [albumentations-team/albumentations#1060]
## Feature request.
Hi! Thanks for an awesome library.
I have an idea for new augmentation(-s) to make it even better =)

Currently Albumentations has 5 types of blur filtering: 
1. `transforms.Blur` — which applies **box** filter with randomly selected kernel size.
2. `transforms.MedianBlur` — which applies **median** filtering 
3. `transforms.GaussianBlur`  — which applies **isotropic (symmetric) Gaussian** filter. See example below:
![photo_2021-11-18_23-27-23](https://user-images.githubusercontent.com/15848838/142492199-bcf41336-4e0e-456e-9052-5cf5fd687956.jpg)
4. `transforms.GlassBlur` — which again does multiple blurring iterations with **isotropic Gaussian**
5. `transforms.MotionBlur` — which blurs by a "line" filter. See example below:
![image](https://user-images.githubusercontent.com/15848838/142492851-8bd9acf9-50a7-4a3b-a2c3-e8d2a2395076.png)

Here is the thing — isotropic Gaussian is the **simplest** case of a more general normal distribution. 
1. Kernel can be asymmetric (anisotropic). See example:
![photo_2021-11-18_23-27-25](https://user-images.githubusercontent.com/15848838/142493129-26e2b5ba-cac8-4c68-b853-f6700f716be5.jpg)
2. It isn't fixed to XY coordinates and can be rotated to any degree `theta`. See example:
![photo_2021-11-18_23-27-26](https://user-images.githubusercontent.com/15848838/142493204-b026c083-7d89-45d0-b531-3efa2e510b44.jpg)
3. By varying distribution generalisation parameter we can make it tails heavier of lighter.  See examples: 
![photo_2021-11-18_23-27-27](https://user-images.githubusercontent.com/15848838/142493523-7ebab5d2-205d-4fa0-b3d0-444f425596d9.jpg)  |  ![photo_2021-11-18_23-27-28](https://user-images.githubusercontent.com/15848838/142493552-75ce3d72-d068-477f-9eb2-87bb852ad942.jpg)

4. We can also include **noise**  on kernel level, which is shown to better model camera ISP pipelines. See examples: 

![photo_2021-11-18_23-27-32](https://user-images.githubusercontent.com/15848838/142493745-b01e2932-197c-47ef-903a-664bccda2af2.jpg) | ![photo_2021-11-18_23-27-33](https://user-images.githubusercontent.com/15848838/142493777-073a3029-c550-4770-b33f-fef42269ec2d.jpg)
 
![photo_2021-11-18_23-27-34](https://user-images.githubusercontent.com/15848838/142494022-c67973dc-3cd9-4ff0-90d5-d5ac9fc80597.jpg) | ![photo_2021-11-18_23-27-35](https://user-images.githubusercontent.com/15848838/142494033-1497540a-36bf-4b18-a66f-c0804961ff4e.jpg)

## Implementation details

Code to generate images above is take from BasicSR repo: https://github.com/xinntao/BasicSR/blob/master/basicsr/data/degradations.py
It can be enhanced, cleaned up and placed into new `AdvancedBlur` transform that does everything at once.

**Comment by Dipet** [comment]
Thanks for the idea!
We need to think about how to implement this feature.
It looks like we need some kind of transformation that could apply any convolution filter to the image.

**Comment by zakajd** [comment]
@Dipet you already have it 
https://github.com/albumentations-team/albumentations/blob/477156d5f14a26f8f0f71c5f2c0d59748bb7de4b/albumentations/augmentations/functional.py#L630-L633

**Comment by zakajd** [comment]
I did a draft implementation in my private project, will create a PR later today with it so we can discuss design choices there.
