### ISSUE TITLE
ShiftScaleRotate does not reflect the Bounding box

### ISSUE THREAD

**Issue by joihn** [albumentations-team/albumentations#1067]
## 🐛 Bug

[ShiftScaleRotate](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.ShiftScaleRotate) use by default `border_mode=cv2.BORDER_REFLECT_101` which will reflect (=mirror) the image as a padding.

If an object (close to border) gets reflected, the reflection won't be annotated with a Bounding box.
 
## To Reproduce

1. pick an image with an object close to border and with Bouding Box GND
1.use big limits to make it more obvious, such as `shift_limit=0.6, scale_limit=0.6`

## Expected behavior

The bouding box anotation should also be present in the reflection.
## Environment

 - Albumentations version : 1.1
 - Python version :3.9
 - ubuntu 20.04

**Comment by Dipet** [comment]
This is a problem for all transforms that work with boxes. Unfortunately, we do not have a solution how to implement different border modes for bboxes and keypoints.

**Comment by AlexandrOsornio** [comment]
Any updates for this issue? It is quite crucial for border reflections to reflect annotations too as not doing it results in 2 side by side   objects, one annotated and one not

**Comment by nmpowell** [comment]
This seems like a pretty critical bug because of the possibility of classifying true instances (in reflections) as background. [This PR](https://github.com/albumentations-team/albumentations/pull/1125) seems to address it but it's a shame it has been an open issue for so long.

**Comment by ternaus** [comment]
Looking into it.

**Comment by ternaus** [comment]
@joihn @nmpowell @AlexandrOsornio  

Addressed in https://github.com/albumentations-team/albumentations/pull/1898
