### ISSUE TITLE
Picking up negative values in bounding boxes when it should not

### ISSUE THREAD

**Issue by lpkoh** [albumentations-team/albumentations#1073]
## 🐛 Bug

I am running a script to crop images. I have yolo bounding boxes for those images. When I pass a bbox to transform, it reads in a completely different bounding box at random, that has negative value.

As seen, I have run the code to print out the bbox right before passing it to transform. I then show the error message.
![image](https://user-images.githubusercontent.com/48631399/144192423-a6a9e618-3c83-4079-abbf-8d8ca7401da7.png)
![image](https://user-images.githubusercontent.com/48631399/144192488-9f4dffad-f5c6-412d-97ff-275490db9899.png)

## Expected behavior

It should not pick up the bounding box.

## Environment

 - Albumentations version (1.0.3):
 - Python version (3.7):
 - OS (Linux):
 - How you installed albumentations (`conda`):
 - Any other relevant information:

**Comment by lpkoh** [comment]
Understand the error

**Comment by chungtiendat8102000** [comment]
How to fix it? I have met the same error.
