### ISSUE TITLE
Diagram explaining xyas keypoints is very misleading

### ISSUE THREAD

**Issue by Multihuntr** [albumentations-team/albumentations#1078]
## 📚 Documentation

The page describing keypoints augmentation implies that the scale is just the x component of the length, rather than actually being the  hypotenuse length. 

Page: https://albumentations.ai/docs/getting_started/keypoints_augmentation/

Diagram:
![offending diagram](https://albumentations.ai/docs/images/getting_started/augmenting_keypoints/keypoint_with_scale_and_angle.png)

**Comment by Multihuntr** [comment]
Oh; I found it. It's in a different repo. I'll open this over there.

**Comment by RGring** [comment]
@Multihuntr I agree with your observation. What do you mean by different repo? Wouldn't it make sense to get the scale for both directions: x and y.

**Comment by Multihuntr** [comment]
I think that describing a vector using an "x-scale"/"y-scale" or using "scale"/"angle" are both equally valid and expected. Each is more or less useful in different situations. However, the order of priorities are:

1. Maintain current interfaces.
2. Make sure it can be used in underlying libraries without changes.
3. Minimise changes to "x-scale"/"y-scale" internally.

So, I think it wouldn't make sense to change it to be represented as "x-scale"/"y-scale".

As for "different repo"... The albumenatations.ai website is in its own repo. https://github.com/albumentations-team/albumentations.ai I opened an issue on it providing the current diagram. https://github.com/albumentations-team/albumentations.ai/issues/22

So, that's my *new* diagram you're complaining about. :sweat_smile: Previously it looked like it was using an "x-scale"/"angle" representation, rather than what it actually does: uses "scale"/"angle" representation. This issue was about the accuracy of the diagram; not asking the code to change.
