### ISSUE TITLE
Affine rotation direction inconsistant with Rotate/ShiftScaleRotate and incompatible using xyas keypoints

### ISSUE THREAD

**Issue by Multihuntr** [albumentations-team/albumentations#1079]
## 🐛 Bug

In a graph with +ve Y pointing up, +ve rotation is conventionally counter-clockwise.
Thus, in an image, with +ve Y pointing down, +ve rotation should then typically be clockwise. 

This convention is respected by `Affine`, but not `Rotate` or `ShiftScaleRotate`. This means that a pipeline with both `Affine` and `Rotate`/`ShiftScaleRotate` when using `xyas` keypoints will rotate those keypoints incorrectly.

## To Reproduce

For my examples it's easier to start with a visualisation. Pretend we have an image shaped (200, 100) (xy) and a single keypoint at (0, 0) with an angle of 45 degrees.

![rotate](https://user-images.githubusercontent.com/10515040/145353778-4a236fed-70a1-44ea-bf40-8f56ff061b88.png)

If +ve is considered clockwise, then (0,0) becomes approximately (64, -56), and we look at the green arrow. If +ve is considered counter-clockwise, then (0,0) becomes approx. (-6, 85) and we look at the blue arrow.

Here I show that :

- `Rotate` and `ShiftScaleRotate` treats +ve rotation as counter-clockwise in an image. 
- `Affine` treats +ve rotation as clockwise in an image. 
- The discrepancy between `Affine` then `Rotate` causes the rotations of the keypoints to be misinterpreted

```python
import math

import skimage.transform
import albumentations as A
import numpy as np

kp_params = A.KeypointParams(format='xya', remove_invisible=False)
img = np.zeros((100, 200))
kp1 = (0, 0, 45, 1)
transform1 = A.Compose(
    [A.Rotate((45, 45), p=1)],
    keypoint_params=kp_params
)
transform2 = A.Compose(
    [A.ShiftScaleRotate(shift_limit=(0, 0), scale_limit=(0, 0), rotate_limit=(45, 45), p=1)],
    keypoint_params=kp_params
)
transform3 = A.Compose(
    [A.Affine(rotate=[45,45], p=1)],
    keypoint_params=kp_params
)
transform4 = A.Compose(
    [
        A.Affine(rotate=[45,45], p=1),
        A.Rotate((45, 45), p=1)
    ],
    keypoint_params=kp_params
)

print(transform1(image=img, keypoints=[kp1])['keypoints'])
# [(-6, 85, 90.0, 1)]
print(transform2(image=img, keypoints=[kp1])['keypoints'])
# [(-6, 85, 90.0, 1)]
print(transform3(image=img, keypoints=[kp1])['keypoints'])
# [(64.14466094067262, -55.85891039679558, 90.0, 1)]
print(transform4(image=img, keypoints=[kp1])['keypoints'])
# [(6.217248937900877e-15, 0.0, 135.0, 1)]
```

**Comment by Multihuntr** [comment]
After a bit of research, I think that OpenCV might just be clockwise because of a bug. Most libraries adjust their definition of "clockwise" and "counter-clockwise" to match the "+ve Y is down" paradigm of images despite the incompatibility with the "+ve Y is up" paradigm used in general mathematics. And the docs for [cv2.getRotationMatrix2D()](https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html#gafbbc470ce83812914a70abfb604f4326) say that it's supposed to be counter-clockwise, too.

Here are some libraries that treat +ve as "counter-clockwise" while using "+ve Y is down":
- [MATLAB](https://au.mathworks.com/help/images/rotate-an-image.html) 
- [Matplotlib](https://github.com/matplotlib/matplotlib/blob/v3.5.0/lib/matplotlib/transforms.py#L1996-L2010)
- [Torchvision](https://pytorch.org/vision/master/generated/torchvision.transforms.functional.rotate.html#torchvision.transforms.functional.rotate)
- albumentations, of course.

So, I guess I should raise this with OpenCV. In the meantime, maybe it should be noted in the docs that rotation angle for `Affine` is clockwise?

**Comment by Multihuntr** [comment]
Goodness me, I apologise for being extremely bad at keeping + and - straight in my head. `cv2.getRotationMatrix2D()` does, in fact, do a CCW rotation in imageland; my code scraps I used for testing were bad. 

So, there must be something in `albumentations.Affine` which flips the angle.

**Comment by Dipet** [comment]
Thanks a lot for finding this bug and investigating the issue. Please have a look at my attempt to fix this issue: https://github.com/albumentations-team/albumentations/pull/1091
