### ISSUE TITLE
How to perform pixelwise Dropout with Albumentations

### ISSUE THREAD

**Issue by Lucas-rbnt** [albumentations-team/albumentations#1081]
Hi, my request may seem trivial but I can't find any Albumentations class that can handle dropout, even though it is present in all the other Data Augmentation libraries. (put a desired proportion of pixel equal to zero or one)

Thanks everyone, sorry to bother you :)
Have a nice week-end!

**Comment by Dipet** [comment]
It looks like the library really doesn't have this feature yet. Closest is [CoarseDropout](https://albumentations.ai/docs/api_reference/full_reference/#albumentations.augmentations.transforms.CoarseDropout)

**Comment by ternaus** [comment]
@Lucas-rbnt 

Added: https://explore.albumentations.ai/transform/PixelDropout
