### ISSUE TITLE
Unclear warning when using Perspective transform in ReplayMode

### ISSUE THREAD

**Issue by EtagiBI** [albumentations-team/albumentations#1083]
Hi, I'm trying to use [Perspective transform](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.Perspective) to generate a dataset of augumented images and corresponding transormation matrices. 

Here's a code:
```
def albumentate(image):
    transform = A.ReplayCompose([
        A.Perspective(scale=(0.06, 0.06),
                      keep_size=True,
                      pad_mode=cv2.BORDER_REPLICATE,
                      pad_val=0,
                      mask_pad_val=0,
                      fit_output=True,
                      interpolation=1,
                      always_apply=True,
                      p=1.0)
    ])
    augmented = transform(image=image)
    matrix = augmented["replay"]["transforms"][0]["params"]["matrix"]
    augmented_image = augmented['image']
    print(matrix)
    return augmented_image, matrix
```
When I run the code, I get a warning:
```
C:\Python3\lib\site-packages\albumentations\core\transforms_interface.py:93: UserWarning: Perspective could work incorrectly in ReplayMode for other input data because its' params depend on targets.
  self.get_class_fullname() + " could work incorrectly in ReplayMode for other input data"
```
I have to use ReplayMode, because I need resulting transformation matrices.
Should I worry about this warning? 
It would be nice to have this nuance covered in the docs.

**Comment by Dipet** [comment]
Everything will work correctly.
This warning means that, for example, if you provide an image and targets with different shapes than original data for reproduction (only when you call `transform.replay(**replay_args)`), it may not work correctly.
