### ISSUE TITLE
[Company] NewYorker

### ISSUE THREAD

**Issue by AlekseySh** [albumentations-team/albumentations#1088]
### Name

NewYorker

### Website

https://www.newyorker.de/ru/

### Link to a logo

https://www.suedring-paderborn.de/medium/new-yorker.jpg?m=2670&w=645&h=461&g=0

### Confirmation

- [X] I hereby confirm that I have permission from the company specified above to use its name, link to a website, and logo to mention it as a user of Albumentations.

**Comment by creafz** [comment]
Hi. Thanks. NewYorker was added to the list of companies that use Albumentations at https://albumentations.ai/.
