### ISSUE TITLE
Affine doesn't rotate bounding boxes the same as Rotate

### ISSUE THREAD

**Issue by Multihuntr** [albumentations-team/albumentations#1093]
## 🐛 Bug

`Affine` doesn't rotate bounding boxes the same way that `Rotate` does. This is a bug in `Affine`.

## To Reproduce

```python
import albumentations as A
import numpy as np

bbox_in = (0.4, 0.4, 0.6, 0.6)
bbox_params = A.BboxParams('albumentations', label_fields=['cl'])
transform1 = A.Compose(
    [A.Affine(rotate=(90, 90), p=1)],
    bbox_params=bbox_params)
transform2 = A.Compose(
    [A.Rotate((90, 90), p=1)],
    bbox_params=bbox_params)

img = np.ones((100, 100, 3)) * 255

bbox_out1 = transform1(image=img, bboxes=[bbox_in], cl=[0])['bboxes'][0]
print(bbox_out1) # (0.39, 0.4, 0.5900000000000001, 0.6000000000000001)
bbox_out2 = transform2(image=img, bboxes=[bbox_in], cl=[0])['bboxes'][0]
print(bbox_out2) # (0.4, 0.4, 0.6, 0.6)
```

## Expected behavior

Rotating a symmetric bounding box about the centre of the image should result in a symmetric bounding box.

## Additional context

Here's what's happening: in [`Affine.get_params_dependent_on_targets`](https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/geometric/transforms.py#L649), the created transformation matrix includes an offset that is required for sampling, and then, this matrix is applied directly to the bounding boxes.

To solve this: you need to apply different matrices in `cv2.warpAffine` and to your points. The "black border" that is noted in the comments is because OpenCV treats (0, 0) as the centre of the top-left pixel, while bounding boxes treat (0, 0) as the top-left of the top-left pixel. In particular you can see that the bounding box here is offset by 1 pixel. 

Then, the solution is to wrap all calls to `cv2.warpAffine` using some matrix M with a `+(0.5, 0.5) @ M @ -(0.5, 0.5)` instead of building that sampling offset directly into the matrix itself.

**Comment by ternaus** [comment]
Added tests for this case. Everything works as expected in version 1.4..14+
