### ISSUE TITLE
[Company] AriSaf Tech

### ISSUE THREAD

**Issue by TashinAhmed** [albumentations-team/albumentations#1098]
### Name

AriSaf Tech

### Website

https://arisaftech.co.jp/

### Link to a logo

https://arisaftech.co.jp/wp-content/uploads/2021/01/LogoWithTitle.png

### Confirmation

- [X] I hereby confirm that I have permission from the company specified above to use its name, link to a website, and logo to mention it as a user of Albumentations.

**Comment by creafz** [comment]
Hi. Thanks. AriSaf Tech was added to the list of companies that use Albumentations at https://albumentations.ai/.
