### ISSUE TITLE
edge smooth binary segmentation mask

### ISSUE THREAD

**Issue by Suzan009** [albumentations-team/albumentations#1099]
## 📚 Documentation

I was reading this illustration of semantic segmentation. https://github.com/albumentations-team/albumentations#object-detection-and-semantic-segmentation-on-the-mapillary-vistas-dataset. I've used this library for my binary mask segmentation dataset. The resultant mask is somewhat good but the edge is too noisy. 

[Sample Mask.](https://i.stack.imgur.com/rgryj.jpg) 

How to smooth the edge?

**Comment by Suzan009** [comment]
@ternaus I've found that you won [1st place](https://www.kaggle.com/c/carvana-image-masking-challenge/discussion/46176) in such a similar dataset. Can you give some suggestions?

**Comment by ternaus** [comment]
Could you please provide the code that generated this mask?

**Comment by Suzan009** [comment]
I did as follows to get the mask. 

```python
# my model 
model = [
    input = shape=(None, 224, 224, 3)
    encoder
    decoder
    output = layers.Conv2d(1, activation='sigmoid')
]

# inference
y_pred = (model.predict(x)  > 0.5).astype(np.int32)
y_pred.shape (224, 224, 1) # 

plt.imshow(y_pred, cmap=gray) # above mask 
```

To smooth the edge, I've checked [this](https://stackoverflow.com/questions/63392049/smoothing-the-edges-of-segmented-images). But all solution is not general for all inference samples.

**Comment by ternaus** [comment]
It looks like your question is not related to Albumentations.

We did not use any post-processing in the Carvana Challenge, models were good enough to predict an accurate mask.

You may try to use erosion / dilation to smooth your masks. https://docs.opencv.org/3.4/db/df6/tutorial_erosion_dilatation.html
