### ISSUE TITLE
The mask information was incorrectly converted

### ISSUE THREAD

**Issue by hammerAttack** [albumentations-team/albumentations#1103]
Here is my code：
    transform=HorizontalFlip(p=1.)
    json_info = json.load(open("images.json", "r"))
    mask_info= copy.deepcopy(json_info["shapes"][0]['points'])
    image = cv2.imread("images.jpg")
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    mask = np.array(mask_info)
    # 转换后图像为 numpy数组 格式
    transformed = transform(image=image,mask=mask)
    transformed_image = transformed["image"]
    transformed_mask = transformed["mask"]

    json_info["shapes"][0]['points']=copy.deepcopy(transformed_mask.tolist())
    cv2.imwrite("images_out.jpg", transformed_image)
    with open("images_out.json", "w") as f:
        json.dump(json_info, f)

**Comment by hammerAttack** [comment]
![图片](https://user-images.githubusercontent.com/66540522/148031894-9a92eef7-5214-4120-98cf-e5a62855eadd.png)

**Comment by Dipet** [comment]
This is not a pixel mask. These are keypoints in our terms.
Try this:
```python
transform = A.Compose([A.HorizontalFlip(p=1.)], keypoint_params=A.KeypointParams("xy"))
```

**Comment by hammerAttack** [comment]
> This is not a pixel mask. These are keypoints in our terms. Try this:
> 
> ```python
> transform = A.Compose([A.HorizontalFlip(p=1.)], keypoint_params=A.KeypointParams("xy"))
> ```

Thank you， I understand.
