### ISSUE TITLE
multi-person keypoints error: <= not supported between instances of int and tuple albumentations

### ISSUE THREAD

**Issue by teddylegessemunea** [albumentations-team/albumentations#1106]
## To Reproduce

1. an image may have multi-person on the image
2. number of people unknown
3. the keypoints shown on each individual can be different
4. the code below, the first person has 11 keyponts shown while the second person 15 keypoints shown
5.  I am getting typeerror <= not supported between instances of int and tuple albumentations
6. when I put all of them on 1 list it works
7. if it is 1 list, after augmentation I may not know which keypoints are returned based on the cropped result
8. please help

transform = alb.Compose([alb.RandomSizedCrop(min_max_height=(320, 480), height=512, width=512, p=0.5),
                         alb.HorizontalFlip(p=0.5),
                         alb.OneOf([alb.HueSaturationValue(p=0.5), alb.RGBShift(p=0.7)], p=1),
                         alb.RandomBrightnessContrast(p=0.5), ],
                        keypoint_params=alb.KeypointParams(format='xy', label_fields=['keypoints_ids'],
                                                           remove_invisible=True, angle_in_degrees=True))

keypoints = [[(271, 233), (271, 239), (287, 239), (266, 257), (261, 268), (285, 261), (298, 260), (282, 285),
              (284, 278), (286, 311), (291, 298)],
             [(363, 226), (363, 222), (369, 218), (380, 227), (383, 213), (400, 235), (397, 199), (390, 252),
              (409, 183), (399, 266), (390, 259), (384, 305), (364, 270), (376, 338), (364, 290)]]

keypoints_ids = [[3, 5, 6, 7, 9, 11, 12, 13, 14, 15, 16], [0, 1, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]

transformed = transform(image=image, keypoints=keypoints, keypoints_ids=keypoints_ids)

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7):
 - tensorlflow 2.4.0
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

**Comment by Dipet** [comment]
You need to flatten keypoints into `List[Tuple[float, float]]`.
If you want to split keypoints by persons you could use [additional_targets](https://albumentations.ai/docs/examples/example_multi_target/#applying-the-same-augmentation-with-the-same-parameters-to-multiple-images-masks-bounding-boxes-or-keypoints) or set person id for each keypoint as its label.
