### ISSUE TITLE
RandomRotate90 always apply not working 

### ISSUE THREAD

**Issue by JulenBarr** [albumentations-team/albumentations#1107]
## 🐛 Bug

Hey everyone, I've trying to figure out what is wrong with my code and as far as I'm concerned it may be a bug. 
## To Reproduce

Rotation = []
def RandomRotate(image):
    aug = A.RandomRotate90(always_apply=True, p = 1.0)

    augmented = aug(image=image)

    rotation = augmented['image']

    visualize_masks(rotation)
    
    Rotation.append(rotation)
RandomRotate(masks[0])

## Expected behavior
Since I'm applying always_apply = True and p = 1 (I've tried a lot of times) I would expect to always rotate my image 90º

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7): 3.7 
 - OS (e.g., Linux): Widnows 10 
 - How you installed albumentations (`conda`, `pip`, source): pip 
 - Any other relevant information:

**Comment by Dipet** [comment]
Just read the docs:
```
Randomly rotate the input by 90 degrees zero or more times.
```
The image will be rotated 0, 1, 2, or 3 times 90 degrees. This means that the image will be randomly rotated 0, 90, 180, 270 degrees.
If you want to rotate the image to 90 degrees it's better to use `A.Rotate([90, 90], p=1)`
