### ISSUE TITLE
Transform to scale image between 0 to 1

### ISSUE THREAD

**Issue by sri9s** [albumentations-team/albumentations#1108]
Does albumentation provide a transform to incluse in compose to scale images bwteen 0 to 1?

**Comment by Dipet** [comment]
Yes, for this reason, you can use [RandomScale](https://albumentations.ai/docs/api_reference/augmentations/geometric/resize/#albumentations.augmentations.geometric.resize.RandomScale):
```python
RandomScale(scale_limit=(-1, 0))
```
Yes, it is a little bit strange to use this range, but it is a legacy problem.

**Comment by sri9s** [comment]
> Yes, for this reason, you can use [RandomScale](https://albumentations.ai/docs/api_reference/augmentations/geometric/resize/#albumentations.augmentations.geometric.resize.RandomScale):
> 
> ```python
> RandomScale(scale_limit=(-1, 0))
> ```
> 
> Yes, it is a little bit strange to use this range, but it is a legacy problem.

According to definition:
`scaling factor range. If scale_limit is a single float value, the range will be (1 - scale_limit, 1 + scale_limit).`

In that case should the scale_limit be (1,0) if I want to scale the images between 0 to 1?

**Comment by Dipet** [comment]
If you want to scale image between 0 to 1 use this settings:
```python
RandomScale(scale_limit=(-1, 0))
````

**Comment by sri9s** [comment]
Doesnt work, changes the image shape altogether!

**Comment by Dipet** [comment]
Do you want to scale height and with independently?

**Comment by sri9s** [comment]
Want to scale (normalize) the values

**Comment by Dipet** [comment]
https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.Normalize
