### ISSUE TITLE
Can no longer install Albumentations after 4+ months of Albumentations working in my Google Colab notebook

### ISSUE THREAD

**Issue by RachelRamirez** [albumentations-team/albumentations#1110]
## 🐛 Bug: Can not Install Albumentations 

For several months, I had no issue, but as of today, I can no longer "import albumentations as A" in google colab.   It started when I realized I could no longer install 'imgaug' which I used to seed my augmentations.  I tried to skip this step and go forward with installing albumentations but could not.   I believe it may be a dependency on open CV causing the issue but I cannot resolve.   
 

## To Reproduce

1.  I tried to install Albumetations the way I have for the last several months, in Google Colab, I type the following code:

```
!pip install -U git+https://github.com/albumentations-team/albumentations -q
# necessary imports
from functools import partial
import albumentations as A
import cv2 as cv2   
import tensorflow as tf
AUTOTUNE = tf.data.experimental.AUTOTUNE
```
However, the following error results:

_

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-62-1157375eeb5e> in <module>()
> ----> 1 import cv2 as cv2
> 
> 3 frames
> /usr/local/lib/python3.7/dist-packages/cv2/__init__.py in <module>()
>       7 
>       8 from .cv2 import *
> ----> 9 from .cv2 import _registerMatType
>      10 from . import mat_wrapper
>      11 from . import gapi
> 
> ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so)
> ---------------------------------------------------------------------------

_

I tried to install Albumentations this way instead: `pip install -U albumentations --no-binary qudida,albumentations`
it looks like it works fine.  Should the next line work?  I need to identify the package as "A" for the rest of my code to work.   `import albumentations as A`

> Requirement already satisfied: albumentations in /usr/local/lib/python3.7/dist-packages (1.1.0)
> Requirement already satisfied: scikit-image<0.19,>=0.16.1 in /usr/local/lib/python3.7/dist-packages (from albumentations) (0.18.3)
> Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from albumentations) (3.13)
> Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.7/dist-packages (from albumentations) (1.19.5)
> Requirement already satisfied: opencv-python>=4.1.1 in /usr/local/lib/python3.7/dist-packages (from albumentations) (4.1.2.30)
> Requirement already satisfied: qudida>=0.0.4 in /usr/local/lib/python3.7/dist-packages (from albumentations) (0.0.4)
> Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from albumentations) (1.4.1)
> Requirement already satisfied: scikit-learn>=0.19.1 in /usr/local/lib/python3.7/dist-packages (from qudida>=0.0.4->albumentations) (1.0.2)
> Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from qudida>=0.0.4->albumentations) (3.10.0.2)
> Requirement already satisfied: opencv-python-headless>=4.0.1 in /usr/local/lib/python3.7/dist-packages (from qudida>=0.0.4->albumentations) (4.5.5.62)
> Requirement already satisfied: pillow!=7.1.0,!=7.1.1,>=4.3.0 in /usr/local/lib/python3.7/dist-packages (from scikit-image<0.19,>=0.16.1->albumentations) (7.1.2)
> Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from scikit-image<0.19,>=0.16.1->albumentations) (1.2.0)
> Requirement already satisfied: imageio>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from scikit-image<0.19,>=0.16.1->albumentations) (2.4.1)
> Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.7/dist-packages (from scikit-image<0.19,>=0.16.1->albumentations) (2.6.3)
> Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-image<0.19,>=0.16.1->albumentations) (3.2.2)
> Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.7/dist-packages (from scikit-image<0.19,>=0.16.1->albumentations) (2021.11.2)
> Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image<0.19,>=0.16.1->albumentations) (1.3.2)
> Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image<0.19,>=0.16.1->albumentations) (0.11.0)
> Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image<0.19,>=0.16.1->albumentations) (3.0.6)
> Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image<0.19,>=0.16.1->albumentations) (2.8.2)
> Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib!=3.0.0,>=2.0.0->scikit-image<0.19,>=0.16.1->albumentations) (1.15.0)
> Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations) (3.0.0)
> Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations) (1.1.0)
> albumentations @ git+https://github.com/albumentations-team/albumentations@880c1aaed10ab74cfe851496a476c1c34cadcd0f is successfully installed
> 
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-82-88618286046f> in <module>()
>       2 get_ipython().system('echo "$(pip freeze | grep albumentations) is successfully installed"')
>       3 
> ----> 4 import albumentations as A
> 
> 7 frames
> /usr/local/lib/python3.7/dist-packages/cv2/__init__.py in <module>()
>       7 
>       8 from .cv2 import *
> ----> 9 from .cv2 import _registerMatType
>      10 from . import mat_wrapper
>      11 from . import gapi
> 
> ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so)
> 
> ---------------------------------------------------------------------------
> NOTE: If your import is failing due to a missing package, you can
> manually install dependencies using either !pip or !apt.
> 
> To view examples of installing some common dependencies, click the
> "Open Examples" button below.
> ---------------------------------------------------------------------------

## Expected behavior

Import Albumentations is the expected behavior, but it is not importing.  

## Environment

 - Albumentations version (e.g., 0.1.8):  1.10 ?
 - Python version (e.g., 3.7):  Google Colab default version: Python 3.6.9?
 - OS (e.g., Linux):  Windows 10
 - How you installed albumentations (`conda`, `pip`, source):  Tried to do it from Google Colab with the code above 
 - Any other relevant information:

**Comment by Dipet** [comment]
Have you tried this solution?
https://github.com/albumentations-team/albumentations/issues/1100#issuecomment-1003467333

**Comment by RachelRamirez** [comment]
@Dipet that worked, thank you
