### ISSUE TITLE
Could it process list of images with bboxes?

### ISSUE THREAD

**Issue by HanKunChai** [albumentations-team/albumentations#1111]
## 📚 Documentation

img : ndarray by cv2
bboxes : pascal_voc type bbox with class label at `bboxes[...,4]`
`imgs = np.array([img for _ in range(2)])`
`bboxes_ = np.array([bboxes for _ in range(2)])`
`x = trans(images = imgs,bboxes =bboxes_ )`

And it raises an error like
 File "C:\Python_related\envs\frcnn\lib\site-packages\albumentations\augmentations\bbox_utils.py", line 77, in normalize_bbox
    x_min, x_max = x_min / cols, x_max / cols
TypeError: unsupported operand type(s) for /: 'list' and 'int'

I want to know if I could pass a list of images and bboxes to fucntion.

**Comment by HanKunChai** [comment]
It cannot process a batch of images.

**Comment by Dipet** [comment]
If you want to process batch of targets in the same way look to `additional_targets`:  https://albumentations.ai/docs/examples/example_multi_target/
