### ISSUE TITLE
run augment pipeline in random order

### ISSUE THREAD

**Issue by RuoyuGuo** [albumentations-team/albumentations#1114]
## 📚 Documentation

I know the current augmentation pipelines will be executed in order.

```
A.Compose([
    A.Aug1(),
    A.Aug2(),
    A.Aug3()
])
```

The above augmentation will run in Aug1, Aug2, then Aug3.  Is there any way to run them in random order? 
Like `random_order=True` in `imgaug`

```
iaa.Sequential([
    iaa.Aug1(),
    iaa.Aug2(),
    iaa.Aug3()
]),  random_order=True
)
```

Thank you

**Comment by BloodAxe** [comment]
You can use `A.SomeOf` which should give you desired behavior.
