### ISSUE TITLE
[Company] Celsus

### ISSUE THREAD

**Issue by crazyfrogspb** [albumentations-team/albumentations#1118]
### Name

Celsus

### Website

https://celsus.ai/en

### Link to a logo

https://svgshare.com/i/drc.svg

### Confirmation

- [X] I hereby confirm that I have permission from the company specified above to use its name, link to a website, and logo to mention it as a user of Albumentations.

**Comment by creafz** [comment]
Hi. Thanks. Celsus was added to the list of companies that use Albumentations at https://albumentations.ai/.
