### ISSUE TITLE
PadIfNeeded bug due to roundings

### ISSUE THREAD

**Issue by salvacarrion** [albumentations-team/albumentations#1119]
## 🐛 Bug

Images are not padded correctly for odd paddings due to floor round cause by `int()`. 
For instance, if I have an image with dimensions (296, 256) and I want to pad it to 256 (if needed), the PadIfNeeded function will do the following:

```
256-221 = 35 pixels to pad
35px / 2 = int(17.5) = 17
so 1px will be lost due to round
```

This can be seen here: [https://github.com/albumentations-team/albumentations/blob/880c1aaed10ab74cfe851496a476c1c34cadcd0f/albumentations/augmentations/transforms.py#L152](https://github.com/albumentations-team/albumentations/blob/880c1aaed10ab74cfe851496a476c1c34cadcd0f/albumentations/augmentations/transforms.py#L152)

To fix it you could simply add the missing pixel to one of the sides (or throw an warning/error):
```
256-221 = 35 pixels to pad
35px / 2 = int(17.5) = 17
left = 17
right = 35-17 = 18
```

## To Reproduce

```python
def resize_pad_fn(height, width):
    train_transform = [
        A.LongestMaxSize(max_size=256, always_apply=True),
        A.PadIfNeeded(min_height=256, min_width=256, border_mode=cv2.BORDER_CONSTANT, always_apply=True),
    ]
    return A.Compose(train_transform)

# Inputs= (296, 256)
self.resize_pad_fn(image=image)
# Desired output=(256, 256)
```

## Environment

 - Albumentations version: v1.1.0
 - Python version: 3.8.12
 - OS Linux - Ubuntu 20.04 LST
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by BloodAxe** [comment]
There is no bug in padding. But you should ensure that there are no image and mask dimensions mismatch.
```
import albumentations as A
import numpy as np

pad = A.PadIfNeeded(min_height=256, min_width=384)
image = np.zeros((253, 381))

print(pad(image=image)["image"].shape) # (256, 384)
```
