### ISSUE TITLE
Documentation of Downscale Method seems incomplete.

### ISSUE THREAD

**Issue by rohan-paul** [albumentations-team/albumentations#1120]
## 📚 Documentation
Documentation of the Downscale Method seems incomplete as can be seen [here](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.Downscale)

![image](https://user-images.githubusercontent.com/12703975/152356101-71207e2a-5703-404e-a1f9-4553f53fbab0.png)

**Comment by ternaus** [comment]
Fixed
