### ISSUE TITLE
module 'albumentations' has no attribute 'Sequential'

### ISSUE THREAD

**Issue by schleptech** [albumentations-team/albumentations#1123]
## 🐛 Bug

Trying to follow this guide:
https://medium.com/@alexppppp/how-to-train-a-custom-keypoint-detection-model-with-pytorch-d9af90e111da

## To Reproduce

Got to step 4 with error:
`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-57-a2726a244826>](https://localhost:8080/#) in <module>()
      1 KEYPOINTS_FOLDER_TRAIN = 'glue_tubes_keypoints_dataset_134imgs/train'
----> 2 dataset = ClassDataset(KEYPOINTS_FOLDER_TRAIN, transform=train_transform(), demo=True)
      3 data_loader = DataLoader(dataset, batch_size=1, shuffle=True, collate_fn=collate_fn)
      4 
      5 iterator = iter(data_loader)

[<ipython-input-55-22093f94322e>](https://localhost:8080/#) in train_transform()
      1 def train_transform():
      2     return A.Compose([
----> 3         A.Sequential([
      4             A.RandomRotate90(p=1), # Random rotation of an image by 90 degrees zero or more times
      5             A.RandomBrightnessContrast(brightness_limit=0.3, contrast_limit=0.3, brightness_by_max=True, always_apply=False, p=1), # Random change of brightness & contrast

AttributeError: module 'albumentations' has no attribute 'Sequential'
`

## Environment
Google Colab notebook

**Comment by ternaus** [comment]
Everything works now
