### ISSUE TITLE
Can I publish webapp using albumentations?

### ISSUE THREAD

**Issue by yoyoyo-yo** [albumentations-team/albumentations#1126]
Thank you for nice library. I love it.

I made webapp which simulate albumentations result using streamlit.

Can I publish that via _streamlit share_ (https://streamlit.io/cloud) ?

**Comment by BloodAxe** [comment]
We would love to see that :)

**Comment by yoyoyo-yo** [comment]
@BloodAxe 
Thank you!

This is my app https://share.streamlit.io/yoyoyo-yo/albumentation_sim_sl/main/app.py

If you have any problems, please tell me here.
