### ISSUE TITLE
AttributeError: module 'albumentations' has no attribute 'PixelDropout'

### ISSUE THREAD

**Issue by mb010** [albumentations-team/albumentations#1130]
## 🐛 Bug

A.PixelDropout not found.

## To Reproduce

1. Install python 3.8.10
1. Create a new venv
1. pip isntall Albumentations
1. Try using A.PixelDropout

```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import albumentations as A
>>> A.P
A.PadIfNeeded(                  A.PiecewiseAffine(              A.Posterize(                    
A.Perspective(                  A.PixelDistributionAdaptation(  
>>> A.PixelDropout
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'albumentations' has no attribute 'PixelDropout'
```

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python 3.8.10
 - Ubuntu 20.04:
 - pip installed
 - Tested on a clean venv after failing in my development space.

My venv `pip list`:
```
Package                Version
---------------------- --------
albumentations         1.1.0
imageio                2.16.0
joblib                 1.1.0
networkx               2.6.3
numpy                  1.22.2
opencv-python-headless 4.5.5.62
packaging              21.3
Pillow                 9.0.1
pip                    22.0.3
pkg_resources          0.0.0
pyparsing              3.0.7
PyWavelets             1.2.0
PyYAML                 6.0
qudida                 0.0.4
scikit-image           0.19.2
scikit-learn           1.0.2
scipy                  1.8.0
setuptools             44.0.0
threadpoolctl          3.1.0
tifffile               2022.2.9
typing_extensions      4.1.1
```

## Additional context

Development is early, but I'm working on a domain specific set of [augmentations for astronomy](https://github.com/mb010/AstroAugmentations) building on Albumentations, where A.PixelDropout is used to emulate instrumentation errors / certain types of noise.

**Comment by i-aki-y** [comment]
This feature looks to be added after the current version 1.1.0 was released and has not been released yet.

**Comment by mb010** [comment]
Thanks! I didn't track that I had designed my code around the git installed version. Any ideas on when the next update might be released? @i-aki-y

**Comment by i-aki-y** [comment]
@mb010  Sorry, I'm not sure about that. 

I think a simple workaround is to install the master version by using `git+https://...` syntax.
The drawback is that this may be unstable.

Another workaround would be to copy the related codes into your codebase, and replace them after the next albumentations version is released.
Since the code looks well isolated, see #1082, copying a `pixel_dropout` function and a `PixelDropout` class seem to work.
(For other dependencies, you can import from the current version by:`from albumentations import preserve_shape, DualTransform`.)
