### ISSUE TITLE
 module 'albumentations' has no attribute 'Compose

### ISSUE THREAD

**Issue by dugudongfangshuo** [albumentations-team/albumentations#1132]
on windows
     ```pip install albumentations```
I run this code 

```import albumentations as A
import cv2
transform = A.Compose([
    A.RandomCrop(width=256, height=256),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
])
```

result is  module 'albumentations' has no attribute 'Compose

**Comment by Dipet** [comment]
What version of the library are you using?
What shows `print(A.__version__)`?

**Comment by nivesha2000** [comment]
> What version of the library are you using? What shows `print(A.__version__)`?

It shows 1.3.0 version for me

**Comment by Dipet** [comment]
It looks strange. Try to trace imports by calling your test script like this:
```
python -v -m test.py
```
