### ISSUE TITLE
Support Keypoints as targets for CoarseDropout

### ISSUE THREAD

**Issue by enaskopelja** [albumentations-team/albumentations#1136]
## 🐛 Bug
Coarse dropout is listed as supported with Keypoints targets _(see image below or [source](https://albumentations.ai/docs/getting_started/transforms_and_targets/#spatial-level-transforms))_ but raises: 

`NotImplementedError: Method apply_to_keypoint is not implemented in class CoarseDropout`.

<img width="1002" alt="Untitled" src="https://user-images.githubusercontent.com/50400193/156389508-b5ef4a58-b034-4d37-ba11-af8fa595ef98.png">

## To Reproduce
```python
import albumentations as A
import numpy as np

AUGMENTATION = A.Compose(
    [
        A.CoarseDropout(always_apply=True)
    ],
    keypoint_params=A.KeypointParams(format="xy"),
    p=1,
)

if __name__ == '__main__':
    image = np.ones((30, 30))
    label = np.array(
        [
            [10, 10],
            [10, 20],
            [20, 10],
            [20, 20],
        ]
    )

    augmented = AUGMENTATION(image=image, keypoints=label)
    augmented_image, augmented_label = augmented["image"], augmented["keypoints"]

```

## Expected behavior
`CoarseDropout` of the rectangular regions in the image. Removes or better still, in some way marks keypoints that are covered by the rectangular regions.

## Environment
 - Albumentations version (e.g., 0.1.8): `1.1.0`
 - Python version (e.g., 3.7): `3.9`
 - OS (e.g., Linux): `macOS Monterey 12.2.1`
 - How you installed albumentations (`conda`, `pip`, source): `pip`

**Comment by bartoszptak** [comment]
I have the same issue.
**Environment:**
* Albumentations version (e.g., 0.1.8): `1.1.0`
* Python version (e.g., 3.7): `3.9.5`
* OS (e.g., Linux): Ubuntu `20.04`
* How you installed albumentations (conda, pip, source): `pip`

**Comment by alercelik** [comment]
Issue continues with latest pip version (1.3.0) as well. Installing from source did not fix too.

**Comment by Dipet** [comment]
Problem fixed with latest release. Everything works fine, I can not reproduce any problem with clear virtual environment.
