### ISSUE TITLE
Clarifying the generation of images 

### ISSUE THREAD

**Issue by lchunleo** [albumentations-team/albumentations#1138]
## 📚 Documentation
I like to check my understanding on the use of albumentations in pytorch .

When the albumentations is applied to the set of images in the albumentations pipeline , are there actually new images generated on top of the original data? E.g. original data set is 2000, at every epoch , the data is taken and applied transform prior used for training. Thus am I seeing 2000 augmented images plus 2000 original images ? Or the number of epochs is the key to generate multiple images ? I read in the doc that a new image is created through each transform thus running multiple times (via epoch) create new images ? Thanks 

Is achieving multiple images should be done with albumentations outside the pipeline ? E.g. a script to do the albumentations on the original images to create more of them ? Thanks 

Regarding the Compose function, it seem that if we put it 10 different types of augmentations method, only 1 image will be generated each time and not multiple of them ? Is this correct ? Thanks

**Comment by ternaus** [comment]
Yes
