### ISSUE TITLE
What is the simplest way to achive all 8 dehidral transform with equal probability?

### ISSUE THREAD

**Issue by Tomakko** [albumentations-team/albumentations#1148]
Hi,

as described [here](https://albumentations.ai/docs/examples/example_kaggle_salt/#Non-destructive-transformations.-Dehidral-group-D4) there are 8 possibilities to rotate/flip/transpose an image. What is the easiest way to achive equal probability for all 8 cases?

My first approach was 

`dehidral_tf = A.OneOf(
            [
                A.HorizontalFlip(p=1),
                A.VerticalFlip(p=1),
                A.RandomRotate90(p=1),
                A.Transpose(p=1)
            ],
            p=0.875
            )`

but that would mean that the 90° rotations are underrepresented if i understand its mechanics correctly.

Any help is appreciated!

**Comment by ternaus** [comment]
```
dehidral_tf = A.Compose( [ A.HorizontalFlip(p=0.5), A.RandomRotate90(p=1)], p=1 )
```
Will do the job.
