### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'BORDER_CONSTANT'

### ISSUE THREAD

**Issue by xixivvv** [albumentations-team/albumentations#1153]
## 🐛 Bug

        cval: Union[int, float, Sequence[int], Sequence[float]] = 0,
        cval_mask: Union[int, float, Sequence[int], Sequence[float]] = 0,
        mode: int = cv2.BORDER_CONSTANT,
        fit_output: bool = False,
        always_apply: bool = False,
        p: float = 0.5,
    ):

    mode: int = cv2.BORDER_CONSTANT,
AttributeError: module 'cv2' has no attribute 'BORDER_CONSTANT'

How to solve this problem? Should "cv2.BORDER_CONSTANT" be quoted in source code?

 - Albumentations version ( 0.1.10):
 - Python version ( 3.8):
 - OS ( Linux):
 - How you installed albumentations (pip):

**Comment by ternaus** [comment]
Cannot reproduce:

```python
In [3]: import cv2

In [4]: cv2.BORDER_CONSTANT
Out[4]: 0

```
