### ISSUE TITLE
Affine translate_percent dictionary params default to 1.0 instead of 0.

### ISSUE THREAD

**Issue by amitz25** [albumentations-team/albumentations#1155]
## 🐛 Bug

When using Affine with translate_percent set to a dictionary, and setting only "x" or "y" (but not both), the other unset param will be 1.0 by default instead of 0. That means cutting the whole axis resulting in a meaningless black image.

## To Reproduce
transforms = A.Affine(translate_percent={"x": 0.2})
This augmentation will now blacken any image it is applied on as it is initialized to A.Affine(translate_percent={"x": 0.2, "y": 1.0})

## Expected behavior
the unset variable ("y" in the above example) should be 0 by default instead of 1 when using translate_percent

**Comment by Dipet** [comment]
Fixed in #1183
