### ISSUE TITLE
numpy randn is used in random_utils.rand

### ISSUE THREAD

**Issue by hir0sa** [albumentations-team/albumentations#1165]
## 🐛 Bug
In the recently introduced `random_utils` module (#1070),  `rand` function uses numpy `randn` ( _N(0, 1)_ ) internally which results in unexpected behavior of some functions. For example,   [elastic_transform](https://github.com/albumentations-team/albumentations/blob/89a675cbfb2b76f6be90e7049cd5211cb08169a5/albumentations/augmentations/geometric/functional.py#L234) uses `random_utils.rand` as _U(0, 1)_. 

https://github.com/albumentations-team/albumentations/blob/880c1aaed10ab74cfe851496a476c1c34cadcd0f/albumentations/random_utils.py#L29-L32

 https://github.com/albumentations-team/albumentations/blob/89a675cbfb2b76f6be90e7049cd5211cb08169a5/albumentations/augmentations/geometric/functional.py#L295

## Expected behavior
`random_utils.rand` should use numpy `rand` ( _U(0, 1)_ )  instead of `randn` ( _N(0, 1)_ ).

## Environment

 - Albumentations version (e.g., 0.1.8): master [89a675c](https://github.com/albumentations-team/albumentations/commit/89a675cbfb2b76f6be90e7049cd5211cb08169a5)
 - Python version (e.g., 3.7): 3.8
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by Dipet** [comment]
Fixed in #1166
