### ISSUE TITLE
How can I use albumentations for Multi-label pixel

### ISSUE THREAD

**Issue by AceCHQ** [albumentations-team/albumentations#1172]
Hello, I want to use albumentations to enhance multi-label GT. My GT is composed of multiple channels, whose value is 0 or 1. But albumentations  can't accept GT with more than 3 channels, how should I solve it? Thank you!

**Comment by Dipet** [comment]
I am not sure I understand correctly what you want to do. Could you give a small example?

**Comment by AceCHQ** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you! I have solved it.
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    On 5/27/2022 17:29，Mikhail ***@***.***> wrote： 



I am not sure I understand correctly what you want to do. Could you give a small example?
