### ISSUE TITLE
slant_upper and slant_lower has no effect in RandomRain

### ISSUE THREAD

**Issue by mucsacso03** [albumentations-team/albumentations#1175]
## 🐛 Bug

I'm using the RandomRain transformation and selecting any slant_upper and slant_lower value won't have any effect on the outcome of the rain. The rain looks always the same.

Code:
`x = RandomRain(slant_lower=10, slant_upper=20, blur_value=3, p=1, rain_type='drizzle')(image=x)["image"]`

## Environment

 - Albumentations version: 1.1.0
 - Python version: 3.8.10
 - OS: Linux
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by Dipet** [comment]
Fixed in #1179
