### ISSUE TITLE
CoarseDropout mask augmentation returns modified image instead of modified mask

### ISSUE THREAD

**Issue by faustomorales** [albumentations-team/albumentations#1178]
I can file a PR to fix this but I wanted to check whether my understanding is correct or not. Shouldn't this method return `cutout(mask, holes, mask_fill_value)` instead of `cutout(img, holes, mask_fill_value)`? It seems odd that the mask augmentation would result in the input image being returned.

https://github.com/albumentations-team/albumentations/blob/4afa308646dd9fa5e7cd37b8dcc38da416a6a5ad/albumentations/augmentations/dropout/coarse_dropout.py#L100-L109

**Comment by Dipet** [comment]
`img` is a name for local variable. In that case `img` will contain the mask.
