### ISSUE TITLE
Feature: Proper RGB shifts to avoid value saturation

### ISSUE THREAD

**Issue by zakajd** [albumentations-team/albumentations#1194]
Hi, thanks again for the very useful library.

I have a comment / feature requests to modify the behaviour of RGB shift augmentation. What it currently does is, basically creates a linear mapping from original values to a shifted by deltaR, deltaG, deltaB values using LUT. 

Don't know what was the initial idea behind this augmentation, but I would assume that it was a way to mimic improper white-balance. One issue with such approach is that it leads to values saturation and clipping. E.g. if I shift R by +128 this would results in part of red pixels going way beyond [0, 255] range -> clipping -> information loss.

In professional software like Photoshop, RGB shifts implemented in a different fashion. Instead of adding fixed value to all value ranges, they add something closer to a parabola, so that 0 values are always stay at zero, no matter how big is added delta, and 255 values stay at max, without over saturation. See an example image below of how corresponding curves for red and blue channels could look like for a different values of delta. 

![](https://static1.discoverdigitalphotography.com/wp-content/uploads/2011/image-editing-adjusting-color-with-the-curves-tool/curves-color-correct.png)

My proposal: modify `shift_rgb` function to generate something close to this. 

Pros:
- Closer mimic colour problems on photographs
- Avoid value clipping

Cons:
- Introduce breaking change in long-existing augmentation 
- More computationally heavy aug -> slower execution time. 

What do you think? I can dedicate some time to implement this, if you are interested.

**Comment by Dipet** [comment]
Hello, thanks for your contribution to the library.
I think it is a good idea!
But I think it is better not to change the logic, but add a new option as a `method` or `mode`, something like `simple` - the current implementation and `advanced` - your proposal.

**Comment by zakajd** [comment]
Found repo, which basically solves the same problem - [correct White-Balance augmentation](https://github.com/mahmoudnafifi/WB_color_augmenter). 
Maybe will just port Python code from there (MIT license allows this) 🤔

**Comment by zakajd** [comment]
Closing this issues, because found that RandomToneCurve augmentation does exactly what I proposed

**Comment by zakajd** [comment]
Okey, not exactly what I wanted. It now only changes tone curve for the whole image, not per channel, so new augmentation is still needed. Or maybe just modify the `RandomToneCurve` with `per_channel` flag as for some other augmentations.

**Comment by ternaus** [comment]
Addressed in https://github.com/albumentations-team/albumentations/pull/1827
