### ISSUE TITLE
Version of scikit-image

### ISSUE THREAD

**Issue by 23pointsNorth** [albumentations-team/albumentations#1195]
## 🐛 Bug

In larger systems with more dependencies, we have external reasons to track the latest version of libraries. Right now, [scikit-image 0.19.3 ](https://pypi.org/project/scikit-image/) has been released, which conflicts with the top version of Albumentations as specified in the [setup.py](https://github.com/albumentations-team/albumentations/blob/master/setup.py#L8) of <0.19.

## To Reproduce

1. Install latest of scikit-image 
1. Install latest of albumentations

## Expected behavior

Not to specify a top version for external libraries.

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

**Comment by Dipet** [comment]
Related PR: #1121

**Comment by 23pointsNorth** [comment]
Also #1076

**Comment by Dipet** [comment]
Fixed in #1121

**Comment by 23pointsNorth** [comment]
Thanks for the quick turnaround! Do you know how often patch versions are generally released?

**Comment by Dipet** [comment]
To be honest, not very often. Usually, once every few months. Maybe more often if there are a lot of changes.
