### ISSUE TITLE
Mask transformed differently than image.

### ISSUE THREAD

**Issue by davidrzs** [albumentations-team/albumentations#1196]
## 🐛 Bug

I want to have the mask rotated the same way that the image is being rotated but they are being rotated differently.

## To Reproduce

```python
# somewhat simplified python code of problem:

sat_img = cv2.imread(str(current_image_path))
sat_img = cv2.cvtColor(sat_img, cv2.COLOR_BGR2RGB)

segmentation = cv2.imread(str(current_label_path))

print('before shape:', sat_img.shape, segmentation.shape)
# prints: before shape: (400, 400, 3) (400, 400)

aug = A.augmentations.geometric.rotate.Rotate()
sample = aug(image=sat_img, mask=segmentation)

f, axarr = plt.subplots(2)

axarr[0].imshow(train_data[s4][0])
axarr[1].imshow(train_data[s4][1])

```
Problem: it rotates the mask separately from the image (not same rotation) Horizontal and Vertical Flipping have the same problem.

Unfortunately, I cannot include a screenshot as the data is confidential.

## Expected behavior

Both rotated by x degrees, not image by x and mask by y with y being different from x

## Environment

 - Albumentations version (e.g., 0.1.8): 1.2.0
 - Python version (e.g., 3.7): 3.8
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed albumentations (`conda`, `pip`, source): pip (via pipenv)
 - Any other relevant information:

## Additional context

I might also be really stupid and just use it wrongly, but after hours of debugging I am still puzzled, hence me opening this bug / question. Or is this actually the desired behavior?

**Comment by Dipet** [comment]
All works fine:
```python
import albumentations as A
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv

sat_img = np.zeros([400, 400, 3], np.uint8)
sat_img[:, :, 0] = 255

segmentation = np.zeros([400, 400], np.uint8)
segmentation += 255

aug = A.Rotate((45, 45), p=1, border_mode=cv.BORDER_CONSTANT, value=0, mask_value=0)
sample = aug(image=sat_img, mask=segmentation)

plt.subplot(211)
plt.imshow(sample["image"])
plt.subplot(212)
plt.imshow(sample["mask"], cmap="gray")
plt.show()
```

In your example you plot different data

**Comment by davidrzs** [comment]
Thank you so much. I feel very, very embarrassed. It was a very stupid problem on my side. Namely, I polled the transform twice in my code, once to get the mask and once to get the image, hence the random augmentations were different. So sorry for this.
