### ISSUE TITLE
Add D4 augmentaion

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1201]
Add D4 augmentation, which is effectively:

```
D4 = A.Compose( [ A.HorizontalFlip(p=0.5), A.RandomRotate90(p=1)], p=1 )
```

**Comment by ternaus** [comment]
@bonlime what is the objection to this transformation? :)

**Comment by bonlime** [comment]
@ternaus I don't think it's useful to add something that could be achieved by 2 lines of current augs. For me augmentations list is always pretty long and has 10+ augs. Saving one line wouldn't help.

**Comment by ternaus** [comment]
Added in https://github.com/albumentations-team/albumentations/pull/1660
