### ISSUE TITLE
Confusion of the criteria for the pixel coordinate origin

### ISSUE THREAD

**Issue by whikwon** [albumentations-team/albumentations#1209]
## 📚 Documentation

I am curious about the criteria for pixel coordinate origin. In some cases (-0.5, -0.5):[keypoint_rotate](https://github.com/albumentations-team/albumentations/blob/3f321e23ef301a28ef6e2bf52d7b1aebb3ac1fca/albumentations/augmentations/geometric/functional.py#L166) and in some cases (0, 0):[keypoint_shift_scale_rotate](https://github.com/albumentations-team/albumentations/blob/3f321e23ef301a28ef6e2bf52d7b1aebb3ac1fca/albumentations/augmentations/geometric/functional.py#L202) seem to be used.

**Comment by ternaus** [comment]
Fixed
