### ISSUE TITLE
[QUESTION] Differences between always_apply and p

### ISSUE THREAD

**Issue by domef** [albumentations-team/albumentations#1213]
Most of the augmentations have these 2 parameters: `always_apply` and `p`.

If I want an augmentation to be always applied, should I use `always_apply=True` or `p=1.0`? What's the difference between these 2 parameters?

**Comment by Shubhamai** [comment]
Just found out about it in the FAQ of the docs - [Augmentations have a parameter named p that sets the probability of applying that augmentation, but they also have the always_apply parameter that can either be True or False. What is the difference between p and always_apply? Is always_apply=True equals to p=1.0?](https://albumentations.ai/docs/faq/#augmentations-have-a-parameter-named-p-that-sets-the-probability-of-applying-that-augmentation-but-they-also-have-the-always_apply-parameter-that-can-either-be-true-or-false-what-is-the-difference-between-p-and-always_apply-is-always_applytrue-equals-to-p10)

**Comment by domef** [comment]
Thank you very much!
