### ISSUE TITLE
Created an application to experiment with albumentations (albumentations demo)

### ISSUE THREAD

**Issue by phrasenmaeher** [albumentations-team/albumentations#1232]
For those interested in experimenting with `albumentation`'s transformations, a demo (kindly hosted by Streamlit) is available [here](https://phrasenmaeher-image-augmentations-visualization-start-2s9zvq.streamlitapp.com). It runs in your browser and lets you build your own pipelines and visualize their effects on the input data.
Additionally, you can explore individual transformations in depth and change (some of) their parameters.

The underlying code is [available on GitHub](https://github.com/phrasenmaeher/image_augmentations_visualization).

**Comment by ternaus** [comment]
New demo works on https://explore.albumentations.ai/
