### ISSUE TITLE
Разные названия одного параметра.

### ISSUE THREAD

**Issue by MichaelMonashev** [albumentations-team/albumentations#1236]
В [A.Rotate](https://albumentations.ai/docs/api_reference/full_reference/#albumentations.augmentations.geometric.rotate.Rotate) и [A.ShiftScaleRotate](https://albumentations.ai/docs/api_reference/full_reference/#albumentations.augmentations.geometric.transforms.ShiftScaleRotate) ОДИН И ТОТ ЖЕ метод поворота bbox-ов задаётся параметрами с РАЗНЫМИ названиями (`method` и `rotate_method`), что вводит путаницу и добавляет неудобство.

**Comment by Dipet** [comment]
Хм, справедливо. Что-то мы по запарке не обратили внимания.
@ternaus @creafz Мы уже релизнули эти изменения в последнем минорном релизе. Кажется что ещё можно изменить имя без особых проблем с обратной совместимостью. Как думаете?

**Comment by MichaelMonashev** [comment]
Я тоже не заметил. Везде написал `rotate_method`, запускаю, не работает. Смотрю код. Там надо `method` писать. Исправил везде, запускаю, не работает. Только потом понял, что в одной трансформации одно название параметра, а в другом - другое.

**Comment by Dipet** [comment]
Fixed in #1258
