### ISSUE TITLE
Get different transforms (with albumentation API) of the same Image Samples (as in SimCLR approach)

### ISSUE THREAD

**Issue by zeeshannisar** [albumentations-team/albumentations#1238]
I am trying to get 2 different transforms of the same images using **`tf.Dataset`** Pipeline and **`Albumentation`**. 

With **`tf.Dataset`** Pipeline I have loaded the dataset using following code snippet: The code is available [Here][1] 

Finally modifying the above dataset pipeline according to the tranforms:

    filenames_ds = tf.data.Dataset.from_tensor_slices(self.get_files())
    dataset = filenames_ds.map(self.parse_image, num_parallel_calls=self.AUTOTUNE)
    dataset = dataset.map(self.process_augmentation, num_parallel_calls=self.AUTOTUNE).prefetch(self.AUTOTUNE)
    dataset = dataset.map(self.set_shape, num_parallel_calls=self.AUTOTUNE)
    dataset = self.configure_performance(dataset)

All this code is perfectly working to generate transforms for the image_samples. 

What I want is to generate two different transforms for the same image sample . Like if I have image A I want two different transforms of this image transform_1_A and tranform_2_A as I have attached in the picture below [![Goal][3]][3]. 

I have tweaked the above code (a bit) to achieve this but I always get the same transformations as you can see in the results below.    

I am stuck here and therefore I am making a request to the experts like (the community here) to please help me achieving this goal. Thanks in advance. 

  [1]: https://towardsdatascience.com/what-is-the-best-input-pipeline-to-train-image-classification-models-with-tf-keras-eb3fe26d3cc5
  [2]: https://www.kaggle.com/code/junyingsg/tf-data-pipeline-with-albumentation-cutmix-up/notebook
  [3]: https://i.stack.imgur.com/Gvy9e.png

**Comment by zeeshannisar** [comment]
@ZFTurbo @BloodAxe @Dipet

**Comment by Dipet** [comment]
I can not understand what wrong. Everythink must work ok from albumentations side.
```python
import random
import cv2 as cv
import albumentations as A
import matplotlib.pyplot as plt

random.seed(0)
flip_p = 0.5


def augment_function(image):
    transform = A.Compose(
        [
            A.RandomResizedCrop(height=256, width=256, scale=(0.2, 1.0), p=0.5),
            A.Flip(p=flip_p),
            A.ColorJitter(brightness=0.8, contrast=0.8, saturation=0.8, hue=0.2, p=0.8)]
    )

    return transform(image=image)["image"], transform(image=image)["image"]


img = cv.imread(r"C:\Users\dipet\parrot.jpg")
img = cv.cvtColor(img, cv.COLOR_BGR2RGB)

img1, img2 = augment_function(img)

plt.subplot(131, title="original")
plt.imshow(img)
plt.subplot(132, title="img1")
plt.imshow(img1)
plt.subplot(133, title="img2")
plt.imshow(img2)
plt.show()
```
![image](https://user-images.githubusercontent.com/7512250/181776002-9eeb02e5-5254-4f81-9a64-bb5eaef2c0ce.png)
