### ISSUE TITLE
Streamlit demo on website is broken

### ISSUE THREAD

**Issue by qzyu888** [albumentations-team/albumentations#1248]
## 🐛 Bug

The streamlit app (https://albumentations-team-albumentations-demo-srcapp-w930cw.streamlitapp.com) on the documentation (https://albumentations.ai/docs/getting_started/image_augmentation/) is broken.

## To Reproduce

1. Go to the document link above.
2. Find the link for the demo that supposedly shows the augmentations.
3. See the blank page.

## Expected behavior

A streamlit app that shows the augmentations.

## Environment

 - Albumentations version (e.g., 0.1.8): N/A
 - Python version (e.g., 3.7): N/A
 - OS (e.g., Linux): Mac
 - How you installed albumentations (`conda`, `pip`, source): N/A
 - Any other relevant information: The website as of 08/03/2022.

**Comment by Dipet** [comment]
Now everything works fine for me, please check again. Please, write about the demo project on the project page https://github.com/albumentations-team/albumentations-demo

**Comment by qzyu888** [comment]
Oh, it seems to not work with Safari on Mac OS. I loaded it on Chrome and it worked. I think this is a problem out of this team's hands.
