### ISSUE TITLE
Fill_value as a float

### ISSUE THREAD

**Issue by davidecarnevali** [albumentations-team/albumentations#1251]
Hi,
The documentation for `fill_value` (e.g. in GridDropOut) state this parameter requires a INT value.
However using a float does not raise any error.
Moreover, it seems to accept also multiple values (as a tensor). Indeed setting it to (0.5,0.5,0.5) to represent the gray color when using RGB images, it does not raise any error too.
Which is the exact format for this parameter? Am I allowed to use float and different values for each channel?
Thank you

**Comment by davidecarnevali** [comment]
I saw this issue has been marked as "enhancement".
Because I am actually running tests, could someone meanwhile tell me if using fill_value=(0.5,0.5,0.5) is correct to represent grey color in RGB images normalized between 0 and 1?
Can I use this format?
Thank you

Davide

**Comment by Dipet** [comment]
Sorry, that I didn't write the answer. Yes, `0.5,0.5,0.5` means grey color.
Example:
```python
import albumentations as A
import numpy as np
import matplotlib.pyplot as plt


img = np.full([100, 100, 3], 0, dtype=np.float32)
t = A.Compose([A.GridDropout(fill_value=(0.5, 0.5, 0.5), p=1)])
res = t(image=img)["image"]
plt.imshow(res)
plt.show()
```

> Which is the exact format for this parameter?

Any value that represents image color. For grayscale image it will be single number (float or int), for multichannel images - single number or sequence of number with length equal to count of channels.  

I added these tags because we need enhance documentation and add correct types and descriptions for all functions that uses fill values.

**Comment by davidecarnevali** [comment]
Thank you!
Davide

**Comment by Dipet** [comment]
I can not reproduce the problem

```python
import albumentations as A
import numpy as np
import matplotlib.pyplot as plt
import random

random.seed(0)
np.random.seed(0)

img = np.full([100, 100, 3], 0, dtype=np.float32)

t = A.Compose(
    [
        A.LongestMaxSize(max_size=768, interpolation=1),
        A.PadIfNeeded(min_height=768, min_width=768, border_mode=0, value=(1, 1, 1)),
        A.HorizontalFlip(),
        A.VerticalFlip(),
        A.Rotate(limit=180, border_mode=0, value=(1, 1, 1), p=0.7),
        A.GridDropout(
            ratio=0.3,
            unit_size_min=128,
            unit_size_max=384,
            random_offset=True,
            fill_value=(0.5, 0.5, 0.5),
            mask_fill_value=None,
            always_apply=False,
            p=0.7,
        )
    ]
)
A.save(t, "test.json")
t = A.load("test.json")

res = t(image=img)["image"]
plt.imshow(res)
plt.show()
```

**Comment by davidecarnevali** [comment]
Hi,
I got it....I was using ver. 1.0.3
Now that I have updated to the latest one everything works fine
Thank you
D.
