### ISSUE TITLE
ImportError: cannot import name 'Crop'

### ISSUE THREAD

**Issue by lappemic** [albumentations-team/albumentations#1256]
## 🐛 Bug

If try to import the different transformation methods of albumentations l always get an Import Error.

**Import statement:**
```Python
from albumentations.augmentations.transforms import Crop, VerticalFlip, HorizontalFlip, Flip, Transpose, Resize, CenterCrop, RandomCrop, Cutout, RandomSizedCrop, OpticalDistortion, GridDistortion, ElasticTransform
```
Which leads to the following import error:
```Python
ImportError                               Traceback (most recent call last)
[<ipython-input-25-bc25519adb09>](https://localhost:8080/#) in <module>()
----> 1 from albumentations.augmentations.transforms import Crop, VerticalFlip, HorizontalFlip, Flip, Transpose, Resize, CenterCrop, RandomCrop, Cutout, RandomSizedCrop, OpticalDistortion, GridDistortion, ElasticTransform

ImportError: cannot import name 'Crop' from 'albumentations.augmentations.transforms' (/usr/local/lib/python3.7/dist-packages/albumentations/augmentations/transforms.py)
```
## Expected behavior
It should just import the stated functions.

## Environment
The error occurs locally (jupyter lab on macos) as well as in google colab.

## Additional context
I try actually to import [solaris](https://github.com/CosmiQ/solaris) which throughs errors as well, why i try to install the dependencies which crash individually.

**Comment by Dipet** [comment]
`from albumentations import Crop` or `from albumentations.augmentations.crops.transforms import Crop`
