### ISSUE TITLE
Some classes described in the documentation are missing (or are in different locations) in the library 

### ISSUE THREAD

**Issue by sufftea** [albumentations-team/albumentations#1261]
## 📚 Documentation

Whenever I try to use one of these classes I get `no attribute` error:
- `albumentations.augmentations.crops.transforms.BBoxSafeRandomCrop`,
- `albumentations.augmentations.geometric.transforms.HorizontalFlip` (this one exists but is located directly in `albumentations`)
-  `albumentations.augmentations.geometric.transforms.OpticalDistortion`

The error:
```
AttributeError: module 'albumentations.augmentations.geometric.transforms' has no attribute 'OpticalDistortion'
```

My library version:
```
print(A.__version__) # 1.2.1
```
```
$ pip show albumentations
Name: albumentations
Version: 1.2.1
Summary: Fast image augmentation library and easy to use wrapper around other libraries
Home-page: https://github.com/albumentations-team/albumentations
Author: Buslaev Alexander, Alexander Parinov, Vladimir Iglovikov, Eugene Khvedchenya, Druzhinin Mikhail
Author-email: 
License: MIT
Location: /home/alexander/miniconda3/envs/tf/lib/python3.9/site-packages
Requires: numpy, opencv-python-headless, PyYAML, qudida, scikit-image, scipy
Required-by: 
```
This is the same version that is shown on the documentation website currently

**Comment by Dipet** [comment]
It looks like website is taking sources from the github master branch and it is different to latest pip version. @creafz I'm right? Can we add to website select button to choose albumentations version based on github tags?
@KhorunzhyiAl Why you import augs using direct module path?
Try this:
```python
from albumentations import BBoxSafeRandomCrop, HorizontalFlip, OpticalDistortion
```

**Comment by KhorunzhyiAl** [comment]
> Try this:
> 
> from albumentations import BBoxSafeRandomCrop, HorizontalFlip, OpticalDistortion

Thanks! New to Python, didn't think of that
