### ISSUE TITLE
Support of float32 dtype for `InvertImg`

### ISSUE THREAD

**Issue by Dipet** [albumentations-team/albumentations#1263]
Add correct work with float32 dtype for [`InvertImg`](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.InvertImg)

**Comment by dmitrie-ai** [comment]
Hey, I would like to take this on.
My guess is that the purpose of `float p` is to be the probability of returning the inverted image. Is that correct?
And if so, in what circumstances is there a need for this feature?
Thank you

**Comment by dmitrie-ai** [comment]
After implementing it as such, one of the tests fail. I think this is because the test for InvertImg doesn't account for this probability `p`.

**Comment by ternaus** [comment]
Works.
