### ISSUE TITLE
Float input values for RandomGamma

### ISSUE THREAD

**Issue by zahragolpa** [albumentations-team/albumentations#1286]
## 🐛 Bug

I get an error when I run RandomGamma transform with a float `gamma_limit` value.

## To Reproduce

1. Run RandomGamma with a float `gamma_limit` value.

```
import albumentations as A
import cv2

input_image_numpy = cv2.imread(PATH_TO_INPUT_IMAGE)
transform = A.Compose([A.RandomGamma(gamma_limit=(80.8, 120.2), p=1)])
transformed = transform(image=input_image_numpy)
transformed_image = transformed["image"]
cv2.imwrite('output.png', transformed_image)
```

The error I get: 

```
ValueError: non-integer arg 1 for randrange()
```

## Expected behavior

Should produce the output image even when input is float, as stated in the [documentation](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.RandomGamma).
## Environment

 - Albumentations version: albumentations==1.1.0
 - Python version: Python 3.8.8
 - OS: macOS

**Comment by Dipet** [comment]
Fixed  in #1287
