### ISSUE TITLE
Cannot import the Spatter augmentation.

### ISSUE THREAD

**Issue by hoel-bagard** [albumentations-team/albumentations#1288]
## 🐛 Bug

I cannot import the [Spatter augmentation](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.Spatter).

## To Reproduce

1. Pip install albumentations.
2. In a python interpreter import albumentations and try to access the Spatter augmentation.

```
In [1]: import albumentations

In [2]: albumentations.Spatter
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 albumentations.Spatter

AttributeError: module 'albumentations' has no attribute 'Spatter'
```

```
In [1]: from albumentations import Spatter
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from albumentations import Spatter

ImportError: cannot import name 'Spatter' from 'albumentations' (/home/hoel/work/grasping/PyTorchGrasping/venv/lib/python3.10/site-packages/albumentations/__init__.py)
```

## Expected behavior

The augmentation can be used without error.

## Environment

 - Albumentations version: 1.2.1
 - Python version: 3.10
 - OS: Linux
 - How you installed albumentations: pip
 - Any other relevant information: It seems to work fine when installing from source.

**Comment by Dipet** [comment]
This tansform is not released yet to PYPI. Try to install library from github: `pip install git+https://github.com/albumentations-team/albumentations`
We will releasea  new version to PYPI soon.

**Comment by ternaus** [comment]
```python

In [1]: import albumentations
   ...:
   ...: albumentations.Spatter
Out[1]: albumentations.augmentations.transforms.Spatter

```
