### ISSUE TITLE
Any plan to support on-GPU augmentations?

### ISSUE THREAD

**Issue by nttstar** [albumentations-team/albumentations#1292]
Hello, is there any plan to support on-devices(GPU) augmentations? It will be quite useful to boost the performance on multi-GPUs servers.

**Comment by Dipet** [comment]
Unfortunately, now we don't have our own resources to add this support. If someone tries add this functionality to the library, we will be very happy.
If you need GPU augmentations you might look to https://github.com/NVIDIA/DALI and https://github.com/kornia/kornia

**Comment by ternaus** [comment]
No plans to support DALI
