### ISSUE TITLE
PadIfNeeded bug

### ISSUE THREAD

**Issue by MichaelMonashev** [albumentations-team/albumentations#1295]
## 🐛 Bug
albumentations              1.2.1
Python 3.8.10
Ubuntu 20.04.3 LTS

Эта последовательность аугментаций иногда выдавала ошибку, что в RandomCrop() пришла картинка или маска размера 319х320, хотя ожидается не менее 320х320. Видимо PadIfNeeded() иногда ошибается на единичку с размером.
```
Compose([
...
        PadIfNeeded(min_height=320, min_width=320, position="random", border_mode=cv2.BORDER_CONSTANT, value=(0,0,0), p=1.0),
        RandomCrop(320, 320, always_apply=True, p=1.0),
...
        HorizontalFlip(p=0.5),
        RandomRotate90(p=1.0),

        Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(transpose_mask=True),
    ], p=p)
```

Ошибка:
```
  File "/home/xxx/yyy/train_segmentation.py", line 867, in __next__
    augmented = self.augmentation(**data)
  File "/home/xxx/.local/lib/python3.8/site-packages/albumentations/core/composition.py", line 205, in __call__
    data = t(force_apply=force_apply, **data)
  File "/home/xxx/.local/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 98, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 111, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/home/xxx/.local/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 240, in apply_to_mask
    return self.apply(img, **{k: cv2.INTER_NEAREST if k == "interpolation" else v for k, v in params.items()})
  File "/home/xxx/.local/lib/python3.8/site-packages/albumentations/augmentations/crops/transforms.py", line 48, in apply
    return F.random_crop(img, self.height, self.width, h_start, w_start)
  File "/home/xxx/.local/lib/python3.8/site-packages/albumentations/augmentations/crops/functional.py", line 46, in random_crop
    raise ValueError(
ValueError: Requested crop size (320, 320) is larger than the image size (319, 320)
```

**Comment by MichaelMonashev** [comment]
Обновился до albumentations 1.3.0, ошибка не пропала.
Добавил `mask_value=(0,0,0)`, ошибка не пропала.
Убирал `position="random"`, ошибка не пропала.

**Comment by MichaelMonashev** [comment]
Ошибка какая-то плавающая. Иногда одну эпоху аугментирует нормально, вторую тоже нормально, а на третьей падает.

**Comment by Dipet** [comment]
что-то не получается вопроизвести
```python
import albumentations as A
import numpy as np
import cv2
from tqdm import tqdm

t = A.Compose([
    A.PadIfNeeded(min_height=320, min_width=320, position="random", border_mode=cv2.BORDER_CONSTANT, value=(0,0,0), p=1.0),
    A.RandomCrop(320, 320, always_apply=True, p=1.0),
])

for i in tqdm(range(320 * 320)):
    x = i // 320
    y = i % 320
    img = np.empty([x, y, 3], dtype=np.uint8)
    t(image=img)
```

**Comment by MichaelMonashev** [comment]
Так и у меня воспроизводится редко. Долго работает, а потом ошибку выдаёт. И возможно оно падает не на изображении, а на паре: картинка+маска.

**Comment by MichaelMonashev** [comment]
opencv-python-headless      4.5.5.64

попробую его обновить, может в нём бага...

**Comment by Dipet** [comment]
Попробуй поставить try except и при ошибке вывести параметры маски и
изображения. Скорее всего у тебя маска и изображение по шейпам на 1 пиксел
отличаются во время ошибки

вс, 25 сент. 2022 г., 21:44 Michael Monashev ***@***.***>:

**Comment by MichaelMonashev** [comment]
Хорошая мысль! Спасибо!

**Comment by MichaelMonashev** [comment]
Ты оказался прав. Есть пары картинка+маска, где размеры не совпадаю. Причём не на пиксель, а вот так: (299, 400, 3) (374, 500, 1) . Как раз из-за округления будут отклонения в 1 пиксель туда-сюда.

Правда сейчас нет возможности проверить, что ошибка именно в этом. Другая нейронка учится и не хочу прерывать...

**Comment by MichaelMonashev** [comment]
Ошибка конечно пакостная. Я слышал, что операция округления при работе с float-ами в процессоре не детерминирована и может на один и тот же специально подобранный аргумент выдавать разные результаты в зависимости от такта процессора. Здесь видимо так и было.
