### ISSUE TITLE
Unchange array by using albumentations

### ISSUE THREAD

**Issue by DeidaraYang** [albumentations-team/albumentations#1302]
## 🐛 Bug

When I use the image augmentation package "albumentations" for affine transformation, two arries are inputed but only the prior one vaired. The codes are listd below:

```
import numpy as np
import albumentations as alb

f=alb.Affine(
                translate_percent={'x':(-0.03,0.03),'y':(-0.015,0.015)},
                scale=[0.95,1/0.95],
                fit_output=False,
                p=1)

a,b = np.ones((10,10)), np.ones((10,10))
transformed=f(image=a,mask=b)
print('{} \n {}'.format(transformed['image'], transformed['mask']))
```

I appreciate you for helping me understand the unchanged reason for the seconde array!

**Comment by Dipet** [comment]
The changes are too small and difference is only in the interpolation flag. Try to set the same `interpolation` and `mask_interpolation`.

**Comment by DeidaraYang** [comment]
Thanks!
