### ISSUE TITLE
[Company] <DataClap>

### ISSUE THREAD

**Issue by rsanjeevk** [albumentations-team/albumentations#1306]
### Name

DataClap

### Website

https://dataclap.co

### Link to a logo

https://drive.google.com/file/d/1Sy-36AbmGao9XlasxTZZssEW8QiLpqJ8/view?usp=sharing

### Confirmation

- [X] I hereby confirm that I have permission from the company specified above to use its name, link to a website, and logo to mention it as a user of Albumentations.

**Comment by creafz** [comment]
Hey, thank you, the company was added to the list of companies that use Albumentations - https://albumentations.ai/whos_using
