### ISSUE TITLE
documentation in GitHub readme, many links are broken

### ISSUE THREAD

**Issue by neuronflow** [albumentations-team/albumentations#1319]
many links are broken in the GitHub documentation:
https://github.com/albumentations-team/albumentations#pixel-level-transforms

e.g. -> blur -> 404
https://albumentations.ai/docs/api_reference/augmentations/blur/transforms/#albumentations.augmentations.blur.transforms.Blur

**Comment by creafz** [comment]
Hey @neuronflow. Thank you for your report. I have fixed the site pages. These links should work now.
