### ISSUE TITLE
RandomCrop function

### ISSUE THREAD

**Issue by rose-jinyang** [albumentations-team/albumentations#1341]
Hello
Thanks for contributing to this project.
I found that RandomCrop of this lib is different from torchvision.transforms.RandomCrop.
Torch's RandomCrop is capable to crop at any position with padding.
But RandomCrop of this lib can NOT crop when crop size is greater than the image size.
Could u implement the same function as Torch's RandomCrop?
Thanks

**Comment by ternaus** [comment]
@rose-jinyang 

Added option to pad if needed [Crop](https://explore.albumentations.ai/transform/Crop), [RandomCrop](https://explore.albumentations.ai/transform/RandomCrop) and [CenterCrop](https://explore.albumentations.ai/transform/CenterCrop)
