### ISSUE TITLE
Rotation distorts the segmentation probability map

### ISSUE THREAD

**Issue by Abermal** [albumentations-team/albumentations#1344]
## 🐛 Bug
My label is a set of 2d gaussian distributions that are used to train a model for detection task and I've noticed that your rotation implementation distorts the segmentation mask.

Vanila:
![image](https://user-images.githubusercontent.com/34352604/202902436-79d2ca31-58e6-429a-8bed-b97c97f9b06e.png)

Albumentations:
![image](https://user-images.githubusercontent.com/34352604/202902396-372c357f-862e-498f-8f30-1c8731fb03e4.png)

## To Reproduce

     
```python
    def make_gaussian(height: int, width: int, sigma=3, center=None) -> np.array:
        """
        Make a square gaussian kernel.

        :param height: height of heatmap
        :param width: width of heatmap
        :param sigma: effective radius around the landmark
        :param center: coordinates of the landmark to make a gaussian representation
        :return: gaussian heatmap
        """
        x = np.arange(0, width, 1, float)
        y = np.arange(0, height, 1, float)[:, np.newaxis]
        if center is None:
            x0 = width // 2
            y0 = height // 2
        else:
            x0, y0 = center
        return np.exp(-4 * np.log(2) * ((x - x0) ** 2 + (y - y0) ** 2) / sigma ** 2)

plt.figure(figsize=(15, 15))
mask = make_gaussian(64, 64, sigma=20)
plt.subplot(2, 2, 1)
plt.imshow(mask, cmap='binary')

transform = A.Compose([
    A.Rotate(
        limit=45,
        interpolation=cv2.INTER_CUBIC,
        border_mode=cv2.BORDER_REFLECT,
        p=1.
    ),
])


plt.subplot(2, 2, 2)
mask_rotated = transform(image=mask, mask=mask)['mask']
plt.imshow(mask_rotated, cmap='binary')
plt.subplot(2, 2, 3)
plt.imshow(mask, cmap='binary')
plt.subplot(2, 2, 4)
mask_rotated = transform(image=mask, mask=mask)['mask']
plt.imshow(mask_rotated, cmap='binary')

```
![image](https://user-images.githubusercontent.com/34352604/202910710-c906252b-df87-4059-a0e2-7eaf3458532c.png)

## Environment

 - Albumentations version (1.3.0):
 - Python version (3.9):
 - OS (e.g., Linux):
 - How you installed albumentations (`pip`):

**Comment by Dipet** [comment]
You are using a strange segmentation mask that has non-discrete values (not just 0 and 1).
We use `INTER_NEAREST ` interpolation for all masks, so you will always see changes on masks. https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html#ga5bb5a1fea74ea38e1a5445ca803ff121
Unfortunately, we don't currently have the option to change the interpolation flag for masks.

**Comment by Abermal** [comment]
The mask is for the detection task actually.  That's why non-discrete values.
Any chance there is another interpolation that works for both discrete and non-discrete values you could apply?

**Comment by ternaus** [comment]
@Abermal 

- Added an option to choose interpolation for mask for every transform that has `mask_interpolation`
- Added an option to define `mask_interpolation` in Compose that overrides ones defined in individual transforms
