### ISSUE TITLE
Missing keypoint TF for OpticalDistortion and ElasticTransform

### ISSUE THREAD

**Issue by 23pointsNorth** [albumentations-team/albumentations#1345]
## 🐛 Bug

Looking at the [transforms and targets](https://albumentations.ai/docs/getting_started/transforms_and_targets/#spatial-level-transforms) table, there are a few transformations with known, parameterized outcomes when applied to the keypoints case. These include OpticalDistortion and ElasticTransform. Given they are defined for the masks case, the movement of the the keypoints will have a known shift.

## Additional context

There are a few other transformation that may have a similar behaviour - [RandomSizedBBoxSafeCrop](https://albumentations.ai/docs/api_reference/augmentations/crops/transforms/#albumentations.augmentations.crops.transforms.RandomSizedBBoxSafeCrop), [BBoxSafeRandomCrop](https://albumentations.ai/docs/api_reference/augmentations/crops/transforms/#albumentations.augmentations.crops.transforms.BBoxSafeRandomCrop), and for the bbox there are a few that may have different interpretations of what needs to happen - [CoarseDropout](https://albumentations.ai/docs/api_reference/augmentations/dropout/coarse_dropout/#albumentations.augmentations.dropout.coarse_dropout.CoarseDropout) - if one side of the box is shrunc, the box size can be decreased, otherwise keep as is;

Found a Relevant PR as #1325 #686

**Comment by MihailMihaylov97** [comment]
I have also encountered this issue. Are there any updates on this?

**Comment by ternaus** [comment]
@23pointsNorth @MihailMihaylov97 

Bboxes and ketpoint support added to all these transforms
