### ISSUE TITLE
run error with random.choice

### ISSUE THREAD

**Issue by whlook** [albumentations-team/albumentations#1357]
## To Reproduce

error with routine using

```python
 transforms = [
        A.CLAHE(p=0.5),
        A.RandomRotate90(p=0.6), 
        A.Flip(p=0.5),
        A.Transpose(p=0.5),
        A.GaussNoise(p=0.4),
        A.OneOf([
            A.MotionBlur(p=.2),
            A.MedianBlur(blur_limit=3, p=0.1),
            A.Blur(blur_limit=3, p=0.1),
            ], p=0.3),
        A.ShiftScaleRotate(shift_limit=0.0625, scale_limit=0.3, rotate_limit=45, p=0.5),
        A.HueSaturationValue(hue_shift_limit=10,sat_shift_limit=10,val_shift_limit=50,p=1),
]
```
## Environment

 - Albumentations version (e.g., 0.1.8):1.3.0
 - Python version (e.g., 3.7):3.11.0
 - OS (e.g., Linux):5.4.0-120-generic #136~18.04.1-Ubuntu SMP Fri Jun 10 18:00:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - How you installed albumentations (`conda`, `pip`, source):pip
 - Any other relevant information:numpy:1.23.4

## Additional context

![image](https://user-images.githubusercontent.com/13912755/204704258-d3550488-d975-4d7e-9de8-325a763cd45b.png)

**Comment by Dipet** [comment]
Idiot approach inside python3.11 for checking if a sequence is empty 🤦‍♂️

**Comment by ternaus** [comment]
Fixed
