### ISSUE TITLE
KeyError: dtype('float64') on certain filters, ie Solarize

### ISSUE THREAD

**Issue by jeanmonet** [albumentations-team/albumentations#1358]
## 🐛 Bug

```
File /.../python3.10/site-packages/albumentations/augmentations/functional.py:184, in solarize(img, threshold)
    173 """Invert all pixel values above a threshold.
    174 
    175 Args:
   (...)
    181 
    182 """
    183 dtype = img.dtype
--> 184 max_val = MAX_VALUES_BY_DTYPE[dtype]
    186 if dtype == np.dtype("uint8"):
    187     lut = [(i if i < threshold else max_val - i) for i in range(max_val + 1)]

KeyError: dtype('float64')
```

## To Reproduce

```
  composition = albu.Compose([albu.HorizontalFlip(p=0.5),
                              albu.VerticalFlip(p=0.5),
                              albu.RandomBrightnessContrast(brightness_by_max=False, p=0.2),
                              albu.ShiftScaleRotate(p=0.5),
                              albu.Solarize(threshold=130, p=0.5), ])
```

Used during training on cifar-10 dataset.

## Environment

 - Albumentations version (e.g., 0.1.8): 1.3.0
 - Python version (e.g., 3.7): 3.10
 - OS (e.g., Linux): Ubuntu
 - How you installed albumentations (`conda`, `pip`, source): conda

**Comment by Dipet** [comment]
Library do not support `float64` as image dtype

**Comment by jeanmonet** [comment]
The dataset is uint8 actually, so I do not understand where the error comes from. I'm having this problem on multiple (but not all) filters.

**Comment by AdvancingEther** [comment]
I meet the same problem, have you solved yet?

**Comment by ternaus** [comment]
@jeanmonet @AdvancingEther 

We will look into it, but it would be easier if you provided an example to reproduce the issue. 

Do you have one?

**Comment by ternaus** [comment]
Could be related to https://github.com/albumentations-team/albumentations/issues/1574

**Comment by ternaus** [comment]
It is recommended to normalize image at the end as unit8 images are processed faster than float32
