### ISSUE TITLE
ToTensorV2() transformation doesn't scale image values into range [0,1] which is done by ToTensor() from PyTorch

### ISSUE THREAD

**Issue by blazejdolicki** [albumentations-team/albumentations#1360]
## 🐛 Bug

ToTensorV2() is supposed to replicate the behaviour of  ToTensor() from PyTorch which scales image values from range [0,255] to [0,1] and convert input numpy ndarray to torch.Tensor(). However, the current implementation of Albumentations doesn't perform the scaling. I believe this bug was introduced when switching to V2 of this function in Albumentations.

## To Reproduce

Run the following code to see the difference:
```
from albumentations.pytorch.transforms import ToTensorV2
from torchvision.transforms import ToTensor
from PIL import Image
import numpy as np

# Note:
# if we transform PIL image, the values are scaled to range [0,1]
# if we transform ndarray with dtype other than uint8, the values will remain in range [0,255]
to_tensor_torch = ToTensor()
to_tensor_album = ToTensorV2()


img = np.random.randint(0, 255, size=(4, 4, 3), dtype=np.uint8) # to read real image: img = np.asarray(Image.open(<img_path>))
print("Original image")
print(img)

transformed_img = to_tensor_torch(img)
print("Shape and type of image transformed with PyTorch", transformed_img.shape, type(transformed_img))
print("Image transformed with PyTorch")
print(transformed_img)

transformed_img = to_tensor_album(image=img)["image"]
print("Shape and type of image transformed with Albumentations", transformed_img.shape, type(transformed_img))
print("Image transformed with Albumentations")
print(transformed_img)

```
The output is:
```
Original image
[[[187 116 185]
  [140  63  53]
  [ 45  25 175]
  [154 135 132]]

 [[104   8 119]
  [250 104  70]
  [ 14 107   2]
  [158 134 229]]

 [[175 182  33]
  [103  17  64]
  [ 60 179 113]
  [180 241  63]]

 [[189 108 118]
  [127 222 104]
  [ 95 250  51]
  [146 254  17]]]
Shape and type of image transformed with PyTorch torch.Size([3, 4, 4]) <class 'torch.Tensor'>
Image transformed with PyTorch
tensor([[[0.7333, 0.5490, 0.1765, 0.6039],
         [0.4078, 0.9804, 0.0549, 0.6196],
         [0.6863, 0.4039, 0.2353, 0.7059],
         [0.7412, 0.4980, 0.3725, 0.5725]],

        [[0.4549, 0.2471, 0.0980, 0.5294],
         [0.0314, 0.4078, 0.4196, 0.5255],
         [0.7137, 0.0667, 0.7020, 0.9451],
         [0.4235, 0.8706, 0.9804, 0.9961]],

        [[0.7255, 0.2078, 0.6863, 0.5176],
         [0.4667, 0.2745, 0.0078, 0.8980],
         [0.1294, 0.2510, 0.4431, 0.2471],
         [0.4627, 0.4078, 0.2000, 0.0667]]])
Shape and type of image transformed with Albumentations torch.Size([3, 4, 4]) <class 'torch.Tensor'>
Image transformed with Albumentations
tensor([[[187, 140,  45, 154],
         [104, 250,  14, 158],
         [175, 103,  60, 180],
         [189, 127,  95, 146]],

        [[116,  63,  25, 135],
         [  8, 104, 107, 134],
         [182,  17, 179, 241],
         [108, 222, 250, 254]],

        [[185,  53, 175, 132],
         [119,  70,   2, 229],
         [ 33,  64, 113,  63],
         [118, 104,  51,  17]]], dtype=torch.uint8)
```

## Expected behavior

The image transformed with Albumentations should be the same as the image transformed with PyTorch.

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source): pip install -U albumentations
 - Any other relevant information:

**Comment by Dipet** [comment]
`ToTensor` only transforms image to `torh.Tensor` and change from `HWC` to `CHW` format.
If you need normalize image to `Normalize` transform.

**Comment by wm-mask** [comment]
@Dipet no, this is not true: 👎 https://albumentations.ai/docs/api_reference/pytorch/transforms/#albumentations.pytorch.transforms.ToTensor

I have had the same issue

I just need to apply a divide by 255 on the image, not to normalize it to bring it to [0, 1]

There is no way today to do it in albumentations. You need to transform your image to [0, 1] using PIL or numpy or cv2 before passing it to the Compose of transforms

**Comment by wm-mask** [comment]
I guess the solution is to apply `A.Normalize(mean=[0, 0, 0], std=[1, 1, 1])` to divide by `max_pixel_value=255`

**Comment by Dipet** [comment]
`ToTensor` is deprecated because it is overcomplicated. Use `ToTensorV2` and `Normalization` instead.
