### ISSUE TITLE
How can I get the pictures in docs?

### ISSUE THREAD

**Issue by ml3082298291** [albumentations-team/albumentations#1362]
## To Reproduce

1. Just like in doc https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/
, I am learning the Tutorials Provided， but I can not get the pictures .

Thank a lot

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

**Comment by Dipet** [comment]
Download links to dataset are here: https://cocodataset.org/#download
