### ISSUE TITLE
The `add_targets` method sets targets instead of adding them

### ISSUE THREAD

**Issue by ernest-tg** [albumentations-team/albumentations#1372]
Suppose you do 
```python
import albumentations as A
t = A.ToGray()  # Works with all transformations
t.add_targets({"my_image1": "image"})
t.add_targets({"my_image2": "image"})
print(t._additional_targets)
```
You get `{'my_image2': 'image'}`. That seems to be what you want since you (albu) wrote 

```python
class BasicTransform(Serializable):
    ...
    def add_targets(self, additional_targets):
        ...
        self._additional_targets = additional_targets
```

But, given the name of the function, and the docstring "Add targets to transform them the same way as one of existing targets", I expected `{'my_image1': "image", 'my_image2': "image"}`.

My own use case is very uncommon, but I could see other people adding some targets in 2 different places for some other reason. I would suggest either:
* Replace `self._additional_targets = additional_targets` by `self._additional_targets.update(additional_targets)`
* Rename `add_targets` to `set_targets` / `set_additional_targets`

For completeness purpose, my own use case is that I have a child class (named `Tee`) of `BasicTransform` which outputs 2 keys from one key. So my pipeline looks like:

```python
before_tee1 = A.SomeTransform(...)
before_tee2 = A.SomeTransform(...)
tee = Tee(...)
after_tee1 = A.SomeTransform(...)
after_tee2 = A.SomeTransform(...)
for transfo in [after_tee1, after_tee2]:
    transfo.add_targets({"image_copy": "image"})

...

dynamic_composed_transfo = A.Compose(
    [before_tee1, before_tee2, tee, after_tee1, after_tee2], additional_targets=dynamic_targets)
```

**Comment by Dipet** [comment]
This method designed for internal use only. How to use additional targets you could read there: https://albumentations.ai/docs/examples/example_multi_target/

**Comment by ernest-tg** [comment]
I can write the pipeline above using only the `additional_targets` parameter from `Compose`, but I still have the same issue. Or, for a simpler pipeline:

```
import albumentations as A
t1 = A.Flip()
t2 = A.ToGray()
c2 = A.Compose([t2], additional_targets={'image_for_t2': "image"})
c = A.Compose([t1, c2], additional_targets={'image_for_t1_t2': "image"})

print(c.transforms[1].transforms[0]._additional_targets)
```
I would expect the targets of `t1` to be "image_for_t1_t2", and the targets of `t2` to be both "image_for_t1_t2" and "image_for_t2". 
But the targets of `t2` is only {"image_for_t1_t2": "image"}. I'm guessing that, applying only part of the pipeline to some inputs, is not supported either. Which is fair. I guess the less hacky way for me to do this is to implement this outside of Albumentations: apply the first part of the pipeline, add some targets, and apply the second part of the pipeline.

**Comment by ternaus** [comment]
@ernest-tg should be fixed in https://github.com/albumentations-team/albumentations/pull/1647

Would you, or your company consider becoming sponsors for Albumentations? 

https://github.com/sponsors/albumentations-team

It will could speed up the work and decrease response time.
