### ISSUE TITLE
Support different rgb to grayscale methods.

### ISSUE THREAD

**Issue by Dipet** [albumentations-team/albumentations#1374]
Support different [methods](https://docs.gimp.org/2.6/en/gimp-tool-desaturate.html) for grayscale conversions:
- `Luminosity` with different coefficients.
- `Lightness`
- `Average`
Some info you can find on wiki: https://en.wikipedia.org/wiki/Grayscale

**Comment by pneycho** [comment]
Hi @Dipet, It'd be great if you could take a look at the commit. There is an issue I fixed, about the gray image inversion if the mean pixel value of the resultant value is over 127 (which is mentioned was mentioned in the docstring but not implemented). Is there any specific reason why that is being done? The only thing I could think of is visibility enhancement of specific structures. Am I correct in assuming that?

**Comment by Dipet** [comment]
@pneycho 
About what commit are you talking? I do not see any pull request there. Try to create it please

**Comment by Dipet** [comment]
Ok, I see. It looks like we talking about #1387

**Comment by ternaus** [comment]
@pneycho Desired functionality merged.
