### ISSUE TITLE
RandomGridShuffle error

### ISSUE THREAD

**Issue by bekhzod-olimov** [albumentations-team/albumentations#1375]
## 🐛 Bug

RandomGridShuffle does not function properly.

## To Reproduce
```python
plt.figure(figsize=(15,10))
display_ims = 20
grid = (3, 3)
p = 0.5

for i in range(display_ims):   
    tfs = A.Compose([A.RandomGridShuffle()])
    tfs_im = tfs(image=im)
    plt.subplot(4, display_ims // 4, i+1)
    plt.imshow(tfs_im["image"])
    plt.axis("off")
```

## Environment
 - Albumentations version (1.3.0):
 - Python version (3.9):
 - OS (Linux):
 - How you installed albumentations (pip):

## Additional context

```python
height_split = np.linspace(0, height, n + 1, dtype=np.int)
width_split = np.linspace(0, width, m + 1, dtype=np.int)
```
AttributeError: module 'numpy' has no attribute 'int'

**Comment by adrigrillo** [comment]
This should be fixed now with the change from `np.int` to `np.int32` here: 

```python
height_split = np.linspace(0, height, n + 1, dtype=np.int32)
width_split = np.linspace(0, width, m + 1, dtype=np.int32)
```
in https://github.com/albumentations-team/albumentations/blob/e3b47b3a127f92541cfeb16abbb44a6f8bf79cc8/albumentations/augmentations/transforms.py#LL138C1-L139C67 so this can be closed.

**Comment by ternaus** [comment]
Thanks @adrigrillo
