### ISSUE TITLE
Gaussian Noise Application

### ISSUE THREAD

**Issue by bekhzod-olimov** [albumentations-team/albumentations#1380]
## 🐛 Bug

Display of the Gaussian Noise transformation results in no change at all.

## To Reproduce

```python
import albumentations as A
import cv2
from PIL import Image
import matplotlib.pyplot as plt

im = cv2.cvtColor(cv2.imread("test1.jpg"), cv2.COLOR_BGR2RGB)
display(Image.fromarray(im))

plt.figure(figsize=(15,10))
display_ims = 20
var_limit = (0.0, 60.0)
p = 0.5

for i in range(display_ims):   
    tfs = A.Compose([A.GaussNoise(var_limit = (var_limit[0] + i, var_limit[1] + i), 
                                  mean = i, always_apply=True, p = (p * (i + 1)))])
    tfs_im = tfs(image=im)
    plt.subplot(4, display_ims // 4, i+1)
    plt.imshow(tfs_im["image"])
    plt.axis("off")
    plt.title(f"{(var_limit[0] + i, var_limit[1] + i)} {i+1}")
plt.savefig('pngs/gauss_noise.png', dpi = 300)
```

## Environment

 - Albumentations version (1.3.0):
 - Python version (3.9):
 - OS (Linux):
 - pip installation.
![gauss_noise](https://user-images.githubusercontent.com/50166164/211468070-bcc7dd97-6733-43e6-b34a-5b926c534c34.png)

**Comment by i-aki-y** [comment]
I think it is difficult to judge the presence of Gauss noise in your example. What will happen if you plot the diff between the original and the transformed?

```py
plt.imshow(im - tfs_im["image"])
```

**Comment by bekhzod-olimov** [comment]
> I think it is difficult to judge the presence of Gauss noise in your example. What will happen if you plot the diff between the original and the transformed?
> 
> ```python
> plt.imshow(im - tfs_im["image"])
> ```
I think it works properly, meaning that Gaussian noise is added to the original image but it is not very noticeable when the noisy image is concatenated with the original one. When plotted the noise only (subtracting noisy image from the original image), noise is clear.

![image](https://user-images.githubusercontent.com/50166164/211726410-374fcb5b-fc17-4dc5-84ac-fd422dc196ab.png)
