### ISSUE TITLE
Augment multiple images and bounding boxes in a folder with different 7 classes in it.

### ISSUE THREAD

**Issue by muhammadd7** [albumentations-team/albumentations#1384]
I'm a beginner. I would like to know how to apply the same augmentation pipeline with the same parameters to a folder of images with their corresponding bounding box labels. I only have 7 classes in a folder. and want to increase all classes to a specific number because all classes are unbalanced right now.

**Comment by ternaus** [comment]
Closing this for now, but would be happy to open and help if you describe your problem in more details.
