### ISSUE TITLE
Import CourseDropout

### ISSUE THREAD

**Issue by Payden-McBee** [albumentations-team/albumentations#1385]
## 📚 Documentation

With pytorch 1.10 you import Albumentations.dropout.course_dropout.CourseDropout, but this will not work with pytorch 1.12, instead you import Albumentations.CourseDropout. This is important bc the A100 GPU requires CUDA 11, which pytorch 1.12 uses and pytorch 1.10 does not (it uses CUDA 10.2 instead which is not compatible).

**Comment by Dipet** [comment]
We are independent to pytorch version.
