### ISSUE TITLE
how can I return random arugments generate by albumentation?

### ISSUE THREAD

**Issue by jeannotes** [albumentations-team/albumentations#1395]
hi, thanks for your amaziong job, I can easily transform image with random generate arguments, such as scale ratio, translation ratio etc.
but I want to also return those random generate arguments for debug use, how can I do that?

**Comment by Dipet** [comment]
You need [`ReplayCompose`](https://albumentations.ai/docs/examples/replay/#debugging-an-augmentation-pipeline-with-replaycompose)
