### ISSUE TITLE
Affine has no `rotate_method` in `1.3.0`

### ISSUE THREAD

**Issue by 23pointsNorth** [albumentations-team/albumentations#1399]
## 🐛 Bug

In the [documentation ](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.Affine) + Rotate we have a paramter named `rotate_method` for `v 1.3.0`, however installing `1.3.0` we get the following error:

```
>>> import albumentations as A
>>> A.__version__
'1.3.0'
>>> A.Affine
<class 'albumentations.augmentations.geometric.transforms.Affine'>
>>> A.Affine(rotate_method="elipse")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'rotate_method'
```

Confirming that the locally installed wheel does not have this param.

**Comment by Dipet** [comment]
Current PyPi version do not have these changes. This is issue with documentation - it shows current master state, not latest PyPi version.
You can install latest version of library from github directly `pip install git+https://github.com/albumentations-team/albumentations.git`

**Comment by Dipet** [comment]
Maybe after merging changes from #1396

**Comment by ternaus** [comment]
@23pointsNorth In the latest version Affine supports:

- Rotate
- Scale
- Translate
- Shear
