### ISSUE TITLE
Behaviour of Compose and Sequential

### ISSUE THREAD

**Issue by FlorentMeyer** [albumentations-team/albumentations#1408]
## 📚 Documentation

Hello,

I have a few questions about things I don't find very clear in the docs:

1. [This](https://github.com/albumentations-team/albumentations/issues/1051) says that Sequential has to be used inside a set of nested transforms, so is Sequential a replacement that works otherwise _exactly_ like Compose? At the beginning I really thought Sequential was meant to apply _all_ transforms inside it VS Compose would apply transforms _based on probabilities_.
2. Does that mean that Compose is the only transform that can be used at the root of nested transforms, or can one have:
```
>>> transforms = A.OneOf([
>>>        A.Sequential([...]),
>>>        A.Sequential([...]),
>>>    ], p=1)
```

3. Finally, [this](https://albumentations.ai/docs/api_reference/core/composition/#albumentations.core.composition.OneOf) says that in OneOf, "Selected transform will be called with force_apply=True". However in this example:
```
>>> transform = A.Compose([
>>>    A.OneOf([
>>>        A.Sequential([
>>>            A.Resize(height=250, width=50),
>>>            A.HorizontalFlip(),
>>>        ]),
>>>        A.Sequential([
>>>            A.Resize(height=50, width=250),
>>>            A.VerticalFlip(),
>>>        ]),
>>>    ], p=1)
>>> ])
```
I thought I would be getting only 2 possible results. However, I get 4:

- A.Resize(height=250, width=50)
- A.Resize(height=250, width=50) AND A.HorizontalFlip()
- A.Resize(height=50, width=250)
- A.Resize(height=50, width=250) AND A.VerticalFlip()

So it seems like the default p=0.5 for HorizontalFlip and VerticalFlip is not overriden by "Selected transform will be called with force_apply=True".

Thanks in advance :)

**Comment by Dipet** [comment]
1. `Sequential` is a simplified version of `Compose` without logic for pre- and post-processing of bboxes and keypoints.
2. You can use any transform as top level transform, but only `Compose` do pre- and post-processing for targets such as bboxes and keypoints. We recommend only using `Compose` as your top-level transform.
3. Looks like a bug in the documentation or implementation...

**Comment by FlorentMeyer** [comment]
Thank you very much for the details!
3. can obviously be quickly "fixed" by using p=1 where needed.

**Comment by TonyCongqianWang** [comment]
I was pondering about this as well. Somehow Copilot brought me to this issue since I couldn't find this information anywhere.

Is there a point to ever use Sequential over Compose? It is less complex under the hood, but it doesnt affect me as a user unless the performance is worse. Always using Compose has the advantage of 1. not having to think about which to use and 2. its shorter to and easier to spell.
