### ISSUE TITLE
ambiguity of albumentations.ToGray() 

### ISSUE THREAD

**Issue by defensetongxue** [albumentations-team/albumentations#1412]
## 🐛 Bug
albumentations.augmentations.transforms.ToGray return a 3 channels image from 
```python
# albumentations/albumentations/augmentations/funtional.py
def to_gray(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    return cv2.cvtColor(gray, cv2.COLOR_GRAY2RGB)
```
which means this funtion repeat the gray scale channel for 3 times. i thinl it would be suitable to return 'gray' directly or add some annotation to disambiguation
## To Reproduce

1. call the albumentations.ToGray() for  any 3 channnel image

**Comment by mikel-brostrom** [comment]
Maybe an argument to specify 1/3 channels to return would be enough?

```python
def to_gray(img, gray2rgb=False):
    if gray2rgb:
        gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        return gray
    else:
        return cv2.cvtColor(gray, cv2.COLOR_GRAY2RGB)
```

**Comment by defensetongxue** [comment]
May be it can refer to the
    `torchvision.transforms.Grayscale(num_output_channels=1)`
```python
def to_gray(img, num_output_channels=3):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    if num_output_channels==3:
        return cv2.cvtColor(gray, cv2.COLOR_GRAY2RGB)
    elif num_output_channel==1:
        return gray
    else:
        raise ImplementError# rasie an error
```
By setting the default argument 'num_output_channels' to 3, we can maintain the same visualization as before.

**Comment by ternaus** [comment]
@mikel-brostrom @defensetongxue 

Fix merged.
