### ISSUE TITLE
 use A.RandomGamma and A.Sharpen will make image with np.nan pixle

### ISSUE THREAD

**Issue by yunshangyue71** [albumentations-team/albumentations#1422]
## 🐛 Bug

 use A.RandomGamma and A.Sharpen will make image with np.nan pixle

1.
1.
1.

## Expected behavior

with no nan， this will make CNN failed

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

**Comment by Dipet** [comment]
Please, provide a minimal reproducible example.
