### ISSUE TITLE
Make heavy dependencies optional

### ISSUE THREAD

**Issue by duylp** [albumentations-team/albumentations#1425]
Do you consider making heavy dependencies like `qudida`, `scikit-image` optional? User may not need to use `PixelDistributionAdaptation` but still have to install `qudida`, which installs `scikit-learn` and then a bunch of other packages.

This idea could be implemented via `extras_require` in `setup.py`, e.g.:
- `pip install albumentations`
- `pip install albumentations[domain-adaptation]`
- `pip install albumentations[all]`

Relates to #1424.

**Comment by ternaus** [comment]
Removed scikit learn depencency in https://github.com/albumentations-team/albumentations/pull/1854
