### ISSUE TITLE
Maybe it conflict with cv2

### ISSUE THREAD

**Issue by NicolasHarding** [albumentations-team/albumentations#1427]
## 🐛 Bug

I install cv2 and albumentations using 2 statement below;
`conda install -c conda-forge opencv`
`conda install -c conda-forge albumentations`

Then, when ever I use `cv2.imshow()`, an error raise : 
`QMimeDatabase: Error loading internal MIME data An error has been encountered at line 1 of <internal MIME data>: Premature end of document.:`
## To Reproduce
Using pip instead (Is there any way to install both cv2 and albumentations using conda?)

1.
1.
1.

## Environment

 - Albumentations version : 0.1.8
 - Python version : 3.10.9
 - OS : window 11
 - install using conda

**Comment by Dipet** [comment]
It looks like your file is corrupted. That not albumentations issue
