### ISSUE TITLE
Note about data type conversion in CenterCrop docstring

### ISSUE THREAD

**Issue by sestras** [albumentations-team/albumentations#1429]
Hello,

reading the documentation, I noticed the following note in the docstring of the CenterCrop transform:

https://github.com/albumentations-team/albumentations/blob/b773a1aa69f9c823c7f593205614d05d32c039cb/albumentations/augmentations/crops/transforms.py#L84-L87

I wondered why there would be a type conversion involved in center cropping and looking at the code, I could not find anything related to that. It just takes a slice of the array, as I would expect. Also, none of the other transforms, such as RandomCrop and Crop, contain this note in their docstring. Is this simply a leftover from the past or is this note still correct/relevant?

**Comment by ternaus** [comment]
It is leftover from the past, not really the case anymore.
