### ISSUE TITLE
ValueError(f"Expected {name} for bbox {bbox} to be in the range [0.0, 1.0], got {value}.")

### ISSUE THREAD

**Issue by alejopaullier96** [albumentations-team/albumentations#1431]
## 🐛 Bug

I am getting the following bug which was already addressed [here](https://github.com/albumentations-team/albumentations/issues/679) but apparently the bug still persists in albumentations version `1.3.0`:
```
ValueError(f"Expected {name} for bbox {bbox} to be in the range [0.0, 1.0], got {value}.")
ValueError: Expected y_max for bbox (0.14792899408284024, 0.9671641791044776, 0.28205128205128205, 1.0029850746268656, tensor(2)) to be in the range [0.0, 1.0], got 1.0029850746268656.
```

I am using the following  augmentations for an object detection problem:
```
def get_train_transforms():
    return A.Compose(
        [
            A.Resize(height=config.RESOLUTION, width=config.RESOLUTION, p=1),
            A.Normalize(p=1),
            ToTensorV2(p=1.0),
        ], 
        p=1.0, 
        bbox_params=A.BboxParams(
            format='pascal_voc',
            min_area=0, 
            min_visibility=0,
            label_fields=['labels']
        )
    )

def get_valid_transforms():
    return A.Compose(
        [
            A.Resize(height=config.RESOLUTION, width=config.RESOLUTION, p=1.0),
            A.Normalize(p=1),
            ToTensorV2(p=1.0),
        ], 
        p=1.0, 
        bbox_params=A.BboxParams(
            format='pascal_voc',
            min_area=0, 
            min_visibility=0,
            label_fields=['labels']
        )
    )
```

## Expected behavior

Bounding boxes should not be larger than image dimensions after transformations.

## Environment

 - Albumentations version: `1.3.0`
 - Python version (e.g., 3.7): `3.7.12`
 - OS (e.g., Linux): `Linux-5.15.89+-x86_64-with-debian-bullseye-sid`
 - How you installed albumentations (`conda`, `pip`, source): `pip`
 - Any other relevant information: Run with GPU on a Kaggle environment (2023-03-29)

## Additional context

GPU info: Cuda: Tesla P100-PCIE-16GB

**Comment by AriyaRasekh** [comment]
The bug is defiantly there, I'm assuming some numbers after decimal point somehow is messing up the calculation in the backed, you can try limiting the numbers after decimal point to 6 or 10 and try again.

**Comment by ternaus** [comment]
@alejopaullier96 @AriyaRasekh 

The issue could be resolved if one passes `clip=True` to BboxParams

**Comment by ternaus** [comment]
@AlexPapas Could you please provide a minimal version of the code that reproduces the issue?
