### ISSUE TITLE
The default parameter to Horizontal/VerticalFlip is actually `always_apply` not `p`

### ISSUE THREAD

**Issue by nharada1** [albumentations-team/albumentations#1435]
## 🐛 Bug

The way I believe most people would read the following code:

`VerticalFlip(0.5)`

would be to assume that this means the probability of a flip is 50%. However, the first parameter value of the transform is a bool, and so any value causes `always_apply` to be true and thus will always apply the transform. I believe the default value should be `p` instead, or you should not accept default args.

## To Reproduce

```
import albumentations as A
import numpy as np

tfx = A.Compose([
  A.HorizontalFlip(0.00000001),
])

a = np.arange(9).reshape((3, 3, 1))
print(a[:, :, 0])
b = tfx(image=a)["image"]
print(b[:, :, 0])
```

## Expected behavior

The flip should almost never happen, since a reasonable assumption is the p=1e-8. Instead, it will ALWAYS happen.

## Environment

 - Albumentations version (e.g., 0.1.8): 1.2.1
 - Python version (e.g., 3.7): 3.9
 - OS (e.g., Linux): Colab, Ubuntu
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

**Comment by ternaus** [comment]
Fixed
