### ISSUE TITLE
MaskDropout Augmentation encounter an error

### ISSUE THREAD

**Issue by ynhuhu** [albumentations-team/albumentations#1440]
## 📚 Documentation

On Kaggle platform MaskDropout augmentation encounter an error.
My input image shape is (224,224,12), mask shape is (224,224,1)
Error msg:
File "/opt/conda/lib/python3.7/site-packages/albumentations/augmentations/dropout/mask_dropout.py", line 86, in apply
    img[dropout_mask] = self.image_fill_value
IndexError: boolean index did not match indexed array along dimension 2; dimension is 12 but corresponding boolean dimension is 1
Documentation desciptions：Mask must be single-channel image, zero values treated as background. Image can be any number of channels.
Shape looks as described in the documentation. I don't know what's wrong.

**Comment by GdoongMathew** [comment]
In albumentations, usually an image or mask is defined in channel-last style, thus you'll have to transpose it like
```python
image = image.transpose(1, 2, 0)
```

**Comment by ynhuhu** [comment]
I didn't describe clearly. Before dataloader, my input image shape is (224,224,12), mask shape is (224,224,1).

**Comment by GdoongMathew** [comment]
@ynhuhu 
did you use any thing like transpose or ToTorchV2 layers in your Compose?
or probably you can provide that piece of code? Thanks~

**Comment by ynhuhu** [comment]
> 
I use ToTensorV2(transpose_mask=True) in final Compose after MaskDropout(max_objects=(0,5),p=0.5).

**Comment by ternaus** [comment]
@ynhuhu  @GdoongMathew Should work now.
