### ISSUE TITLE
PiecewiseAffine Randomly Causes TypeError

### ISSUE THREAD

**Issue by belfner** [albumentations-team/albumentations#1442]
## 🐛 Bug

There is a small but non-negligible probability that the `PiecewiseAffine` augmentation will cause a `TypeError` to be raised when an image is processed through it.

##### Code

```python
import albumentations as A
import numpy as np
import random

transform = A.Compose([A.PiecewiseAffine(scale=0.01, nb_rows=2, nb_cols=2, p=1)])
image = np.zeros((20, 20, 3), dtype='uint8') # image size does not matter 

# To force the bug to occur I have seeded the RNG to force the bug
# If not included there is still a 1/256 chance that the bug occurs
random.seed(196) 

transform(image=image)
```

##### Resulting Stack Trace

```
Traceback (most recent call last):
  File "/home/belfner/PycharmProjects/albumentations/reproduce.py", line 8, in <module>
    transform(image=image)
  File "/home/belfner/PycharmProjects/albumentations/albumentations/core/composition.py", line 210, in __call__
    data = t(**data)
  File "/home/belfner/PycharmProjects/albumentations/albumentations/core/transforms_interface.py", line 118, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/home/belfner/PycharmProjects/albumentations/albumentations/core/transforms_interface.py", line 131, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/home/belfner/PycharmProjects/albumentations/albumentations/augmentations/geometric/transforms.py", line 948, in apply
    return F.piecewise_affine(img, matrix, self.interpolation, self.mode, self.cval)
  File "/home/belfner/PycharmProjects/albumentations/albumentations/augmentations/utils.py", line 68, in wrapped_function
    return clip(func(img, *args, **kwargs), dtype, maxval)
  File "/home/belfner/PycharmProjects/albumentations/albumentations/augmentations/geometric/functional.py", line 698, in piecewise_affine
    return skimage.transform.warp(
  File "/home/belfner/PycharmProjects/albumentations/start/lib/python3.8/site-packages/skimage/transform/_warps.py", line 937, in warp
    coords = warp_coords(coord_map, output_shape)
  File "/home/belfner/PycharmProjects/albumentations/start/lib/python3.8/site-packages/skimage/transform/_warps.py", line 624, in warp_coords
    tf_coords = coord_map(tf_coords)
  File "/home/belfner/PycharmProjects/albumentations/start/lib/python3.8/site-packages/skimage/transform/_warps.py", line 928, in coord_map
    return inverse_map(*args, **map_args)
TypeError: 'NoneType' object is not callable
```

## Expected behavior

The augmentation should never throw an error when valid parameters and inputs are used.

## Environment

 - Python version: 3.8.16
 - OS: Linux (but issue has been observed on Windows as well)
 - How you installed albumentations: pip/source

I tried several combinations of albumentations versions and scikit-image versions. The table below marks the combinations I tried.

|              |                 | Albumentation |    Versions    |
| :----------: | :-------------: | :-----------: | :------------: |
| Scikit-image |                 |     1.0.0     | 1.3.0 (latest) |
|   Versions   |     0.16.2      |       x       |                |
|              |     0.18.1      |       x       |                |
|              | 0.20.0 (latest) |               |       x        |

The bug was observed in all combinations tried.

Also all tests completed successfully for all combinations tried. 

## Additional context

I did some digging and the error seems to stem from the `get_params_dependent_on_targets` method of the `PiecewiseAffine` class in the `albumentations/augmentations/geometric/transforms.py` file. The dictionary returned from this function contains the key `'matrix'`. The value of that key eventually becomes the `inverse_map` function used internally in scikit-image at line `928` of `skimage/transform/_warps.py`. As shown in the last frame of the stack trace, `inverse_map` has the value of `None` raising the `TypeError` when it is called. 

Looking at the contents of `get_params_dependent_on_targets`, I saw the following code:
```python
h, w = params["image"].shape[:2]

nb_rows = np.clip(random.randint(*self.nb_rows), 2, None)
nb_cols = np.clip(random.randint(*self.nb_cols), 2, None)
nb_cells = nb_cols * nb_rows
scale = random.uniform(*self.scale)

jitter: np.ndarray = random_utils.normal(0, scale, (nb_cells, 2))
if not np.any(jitter > 0):
    return {"matrix": None}
```

The error occurs when none of the values generated by `random_utils.normal` are greater than 0 causing the value of the `'matrix'` key to be `None`. This causes `inverse_map` to be `None` and the `TypeError` is raised. 

#### Guessing at purpose of check

I am still not completely sure why this check is needed as no obvious errors occur if it is removed and `jitter` contains no positive values. My best guess would be that it imposes some forced "randomness" to the affine transforms but that would not explain why `None` is returned. Also if that were the case I would assume the opposite check (jitter contains no negative values) would also be implemented.

#### Chance of error occurring

Doing some quick math, it can be shown that the chance the error occurs is `(1 / 2) ^ (nb_rows * nb_cols * 2))`. This is because the number of jitter values generated by `random_utils.normal` is `nb_rows * nb_cols * 2` and each value has a 50% chance of being negative since the normal distribution has a mean of 0. So even for the simplest case where `nb_rows = 2` and `nb_cols = 2` the chance of the error occurring is 1/256 or ~0.39%.

#### Possible solutions

I have come up with some possible solutions:

1. If the check is needed, simply regenerate jitter until it is valid. The only reason I feel this is an adequate solution is due to the low chance of the error occurring even in the simplest of cases.

   ```python
   while True:
       jitter: np.ndarray = random_utils.normal(0, scale, (nb_cells, 2))
       if np.any(jitter > 0):
           break
   ```

   or if `while True` is disliked:

   ```python
   jitter: np.ndarray = random_utils.normal(0, scale, (nb_cells, 2))
   while not np.any(jitter > 0):
       jitter: np.ndarray = random_utils.normal(0, scale, (nb_cells, 2))
   ```

   or some other variation.

2. If the check is not needed simply remove it.

#### Rational behind version testing

When looking at the code in its current state, I do not see any reason the value associated with `'matrix'` should ever be `None` (but I could be wrong). I assumed there must have been some previous combination of albumentations and scikit-image where  `None` made sense. So I tested the same code as above with `albumentations==1.0.0` and the minimum and the "for the time" maximum versions of scikit-image. As stated above the bug was observed for all tested combinations. Note: to force the bug with `albumentations==1.0.0`, the random seed to use is `117`.

## Final thoughts

- I hope my math is correct. 

- If this behavior is truly a bug, I would be happy to handle making a PR.

**Comment by kv-rbarton** [comment]
any updates on this?
