### ISSUE TITLE
CoarseDropout: Missing/wrong types on some arguments

### ISSUE THREAD

**Issue by pvicente-sensei** [albumentations-team/albumentations#1448]
Hi guys!

On CoarseDropout Class, the following arguments have the wrong type

```
        max_height: int = 8,
        max_width: int = 8,
        min_height: Optional[int] = None,
        min_width: Optional[int] = None,
```
It should be a union between int and float (according to the docstring and code)

For example:

https://github.com/albumentations-team/albumentations/blob/b773a1aa69f9c823c7f593205614d05d32c039cb/albumentations/augmentations/dropout/coarse_dropout.py#L17-L18

**Comment by ternaus** [comment]
Addressed in https://github.com/albumentations-team/albumentations/pull/1677
