### ISSUE TITLE
question: why compose need _make_targets_contiguous 

### ISSUE THREAD

**Issue by xbkaishui** [albumentations-team/albumentations#1449]
## Question

I saw in composition.py there is a _make_targets_contiguous method called by every transformer.appy

just wonder why we need it?  

I came a problem that I want to remove duplicated images after augmented_image,  I found every image is unique after called _make_targets_contiguous,  is that expected ?

Thanks

**Comment by Dipet** [comment]
Yes it is expected. In common user waits that images after transforms will be contiguous, also some transform could work incorrectly with non contiguous images.
