### ISSUE TITLE
"Installation failure due to opencv version conflict : Enforcing existing OpenCV version for Albumentations on Python 3.6.8

### ISSUE THREAD

**Issue by karpathyan** [albumentations-team/albumentations#1452]
I'm trying to install albumentaion on python 3.6.8 using `pip`. However, the installation is failing with the following error

```
Failed to build opencv-python
ERROR: Could not build wheels for opencv-python, 
which is required to install pyproject.toml-based projects
```

This is happening because my Python version is 3.6.8 and the installed opencv-python version is 3.4.13.47 and albumentation is trying to install the latest version of opencv-python (4.7.x). As per the install instructions of albumentations as given [here](https://albumentations.ai/docs/getting_started/installation/), there is a flag to force-use the existing opencv version

```pip install -U albumentations --no-binary qudida, albumentations```

However, even after using these flags, albumentation is trying to install opencv-python-4.7.0.72, and this is failing.

How can we force this to use the existing opencv version?

## To Reproduce
1. ```pip install -U albumentations --no-binary qudida, albumentations```

```
ERROR: Failed building wheel for opencv-python
Failed to build opencv-python-headless opencv-python
ERROR: Could not build wheels for opencv-python-headless, opencv-python, which is required to install pyproject.toml-based projects

```

## Environment

 - Albumentations version (e.g., 0.1.8): any
 - Python version: 3.6.8
 - OS: Linux
 - How you installed albumentations: pip
 - Any other relevant information: opencv-python version == 3.4.13.47
 -  Operating System: CentOS Linux 7 (Core)
 - CPE OS Name: cpe:/o:centos:centos:7 
 - Kernel: Linux 3.10.0-1160.88.1.el7.x86_64 
 -  Architecture: x86-64

**Comment by ternaus** [comment]
We removed python 3.6 support as it's life support ended at the end of the 2021.

Do you get the same issue on python 3.8 and later?
