### ISSUE TITLE
How to augmentation two input images and a mask at the the same time? 

### ISSUE THREAD

**Issue by QJieWang** [albumentations-team/albumentations#1455]
I have two input images, but `temp = Trans_train(image=[img_1, img_2], mask=mask)` is not supported. It only works with `temp = Trans_train(image=img_1, mask=mask)`. It's okay to augment the input images separately, but it's not convenient. So, is there any way to implement this requirement?

**Comment by Dipet** [comment]
https://albumentations.ai/docs/examples/example_multi_target/

**Comment by QJieWang** [comment]
Thank you so much.
