### ISSUE TITLE
Numpy deprecation dependency problem

### ISSUE THREAD

**Issue by Treeboy2762** [albumentations-team/albumentations#1458]
## 🐛 Bug

Import error with dependency collision with numpy. Searched through issue, but seems like I am the only one experiencing the problem. Reporting because I find it weird.

## To Reproduce

import albumentations as A

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 import albumentations as A

File [~/anaconda3/envs/ds/lib/python3.9/site-packages/albumentations/__init__.py:5](https://vscode-remote+ssh-002dremote-002bserver.vscode-resource.vscode-cdn.net/media/storage3/Daesung/Prototype_toy/reduced_iaiabl/~/anaconda3/envs/ds/lib/python3.9/site-packages/albumentations/__init__.py:5)
      1 from __future__ import absolute_import
      3 __version__ = "1.3.0"
----> 5 from .augmentations import *
      6 from .core.composition import *
      7 from .core.serialization import *

File [~/anaconda3/envs/ds/lib/python3.9/site-packages/albumentations/augmentations/__init__.py:8](https://vscode-remote+ssh-002dremote-002bserver.vscode-resource.vscode-cdn.net/media/storage3/Daesung/Prototype_toy/reduced_iaiabl/~/anaconda3/envs/ds/lib/python3.9/site-packages/albumentations/augmentations/__init__.py:8)
      5 from .crops.transforms import *
      7 # New transformations goes to individual files listed below
----> 8 from .domain_adaptation import *
      9 from .dropout.channel_dropout import *
     10 from .dropout.coarse_dropout import *

File [~/anaconda3/envs/ds/lib/python3.9/site-packages/albumentations/augmentations/domain_adaptation.py:6](https://vscode-remote+ssh-002dremote-002bserver.vscode-resource.vscode-cdn.net/media/storage3/Daesung/Prototype_toy/reduced_iaiabl/~/anaconda3/envs/ds/lib/python3.9/site-packages/albumentations/augmentations/domain_adaptation.py:6)
      4 import cv2
      5 import numpy as np
----> 6 from qudida import DomainAdapter
      7 from skimage.exposure import match_histograms
      8 from sklearn.decomposition import PCA
...

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?ff8ce457-9550-4034-b98b-435ff699859f) or open in a [text editor](command:workbench.action.openLargeOutput?ff8ce457-9550-4034-b98b-435ff699859f). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

## Expected behavior

Should import well

## Environment

 - Albumentations version (e.g., 0.1.8): 1.3.0
 - Python version (e.g., 3.7): 3.9
 - OS (e.g., Linux): linux
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant inormation: numpy 1.24

**Comment by Dipet** [comment]
This is weird. I have the same version of numpy. What exact versions of libs do you have?
For me:
```
qudida==0.0.4
numpy==1.24.3
```

To check `qudida` version write:
```
pip freeze | grep qudida
```

**Comment by Treeboy2762** [comment]
I have deleted the conda environment and started from scratch to work around the problem.

Was gonna close the issue, but I will leave it open for now.

**Comment by sestras** [comment]
I noticed that my error from above has already been fixed with PR #1370 some time ago, so I'd say you can close this issue. We'll just have to wait for the next albumentations release and the incompatibilities with numpy >= 1.24 should be resolved.

**Comment by Treeboy2762** [comment]
Closing. Have a nice day~
