### ISSUE TITLE
[Bug/Improvement] Global Parameters setting

### ISSUE THREAD

**Issue by FrsECM** [albumentations-team/albumentations#1461]
## 🐛 Bug

In my company we developped a library in order to train models and our default augmentation library is Albumentations.
The idea is to reduce the technical background necessary to train models for computer vision.

The user have the ability to "override" albumentations augmentations. But we would like it to be as smooth as possible.

The problem is that in our implementation of semantic segmentation, we store our labels as polygons (because it's compatible with either semantic and instance segmentation).
And we did an optimisation in order to generate the mask directly with the right size in order to save some CPU time when we do a downsampling of the image.
The problem is that with version 1.3.1, we have an error regarding the size of the mask that is not the same of the size of the image.
For exemple :<br>
![image](https://github.com/albumentations-team/albumentations/assets/26071804/8e02b2ec-0001-4616-ae67-09ba9b602660)
Generate an issue if the mask is at the same shape than the final resized shape.

## To Reproduce

1. Generate a mask with shape 128x128 for an image 256x256
2. Create a bunch of augmentation (with a resize to 128x128)
3. Try to apply the augmentation

Crash ! 

The fix is to set the parameter.
![image](https://github.com/albumentations-team/albumentations/assets/26071804/a3785e84-a8e6-4d6b-ade9-e518e082d0e2)

But my user is not supposed to know this trick and implementation detail, then i would like a way to set it "globally" for him.

## Expected behavior

I would like to avoid this error that is blocking without asking the user to add an extra parameter when he overrides augmentations.

## Environment

 - Albumentations version  1.3.1
 - Python version 3.8
 - OS (e.g., Linux): WSL
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by ternaus** [comment]
@FrsECM 

1. Very curious to see how much speed one gets, when processing masks in a smaller form. Could you please share numbers?

2. We are open to add desired functionality if needed. But as it is kind of unique request - would your company consider becoming a sponsor for the library to speed up the development of new features?
