### ISSUE TITLE
Empty Transformed Results

### ISSUE THREAD

**Issue by MR-hyj** [albumentations-team/albumentations#1468]
My pipeline is as follows:
```python
transforms = A.Compose(
    [
        A.Resize(p=1 if RESIZE_SHAPE else 0, height=RESIZE_SHAPE[0], width=RESIZE_SHAPE[1]),
        A.HorizontalFlip(p=0.5), 
        A.VerticalFlip(p=0.5), 
        A.Rotate(p=0.5), 
        A.GaussNoise(p=0.5), 
        A.RandomBrightnessContrast(p=0.5), 
        A.CLAHE(p=0.5), 
        A.Emboss(p=0.5), 
        A.FancyPCA(p=0.5), 
        A.Sharpen(p=0.5), 
    ], 
    bbox_params=A.BboxParams(
        format='pascal_voc', label_fields=['bbox_classes']
    )
)


transformed = transforms(
        image=corr_image, 
        bboxes=corr_bndbox, 
        bbox_classes=[class_name]*corr_bndbox.shape[0]
)
```
During running, the following two issues are detected

Firstly, there is a small chance that `transformed['image']` is an empty list, and the randomness is so high, making the issue almost irreproducible. Out of my 16,000 samples, approximately 40 of them encounter this problem. To address this issue, I had to implement a while loop as a workaround:
```python 
transformed = transforms(
        image=corr_image, 
        bboxes=corr_bndbox, 
        bbox_classes=[class_name]*corr_bndbox.shape[0]
)
while not transformed['image']:
    transformed = transforms(
        image=corr_image, 
        bboxes=corr_bndbox, 
        bbox_classes=[class_name]*corr_bndbox.shape[0]
    )
```

Another issue is that in the original labels, there might be ten instances, but after the transformation, the number of instances could decrease. This can be verified from `transformed['bboxes']`. Similarly, this is also a very low probability event.

**Comment by Dipet** [comment]
> Firstly, there is a small chance that transformed['image'] is an empty list, 

It looks like problem with your dataloader because error occured before albumentations pipeline call.

> Another issue is that in the original labels, there might be ten instances, but after the transformation, the number of instances could decrease.

Check docs: https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/#step-2-define-an-augmentation-pipeline
You can control this behaviour with `BboxParams`
