### ISSUE TITLE
 module 'albumentations' has no attribute 'BboxProcessor'

### ISSUE THREAD

**Issue by uuup111** [albumentations-team/albumentations#1502]
## To Reproduce

1.  bbox_params = A.BboxParams(
            format='pascal_voc', min_area=min_area,
            min_visibility=min_visibility, label_fields=['labels', 'box_ids'])
        self.bbox_process = A.BboxProcessor(bbox_params)

## Environment

 - Albumentations version (e.g., 0.1.8):   albumentations-1.3.1
 - Python version (e.g., 3.7): 3.11
 - OS (e.g., Linux): Windows 11
 - How you installed albumentations (`conda`, `pip`, source): pip and source
 - Any other relevant information:

**Comment by Dipet** [comment]
`BboxProcessor` is an internal class an does not propagated to the top import level.
`from albumentations.core.bbox_utils import BboxProcessor`
