### ISSUE TITLE
95 tests fail

### ISSUE THREAD

**Issue by yurivict** [albumentations-team/albumentations#1505]
## 🐛 Bug

[log](https://freebsd.org/~yuri/py-albumentations-1.3.1-tests.log)

## Environment

 - Albumentations version (e.g., 0.1.8): 1.3.1
 - Python version (e.g., 3.7): 3.9
 - OS (e.g., Linux): FreeBSD 14.0
 - How you installed albumentations (`conda`, `pip`, source): FreeBSD port

**Comment by ternaus** [comment]
Everything should work now.
