### ISSUE TITLE
albumentations 1.4 pulls in both opencv-python and opencv-python-headless

### ISSUE THREAD

**Issue by vonschultz** [albumentations-team/albumentations#1528]
## 🐛 Bug

albumentations 1.4 pulls in both `opencv-python` and `opencv-python-headless`

## To Reproduce

```
python3.10 -m venv albumentations-1.4 && (source albumentations-1.3/bin/activate && pip install albumentations==1.4.0 && pip list | grep opencv)
```

Compare against albumentations 1.3.1, which doesn't have this problem.

```
python3.10 -m venv albumentations-1.3 && (source albumentations-1.3/bin/activate && pip install albumentations==1.3.1 && pip list | grep opencv)
```

## Expected behavior

In albumentations 1.3.1 the output from grep is just
```
opencv-python-headless 4.9.0.80
```

We only get opencv-python-headless.

## Actual behavior

In albumentations 1.4 the output from grep is
```
opencv-python          4.9.0.80
opencv-python-headless 4.9.0.80
```
where we got both `opencv-python` and `opencv-python-headless`.

## Environment

 - Albumentations version (e.g., 0.1.8): 1.4
 - Python version (e.g., 3.7): 3.10
 - OS (e.g., Linux): Ubuntu Linux
 - How you installed albumentations (`conda`, `pip`, source): pip
## Additional context

`qudida` pulls in  `opencv-python-headless`, so if you're depending on `qudida`, please use the same. Also, according to https://albumentations.ai/docs/getting_started/installation/ you should be giving us  `opencv-python-headless` if `opencv-python` is not already installed.

**Comment by ternaus** [comment]
Thank you for reporting.

We will move quida code base to the library, which will remove this issue..

**Comment by ternaus** [comment]
Should be fixed in https://github.com/albumentations-team/albumentations/pull/1546
