### ISSUE TITLE
 module 'albumentations' has no attribute 'BrightnessContrast'

### ISSUE THREAD

**Issue by aniruddhakasar** [albumentations-team/albumentations#1554]
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_12312\71125488.py in <cell line: 0>()
      4     A.HorizontalFlip(p=0.5),
      5     A.Rotate(p=0.5),
----> 6     A.BrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),  # Adjust brightness and contrast
      7     A.OneOf([
      8         A.MotionBlur(blur_limit=5, p=0.25),

AttributeError: module 'albumentations' has no attribute 'BrightnessContrast'

**Comment by ternaus** [comment]
[RandomBrightnessContrast](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.RandomBrightnessContrast) should work
