### ISSUE TITLE
[Doc] Style of parameter tables in API reference is being broken

### ISSUE THREAD

**Issue by i-aki-y** [albumentations-team/albumentations#1555]
## 📚 Documentation

The style of the parameter tables in the API documentation is being broken.
https://albumentations.ai/docs/api_reference/augmentations/transforms/

<img width="1060" alt="api-doc" src="https://github.com/albumentations-team/albumentations/assets/9190086/7de45416-8a9f-48b2-b996-1b56cf349875">

I found recent commit inserts `------` in the docstrings:

```diff
    Args:
+    ----
	para1: ...
	para2: ...
```

This appears to prevent `mkdocs` from parsing the docstring, since mkdocs assumes "google-style" that does not use `-----` for sections.

https://github.com/albumentations-team/albumentations.ai/blob/4fda83887b102ea3f0e08c9f10e5ea7d4dfd4201/mkdocs/src/mkdocs.yml#L13-L14

cf: about google-style
https://mkdocstrings.github.io/python/usage/docstrings/google/
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by ternaus** [comment]
Thanks for pointing this out.

**Comment by ternaus** [comment]
FIxed in https://github.com/albumentations-team/albumentations/pull/1556

The issue was that script that generated docs did not distinguish between Deprecated class and deprecated parameter in the class and did not use it.

**Comment by i-aki-y** [comment]
@ternaus Thank you for your quick response.

But I could not confirm the fix in the documetation site.

Lines "----" appear in commit #1529, where the lines are inserted at some sections (not all sections) of every transform's docstrings.
I think we need to remove those inserted lines “----" to fix the issue.

**Comment by ternaus** [comment]
I was not able to set up ruff to check for "----", it does not flag it as violation of google docstrings format.

I will try to upgrade version of mkdocs, maybe it will be more robust toward formatting of the docstring.

I can also have a custom hook, that just look for "---" and longer in the code.

What exactly don't you like in the existing version of parsed docstrings?

**Comment by i-aki-y** [comment]
The current albumentation dosctring mixes two docstring section styles (google and numpy).
The mkdocs support two of them but can not handle mixed cases in a single project.
I found the following issue discussing more flexible style support in the mkdocs, but the issue is still open and is inconclusive.

https://github.com/mkdocstrings/griffe/issues/5

It would be preferable to format docstring with tools like ruff or black, but currently, they do not seem able to handle docstring styles.
And I could not find other tools that support formatting multiple docstring styles.

If possible, I think writing a custom hook would be a practical workaround, and I expect deleting "---" is sufficient.
I could confirm that the mkdocs correctly rendered the parameter table by deleting lines "----" in a transform docstring on my local machine.

Ex: 
![screenshot_params](https://github.com/albumentations-team/albumentations/assets/9190086/b01a5e45-4b97-42c4-9c84-8893bf68d19f)

**Comment by ternaus** [comment]
Added check for `---` in docstrings and cleaned from the existing code. It is a hack, rather than solution, but hopefully will help for some time: https://github.com/albumentations-team/albumentations/pull/1558

**Comment by ternaus** [comment]
Looks like works

**Comment by i-aki-y** [comment]
@ternaus  Thanks!
