### ISSUE TITLE
Compatibility with FiftyOne Albumentations Integration Plugin

### ISSUE THREAD

**Issue by jacobmarks** [albumentations-team/albumentations#1567]
[FiftyOne](https://docs.voxel51.com/), an open source tool for data curation and visualization, has an [Albumentations plugin](https://github.com/jacobmarks/fiftyone-albumentations-plugin), which allows you to test out augmentation transformations on the dataset level before applying them on-the-fly. 

As part of the plugin, the Albumentations documentation is parsed using the `inspect` module — in particular the `getdoc()` and `signature()` functions. The parsing attempts to identify the types of parameters to each of the transformations. If there are default parameter values, those are used. Otherwise, the docstring is parsed (split at "Arguments" and "Targets") and the type inference is attempted from this.

Any structure/guarantees around the defaults or the format of the docstrings for arguments would be very helpful!

For context, here is the code used to infer type: https://github.com/jacobmarks/fiftyone-albumentations-plugin/blob/184c1686137d1ce8ce3afa98bb19b26ec61dc9c9/__init__.py#L440

**Comment by ternaus** [comment]
Thanks!

Going to add a check that verifies that all docstrings in Tranforms match Google Docstrings to the level that your parser works without issues.
