### ISSUE TITLE
[tech debt] Update params for `RandomResizedCrop`

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1587]
Match signature of `Albumentations.RandomResizedCrop` and `TorchVision.RandomResizedCrop`

i.e. add parameter `size = [height, width]` and throw deprecated warning for `height / width`

**Comment by zetyquickly** [comment]
There are two simple options to consider:

1. Proceed without mandating that arguments be named after the third parameter. This approach can make the function calls appear verbose and potentially less readable, especially if there are many parameters. The code might end up looking quite wordy, which could affect maintainability and clarity:

```python
class RandomResizedCrop(_BaseRandomSizedCrop):
...
  def __init__(
          self,
          size: Union[int, Tuple[int, int]],
          *args,
          ratio: Tuple[float, float] = (0.75, 1.3333333333333333),
          interpolation: int = cv2.INTER_LINEAR,
          always_apply: bool = False,
          p: float = 1.0,
      ):
          if isinstance(size, tuple):
              if len(size) != 2:
                  raise ValueError("Size must be a tuple of two integers (height, width).")
              height, width = size
              if len(args) >= 1:
                  scale = args[0]
              else:
                  scale = (0.08, 1.0)
              if len(args) > 1:
                  ratio = args[1]
          else:
              if len(args) < 1:
                  raise ValueError("Width must be provided when the first argument is an integer.")
              width = args[0]
              if len(args) >= 2:
                  scale = args[1]
              else:
                  scale = (0.08, 1.0)
              if len(args) > 2:
                  ratio = args[2]
              warn(
                  "Initializing with separate height and width is deprecated and will be removed in a future version. "
                  "Please pass a tuple (height, width) as the first argument.",
                  DeprecationWarning,
                  stacklevel=2
              )
              height = size
  
          super().__init__(height=height, width=width, interpolation=interpolation, always_apply=always_apply, p=p)
          self.scale = scale
          self.ratio = ratio
```

2. Go with enforcing named arguments for all parameters after the third one. This approach enhances clarity and readability but might break existing code for users who have not used named arguments in their calls, as illustrated below:

```python
A.RandomResizedCrop(513, 450, (0.08, 1.0)) # Called without argument names
```


implementation [cleaner]:
```python
class RandomResizedCrop(_BaseRandomSizedCrop):
...
  def __init__(
          self,
          size: Union[int, Tuple[int, int]],
          width: Optional[int] = None,
          *,
          scale: Tuple[float, float] = (0.08, 1.0),
          ratio: Tuple[float, float] = (0.75, 1.3333333333333333),
          interpolation: int = cv2.INTER_LINEAR,
          always_apply: bool = False,
          p: float = 1.0,
      ):
          if isinstance(size, tuple):
              if len(size) != 2:
                  raise ValueError("Size must be a tuple of two integers (height, width).")
              height, width = size
          else:
              if width is None:
                  raise ValueError("Width must be provided when 'size' is an integer.")
              height = size
  
          super().__init__(height=height, width=width, interpolation=interpolation, always_apply=always_apply, p=p)
          self.scale = scale
          self.ratio = ratio
 ```

**Comment by Aloqeely** [comment]
While option 1 is the safer choice, I prefer option 2 more, but it needs a deprecation warning for using separate height and width arguments

**Comment by ternaus** [comment]
I prefer something similar to:

[github.com/albumentations-team/albumentations/blob/0cb8de5022a484e4586ce573040fc6e58885b094/albumentations/augmentations/blur/transforms.py#L349
](https://github.com/albumentations-team/albumentations/blob/0cb8de5022a484e4586ce573040fc6e58885b094/albumentations/augmentations/blur/transforms.py#L349)
---
Not a big fan of `*args` in the code, as it complicates readability and type checking.

=>
Just add `size`  When people use `height` and `width,` a deprecation warning will appear, but the transform should still work.

It will break compatibility for people who call transform without argument names, but I don't know how big the issue will be.

@Dipet, what do you think?

**Comment by Aloqeely** [comment]
> I prefer something similar to:
> 
> ## [github.com/albumentations-team/albumentations/blob/0cb8de5022a484e4586ce573040fc6e58885b094/albumentations/augmentations/blur/transforms.py#L349 ](https://github.com/albumentations-team/albumentations/blob/0cb8de5022a484e4586ce573040fc6e58885b094/albumentations/augmentations/blur/transforms.py#L349)
A little off topic, but isn't the warning always going to be triggered in this specific case? Line 336: `sigmaX_limit: ScaleFloatType = (0.2, 1.0),  # noqa: N803` indicates that sigmaX_limit will always have a value, hence the program will always think the user is using that parameter and print a warning

**Comment by ternaus** [comment]
Yes, you are right. We trigger this warning even if user initializes the transform in non-deprecated way. Your PR is welcome.

**Comment by ternaus** [comment]
Done in https://github.com/albumentations-team/albumentations/pull/1615/files
