### ISSUE TITLE
[Feature Request] Add Copy and Paste tramsform 

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1616]
## Feature description

Add CopyAndPaste Augmentation from https://arxiv.org/abs/2012.07177

Used in github.com/ultralytics/yolov5/blob/ac6c4383bc0c7a2a4f7ca18f8733821b49e916bd/utils/augmentations.py#L19

**Comment by zetyquickly** [comment]
Orig. implementation: https://github.com/conradry/copy-paste-aug

**Comment by zetyquickly** [comment]
Isn't it a duplicate of [this issue](https://github.com/albumentations-team/albumentations/issues/1225) ?
It has an unfinished [PR](https://github.com/albumentations-team/albumentations/pull/1297)

**Comment by ternaus** [comment]
Yes, and yes.

Sure, let's close this one and continue the discussion in that issue.
