### ISSUE TITLE
Add transforms from Augraphy

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1623]
For every transform:
1. Double check that there is no 
2. Create separate Pull request.
3. Add the code and check where possible that numpy operations are replaced by the similar OpenCV code.
4. Use vectorized operations where possible.
5. Add link to the original implementation and where possible paper where the transform was intriduced. 

https://augraphy.readthedocs.io/en/latest/doc/source/list_of_augmentations.html

- [ ] BadPhotoCopy
- [ ] BindingsAndFasteners
- [ ] Bleedthrough
- [ ] BrightnessTexturize
- [ ] ColorShift
- [ ] DelaunayTessellation
- [ ] DepthSimulatedBlur
- [ ] DirtyDrum
- [ ] DirtyRollers
- [ ] DirtyScreen
- [ ] DotMatrix
- [ ] DoubleExposure
- [ ] Faxify
- [ ] Hollow
- [ ] InkBleed
- [ ] InkColorSwap
- [ ] InkMottling
- [ ] LCDScreenPattern
- [ ] LensFlare
- [ ] Letterpress
- [ ] LightingGradient
- [ ] LinesDegradation
- [ ] LowInkPeriodicLines
- [ ] LowInkRandomLines
- [ ] LowLightNoise
- [ ] Markup
- [ ] Moire
- [ ] NoiseTexturize
- [ ] NoisyLines
- [ ] PatternGenerator
- [ ] ReflectedLight
- [ ] Scribbles
- [ ] ShadowCast
- [ ] SubtleNoise
- [ ] VoronoiTessellation
- [ ] WaterMark
- [ ] BookBinding
- [ ] Folding
- [ ] GlitchEffect
- [ ] InkShifter
- [ ] Rescale as Rescale2DPI
- [ ] SectionShift

**Comment by ternaus** [comment]
Had discussion with a person working on Document scans. She said that these look like the most valuable:
```
Pixel:
- BadPhotoCopy
- DirtyDrum
- Letterpress
- Markup
- WaterMark

Spatial:
- BookBinding
- Folding
- SectionShift
```

**Comment by MarognaLorenzo** [comment]
Hi, I would like to try implementing BadPhotoCopy.
Should I add it in the "albumentations/augmentations/transforms.py" file? I was thinking I could create a folder like "albumentations/augmentations/augraphy" or "albumentations/augmentations/documents", where all the 42 transformations in this issue will be added.

**Comment by ternaus** [comment]
`albumentations/augmentations/documents` will work
