### ISSUE TITLE
[Tech debt] Update interface for ImageCompression

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1627]
Right now in the transform we have separate parameters for `[quality_lower, quality_upper]`

Better would be to have one parameter `quality_range = [quality_lower, quality_upper]`

=>

We can update transform to use new signature, keep old as working, but mark as deprecated.
----
PR could be similar to https://github.com/albumentations-team/albumentations/pull/1615

**Comment by MarognaLorenzo** [comment]
Hi! I would like to work on it, let me know if anybody is doing it already

**Comment by ternaus** [comment]
@MarognaLorenzo Go ahead

**Comment by MarognaLorenzo** [comment]
![Screenshot 2024-04-25 at 10 49 23](https://github.com/albumentations-team/albumentations/assets/99410146/4f1bde69-0b94-45f3-b42d-822bffdba909)

Hi, I found this interesting problem while working on the issue. For some reason, when I pass an argument to the constructor,  it seems like in some cases it does not receive it. It works when I pass `quality_lower` or `quality_upper` but not with `quality_range'. Any clue?

In the test you're seeing in the screenshot, I am trying to initialize the module with `quality_range` but when I print it in the constructor or I have is the default value. I also tried to change the default value to some valid tuple and the output is that the new default is used and never overwritten by the parameter I passed in input.

Thank you in advance for the help!

**Comment by ternaus** [comment]
You cans see a class `InitSchema`

What is does it:
1. validates inputs to the `__init__`
2. transforms them

and after that feeds to the init

=> all checks and preprocessing should happen there, not in the `__init__`.

If you look at `CoarseDropout` https://github.com/albumentations-team/albumentations/blob/main/albumentations/augmentations/dropout/coarse_dropout.py

It has similar situation, although it is more complex as it needs to process 3 pairs of variables and replace them by ranges.

and after that deprecated variables are not used in the transform at all as they are already not needed.

Quite similar in your case - you need to write `@model_validator`that creates `quality_range` from `[quality_lower, quality_upper]` if `quality_lower and quality_upper` are not None.

P.S. I should probably add this info to `Contributor's guide`....

**Comment by MarognaLorenzo** [comment]
#1691 should solve the issue

**Comment by ternaus** [comment]
Addressed in:

https://github.com/albumentations-team/albumentations/pull/1691
https://github.com/albumentations-team/albumentations/pull/1704
