### ISSUE TITLE
[Tech debt] Update interface for RandomRain

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1629]
Right now in the transform we have separate parameters for `slant_lower` and `slant_upper`

Better would be to have one parameter `slant_range = [slant_lower, slant_upper]`

=>

We can update transform to use new signature, keep old as working, but mark as deprecated.
----
PR could be similar to https://github.com/albumentations-team/albumentations/pull/1704

**Comment by MarognaLorenzo** [comment]
Hi, I would like to work on it
