### ISSUE TITLE
[Tech debt] Improve interface for DropOut

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1635]
* `scale_min`, `scale_max` => `scale_range`

=>

We can update transform to use new signature, keep old as working, but mark as deprecated.
----
PR could be similar to https://github.com/albumentations-team/albumentations/pull/1704

**Comment by MarognaLorenzo** [comment]
Hi, I would like to work on this!

**Comment by ternaus** [comment]
@MarognaLorenzo Would love to get another PR from you!

I guess, the code will be quite similar to https://github.com/albumentations-team/albumentations/pull/1704

**Comment by MarognaLorenzo** [comment]
After checking the code base, it seems to me that there is no place where DropOut uses `scale_min` nor `scale_max`.
They are used into "albumentations/augmentations/transforms.py"@ Downscale(ImageOnlyTransform) - line: 1887.

What is this issue referring to?
