### ISSUE TITLE
[Bug] Check what is fed to Compose

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1636]
Following: https://github.com/albumentations-team/albumentations/issues/422#issuecomment-2040517244

RIght now you may feed a list of targets to compose and if you did not define `additional_targets` it will not apply anything to them.

=> we need to check that no unexpected inputs are fed to `Compose`

**Comment by ternaus** [comment]
@ayasyrev was this issue also addressed in https://github.com/albumentations-team/albumentations/pull/1647 ?

**Comment by ayasyrev** [comment]
No, it's related #1636

**Comment by ayasyrev** [comment]
fixed #1706
