### ISSUE TITLE
Augmentation for multiple keypoints is broken

### ISSUE THREAD

**Issue by domef** [albumentations-team/albumentations#1638]
## Describe the bug

The augmentation for multiple keypoints works only if the `additional_targets` are defined in the constructor whereas if they are added with `add_targets` the angle of the second keypoints are wrong.

First example:
```python
import numpy as np
import albumentations as A

transform = A.Compose(
    transforms=[A.Rotate(limit=(90.0, 90.0), p=1.0)],
    keypoint_params=A.KeypointParams(
        angle_in_degrees=True,
        check_each_transform=True,
        format="xyas",
        label_fields=None,
        remove_invisible=False,
    ),
    additional_targets={"keypoints2": "keypoints"},
)

image = np.zeros((100, 100, 3), dtype=np.uint8)
kps1 = np.array([[10, 10, 1, 0], [20, 20, -100, 0]], dtype=np.float64)
kps2 = np.array([[20, 20, 190, 0], [40, 40, 123, 0]], dtype=np.float64)

out = transform(image=image, keypoints=kps1, keypoints2=kps2)

kps1_t = out["keypoints"]
kps2_t = out["keypoints2"]

print(kps1)
print(kps1_t)
print()
print(kps2)
print(kps2_t)
```
The output is correct:
```
[[  10.   10.    1.    0.]
 [  20.   20. -100.    0.]]
[(9.999999999999993, 89.0, 91.0, 0.0), (19.999999999999993, 79.0, 350.0, 0.0)]

[[ 20.  20. 190.   0.]
 [ 40.  40. 123.   0.]]
[(19.999999999999993, 79.0, 280.0, 0.0), (39.99999999999999, 59.0, 213.0, 0.0)]
```

Second example:
```python
import numpy as np
import albumentations as A

transform = A.Compose(
    transforms=[A.Rotate(limit=(90.0, 90.0), p=1.0)],
    keypoint_params=A.KeypointParams(
        angle_in_degrees=True,
        check_each_transform=True,
        format="xyas",
        label_fields=None,
        remove_invisible=False,
    ),
)
transform.add_targets({"keypoints2": "keypoints"})

image = np.zeros((100, 100, 3), dtype=np.uint8)
kps1 = np.array([[10, 10, 1, 0], [20, 20, -100, 0]], dtype=np.float64)
kps2 = np.array([[20, 20, 190, 0], [40, 40, 123, 0]], dtype=np.float64)

out = transform(image=image, keypoints=kps1, keypoints2=kps2)

kps1_t = out["keypoints"]
kps2_t = out["keypoints2"]

print(kps1)
print(kps1_t)
print()
print(kps2)
print(kps2_t)
```
The output is NOT correct:
```
[[  10.   10.    1.    0.]
 [  20.   20. -100.    0.]]
[(9.999999999999993, 89.0, 91.0, 0.0), (19.999999999999993, 79.0, 350.0, 0.0)]

[[ 20.  20. 190.   0.]
 [ 40.  40. 123.   0.]]
[(19.999999999999993, 79.0, 3.0752371114073043, 0.0), (39.99999999999999, 59.0, 5.190275490382753, 0.0)]
```

### To Reproduce

Python version: 3.8.18
Albumentations version: 1.3.0

**Comment by ternaus** [comment]
The canonical way to add extra targets is with `additional_targets`, and not `add_targets`.

Similar to  https://albumentations.ai/docs/examples/example_multi_target/

I will update the docstring for `add_targets` and FAQ and see what how can we update the code to prevent people from using this functions. 

Thank you for pointing this out!

**Comment by domef** [comment]
Thank you for the response.
I understand that the preferred way to add targets is by passing them in the constructor but what is `add_target` used for? Why isn't it a private method if people shouldn't call it? Moreover the code I showed in the main post works when using angles in radians, so it seems something like a problem of default values used for the newly added keypoints but I don't know if it hide other deeper problems.

**Comment by ternaus** [comment]
We should make `add_target` a private method long ago. But it slipped from our attention. Will address this in a few hours, when I will be in front of the computer.

Of course there could be some hidden problems. If you have a test in mind, that could potentially uncover them, that would be great.

**Comment by ternaus** [comment]
@domef should be fixed in https://github.com/albumentations-team/albumentations/pull/1647

Would you, or your company consider becoming sponsors for Albumentations?

https://github.com/sponsors/albumentations-team

It will could speed up the work and decrease response time.

P.S. If not, still cool. I like how you find interesting bugs in the library. It is ultra useful in itself.

Thanks!

**Comment by domef** [comment]
I confirm that the bug seems resolved.
