### ISSUE TITLE
Confusing error message for `AffineSchema` when both `translate_px` and `translate_percent` are passed

### ISSUE THREAD

**Issue by matsumotosan** [albumentations-team/albumentations#1648]
## Enhancement Description

I came across a confusing error message for the `AffineSchema` when both `translate_px` and `translate_percent` are passed as arguments.

### Motivation and Goals

https://github.com/albumentations-team/albumentations/blob/f9106135dad777c687f44c55e67777560737cd93/albumentations/augmentations/geometric/transforms.py#L637-L639

### Possible Implementation

Fix the message to something like:
```python
msg = "Expected either translate_percent or translate_px to be " "provided, " "but both were provided."
```

### Additional Context

Provide any additional context or examples of similar enhancements in other projects that might help illustrate your suggestion.

**Comment by ayasyrev** [comment]
Do we need error here? Maybe use translate_px and do warning instead?

**Comment by ternaus** [comment]
Fixed in https://github.com/albumentations-team/albumentations/pull/1649
