### ISSUE TITLE
[Feature request] Add option to clip bounding boxes before applying pipline if they are outside of the image.

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1652]
Right now, if user has boxes that fails outside of the image they get an error like:

```python
Expected y_min for bbox (0.564, 1.4433333333333334, 0.659, 1.6916666666666667, 2) to be in the range [0.0, 1.0], got 1.4433333333333334.
```

Which says that there is something wrong with labels.

It could be wrong because:

1. Plainly wrong, because of some bug.
2. Inaccurate labeling, or image is a crop from a bigger one and labels were not updated.

We decided that throwing error is better, as it makes user look with their eyes on the labels.

But we get request for adding clip, as users solid that labels are correct, but just not clipped to the size of the image.

The proposal is to add `clip` parameter to `BBoxParams` that is fed to the `Compose`.

Check box sizes before and
- `If clip = False` => throw error as it is now
- `If clip = True` => clip, throw warning and move on.

It will also remove all issues with Yolo bounding boxes including 1.

**Comment by ternaus** [comment]
Addressed in https://github.com/albumentations-team/albumentations/pull/1671

**Comment by qubvel** [comment]
Thanks, work as expected!
