### ISSUE TITLE
Ability to Apply Crop Augmentation on selected classes 

### ISSUE THREAD

**Issue by m-ali-awan** [albumentations-team/albumentations#1661]
## Feature description

Recently, I came across the problem of under-represented classes in an instance segmentation dataset. And it posed such problem, eg if I am labeling house objects, and `stairs-bannisters` , `wall-painting` are classes. Now, if I simply increase images, bannisters also increase exponentially,
But on the otherhand, if I can augment the dataset with the flexibility of Cropping only around the wall-painting class, I can reduce this data-imbalance by some extent..

### Possible implementation

I don't have complete solution, but I tried a bit. I think, as we can pass class-name or class- id in the `boxes` once we pass it to transform , somehow if we can limit for a particular-transform(possibly a new one), `class-conditional-cropping`, and it only randomly select from selected classes, and it crops around those objects...

**Comment by ternaus** [comment]
No plans to implement this feature in the nearby future, although it is not that hard to implement.

I guess ChatGPT would be able to provide code for a custom transform with this functionality.
