### ISSUE TITLE
Why PerChannel can not be import directly 

### ISSUE THREAD

**Issue by mhtrinh** [albumentations-team/albumentations#1668]
When I try : 
```
import albumentations as A
color = A.PerChannel(channels=[0,1,2], transforms=[
    A.ColorJitter(p=1.0, 
                  brightness=(0.8, 1.2), 
                  contrast=(0.8, 1.99), 
                  saturation=(0.8, 1.2), 
                  hue=(-0.07, 0.07)
                 ),     
],)
```
I get `AttributeError: module 'albumentations' has no attribute 'PerChannel'`

Based on the code [here](https://github.com/albumentations-team/albumentations/blob/35bf09e4a2212dcb083cb22e0ecdd765a0e38e30/albumentations/core/composition.py#L21), `PerChannel` is not exposed like the other class

Is there a reason for such ?

**Comment by ternaus** [comment]
I it an experimental feature and just adding it to `__all__` is not enough.

1. Some transforms like `ColorJitter` could not be applied to one channel, but require 3 channel images. => It should be a Separate Transform, say `SubsetChannels` 
2. In the existing implementation, there is no guarantee that it will be the same transform, applied to different channels as many transforms sample random parameters and different channels would get different values.


We could address both issues and make things work as expected. (It is not just adding to `__all__`).

But, for use to better understand how to do it better, could you please share what problem do you face that requires transform being applied to a subset?

**Comment by mhtrinh** [comment]
I use multi spectral images: RGB, IRA, IRB, IRC, ... So I stack them up to something like 6 channels image.

I still want to do some brightness and color augmentation. So I use `PerChannel` to select and apply color jittering to the "color" image in my stack, and apply Brightness and contrast to the other channels in my image stack. At least that how I hope it should work.

Otherwise, I need to do a separate augmentation pipeline for each type of image independently and then stack them before feeding it to the model ?  How would you do that with `mmpretrain` for example ?

**Comment by ternaus** [comment]
I see. Yep, for stacking images made sense. I did something similar working with satellite images before Albumentations.

We will add the desired functionality. Hopefully in the next couple weeks, before the next release.

**Comment by ternaus** [comment]
Added in https://github.com/albumentations-team/albumentations/pull/1690

But it is called: `SelectiveChannelTransform`
