### ISSUE TITLE
RandomCropFromBorders fails with `crop_left=0.0`

### ISSUE THREAD

**Issue by jakub-h** [albumentations-team/albumentations#1680]
## Describe the bug

After #1624, `random.randint()` is replaced with `np.random.RandomState.randint()` in `RandomCropFromBorders` augmentation. The later one raises an error when it's `high` parameter is 0.0. This happens when you don't want to crop randomly from all sides and set one or more of the `crop_*` parameters to 0.0, due to the following code:
```python
def get_params_dependent_on_targets(self, params: Dict[str, Any]) -> Dict[str, int]:
    img = params["image"]
    x_min = random_utils.randint(0, int(self.crop_left * img.shape[1]))
    x_max = random_utils.randint(max(x_min + 1, int((1 - self.crop_right) * img.shape[1])), img.shape[1])
    y_min = random_utils.randint(0, int(self.crop_top * img.shape[0]))
    y_max = random_utils.randint(max(y_min + 1, int((1 - self.crop_bottom) * img.shape[0])), img.shape[0])
    return {"x_min": x_min, "x_max": x_max, "y_min": y_min, "y_max": y_max}
```
It's even validated using pydantic (`ge=0.0`). 

### To Reproduce

1. Environment - Ubuntu 20.04, python 3.10, albumentations 1.4.4
2. Sample code that produces the bug.
```python
A.RandomCropFromBorders(
    crop_left=0, crop_right=0, crop_top=0, crop_bottom=0.6, p=1.0
)
```
4. Any error messages or incorrect outputs.
![Screenshot from 2024-04-22 15-06-21](https://github.com/albumentations-team/albumentations/assets/23062908/b2ad58ef-43c1-47b6-bfe1-3432ee3f7787)

### Expected behavior

In `1.4.3` it was possible to use `RandomCropFromBorders` with only e.g. one side set to a non-zero value. 

### Actual behavior

This is not possible in `1.4.4` due to an error. (see the bug description)

### Additional context

It should be either disabled to use the augmentation with a `crop_*` parameter set to 0.0 (and reflect it in the pydantic validation too) or fix the numpy randint call.

**Comment by ternaus** [comment]
Thanks! Will work on it ASAP.

**Comment by ternaus** [comment]
Fixed in https://github.com/albumentations-team/albumentations/pull/1682

@jakub-h would you, or our company consider becoming a sponsor?

https://github.com/sponsors/albumentations-team
