### ISSUE TITLE
[Documentation] Don't state `ToGray` would apply a conditional inversion

### ISSUE THREAD

**Issue by j-leuschner** [albumentations-team/albumentations#1684]
## Documentation request

I think the documentation of the `ToGray` transform is wrong in stating that it would invert the image if its mean is greater than 127. It does not appear to do so, and the code looks like plain conversions via `cv2`, without a conditional inversion.

**Comment by ternaus** [comment]
Thank you for the report.

Addressed in https://github.com/albumentations-team/albumentations/pull/1688
