### ISSUE TITLE
GridDistortion Reference

### ISSUE THREAD

**Issue by danielmao2019** [albumentations-team/albumentations#1694]
The blog [http://pythology.blogspot.sg/2014/03/interpolation-on-regular-distorted-grid.html](http://pythology.blogspot.sg/2014/03/interpolation-on-regular-distorted-grid.html) has been removed. Any additional reference for grid_distortion please? Thanks.

grid_distortion is defined here [https://github.com/albumentations-team/albumentations/blob/d47389cd8c40f7f7b5a0ee777a204e251484ed11/albumentations/augmentations/geometric/functional.py#L1256](https://github.com/albumentations-team/albumentations/blob/d47389cd8c40f7f7b5a0ee777a204e251484ed11/albumentations/augmentations/geometric/functional.py#L1256).

**Comment by ternaus** [comment]
Thank you for pointing out. Will remove this reference.

Grid Distorion is such an intuitive thing, that we can probably remove reference at all.

Although if someone can point to the original-original source of the idea - would be happy to add it.

**Comment by danielmao2019** [comment]
Thanks for the reply!

I've seen distortion but wasn't sure what 'grid' distortion does exactly
before looking at the code.

Maybe some reference to papers that uses grid distortion will be helpful,
if finding them doesn't take too long :)

**Comment by ternaus** [comment]
Removed reference to not existing blog post, but expanded docstring in the transform - hopefully it will be easier to understand what the transform is about.

**Comment by danielmao2019** [comment]
Great, thx!
