### ISSUE TITLE
Unexpected Kernel Size Application in `Blur` Transformation

### ISSUE THREAD

**Issue by LeLub** [albumentations-team/albumentations#1698]
I've discovered what seems to be a bug where the `Blur` transformation applies a smaller kernel size than specified by the `blur_limit`. This behavior occurs even when large values are set for the `blur_limit`, leading to blurring effects that do not match the expected intensity.

### Steps to Reproduce

I observed this issue while attempting to blur an image with significantly different kernel sizes. Specifically, when setting a `blur_limit` of `(13, 15)`, the blurring effect was similar to that produced by a much smaller kernel size of 3x3, suggesting that the transformation always uses `3` as kernel size.

To reproduce this behavior, follow these steps:

1. Generate a random image of size 512x512 with 3 color channels.
2. Apply the `Blur` transformation using a `blur_limit` of `(13, 15)`.
3. Apply OpenCV's `blur` function to the same image with a kernel size of 3x3.
4. Compare the two results to observe the discrepancy in blurring intensity.

Here is the Python code that demonstrates this issue:

```python
import albumentations as A
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Generate a random image
image = np.random.randint(0, 256, (512, 512, 3), dtype=np.uint8)

# Apply Albumentations Blur with a large kernel size range
albumentations_blur = A.Blur(p=1, blur_limit=(13, 15))
transformed_image = albumentations_blur(image=image)['image']

# Apply OpenCV Blur with a small kernel size
cv2_blurred_image = cv2.blur(image, (3, 3))

# Check if the images are identical
are_identical = np.array_equal(transformed_image, cv2_blurred_image)
print(f"Are the blurred images identical? {are_identical}")
```
### Expected Behavior
I expected that the image blurred with a `blur_limit` of `(13, 15)` would show a significantly more pronounced blur effect compared to one blurred with a kernel size of 3x3.

### Actual Behavior
The image blurred with the Albumentations `Blur` transformation (`blur_limit` of `(13, 15)`) showed a blur intensity similar to that of the image processed with OpenCV's 3x3 kernel.
### Environment

- **Operating System:** Ubuntu 20.04
- **Python Version:** 3.8.10
- **Albumentations Version:** 1.4.5

**Comment by LeLub** [comment]
The same behavior can be observed on the Albumentations example site: [https://demo.albumentations.ai/](https://demo.albumentations.ai/). No matter what parameters are set for the `kernel_size`, the image does not change as expected.

**Comment by LeLub** [comment]
I've tested this behavior with different versions of Albumentations. The issue is not present in versions up to and including `1.3.1`. The bug seems to have been introduced in subsequent versions.

**Comment by ternaus** [comment]
Thanks! Will address this issue ASAP!

**Comment by ternaus** [comment]
Fixed in https://github.com/albumentations-team/albumentations/pull/1700
