### ISSUE TITLE
Bounding boxes are clipped/discarded incorrectly on right/bottom edge (regression in 1.4.5/1.4.6)

### ISSUE THREAD

**Issue by JulianJvn** [albumentations-team/albumentations#1712]
## Describe the bug

Bounding boxes are incorrectly clipped. The maximum coordinates of bounding boxes are currently $`w - 1`$ and $`h - 1`$, where $`w`$ and $`h`$ are the width and height of the image in pixels. With these maximum coordinates, it is not possible anymore to denote bounding boxes that are exactly on the rightmost or bottommost pixels.

In theory, it should be as follows: The leftmost pixel covers $`x`$ coordinates from 0 to 1. The second pixel covers 1 to 2, and so on. This means the second-to-rightmost pixel covers coordinates $`w - 2`$ to $`w - 1`$, and the rightmost pixel covers $`w - 1`$ to $`w`$. Cutting off at $`w - 1`$ prohibits bounding boxes on the rightmost pixels, similarly for the bottommost pixels.

This was introduced with #1675 (1.4.5/1.4.6). Unfortunately, that PR neither has a description nor any linked issues, so it's hard to tell what and why this PR is trying to fix. The commit messages don't contain additional information, either. The PR bot even made a corresponding suggestion here, but it was dismissed without any comment: https://github.com/albumentations-team/albumentations/pull/1675#discussion_r1571296063.

In #1675, this clipping code was introduced:

https://github.com/albumentations-team/albumentations/blob/9386ad0e7333f0e9cdb611e402e71bb2d4ca0e95/albumentations/core/bbox_utils.py#L495-L498

This means values in $`[w - 1, w]`$ and $`[h - 1, h]`$ are clipped to $`w - 1`$ and $`h - 1`$, respectively. Consequently, in

https://github.com/albumentations-team/albumentations/blob/9386ad0e7333f0e9cdb611e402e71bb2d4ca0e95/albumentations/core/bbox_utils.py#L545-L552

the `clipped_box_area` is 0 for boxes whose x or y coordinates are entirely contained in $`[w - 1, w]`$ or $`[h - 1, h]`$, and the box is discarded.

### To Reproduce

1. Environment: Windows 11, Python 3.11.8
2. Create a new, clean venv
3. Install albumenations either in version 1.4.4 (prints output shown *Expected behavior* below) or the current version 1.4.6 (prints output shown *Actual behavior* below)
4. Run this sample code:

```python
import albumentations
import numpy


transform = albumentations.Compose(
    [albumentations.HorizontalFlip(p=1.0)],
    bbox_params=albumentations.BboxParams(format="coco", label_fields=[]),
)
image = numpy.zeros((4, 4, 3), dtype=numpy.uint8)
bboxes = [  # horizontal flipping means pixel (x, y) should be mapped to (3-x, y)
    [1.0, 1.0, 1.0, 1.0],  # pixel (1, 1) should be mapped to pixel (2, 1)
    [0.0, 1.0, 1.0, 1.0],  # pixel (0, 1) should be mapped to pixel (3, 1)
    [1.0, 0.0, 1.0, 1.0],  # pixel (1, 0) should be mapped to pixel (2, 0)
    [3.0, 1.0, 1.0, 1.0],  # pixel (3, 1) should be mapped to pixel (0, 1)
    [1.0, 3.0, 1.0, 1.0],  # pixel (1, 3) should be mapped to pixel (2, 3)
]
transformed = transform(image=image, bboxes=bboxes)
for bbox in bboxes:
    transformed = transform(image=image, bboxes=[bbox])
    print(f"{bbox} -> {transformed['bboxes']}")
```

### Expected behavior

Output for albumentations 1.4.4:

```plaintext
[1.0, 1.0, 1.0, 1.0] -> [(2.0, 1.0, 1.0, 1.0)]
[0.0, 1.0, 1.0, 1.0] -> [(3.0, 1.0, 1.0, 1.0)]
[1.0, 0.0, 1.0, 1.0] -> [(2.0, 0.0, 1.0, 1.0)]
[3.0, 1.0, 1.0, 1.0] -> [(0.0, 1.0, 1.0, 1.0)]
[1.0, 3.0, 1.0, 1.0] -> [(2.0, 3.0, 1.0, 1.0)]
```

### Actual behavior

Output for albumentations 1.4.5 (withdrawn) and 1.4.6:

```plaintext
[1.0, 1.0, 1.0, 1.0] -> [(2.0, 1.0, 1.0, 1.0)]
[0.0, 1.0, 1.0, 1.0] -> []
[1.0, 0.0, 1.0, 1.0] -> [(2.0, 0.0, 1.0, 1.0)]
[3.0, 1.0, 1.0, 1.0] -> [(0.0, 1.0, 1.0, 1.0)]
[1.0, 3.0, 1.0, 1.0] -> []
```

**Comment by ternaus** [comment]
Thank you, good point, will work on it ASAP.

**Comment by ternaus** [comment]
Fixed in https://github.com/albumentations-team/albumentations/pull/1713

This is good one. I always thought of bounding boxes as lying in the middle of the pixels, but you are right, they lie between them.
