### ISSUE TITLE
[Feature request] Add apply_to_batch 

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1719]
There is request how to apply to video or to batch.

Albumentations was not originally designed to be applied to batch.

But it looks like we can add such functionality without too much pain, by just looping over frames with annotations.

Related to:
https://github.com/albumentations-team/albumentations/issues/465
https://github.com/albumentations-team/albumentations/issues/683
https://github.com/albumentations-team/albumentations/issues/1561

**Comment by GdoongMathew** [comment]
I think #1420 has already implemented fraction of this functionality, tho its mainly focusing on images.
