### ISSUE TITLE
The bbox obtained with HorizontalFlip has a pixel difference

### ISSUE THREAD

**Issue by the-return-of-the-return** [albumentations-team/albumentations#1720]
Here is my calculation process: 
bboxes = [[0, 0, 100, 100]]
after HorizontalFlip
bboxes_flipped = [[540, 0, 640, 100]]
The height and width of the image are 480, 640, so the correct bbox_flipped should be [[539, 0, 639, 100]], which is a confusing issue for me.

I hope it can be answered. Thanks！

**Comment by ternaus** [comment]
Fixes in https://github.com/albumentations-team/albumentations/pull/1713

Feel free to update to version 1.4.7, it has already this issue fixed.

**Comment by the-return-of-the-return** [comment]
thanks
