### ISSUE TITLE
Augmentation outputs Incorrect Bounding Boxes Values

### ISSUE THREAD

**Issue by ahmed-sorour1** [albumentations-team/albumentations#1721]
Hello everyone,

I am doing an Object Detection task and tried to write a code to get my images and it's labels from drive and then do data augmentation.

**The Results:** 
1. Images were good and correctly flipped and rotated.
2. Labels "Bounding Boxes" weren't placed in the right place that they should be at, they were incorrect and not accurate at all.
how should I solve this problem?

This is my code:
![Screenshot 2024-05-12 025520](https://github.com/albumentations-team/albumentations/assets/102744885/bf0d9118-54d0-475e-b738-c7a119841d0b)
![Screenshot 2024-05-12 025559](https://github.com/albumentations-team/albumentations/assets/102744885/dfdc17ce-f2f8-4406-9657-60d6949f745b)
![Screenshot 2024-05-12 025647](https://github.com/albumentations-team/albumentations/assets/102744885/b2febc6f-d770-4cc6-a436-597c9570507a)

If anyone can help I will appreciate it!

**Comment by ayasyrev** [comment]
When you use  transform without Compose you mast use albumentations format for bboxes.
So if you want chose one of transform, use A.OneOf conteiner for it.
As:
```
transforms = A.Compose(
    [A.OneOf(
        [
            A.HorizontalFlip(p=1),
            A.Affine(rotate=90, p=1),
        ]
    )
    ],
    bbox_params=...
)
```

**Comment by ahmed-sorour1** [comment]
@ayasyrev Thanks for you reply!

This isn't the issue as I use `choosen_augmentations = random.sample(augmentations.transforms, 2)` to do both **flip** and **rotate** on separate images.

The problem here is in handling the bounding boxes coordination's after doing augmentation, the new coordination aren't true and not accurate at all.

If you could help me to know the cause or the solution of this problem?

**Comment by ayasyrev** [comment]
In you code you use transforms out of Compose, but all preprocess and post process for bboxes inside Compose.
 
Could you provide more information?
What input data you got and what result you expect?

**Comment by ternaus** [comment]
@ahmed-sorour1 

Feel free to reopen this issue when you could share example that could reproduce the bug
