### ISSUE TITLE
module 'albumentations' has no attribute 'IAASharpen’

### ISSUE THREAD

**Issue by Petrelli** [albumentations-team/albumentations#1722]
## Describe the bug

module 'albumentations' has no attribute 'IAASharpen‘

2. import albumentations as albu
    albu.IAASharpen(p=1)

4. OS: Ubuntu 22.04
    Python: 3.12.2
    albumentations: 1.4.6

**Comment by ternaus** [comment]
IAASharpen was deprecated. Use [Sharpen](https://albumentations.ai/docs/api_reference/full_reference/?h#albumentations.augmentations.transforms.Sharpen) instead
