### ISSUE TITLE
UserWarning: Got proce ssor for bboxes, but no transform to process it

### ISSUE THREAD

**Issue by Laughing-q** [albumentations-team/albumentations#1738]
Hi, Albumentations team!
Much appreciate for the excellent work! I'm one of the core maintainers of [Ultralytics YOLOv8](https://github.com/ultralytics/ultralytics), and we have `Albumentations` included as one of our augmentations which works very well! 
https://github.com/ultralytics/ultralytics/blob/c8b6a8bc37ce196a6b7e0c153539402db4383c16/ultralytics/data/augment.py#L878-L892

However recently we encountered a strange warning of `UserWarning: Got proce ssor for bboxes, but no transform to process it`, and after some digging I found it's introduced in the latest version(1.4.7) of `Albumenations`.

Environment:
```bash
Ubuntu 22.04.3
python 3.10
albumentations 1.4.7
```
Minimal reproducible example:
```python
import albumentations as A

print(A.__version__)
T = [A.Blur(p=0.01)]
transform = A.Compose(T, bbox_params=A.BboxParams(format="yolo", label_fields=["class_labels"]))
```
```bash
1.4.7
/home/laughing/anaconda3/lib/python3.10/site-packages/albumentations/core/composition.py:151: UserWarning: Got proce
ssor for bboxes, but no transform to process it.
  warnings.warn(f"Got processor for {proc.default_data_name}, but no transform to process it.")
```
I'm wondering if this warning affects the augmentation processes? and also is there a way to fix it?
Thanks!

**Comment by ternaus** [comment]
> warning affects the augmentation processes?

**Warning does not affect augmentation process.**

Warning happens because you pass bbox_params to the pipeline that does not have transforms affecting bounding boxes, which could be a signature of misalignment between expected behavior and what is happening in practice.

`Blur` is ImageOnly transform

=> You may just use

```python
transform = A.Compose(T)
```

On the other hand, if there is at least one transform that affects boxes you will not get warning. Example:
```python
In [3]: import albumentations as A
   ...:
   ...: print(A.__version__)
   ...: T = [A.Blur(p=0.01), A.HorizontalFlip(p=0.5)]
   ...: transform = A.Compose(T, bbox_params=A.BboxParams(format="yolo", label_fields=["class_labels"]))
1.4.7
```

P.S.
```python
T = [
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.0),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_lower=75, p=0.0),
            ]
```
It looks like based on the hardcoded probabilities in YOLO package, you can safely remove Albumentations as it barely affects the training process.

**Comment by Laughing-q** [comment]
@ternaus ok got it! Thanks!
@glenn-jocher Then the solution for us might be directly use:
```python
transform = A.Compose(T)
```
since there are no augmentations affecting boxes:
```python
T = [
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.0),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_lower=75, p=0.0),
            ]
```

**Comment by ternaus** [comment]
@Laughing-q There an alternative solution :)

Add transforms that use boxes.

Say replace Letterbox from YOLO aug, flips, etc with transforms from Albumentations.

The full list of possible transforms: https://albumentations.ai/docs/api_reference/full_reference/
