### ISSUE TITLE
Error "Key image is not in available keys" for empty transform

### ISSUE THREAD

**Issue by qubvel** [albumentations-team/albumentations#1740]
## Describe the bug

Empty transform is not working anymore. Behavior changed from 1.4.6 to 1.4.7

### To Reproduce

The following code works with 1.4.6

```python
import numpy as np
import albumentations as A

print(A.__version__)

transform = A.Compose([])
image = np.ones((100, 100, 3), dtype=np.uint8)

transformed = transform(image=image)
print(transformed['image'].shape)
```
For 1.4.7 it raises an error:
```
ValueError: Key image is not in available keys.
```

### Additional context

I need an empty transform for the unification of the pipeline.
As a workaround `A.NoOp()` can be used, it works fine, just submitting this to notify.

**Comment by ternaus** [comment]
Thanks! This is a really good one.

Never tried to use `Compose([])`, but I, guess, it is expected to work as `NoOp()` => `Compose([])`, `SomeOf`, `OneOf`, `SelectedChannels` should work on [] => Good test to add

**Comment by ayasyrev** [comment]
> but I, guess, it is expected to work as `NoOp()` => `Compose([])`, `SomeOf`, `OneOf`, `SelectedChannels` should work on [] => Good test to add
Empty Compose make sense, but container with empty list not sure - one of "zero" or some of zero. By the way, probabilities of containers with empty list will crush with when divided by zero - will add check there.
