### ISSUE TITLE
Incorrect keypoints for RandomSizedBBoxSafeCrop

### ISSUE THREAD

**Issue by qubvel** [albumentations-team/albumentations#1765]
## Describe the bug

It looks like keypoints work incorrectly for RandomSizedBBoxSafeCrop 

### To Reproduce

https://huggingface.co/spaces/qubvel-hf/albumentations-demo?transform=RandomSizedBBoxSafeCrop
Albumentations==1.4.8
<img width="1497" alt="Screenshot 2024-06-01 at 10 14 43" src="https://github.com/albumentations-team/albumentations/assets/31920396/ed1e7c43-2763-46b0-81de-662479d54e04">

**Comment by ternaus** [comment]
Thanks! Will work on this ASAP.

**Comment by Zagreus98** [comment]
I encountered the same problem, the workaround for me was to downgrade to 1.4.7 version. Any update?
