### ISSUE TITLE
`RandomSnow` always raises a `DeprecationWarning` (1.4.8 regression)

### ISSUE THREAD

**Issue by JulianJvn** [albumentations-team/albumentations#1768]
## Describe the bug

Using `RandomSnow` on 1.4.8 always raises a `DeprecationWarning`, even if not using the changed parameters `snow_point_*` (old and new). Those `DeprecationWarning`s make our Python tests fail, so we have to workaround them.

There seems to be some internal code that still uses the deprecated parameters, and that wasn't updated correctly in #1732.

### To Reproduce

1. Windows 11, Python 3.12.3, Albumentations 1.4.8
2. Run the following code:

```python
import albumentations
import warnings

warnings.simplefilter("default")
albumentations.RandomSnow()
```

### Expected behavior

No warning.

### Actual behavior

Warning:

```plaintext
.venv\Lib\site-packages\albumentations\augmentations\transforms.py:480: DeprecationWarning: `snow_point_lower` deprecated.Use `snow_point_range` as tuple (snow_point_lower, snow_point_upper) instead.
  if self.snow_point_lower is not None or self.snow_point_upper is not None:
.venv\Lib\site-packages\albumentations\augmentations\transforms.py:480: DeprecationWarning: `snow_point_upper` deprecated.Use `snow_point_range` as tuple (snow_point_lower, snow_point_upper) instead.
  if self.snow_point_lower is not None or self.snow_point_upper is not None:
```

### Additional context

It might be advisable (if not already the case) to let the Albumentations CI fail if `DeprecationWarning`s (or other warnings) are raised, to prevent this from happening again.

**Comment by ternaus** [comment]
Thanks! Will work on it ASAP.

As a side not, if it is not a secret, for what task did you find RandomSnow transform useful?

**Comment by ternaus** [comment]
Cannot reproduce:
```python
In [1]: import albumentations as A

In [2]: A.RandomSnow()
Out[2]: RandomSnow(p=0.5, snow_point_range=(0.1, 0.3), brightness_coeff=2.5)

In [3]: A.RandomSnow(snow_point_range=(0.3, 0.4))
Out[3]: RandomSnow(p=0.5, snow_point_range=(0.3, 0.4), brightness_coeff=2.5)
```

**Comment by ternaus** [comment]
Fixed.
