### ISSUE TITLE
Targets that should be ignored

### ISSUE THREAD

**Issue by daitakahashi** [albumentations-team/albumentations#1771]
## Feature description

We need a way to declare a target that will be ignored by `Compose`-wrapped transforms.

### Motivation and context

Let say, we have a following data and `Compose`-wrapped transforms.
```python
data = {'image': image, 'mask': mask, 'text_description': 'image description'}
transform = A.Compose([A.Blur()])  # note: A.Blur() is image only
```
What we want to do is applying the transformation on `image` and `mask` but `text_description` without manipulating the data.
```python
transformed = transform(**data)
transformed['text_description'] == 'image description'  # unchanged
```

Before #1706, `Compose` simply ignored all unknown keys. As a result, the above code worked "as expected" (as a byproduct of an issue solved by the pr).

However, current transforms check args by default.
```python
>>> transformed = transform(**data)
Traceback (most recent call last):
...
ValueError: Key text_description is not in available keys.
```
 I expected that we have a way to declare the `text_description` being ignored, e.g., `transform.add_targets({'text_description': 'ignore'})`. But in the current albumentations, this kind of declaration does not work and raises ValueError when it is called.
```python
>>> transform.add_targets({'text_description': 'ignore'})  # or anything other than 'image'
>>> transformed = transform(**data)
Traceback (most recent call last):
...
ValueError: Key text_description is not in available keys.
```

### Alternatives

A currently available workaround is setting `is_check_args` of the `Compose` object to be `False`. The workaround skips all argument checks added by #1706.

**Comment by ternaus** [comment]
Thanks.

Applying transforms, without wrapping with Compose, typically leads to enexpected bugs => better to always wrap with compose. 

At the same time adding `is_check_args` parameter to transforms looks quite doable, and if user knows that they are doing - why not have such functionality?

Will work on this.

**Comment by ayasyrev** [comment]
Do you use single transform or inside Compose?
Single transform don`t check keys - just ignore unused keys.

**Comment by daitakahashi** [comment]
Ayasyrev is right. I found that I have always wrapped transforms with Compose. So the situation I described in this issue is limited to transforms that are wrapped with Compose. I will update this issue to make sure it.

**Comment by daitakahashi** [comment]
By the way, this is a bit unintuitive for me.
```python
>>> tr = A.Compose([A.Blur()])
>>> tr.add_targets({'mask2': 'mask'})
>>> out = tr(image=np.zeros((2, 2, 3)), mask2=np.zeros((2, 2, 3)))
Traceback (most recent call last):
...
ValueError: Key mask2 is not in available keys.
```

**Comment by ternaus** [comment]
It does not look right to me eigher.

**Comment by daitakahashi** [comment]
I feel that checking against `_available_keys` seems to be too restrictive as `_available_keys` depends on transforms inside and key-permissive nature of those transforms.

**Comment by ayasyrev** [comment]
> I encountered it when I compiling an example case of this issue.

This is not OK. Will fix it,

**Comment by ayasyrev** [comment]
> By the way, this is a bit unintuitive for me (albumentations 1.4.8).
> 
> ```python
> >>> tr = A.Compose([A.Blur()])
> >>> tr.add_targets({'mask2': 'mask'})
> >>> out = tr(image=np.zeros((2, 2, 3)), mask2=np.zeros((2, 2, 3)))
> Traceback (most recent call last):
> ...
> ValueError: Key mask2 is not in available keys.
> >>> tr = A.Compose([A.Flip()])
> >>> tr.add_targets({'mask2': 'mask'})
> >>> out = tr(image=np.zeros((2, 2, 3)), mask2=np.zeros((2, 2, 3)))
> >>>
> ```
> 
> I encountered it when I compiling an example case of this issue.

The reason why you get error here - `Blur` is `ImageOnly` transform, so masks not processed here and add some additional key  for mask make not many sense. But as mask is special case, I'll  add this possibility.

**Comment by daitakahashi** [comment]
@ayasyrev Yes, `Blur()` is imageonly, I understand it. I'm concerning a situation that the data format is predefined but transformations are given by user (I often conducted such experiments). And I want the transforms not to crash regardless of algorithms inside.
`A.Compose([A.Flip(p=0), A.Blur()])` will work, because `Flip` knows `mask`. But this doesn't look nice.
