### ISSUE TITLE
Request for simpler examples on how to use Albumentations

### ISSUE THREAD

**Issue by thatstatsguy** [albumentations-team/albumentations#178]
## 📚 Documentation

Hi there,

I'm new to albumentations. It took me a while to figure out how to actually implement any transformations to my image data. Could I suggest that a simple example be put into the documentation before any more complex examples are used. The compose function isn't intuitively obvious to use at first, could I suggest that an example like the following be used?

`from albumentations import VerticalFlip`
`import cv2`
`img= cv2.imread("test.jpg")`
`aug = VerticalFlip(p=1)`
`img= aug.apply(img)`
`img= cv2.imwrite("test_v.jpg",img)`

Many thanks for all the hard work that has gone into this. It's a really nice package to use once you understand how it works.

**Comment by BEEugene** [comment]
That explanation helped me, thanks!

**Comment by BEEugene** [comment]
There is also a problem with apply method it is not allways contain "image" world as an argument, it sometimes "img".
