### ISSUE TITLE
Huggingface demo link in docs does not allow user uploaded images

### ISSUE THREAD

**Issue by ogencoglu** [albumentations-team/albumentations#1781]
## Describe the bug

Huggingface demo link in docs does not allow user uploaded images.

### To Reproduce

Test here:

https://huggingface.co/spaces/qubvel-hf/albumentations-demo?transform=CLAHE

**Comment by ternaus** [comment]
@ogencoglu 

Would you be interested in a paid feature that allows visual inspection of the transforms to your dataset?

**Comment by ogencoglu** [comment]
I can do that quickly in code if I don't feel lazy but probably others would be interested.

**Comment by ternaus** [comment]
For ImageOnly augmentations, you may try: https://explore.albumentations.ai/transform/CLAHE
