### ISSUE TITLE
Environmental variables to disable auto-update seems to be NO_ALBUMENTATIONS_UPDATE but is documented as ALBUMENTATIONS_NO_AUTO_UPDATE

### ISSUE THREAD

**Issue by daitakahashi** [albumentations-team/albumentations#1802]
## Documentation request

[How to disable automatic checks for new versions?](https://albumentations.ai/docs/faq/#how-to-disable-automatic-checks-for-new-versions) states to set `ALBUMENTATIONS_NO_AUTO_UPDATE` to `1` to disable automatic update, but the source code checks a different variable `NO_ALBUMENTATIONS_UPDATE`.

https://github.com/albumentations-team/albumentations/blob/a6ceade9973c47b7250e11caa6d6e7071943ca89/albumentations/__init__.py#L13

**Comment by ternaus** [comment]
Thanks. Updated FAQ on the website and release notes as well.
