### ISSUE TITLE
[it may be a bug but I am not sure] rotating and cropping adding in pixels

### ISSUE THREAD

**Issue by ninjaguardian** [albumentations-team/albumentations#1811]
## Your Question
So i have a image:
![image 9](https://github.com/albumentations-team/albumentations/assets/110734253/c57a49d0-dbc4-4017-bb00-d47351b106c8)
and after applying
`    transform = albumentations.Compose([
        albumentations.Rotate(
            limit=(-30, 30),
            p=0.8,  # float
         ),
        albumentations.RandomCropFromBorders(
            crop_left=0.1,
            crop_right=0.1,
            crop_top=0.1,
            crop_bottom=0.1,
            p=0.7,  # float
        )
    ])`
it looks like this:
![image 9 after transform](https://github.com/albumentations-team/albumentations/assets/110734253/3f7ed1f8-23a7-4ce2-85ca-2e620caedd4b)

Under the tail of the 9, there is some pixels that shouldn't be there.

This also happens:
![Image 9 after transform 2](https://github.com/albumentations-team/albumentations/assets/110734253/f7e4ae1d-9c19-4e11-a583-ccb813eb0a05)

### What have you tried?
I have tried tweaking values, changing out of Rotate and RandomCropFromBorders, searching for my issue, and more.

### Additional Context
[my code](https://colab.research.google.com/drive/1KBcboK2kygG0MT0lUvKgmDaNliAWyeId?usp=sharing)

**Comment by ninjaguardian** [comment]
If you could try helping me get the crop bounding box working it would be helpful!

**Comment by ninjaguardian** [comment]
Other notes posted in the file

**Comment by ternaus** [comment]
Could you please try:

```python
transform = albumentations.Compose([ albumentations.Rotate( limit=(-30, 30), p=0.8,  border_mode=cv2. cv2.BORDER_CONSTANT, value=0 ), 
albumentations.RandomCropFromBorders( crop_left=0.1, crop_right=0.1, crop_top=0.1, crop_bottom=0.1, p=0.7 # float ) ])
```

**Comment by ninjaguardian** [comment]
That seems to work! Thanks!
