### ISSUE TITLE
 keypoint position shifting during image rotation

### ISSUE THREAD

**Issue by medmabcf** [albumentations-team/albumentations#1819]
## Describe the bug

When applying a rotation of π to an image, the positions of the keypoints slightly shift.

### To Reproduce

```python
random.seed(7)

transform = A.Compose(
    [
        A.Affine(rotate=90, p=1.0, mode=cv2.BORDER_CONSTANT, fit_output=True),  # Added shear
    ],
    keypoint_params=A.KeypointParams(format='xy', label_fields=['class_labels'], remove_invisible=False),
    bbox_params=A.BboxParams(format='yolo')
)

transformed = transform(image=image, keypoints=keypoints, bboxes=bboxes, class_labels=class_labels, cropping_bbox=random.choice(bboxes))
```

### Expected behavior
The original image is on the left.
![expected](https://github.com/albumentations-team/albumentations/assets/98539210/6cad15b6-fa38-4e92-82df-fd70b544ed76)

### Actual behavior
The original image is on the left.
![current](https://github.com/albumentations-team/albumentations/assets/98539210/f50a7bd6-f2cb-4f7d-9c75-f1676ef71aff)

**Comment by ternaus** [comment]
Thanks, will look at this ASAP.

Do you have an example of the code that I could run to reproduce the  behavior?

I.e. =

Image + bbox coordinates and keypoint coordinates before and expected result?

**Comment by ternaus** [comment]
Should be fixed in https://github.com/albumentations-team/albumentations/pull/1823

Could you please try use `int(x), int(y)` before passing in your notebook?
