### ISSUE TITLE
Data loading does not start when num_workers > 0 in 1.4.10

### ISSUE THREAD

**Issue by adamnarai** [albumentations-team/albumentations#1825]
Data loading does not start when `num_workers > 0` in 1.4.10, the terminal just hangs and there are no running processes.
~~Everything works as expected in 1.4.8~~
It happens in 1.4.8 too but less frequently and depends on the transform used (e.g. ElasticTransform never works).

Unfortunately, I could not reproduce the issue with a simple dataloader and sample data.

**Comment by ternaus** [comment]
Thanks.

Could be very hard to debug...
There was no code changes that I can think about that could affect parallliation.

Could you please check with 
```python
import os
import cv

cv2.setNumThreads(0)
cv2.ocl.setUseOpenCL(False)

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

import numpy as np
```
?

**Comment by adamnarai** [comment]
Thanks, I was already setting `OMP_NUM_THREADS` and `MKL_NUM_THREADS` to 1, but setting all of these prevented the hanging, however loading/training becomes very slow (as if I was using `num_workers=0`).
I tried to experiment with these settings, but this bug is really annoying, sometimes I find a setup which works, next time under the same conditions it doesn't, randomly hangs mid training or starts to use only one thread and becomes very slow...

**Comment by adamnarai** [comment]
After some experimentation, I believe the problem originates from cv2 and is not specific to albumentations. 
Now (after a few reinstalls) 1.4.10 works fine with num_workers > 0 if I put the following at the very beginning of my pipeline:
```python
import cv2
cv2.setNumThreads(0)
```
See https://github.com/opencv/opencv/issues/5150 and https://github.com/pytorch/pytorch/issues/1355 for future reference of this problem.

@ternaus thanks for your help, I believe this issue can be closed.

**Comment by ternaus** [comment]
Thanks!
