### ISSUE TITLE
ISONoise not working in 1.4.10

### ISSUE THREAD

**Issue by neurohazardous** [albumentations-team/albumentations#1831]
## Describe the bug
With the latest version (1.4.10), the ISONoise transform outputs only black pixels with colours here and there, instead of actually adding the desired noise

### To Reproduce
1. OS: ArchLinux, Python version 3.8.19 and 3.11, albumentations version 1.4.10, matplotlib version 3.7.5, opencv-python-headless version: 4.10.0.84
2. Sample code that produces the bug: if you run this with an arbitrary image, you'll see that the output doesn't have the desired augmentation
``` python
import cv2
import matplotlib.pyplot as plt
import albumentations as A
def visualize(image):
    plt.figure(figsize=(6, 6))
    plt.axis('off')
    plt.imshow(image)
    plt.show()
plt.close('all')
image = cv2.imread('/home/hectordop/Documents/clemex/ClemexStudio/libraries/dl_segmentation/tests/assets/S22008395_00647.webp')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
visualize(image)
transform = A.Compose([
    A.ISONoise(p=1.0)
], p=1)
transformed = transform(image=image)
visualize(transformed['image'])
```
4. Any error messages or incorrect outputs: no error message, only the output is not the expected augmentation.
### Expected behavior
An image with ISONoise added to it
### Actual behavior
The output is mostly black pixels, no real noise added.
### Screenshots
Added the output transformed image
![S22008395_00647_isonoise](https://github.com/albumentations-team/albumentations/assets/18556576/7a6e496d-296a-482c-8aa2-ebd79c16c112)

**Comment by ternaus** [comment]
Fixed in https://github.com/albumentations-team/albumentations/pull/1829

Will release 1.4.11 later today with the fixed version.
