### ISSUE TITLE
Coarse Dropout ignores remove_invisible parameter

### ISSUE THREAD

**Issue by TonyCongqianWang** [albumentations-team/albumentations#1838]
## Describe the bug

As one can see [in the code](https://github.com/albumentations-team/albumentations/blob/de2f0ccdd324c18ab2a30b6e9ef405ded260e272/albumentations/augmentations/dropout/coarse_dropout.py#L259) coarse dropout will sometimes remove keypoints regardless of keypoint_params.

### To Reproduce

Use Coarse Dropout and combine it with Compose with keypoint_params=A.KeypointParams(format="xy", remove_invisible=False)

### Expected behavior

Expect number of outputted keypoints to always stay the same.

### Actual behavior

Sometimes some keypoints get covered and the number of keypoints is less after transformation

### Screenshots
N/A

### Additional context
N/A

**Comment by ternaus** [comment]
@TonyCongqianWang 

Added in https://github.com/albumentations-team/albumentations/pull/1953

You can check in the UI tool at https://explore.albumentations.ai/transform/CoarseDropout
