### ISSUE TITLE
Yolo bbox conversion produces negative values

### ISSUE THREAD

**Issue by jc-9** [albumentations-team/albumentations#1849]
## Describe the bug

Hello, 
This is my first time posting an issue, apologize for the poor format. 
Horizontal Flip transform produces negative yolo bbox values in some cases. 

### To Reproduce

Albumentations v1.4.11
Python 3.9.19

In box.utils.py > def convert_bbox_to_albumentations

Yolo BBOX Values
bbox = [0.408723, 0.482319, 0.581680, 0.964639] 

(x, y, width, height), tail = bbox[:4], bbox[4:]
w_half, h_half = width / 2, height / 2
x_min = x - w_half
y_min = y - h_half # This will return a negative value
x_max = x_min + width
y_max = y_min + height

### Expected behavior

x_min, y_min, x_max, y_max should all be between 0,1

### Actual behavior

y_min = -5.000000000143778e-07, causing an error for negative value

**Comment by ternaus** [comment]
Could you please provide code snippet that will reproduce the issue, including `Compose` and input data.

**Comment by ayasyrev** [comment]
You can use `check_validity=True` to check that bbox is valid.

**Comment by jc-9** [comment]
That works @ayasyrev , thanks. 

@ternaus - I cannot find the image that produces the issue, so I can't post the code. If I come across the error I will repost.

Thank you for the help gents.
