### ISSUE TITLE
Too noisy upgrade warning

### ISSUE THREAD

**Issue by MichaelMonashev** [albumentations-team/albumentations#1851]
This is what I got, when start using albumentations in many dataloader workers:
```
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
...
```

It is too noisy for me.

**Comment by ternaus** [comment]
You can disable the check: https://albumentations.ai/docs/faq/?h=fre#how-to-disable-automatic-checks-for-new-versions

From FAQ
```
To disable automatic checks for new versions, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
``` 

What stops you from updating to version 1.4.11?

**Comment by MichaelMonashev** [comment]
Я ожидаю, что по умолчанию используемые мной питоновские пакеты не ходят в интернет, если это не связано с их функционалом и я явно не вызываю ответствующие их функции. А информирование о выходе новых версий ВКЛЮЧАЕТСЯ пользователем явно, оставаясь по дефолту выключенным.

Подобное информирование о новых версиях - функционал менеджера пакетов: pip, conda или любого другого. Именно при его использовании я ожидаю получать информацию об обновлениях и произвожу их при необходимости.

**Comment by ternaus** [comment]
При достижениии целевого показателя на этой странице, 

https://github.com/sponsors/albumentations-team

функционал про заходы в интернет, конечно, можно будет отключить.

Если есть желание ускорить этот процесс, голосуя деньгами за такой функционал - будет очень кстати.

Еще раз страница, где можно начать финансово поддерживать проект:
https://github.com/sponsors/albumentations-team

**Comment by ternaus** [comment]
But fact that it is not obvious that one can disable the check with environmental variable i an issue. We should have this clearly stated in the warning message.

**Comment by MichaelMonashev** [comment]
Если модуль лезет в инет без ведома юзера, то будущее модуля туманно, ибо всякие security-проверяльщики, антивирусы и пр. будут громко кричать о том, что модуль небезопасен, может нести угрозу, быть частью ботнета и т.д.

Вопрос только в том, когда всё это произойдёт.

**Comment by ternaus** [comment]
Такой риск и правда есть. Но что с этим делать не до конца понятно.
Вообще многие пакеты лазают в инет, иначе вообще непонятно как собирать статистику по использованию. Но там и правда много подводных камней.

**Comment by MichaelMonashev** [comment]
Статистику собирать только после явного разрешения на то пользователя. Так делают в обычном софте не просто так, а именно потому, что иначе скрытый сбор любых данных наказывается. Просто albumentations пока везёт. Но найдётся какой-то ботнет в питоновских пакетах и все стрёмные пакеты быстро объявят небезопасными и зачистят. Или из баз пакетных менеджеров и с гитхаба и с хостинга и т.д. Нужен вам весь этот головняк с пожизненным клеймом на нужном пакете?

По-хорошему, нужно явно писать, что собираются такие-то и такие-то данные, используются они для того-то и того-то, хранятся так-то и так-то, никому более не передаются или передаются и т.д. Вы хотите отдавать данные? Да/нет.

**Comment by ternaus** [comment]
Это будет любопытно. Но поглдим.

Сбор статистики пока вставлять не будем, сейчас это ничего не дает. Обычно ее вставляют по умолчанию и предлагают отписаться если есть возражения. Наоборот просто не работает. Никто не впишется.

А уведомление о новой версии оставим, потому-что хоть и по мелочи, но позволяет перетаскивать юзеров на более новую версию. Это, кстати, распространенная практикаю

**Comment by MichaelMonashev** [comment]
Я проходил подобные истории пару раз. Ничего прикольно нет. Вылезти из бана очень сложно.

**Comment by ternaus** [comment]
А что конкретно происходило в твоих случаях? Тут достаточно широкий спектр того что можно делать.

То, как в Alumentations сделано сейчас  - всем понятный код, который делает запрос на публичный API, при этом ни на какие сторонник ресурсы ничего не сохраняется - мне сложно представить, чтобы за это что-то было.

Сбор детальной статистики под капотом на каждый чих, и отсылка куда-то в стороннюю базу данных, причем без уведомления пользователя - это другой конец спектра.

И много всего посередине.

Например, DVC статистику собирает и за все эти годы проблем у них не было.

Но они ее с первого дня собирали и открытым текстом везде пишут и можно отписаться, все-равно, не всегда очевидно, но проблем пока не было.

**Comment by MichaelMonashev** [comment]
Попадал в бан гугла несколько раз. Проект приносил деньги. На время бана доход падал до нуля и потом длилась от месяца до полугода муторная переписка о том, что удалил плохой контент.

Почтовый сервер попадал в бан Спамхаусу. Было проще сменить домен и ip, чем убрать себя из его чёрного списка. К тому же куча подобных контор тут же скопировало к себе меня. Их неизвестное количество и кто ими пользуется для фильтрации своей почты - неизвестно. И ещё провайдер мозг выносил, что его ip теперь в чёрном списке. Но это был не хостинг, я им много платил и просто оставил ip за собой и платил за него некоторое время.

РКН банил. Трафик сайта сразу становился близким к нулю. Но вопрос быстро решился и буквально через неделю всё восстановилось. Правда трафик из-за инцидента упал процентов на 20% наверное. Не всем юзерам понравилась недоступность их бложиков. Хостер тоже звонил и спрашивал, почему забанили из ip.

Знакомый софтом своим шароварным занимался. С ним такая история, что чем чаще релизы, тем больше вероятность, что какой-то антивирус (один из сотни) найдёт там какую-то подозрительную сигнатуру, добавит в какие-то чёрные списки, на софтовых сайтах напишут, что софтина подозрительная, скачивать её перестанут и потом ходи доказывай, что это ложное срабатывание, что уже вышел новый релиз без этой проблемы, что нужно перезапустить антивирус и всё исправится... Отчасти помогало подписывание софта сертификатами, купленными за деньги.

**Comment by MichaelMonashev** [comment]
Вообще, по опыту могу сказать, что половина проблем произрастает от написание кляуз конкурентами или обиженными юзерами.
