### ISSUE TITLE
How is the pad_cval defined of CropAndPad?

### ISSUE THREAD

**Issue by Pxldi** [albumentations-team/albumentations#1853]
When defining the CropAndPad transformation like this, the color of the padding is (128,0,0), when it should be the grayscale value 128:
``A.CropAndPad(percent=(0, 0.1, 0, 0), pad_cval=(128,128,128)),``

With all other transformations like Rotate and Affine this works and displays the correct grayscale color.
I have tried supplying the value pad_cval=128, but this just displays the red color again.
I have looked in the source code but couldn't find the solution to this.

**Comment by ternaus** [comment]
Thank you. Fixed in https://github.com/albumentations-team/albumentations/pull/1856

This was a good one, affected a few transforms.

main problem is that OpenCV extends padding vector to `(value, 0, 0)`, instead of `(value, value, value)`
