### ISSUE TITLE
Image and mask augmentations cause error when converting NumPy to PyTorch - [ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported.]

### ISSUE THREAD

**Issue by KeithGeorgeCiantar** [albumentations-team/albumentations#1861]
## Describe the bug

In versions 1.4.11 and 1.4.12, operations such as `RandomRotate90`, `ChannelShuffle`, and `ToFloat`, sometimes create negative strides. These strides are not supported in PyTorch and result in an error when using `ToTensorV2`.

When using albumentations version 1.4.10, the image and mask transformations are applied, and the numpy array is converted to a PyTorch tensor using `ToTensorV2` without any issue.

### To Reproduce

Environments tried:
   - macOS 14.5, Python 3.10.14
   - Google Colab, Python 3.10.12

Albumentations versions: 1.4.11, 1.4.12

#### Sample code

```python
import numpy as np
import torch
import albumentations as A
from albumentations.pytorch import ToTensorV2

# Generate sample images
num_images = 3
images_np = [np.random.randint(0, 255, size=(128, 128, 3)).astype(np.float32) for i in range(num_images)]
masks_np = [np.random.randint(0, 255, size=(128, 128, 1)).astype(np.float32) for i in range(num_images)]

# Define individual transformations
transform_horizontal_flip = A.HorizontalFlip(p=1.0)
transform_vertical_flip = A.VerticalFlip(p=1.0)
transform_random_rotate = A.RandomRotate90(p=1.0)
transform_channel_shuffle = A.ChannelShuffle(p=1.0)
transform_to_float = A.ToFloat(max_value=255)
transform_to_tensor = ToTensorV2(transpose_mask=True)

# Apply and check strides after each transformation
def check_transform(image, mask, transform, description):
    transformed = transform(image=image, mask=mask)
    transformed_image = transformed['image']
    transformed_mask = transformed['mask']

    # Debugging: Print strides
    if not torch.is_tensor(transformed_image):
        print(f"{description} image strides: {transformed_image.strides}")
        print(f"{description} mask strides: {transformed_mask.strides}")

    return transformed_image, transformed_mask

for i in range(num_images):
    image = images_np[i]
    mask = masks_np[i]

    print(f"\nProcessing image {i}")
    print(f"Original image strides: {image.strides}")
    print(f"Original mask strides: {mask.strides}")

    image, mask = check_transform(image, mask, transform_horizontal_flip, "After HorizontalFlip")
    image, mask = check_transform(image, mask, transform_vertical_flip, "After VerticalFlip")
    image, mask = check_transform(image, mask, transform_random_rotate, "After RandomRotate90")
    image, mask = check_transform(image, mask, transform_channel_shuffle, "After ChannelShuffle")
    image, mask = check_transform(image, mask, transform_to_float, "After ToFloat")
    image, mask = check_transform(image, mask, transform_to_tensor, "After ToTensorV2")
```

### Expected behaviour

The `ToTensorV2` function should run after all the augmentations have been applied. There should be no errors.

### Actual behaviour

In some cases, the operations create negative strides in the transformed image. These negative strides are not supported in PyTorch, resulting in the error: `ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array with array.copy().)`. 

### Potential fix

From what I understand, this can be resolved in the `apply` method of the `ToTensorV2` class, as shown in #609. Adding a `.copy()`, as suggested in the error, should help resolve the problem.

**Comment by ternaus** [comment]
It could be fixed by wrapping each transform with `A.Compose` as it is the default way to deal with transforms, but I guess, for a better user experience, I will just make sure that every transform returns contiguous array.

Thanks!

**Comment by KeithGeorgeCiantar** [comment]
Thanks for the reply!

In my full code I am using the `A.Compose` and that's how I found the issue.

I put together a tutorial (https://github.com/KeithGeorgeCiantar/Segmentation-Tutorial/blob/main/segmentation_cnn.ipynb), and when I ran it on Colab two weeks ago it worked fine, but today it gave me the error I mentioned before. I noticed that the version I was running locally was 1.4.10 and the one on Colab was updated.

The code shown in the previous comment is from some testing I did to see the strides. It seems that when converting to a PyTorch tensor it gives an error when the strides are negative.

I will try again by wrapping the transforms in an `A.Compose` to see if anything changes.

**Comment by ternaus** [comment]
Thanks. 

Still debugging.

**Comment by ternaus** [comment]
@KeithGeorgeCiantar Thanks! Fixed.

**Comment by KeithGeorgeCiantar** [comment]
Great! Thank you for taking care of it so quickly!
