### ISSUE TITLE
Root logger conflict with my custom logging structure

### ISSUE THREAD

**Issue by Raverss** [albumentations-team/albumentations#1867]
The root logger setup in the version check interferes with the custom logging structure. For example, let's assume that I'm making my own Python package where a top-level logger is setup in the __init__.py of the package, and loggers in the sub-packages inherit from this top-level logger. The top-level logger adds a stream handler. If Albumentations is imported somewhere in the package it will override/setup the root logger with a different stream handler and all the loggers will log twice.

Please do not use the `BasicConfig()` function and instead manually add the handler to your logger.

[This is the line in question](https://github.com/albumentations-team/albumentations/blob/39895a84f45c58c542f42c847449fa2f9761771b/albumentations/check_version.py#L9)

If anybody has the same issue, the workaround is to always check and remove handlers from the root logger (you are most likely not using the root logger anyway) when creating a new logger:
```
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)
```

**Comment by ternaus** [comment]
Thanks, good point. Working on it.

**Comment by ternaus** [comment]
@Raverss thanks for the report. Addressed.
