### ISSUE TITLE
affine with fit_output set to true does not scale bounding boxes correctly

### ISSUE THREAD

**Issue by dominicdill** [albumentations-team/albumentations#1876]
## Describe the bug

Bounding boxes are not augmented as expected when fit_output=True.

### To Reproduce

perform affine augmentation with fit_output=True and observe the decoupling of bounding boxes and objects

### Expected behavior

Bounding boxes should be augmented such that the final image is correctly described by them.

### Actual behavior

Bounding boxes are not to be trusted

### Screenshots

![image](https://github.com/user-attachments/assets/8b1277b7-f50e-47a9-823b-3681aef57e5a)

**Comment by ternaus** [comment]
Thanks, will look into it.
