### ISSUE TITLE
[Feature Request] Make hardcoded parameter `shadow_intensity = 0.5` a paramater  

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1880]
The proposal is to add `shadow_intenisity_range: tuple[int, int]` parameter to the `RandomShadow` class, sample from it and use in `add_shadow` function.

**Comment by ternaus** [comment]
@JonasKlotz

**Comment by JonasKlotz** [comment]
I've implemented the `shadow_intensity_range: tuple[int, int]` not as `int` but as `float`. Also to keep it backwards compatible and simple it's possible to pass a single float value, see:
```
        shadow_intensity_range: float | tuple[float, float] = Field(
            default=0.5,
            description="Value or sample range for the shadow intensity",
        )
```.

**Comment by ternaus** [comment]
@JonasKlotz 

Thanks for the pull request.

Merged it as it was, but removed and option to have constant value. Logic for converting from constant to tuple before sampling is different in various transforms, which is confusing, or even misleading => For the past few months we have a rule:

- If it is constant => constant
- if one needs an option to sample => tuple.

`shadow_intensity_range = (0.5, 0.5)` will effectively work as a constant 0.5 value. 

-----
Also it is preferred to add validaors of the input:

`shadow_intensity_range: Annotated[
            tuple[float, float],
            AfterValidator(check_01),
            AfterValidator(nondecreasing),
        ]
`

This ensures that provided values have correct type, bounded between [0, 1] and second is at least as big as left.

**Comment by JonasKlotz** [comment]
Thank you for the feedback! I did not know that and will consider it in my next PR's.
