### ISSUE TITLE
[Bug] In GridElasticDeform transform last row an column are unaffected

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1888]
![image](https://github.com/user-attachments/assets/1115adb3-63e9-405f-a916-d0bc8613983d)

Looks like last row and columns are not deformed.

**Comment by 4pygmalion** [comment]
```python3
# Generate displacements for internal grid points only
internal_points_height, internal_points_width = grid_height - 2, grid_width - 2
```

it may be induced by ` grid_height - 2, grid_width - 2`.
i think `internal_points_height, internal_points_width = grid_height - 1, grid_width - 1` is correct


for example, given 4 x 4 grid, we should make displacement matrix which have a 3x3 matrix.
```
256 x 256 image with 4 x 4 grid

+------------+------------+------------+------------+
|            |            |            |            |
|            |            |            |            |
|            |            |            |            |
|            |            |            |            |
+------------+------------+------------+------------+
|            |            |            |            |
|            |            |            |            |
|            |            |            |            |
|            |            |            |            |
+------------+------------+------------+------------+
|            |            |            |            |
|            |            |            |            |
|            |            |            |            |
|            |            |            |            |
+------------+------------+------------+------------+
|            |            |            |            |
|            |            |            |            |
|            |            |            |            |
|            |            |            |            |
+------------+------------+------------+------------+


```

**Comment by 4pygmalion** [comment]
![image](https://github.com/user-attachments/assets/03113b44-eb3e-402e-8bca-835bab963160)


i think, we have ignore the last cells:
1) the last points in the displacement matrix
 - AS IS: `internal_points_height, internal_points_width = grid_height - 2, grid_width -2`
 - TO BE: ``internal_points_height, internal_points_width = grid_height - 1, grid_width -1 `

2 ) the last cells in the polygons matrix:

- AS IS 
```python3
# Apply displacements to internal polygon vertices
    for i in range(1, grid_height -1):
        for j in range(1, grid_width-1):
            dx, dy = displacements[i - 1, j - 1]

            # Bottom-right of cell (i-1, j-1)
            polygons[(i - 1) * grid_width + (j - 1), 4:6] += [dx, dy]

            # Bottom-left of cell (i-1, j)
            polygons[(i - 1) * grid_width + j, 6:8] += [dx, dy]

            # Top-right of cell (i, j-1)
            polygons[i * grid_width + (j - 1), 2:4] += [dx, dy]

            # Top-left of cell (i, j)
            polygons[i * grid_width + j, 0:2] += [dx, dy]

    return polygons
```
- TO-BE
```python3
# Apply displacements to internal polygon vertices
    for i in range(1, grid_height):
        for j in range(1, grid_width):
            dx, dy = displacements[i - 1, j - 1]

            # Bottom-right of cell (i-1, j-1)
            polygons[(i - 1) * grid_width + (j - 1), 4:6] += [dx, dy]

            # Bottom-left of cell (i-1, j)
            polygons[(i - 1) * grid_width + j, 6:8] += [dx, dy]

            # Top-right of cell (i, j-1)
            polygons[i * grid_width + (j - 1), 2:4] += [dx, dy]

            # Top-left of cell (i, j)
            polygons[i * grid_width + j, 0:2] += [dx, dy]

    return polygons
```

**Comment by ternaus** [comment]
@4pygmalion Thanks for the fix!

Yep, it was me who introduced the bug, not you )
----
Overall, as you can see, my implementation was heavily based on yours, but there was a number of small changes, like 

- Moving helper functions to another file
- Adding tests
- Adding InitParam class
- changing variable names and even merging some of them 

etc.
----
As you can see, we have a lot of Pull Request that got stack in the phase where person creates PR, we give feedback, person fixes something, during this time code base moves forward and one needs to rebase and PR gets abandonded.
----
=>

Right now, it everything works and passes pre-commits checks and tests, I just merge and refactor add on top of it. It is just faster and prevents pull requests from being abandonded.

=> if you have any other pull requests in mind, or improvements, just create pull request and together we will make everything work.

**Comment by 4pygmalion** [comment]
Thank you for your advice. I plan to implement the vectorization method instead of a loop for displacement. 
Look forward to it!
