### ISSUE TITLE
Suitable augmentation in Albumentations

### ISSUE THREAD

**Issue by jawi289o** [albumentations-team/albumentations#1893]
## Your Question

I am reproducing a code (which is in tensorflow/keras) in which the following augmentations are applied.

`ImageDataGenerator(
    zoom_range=0.1,
    fill_mode='reflect',
    width_shift_range=0.4,
    height_shift_range=0.4)`

Are these augmentations available in Albumentations? I couldn't find them. Any help would be appreciated.

**Comment by ternaus** [comment]
Yes, Look like you need Affine Transform: https://explore.albumentations.ai/transform/Affine
