### ISSUE TITLE
[Tech debt] Remove dependency on scikit-image

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#1895]
Scikit-image is quite heavy and all it's functionality that is used in Albumentations could be easily reimplemented.

**Comment by momincks** [comment]
been testing an improvement to this
https://github.com/albumentations-team/albumentations/blob/36f89ea24a8ac9afc4990c017cad1b5d3fce9e9c/albumentations/augmentations/geometric/functional.py#L890
