### ISSUE TITLE
ValueError when using ToTensorV2 on flipped masks

### ISSUE THREAD

**Issue by robertkbk** [albumentations-team/albumentations#1897]
## Describe the bug

An error is thrown, when trying to convert a flipped (either horizontally or vertically) masks to a torch tensor using `ToTensorV2`.

### To Reproduce

1. Environment:
  - OS: Windows 11 Build 22631
  - Python: 3.10.11
  - albumentations: 1.4.14
  - torch: 2.3.0+cu121

2. Minimal code example:
```py
import numpy as np
from albumentations import Compose, HorizontalFlip
from albumentations.pytorch import ToTensorV2

transforms = Compose(
    [
        HorizontalFlip(p=1),
        ToTensorV2()
    ]
)

transforms(
    image=np.random.randint(0, 255, (224, 224, 3), dtype=np.uint8),
    masks=np.random.randint(0, 1, (2, 224, 224), dtype=np.uint8)
)
```

3. Error message:

```
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array with array.copy().)
```

### Expected behavior

The masks should be converted to a torch tensor properly.

### Actual behavior

An error is thrown when trying to convert masks to a tensor.

### Additional context

The code works fine with `albumentations==1.4.12`, my guess is that the bug has been introduced with changes to _contiguous_ in 1.4.13.
Error message already shows a possible solution: torch does not support negative strides, that are used in flip transformations (like `mask[:, ::-1, :]`).

**Comment by ternaus** [comment]
Thanks, will work on it ASAP

**Comment by ternaus** [comment]
The issue is the `masks` target expects list of `np.arrays`.

If you want multichannel mask, you may just use `mask` target

```python
 transforms = A.Compose(
    [
        A.HorizontalFlip(p=1),
        ToTensorV2()
    ]
    )

    transforms(
        image=np.random.randint(0, 255, (224, 224, 3), dtype=np.uint8),
        mask=np.random.randint(0, 1, (224, 224, 2), dtype=np.uint8)
    )
```

Made a check + more descriptive error message in https://github.com/albumentations-team/albumentations/pull/1900
