### ISSUE TITLE
alb.ShiftScaleRotate raises ValueError

### ISSUE THREAD

**Issue by yellowdolphin** [albumentations-team/albumentations#1908]
## Suggested Improvement

Version 1.4.14 breaks code when passing `value=None` to `ShiftScaleRotate` because this was the default value at some point. Now documentation specifies `value=0` as default, which works. Meanwhile, other classes, like OpticalDistortion, GridDistortion still use a default of None for the same variable. I suggest to deprecate default values before changing them and keep them consistent over classes.

## Potential Benefits

Don't break user code unnecessarily.

**Comment by ternaus** [comment]
@yellowdolphin 

`ShiftScaleRotate` is deprecated, it is recommended to use `Affine`.


Overall, it would be great to avoid such issues and have a consistent parameter names and default values across classes, but such attention to details may require more resources. 
 
Would you consider becoming a sponsor for the project? 

https://github.com/sponsors/albumentations-team 

Financial contribution that you will make every month would help a lot.
