### ISSUE TITLE
CoarseDropout removes the keypoints even the `remove_invisible=False`

### ISSUE THREAD

**Issue by ZombaSY** [albumentations-team/albumentations#1914]
## Describe the bug

CoarseDropout removes the keypoints even the `remove_invisible=False`
If any holes produced from CoarseDropout includes the keypoints coordinate, the keypoints are removed from indices.

### To Reproduce

Set the
`
albumentations.Compose(
[albumentations.CoarseDropout(...),
...],
keypoint_params=albumentations.KeypointParams(format='xy', remove_invisible=False, angle_in_degrees=True)
`
, and performs transforms.

### Environment
- albumentations ==1.4.14

### Expected behavior

The keypoints shoud be remained even the holes include themselves.

### Screenshots

![tmp1](https://github.com/user-attachments/assets/a22d8c58-212a-4fa6-908b-ea346352496c)
![tmp2](https://github.com/user-attachments/assets/34575bd4-bd71-4852-b51d-d70aa7661804)

### Additional context

Same issue on  #1838 #1469

To remain the keypoints regardless of `remove_invisible=False`, modify the script on `corase_dropout.py` -> `apply_to_keypoints()` as below:
`return [keypoint for keypoint in keypoints if not any(keypoint_in_hole(keypoint, hole) for hole in holes)]`
to
`return [keypoint for keypoint in keypoints]`

**Comment by ternaus** [comment]
@ZombaSY Yep, it is an old issue. 

Will work on it.

**Comment by ternaus** [comment]
@ZombaSY 

Added in https://github.com/albumentations-team/albumentations/pull/1953

You can check in the UI tool at https://explore.albumentations.ai/transform/CoarseDropout
