### ISSUE TITLE
ValueError: empty range for randrange() (0, 0, 0)

### ISSUE THREAD

**Issue by GraceKafuu** [albumentations-team/albumentations#1924]
## Describe the bug

albumentations/augmentations/transforms.py line 798, in get_params_dependent_on_data

y = random.randint(0, height - drop_length)

when  height - drop_length == -1   -->   ValueError: empty range for randrange() (0, 0, 0)

height - drop_length should >= 0

**Comment by ternaus** [comment]
Thanks, will look tomorrow.
