### ISSUE TITLE
TextImage.preprocess_metadata issue in bboxes check

### ISSUE THREAD

**Issue by snowvyash** [albumentations-team/albumentations#1926]
- this is throwing the `TypeError: list indices must be integers or slices, not tuple`.

`bbox` should be `np.array([bbox]`

https://github.com/albumentations-team/albumentations/blob/c0af8032c4efa8f3c15c4493d6e13c110d47aba7/albumentations/augmentations/text/transforms.py#L163

**Comment by ternaus** [comment]
Thanks will check out tomorrow
