### ISSUE TITLE
Bounding boxes with one side smaller than 1 pixel are removed (1.4.15 regression)

### ISSUE THREAD

**Issue by JulianJvn** [albumentations-team/albumentations#1928]
## Describe the bug

Albumentations 1.4.15 removes bounding boxes that have an area smaller than 1 square pixel after augmentation, or a width or height smaller than 1 pixel. This is done in `bbox_utils.filter_bboxes()` in lines 466, 469, and 470:

https://github.com/albumentations-team/albumentations/blob/c0af8032c4efa8f3c15c4493d6e13c110d47aba7/albumentations/core/bbox_utils.py#L465-L471

This was introduced in PR #1906, specifically in 0071b6b448.

I can't find documentation on this in the documentation of `filter_bboxes()` or in the release notes, so this is a bug. (Even if it was intended, it would be a documentation bug.) It's not in 1.4.14, so this is a regression.

I would argue such bounding boxes should not be removed. There are specifically the `min_area`, `min_width`, and `min_height` parameters with which the user can control what the minimum area/width/height of the bounding boxes should be. Objects with area < 1, width < 1, or height < 1 can certainly be of interest, depending on the use case. Objects are not always perfectly pixel-aligned, so it's definitely possible to have objects in sub-pixel range (which is also why pixels are floats, not ints). In object detection, far away or small objects can end up with area < 1, width < 1, or height < 1.

### To Reproduce

1. Environment: Windows 11, Python 3.12.5
2. Create a new, clean venv
3. Install Albumentations either in version 1.4.14 (prints _Expected behavior_ output shown below) or the current version 1.4.15 (prints _Actual behavior_ output shown below)
4. Run this sample code:

```python
import albumentations
import numpy as np

transform = albumentations.Compose(
    [albumentations.NoOp()],
    bbox_params=albumentations.BboxParams(format="coco", label_fields=[]),
)
transformed = transform(image=np.zeros((4, 4, 3), dtype=np.uint8), bboxes=[[1.0, 1.0, 0.75, 0.75]])
print(transformed["bboxes"])
````

### Expected behavior

Output for 1.4.14:

```plaintext
[(1.0, 1.0, 0.75, 0.75)]
```

### Actual behavior

Output for 1.4.15:

```plaintext
[]
```

**Comment by ternaus** [comment]
Thanks!

Will look ASAP
