### ISSUE TITLE
Lack of ability to keep output size fit when using IAAAffine

### ISSUE THREAD

**Issue by lamhoangtung** [albumentations-team/albumentations#194]
Hi, when using IAAAffine, there is no way to keep the image after affine transformation to completely contained in the output. A lot of people use this frequently so it is very annoying

Affine Transform in `imgaug` supported this use case, we just need to pass `fit_output=True` when init it, but we can't do that via albumentations.

So I made a small Pull Request to resolve this problem. Can you guys consider to merge it ?

Thanks ❤️

**Comment by ternaus** [comment]
Hello,

Could you please share what is the use case, when you need both the original and transformed image?

**Comment by lamhoangtung** [comment]
Hi @ternaus, 

The problem is after affine transformation parts of the image may be outside of the image plane or the image might make up only a small part of the image plane. Keeping output image fit can be useful e.g. for rotations by 45 degrees to avoid that the image corners are outside of the image plane.

To do that just need to use `fit_output=True` argument when we call `imgaug`, my PR addressed that ;)

**Comment by albu** [comment]
it's `False` by default, let's keep default but passing this argument is good option.

**Comment by lamhoangtung** [comment]
Yeah, my PR make it passable 😂

Vào Th 3, 19 thg 2, 2019 lúc 16:46 Alexander Buslaev <
notifications@github.com> đã viết:

**Comment by ternaus** [comment]
We removed imgaug dependencies. but it has  `fit_ouput` parameter as well
