### ISSUE TITLE
Version 1.4.15 removes bounding boxes inconsistently and without permission

### ISSUE THREAD

**Issue by gui-miotto** [albumentations-team/albumentations#1941]
## Describe the bug

Version 1.4.15 removes bounding boxes with small area when `min_area=0.0` or even `-1.0`.

Moreover, it removes only the bounding box and not it's corresponding label. Which of course brings the data to an inconsistent state.

This behavior is not observed in version 1.4.14.

### To Reproduce

Just run the minimal working example below

```python
import numpy as np
import albumentations as A

in_data = dict(
    image=np.ones((500, 500, 3)),
    bboxes=np.array((0.1, 0.2, 1E-3, 1E-3)).reshape(1, 4),
    classes=np.array([1]),
)

bbox_conf = A.core.bbox_utils.BboxParams(format="yolo", label_fields=["classes"], min_area=-1.)
transf = A.Compose([A.HorizontalFlip(p=1.)], bbox_params=bbox_conf, is_check_shapes=False)

out_data = transf(**in_data)

print(in_data["classes"], in_data["bboxes"])
print(out_data["classes"], out_data["bboxes"])
```

### Expected behavior

Expected output is what is given by version 1.4.14:

```sh
[1] [[0.1   0.2   0.001 0.001]]
[1] [(0.8999999999999999, 0.2, 0.0010000000000000009, 0.0010000000000000009)]
```

### Actual behavior

Inconsistent behavior is given by version 1.4.15. Notice that the the bounding box coordinates is deleted, but the class is kept.

```sh
[1] [[0.1   0.2   0.001 0.001]]
[1] []
```

**Comment by ternaus** [comment]
Thanks, will take a look ASAP.

**Comment by ternaus** [comment]
Good catch. FIxed.
