### ISSUE TITLE
ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils'

### ISSUE THREAD

**Issue by fangchenglin** [albumentations-team/albumentations#1947]
Describe the bug
I encountered an issue while using the latest version of albumentations and albucore. The error occurs when trying to import preserve_channel_dim from albucore.utils during the execution of a script.
To Reproduce
1.Install the latest versions of albumentations (1.4.15) and albucore (0.0.17).
2.Try importing albumentations in a Python script
3. Run the script.
4. See error ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils'

Environment:

Python version: 3.10
albumentations version: 1.4.15
albucore version: 0.0.17
OS: Ubuntu 22

Solution: I was able to resolve the issue by modifying the albumentations package. I replaced all instances of:
from albucore.utils import *
with:
from albucore import *

**Comment by hmaarrfk** [comment]
I think you likely want to backport https://github.com/albumentations-team/albumentations/commit/f8172c17a955d6807ad8cf36e0239b99c8d84417

**Comment by hmaarrfk** [comment]
See 

* https://github.com/albumentations-team/albumentations/issues/1945
* https://github.com/albumentations-team/albumentations/issues/1946

**Comment by ternaus** [comment]
Released version 1.4.16 with a strict binding with a particular albucore version.

`pip install -U albumentions` should work now
