### ISSUE TITLE
RandomGridShuffle doesn't apply to labels and UserWarning: Got processor for bboxes, but no transform to process it.

### ISSUE THREAD

**Issue by veevee2** [albumentations-team/albumentations#1948]
## Your Question

Hi, if i user the RandomGridShuffle transformation i get a warning, and only images rea augmented, **not the labels**.

### What have you tried?

The problem : 

> shuffleTransformation = A.RandomGridShuffle(grid=(5, 5), p=1)
> transform = A.Compose([shuffleTransformation], bbox_params=A.BboxParams(format='yolo'))
> transformed = transform(image=image, bboxes=gt_bboxes)
> aug_img, aug_label = transformed['image'], transformed['bboxes']
> print(f"original labels :{gt_bboxes}")
> print(f"aug_label :{aug_label}")

then i get

> [composition.py:161](file:///C:/Users/olivier/AppData/Roaming/Python/Python312/site-packages/albumentations/core/composition.py:161): UserWarning: Got processor for bboxes, but no transform to process it.

> on 0: original labels :[[0.344313, 0.344577, 0.013175, 0.031597, '7']
> on 0: augmented labels :[(0.344313, 0.344577, 0.013174999999999992, 0.031596999999999986, '7')]
You can notice labels didn't change ... except a small decimal lowering...

### Briefly explain what you have tried so far to find an answer to your question. This could include documentation you have read or experiments you have conducted.

If i replace the A.RandomGridShuffle transformation by A.Crop : everything is ok, no warning and labels are properly transformed.

### Additional Context

none

### Relevant documentation or external resources

i've read other issues regarding this warning, but no solution regarding the labels not augmented.

**Comment by veevee2** [comment]
ok sorry for the question, as documentation here https://albumentations.ai/docs/api_reference/full_reference/#spatial-level-transforms tells that [RandomGridShuffle](https://albumentations.ai/docs/api_reference/full_reference/#albumentations.augmentations.transforms.RandomGridShuffle) doesn't support BBoxes

**Comment by ternaus** [comment]
It is unclear how to apply RandomGridShuffle to bounding boxes. If you have good ideas - would be happy to add.

**Comment by alevangel** [comment]
@ternaus where is the ambiguity? I did a simple custom code that does the job. 
The only limitation I see is in the apply_to_bboxes() function, that only applyes one bbox at time and it want only a bbox in output.

**Comment by ternaus** [comment]
@alevangel How would  you propose to deal with the bounding box look after shuffling if grid splits it in parts?

**Comment by alevangel** [comment]
@ternaus also the bbox should be splitted. For example, if we have 1 bbox in the exact center, a grid=(2,2), then we can have in output 4 bboxes. Do you see any complications in this approach?

Also, we should set as parameter the minum area to be cosidered as bbox.

**Comment by ternaus** [comment]
It is a bit tricky to implement, but possible. I'll think about it.

**Comment by ternaus** [comment]
@veevee2 @alevangel Added.

Can check how it looks at: https://explore.albumentations.ai/transform/RandomGridShuffle

**Comment by alevangel** [comment]
> @veevee2 @alevangel Added.
> 
> Can check how it looks at: https://explore.albumentations.ai/transform/RandomGridShuffle

Yes, that’s the idea.
However, I believe there’s a bug in the handling of bboxes (screenshot attached).
![image](https://github.com/user-attachments/assets/bc8bcc9d-e326-4e7d-b174-c40d95ce5386)

In this case, I think the desired output should be 5 different annotation boxes, not 3.
I believe this is due to the fact that the mask was used as the logic to identify the boxes.

Which commit can I find the code on? I can try pulling it and propose my own fix.

**Comment by veevee2** [comment]
> @veevee2 @alevangel Added.
> 
> Can check how it looks at: https://explore.albumentations.ai/transform/RandomGridShuffle

Thanks ! I will quickly try on my training.

**Comment by ternaus** [comment]
@alevangel 

Just create a pull request to the main branch.

It does not look like a bug.

**Comment by veevee2** [comment]
hi @ternaus 
I just tested this improvement (sorry for the delay after requesting it) : 
It work nice for my need ! thanks a lot for the work !

I had to checkout locally albumentations : in which release will it be included ?

Olivier,

**Comment by ternaus** [comment]
@veevee2 Planing making next release on Tuesday (in two days)

**Comment by ternaus** [comment]
@veevee2 I have added a number of new transforms, working on testing and picking better default arguments.

Release is postponed till I address these things. Not sure about next week - Thanksgiving week in the US, which is holidy, but for sure will release no later than the first week of December.
