### ISSUE TITLE
PlanckianJitter gaussian sampling not working

### ISSUE THREAD

**Issue by RieGo** [albumentations-team/albumentations#1968]
## Describe the bug

whenever i switch the PlanckianJitter to gaussian sampling method i get this error.
uniform is working just fine.

<details><summary>Details</summary>
KeyError                                  Traceback (most recent call last)
Cell In[1], line 862
    860 total_count_train = 0
    861 pbar = tqdm(enumerate(train_loader), total=len(train_loader))
--> 862 for i, data in pbar:
    863     check_pause(model, device)
    864     # print(data[2])

File <python_path>\site-packages\tqdm\notebook.py:250, in tqdm_notebook.__iter__(self)
    248 try:
    249     it = super().__iter__()
--> 250     for obj in it:
    251         # return super(tqdm...) will not catch exception
    252         yield obj
    253 # NB: except ... [ as ...] breaks IPython async KeyboardInterrupt

File <python_path>\site-packages\tqdm\std.py:1181, in tqdm.__iter__(self)
   1178 time = self._time
   1180 try:
-> 1181     for obj in iterable:
   1182         yield obj
   1183         # Update and possibly print the progressbar.
   1184         # Note: does not call self.update(1) for speed optimisation.

File <python_path>\site-packages\torch\utils\data\dataloader.py:630, in _BaseDataLoaderIter.__next__(self)
    627 if self._sampler_iter is None:
    628     # TODO
    629     self._reset()  # type: ignore[call-arg]
--> 630 data = self._next_data()
    631 self._num_yielded += 1
    632 if self._dataset_kind == _DatasetKind.Iterable and \
    633         self._IterableDataset_len_called is not None and \
    634         self._num_yielded > self._IterableDataset_len_called:

File <python_path>\site-packages\torch\utils\data\dataloader.py:673, in _SingleProcessDataLoaderIter._next_data(self)
    671 def _next_data(self):
    672     index = self._next_index()  # may raise StopIteration
--> 673     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    674     if self._pin_memory:
    675         data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)

File <python_path>\site-packages\torch\utils\data\_utils\fetch.py:50, in _MapDatasetFetcher.fetch(self, possibly_batched_index)
     48 if self.auto_collation:
     49     if hasattr(self.dataset, "__getitems__") and self.dataset.__getitems__:
---> 50         data = self.dataset.__getitems__(possibly_batched_index)
     51     else:
     52         data = [self.dataset[idx] for idx in possibly_batched_index]

File <python_path>\site-packages\torch\utils\data\dataset.py:420, in Subset.__getitems__(self, indices)
    418     return self.dataset.__getitems__([self.indices[idx] for idx in indices])  # type: ignore[attr-defined]
    419 else:
--> 420     return [self.dataset[self.indices[idx]] for idx in indices]

File <python_path>\site-packages\torch\utils\data\dataset.py:420, in <listcomp>(.0)
    418     return self.dataset.__getitems__([self.indices[idx] for idx in indices])  # type: ignore[attr-defined]
    419 else:
--> 420     return [self.dataset[self.indices[idx]] for idx in indices]

Cell In[1], line 552
    549     image = imread_unicode(img_path)
    551     if self.transform:
--> 552         image = self.transform(image=image)['image']
    554 return image, self.labels[idx], self.image_files[idx]

File <python_path>\site-packages\albumentations\core\composition.py:348, in Compose.__call__(self, force_apply, *args, **data)
    345 self.preprocess(data)
    347 for t in self.transforms:
--> 348     data = t(**data)
    349     data = self.check_data_post_transform(data)
    351 return self.postprocess(data)

File <python_path>\site-packages\albumentations\core\composition.py:574, in OneOrOther.__call__(self, force_apply, *args, **data)
    571     return data
    573 if random.random() < self.p:
--> 574     return self.transforms[0](force_apply=True, **data)
    576 return self.transforms[-1](force_apply=True, **data)

File <python_path>\site-packages\albumentations\core\composition.py:348, in Compose.__call__(self, force_apply, *args, **data)
    345 self.preprocess(data)
    347 for t in self.transforms:
--> 348     data = t(**data)
    349     data = self.check_data_post_transform(data)
    351 return self.postprocess(data)

File <python_path>\site-packages\albumentations\core\transforms_interface.py:124, in BasicTransform.__call__(self, force_apply, *args, **kwargs)
    122     if self.deterministic:
    123         kwargs[self.save_key][id(self)] = deepcopy(params)
--> 124     return self.apply_with_params(params, **kwargs)

File <python_path>\site-packages\albumentations\core\transforms_interface.py:143, in BasicTransform.apply_with_params(self, params, *args, **kwargs)
    141 target_function = self._key2func[key]
    142 if isinstance(arg, np.ndarray):
--> 143     result = target_function(np.require(arg, requirements=["C_CONTIGUOUS"]), **params)
    144     if isinstance(result, np.ndarray):
    145         res[key] = np.require(result, requirements=["C_CONTIGUOUS"])

File <python_path>\site-packages\albumentations\augmentations\transforms.py:5163, in PlanckianJitter.apply(self, img, temperature, **params)
   5161 if not is_rgb_image(img):
   5162     raise TypeError("PlanckianJitter transformation expects 3-channel images.")
-> 5163 return fmain.planckian_jitter(img, temperature, mode=self.mode)

File <python_path>\site-packages\albucore\functions.py:691, in float32_io.<locals>.float32_wrapper(img, *args, **kwargs)
    689 if input_dtype != np.float32:
    690     img = to_float(img)
--> 691 result = func(img, *args, **kwargs)
    693 return from_float(result, target_dtype=input_dtype) if input_dtype != np.float32 else result

File <python_path>\site-packages\albucore\utils.py:107, in clipped.<locals>.wrapped_function(img, *args, **kwargs)
    104 @wraps(func)
    105 def wrapped_function(img: np.ndarray, *args: P.args, **kwargs: P.kwargs) -> np.ndarray:
    106     dtype = img.dtype
--> 107     return clip(func(img, *args, **kwargs), dtype)

File <python_path>\site-packages\albumentations\augmentations\functional.py:1886, in planckian_jitter(img, temperature, mode)
   1883 w_left = (t_right - temperature) / step
   1884 w_right = (temperature - t_left) / step
-> 1886 coeffs = w_left * np.array(PLANCKIAN_COEFFS[mode][t_left]) + w_right * np.array(PLANCKIAN_COEFFS[mode][t_right])
   1888 img[:, :, 0] = img[:, :, 0] * (coeffs[0] / coeffs[1])
   1889 img[:, :, 2] = img[:, :, 2] * (coeffs[2] / coeffs[1])

</details> 

### To Reproduce

1. Albumentations 1.4.17, Python 3.11.6, image size is 270x270x3
2. A.PlanckianJitter(mode='blackbody', p=1, sampling_method="gaussian")

### Expected behavior

run without errors.

### Actual behavior

error on each image.

**Comment by ternaus** [comment]
Thanks, will look ASAP

**Comment by ternaus** [comment]
Cannot reproduce. Need **minimal** example of the code that reproduces the issue. 

https://explore.albumentations.ai/transform/PlanckianJitter

**Comment by RieGo** [comment]
my bad. it doesn't happen everytime. the error appears randomly. probably has to do with gaussian out of bounds values or something...

Here's a script to reproduce the error:
`import albumentations as A
import numpy as np
import traceback

image = np.random.randint(0, 256, (256, 256, 3), dtype=np.uint8)
augmentation = A.PlanckianJitter(mode='blackbody', p=1, sampling_method='gaussian')
success = 0
errors = 0

for i in range(1, 1001):
    try:
        augmented = augmentation(image=image)
        success += 1
        print(f"Iteration {i}: Success")
    except Exception as e:
        errors += 1
        print(f"Iteration {i}: Error - {e}")
        traceback.print_exc()

print(f"\nAll 1000 augmentations applied with {success} successes and {errors} errors.")
`

**Comment by ternaus** [comment]
Thanks. WIll take a look ASAP.
