### ISSUE TITLE
Feature Request: Add Support for Random Colour Temperature Adjustment

### ISSUE THREAD

**Issue by yihong1120** [albumentations-team/albumentations#1969]
### Feature description

I would like to request the addition of a random colour temperature adjustment feature to Albumentations. This feature would allow for the adjustment of image colour temperature by simulating the effects of varying light conditions, ranging from warm to cool tones. It would enhance the diversity of data augmentation by adding variations in lighting conditions, which is particularly useful for models that need to generalise well across different environments.

### Motivation and context

The feature is important for augmenting image datasets in situations where lighting conditions change, such as in outdoor settings or environments with fluctuating artificial lighting. By adjusting the colour temperature randomly during augmentation, models can become more robust to different lighting environments. This fits well with Albumentations' goal of providing versatile and realistic augmentations, allowing users to create more varied training datasets. This feature is similar to how `RandomBrightnessContrast` and `HueSaturationValue` adjust visual properties, but it specifically simulates changes in ambient light temperature.

For example, adjusting the colour temperature is particularly relevant in applications like autonomous driving, where lighting conditions can vary from dawn to dusk, or in indoor surveillance where lighting may be cooler in industrial settings and warmer in residential ones.

### Possible implementation

The feature could be implemented as a new augmentation class `RandomColourTemperature` within the library. This class would randomly generate a colour temperature value in Kelvin (e.g., between 1000K and 40000K) and adjust the RGB values of the image accordingly. It could be integrated into the existing Albumentations pipeline alongside other augmentations.

Here is an example of how this could be implemented:

```python
import numpy as np

def adjust_colour_temperature(image: np.ndarray, temperature: int) -> np.ndarray:
    if temperature < 6500:
        r_gain = 255
        g_gain = int(99.4708025861 * np.log(temperature) - 161.1195681661)
        b_gain = int(138.5177312231 * np.log(temperature - 10) - 305.0447927307)
    else:
        r_gain = int(329.698727446 * ((temperature - 6000) / 10000) ** -0.1332047592)
        g_gain = int(288.1221695283 * ((temperature - 6000) / 10000) ** -0.0755148492)
        b_gain = 255

    gain = np.array([r_gain / 255.0, g_gain / 255.0, b_gain / 255.0])
    image = image.astype(np.float32) / 255.0
    image = image * gain
    image = np.clip(image * 255, 0, 255).astype(np.uint8)
    
    return image

# Integrate this function into a new Albumentations transform.
class RandomColourTemperature(A.ImageOnlyTransform):
    def __init__(self, temperature_range=(1000, 40000), always_apply=False, p=0.5):
        super().__init__(always_apply, p)
        self.temperature_range = temperature_range

    def apply(self, img, **params):
        temperature = np.random.randint(self.temperature_range[0], self.temperature_range[1])
        return adjust_colour_temperature(img, temperature)
```

This implementation would randomly select a colour temperature value from a defined range (e.g., 1000K to 40000K) and apply the transformation. Users would then include this augmentation in their pipelines just like any other Albumentations augmentation.

### Alternatives

While alternatives such as `ColorJitter` can adjust brightness, contrast, and saturation, they don't directly simulate the effect of varying light temperatures. Another alternative would be manually implementing a similar transform outside of Albumentations, but it would be more efficient and consistent to have this feature as part of the library.

### Additional context

Random colour temperature adjustment would be especially useful for datasets where lighting conditions vary significantly, such as street scenes or environments with varying indoor lighting. This feature would give Albumentations users more control over how their model learns to generalise to different lighting conditions.

**Comment by ternaus** [comment]
Looks like you are llogin for [PlankianJitter](https://explore.albumentations.ai/transform/PlanckianJitter)
