### ISSUE TITLE
Can BBoxSafeRandomCrop replace image/annotations tiling?

### ISSUE THREAD

**Issue by nasserdr** [albumentations-team/albumentations#1974]
I have a data set that is **_unfortunately_** annotated with images of size 8000x6000. 
To train an object detection model, I need to feed images of **_much smaller size_** (say 1024x678).

I have a couple of options:

- Resize the images: this is not doable, simply because the objects are very small and I would definitely loose a lot of features before inputing the image to the network.
- Tiling the image with a fixed grid. This option is doable, but I it will create 1) a lot images with no annotations (which I can easily get rid of later) and (most importantly) 2) it will create some images with occluded objects because the tiling is bound to a fixed grid.

Therefore, I am looking for a way where I can tile (or probably, Safe Crop) the images as well as the annotations respecting these constraints:

- Each image should be tiled/croped to the lowest possible number of tiles/crops.
- Tiles/crops can be randomly positionned around the bounding boxes but not causing any occlusion.

I guess someone would have had this problem before and I do not really want to reinvent the wheel. Does anyone knows of a way/code to do this? would BBoxSafeRandomCrop be an alternative?

**Comment by ternaus** [comment]
I do not see, how to do it easily.
