### ISSUE TITLE
RandomResizedCrop with argument size of type int raise: TypeError: If size is an integer, width as integer must be specified.

### ISSUE THREAD

**Issue by Pikauba** [albumentations-team/albumentations#1979]
## Describe the bug

Providing the constructor of [RandomResizedCrop](https://albumentations.ai/docs/api_reference/full_reference/?h=randomresizedcr#albumentations.augmentations.crops.transforms.RandomResizedCrop) with argument `size` of type int.

### To Reproduce
Instanciate the RandomResizedCrop class provinding the parameter `size` with a integer as following:

```python
transform = A.RandomResizedCrop(size=80) # or any other int value for `size`

```
### Expected behavior

Based on the documentation of [RandomResizedCrop](https://albumentations.ai/docs/api_reference/full_reference/?h=randomresizedcr#albumentations.augmentations.crops.transforms.RandomResizedCrop): "If int, square crop is made of this size."

So we would expected a squared crop of size (80, 80) to be returned. 

However this is not the case.

### Actual behavior

Instead of managing the crop and assume a square crop of shape (size, size) a TypeError will be raised.

TypeError: If size is an integer, width as integer must be specified.

### Additionnal Informations
This is probably due to the fact that this validation is made there: [albumentations/augmentations/crops/transforms.py#L692](https://github.com/albumentations-team/albumentations/blob/1d715740af7f9d86dc11f405418ed38bf8bc76e5/albumentations/augmentations/crops/transforms.py#L692)

where self.width has to be initialized, but this is not the case here as width is never defined.

**Comment by ternaus** [comment]
@Pikauba 

RandomResizedCrop is going through the change in the interface, old one with specifying `height` and `width and `size=None` still works, but discouraged.

Updated docstring so that size could be only `tuple[int, int]` that is `(height, width)`

=>

For square crop

```python
 transform = A.Compose([A.RandomResizedCrop(size=(80, 80)])
 ```
