### ISSUE TITLE
LongestMaxSize does upscale an image in contrast to what notes state(?)

### ISSUE THREAD

**Issue by baptist** [albumentations-team/albumentations#1989]
Regarding the LongestMaxSize transformation the notes state that:

> Note:
>         - If the longest side of the image is already less than or equal to max_size, the image will not be resized.
>         - This transform will not crop the image. The resulting image may be smaller than max_size in both dimensions.
>         - For non-square images, the shorter side will be scaled proportionally to maintain the aspect ratio.
 
In contrast, images **seem to be upscaled** eventhough their maximum size is smaller than the defined max_size attribute:

```
def _func_max_size(img: np.ndarray, max_size: int, interpolation: int, func: Callable[..., Any]) -> np.ndarray:
    image_shape = img.shape[:2]

    scale = max_size / float(func(image_shape))

    if scale != 1.0:
        new_height, new_width = tuple(round(dim * scale) for dim in image_shape)
        return resize(img, (new_height, new_width), interpolation=interpolation)
    return img
```

Is this expected behaviour? Does their exist a transformation that does not upscale the image but resizes (downscales) while maintaining the aspect ratio?

**Comment by ternaus** [comment]
@baptist 

Updated docstring. 

This transform will downscale if max_size is smaller than the largest side of the image, while maintaining aspect ratio
