### ISSUE TITLE
ImportError: cannot import name 'KeypointType' from 'albumentations'

### ISSUE THREAD

**Issue by VincentPelletier1** [albumentations-team/albumentations#1993]
## Describe the bug

The bug is as stated: I cannot import `KeyPointType` and I am constantly getting this error:
```Python
ImportError: cannot import name 'KeypointType' from 'albumentations'
```
. I have seen [this issue that was closed ](https://github.com/albumentations-team/albumentations/issues/1600) on what seems to be the exact same issue. However, doing anything in this thread did not solve my issue, and the versions aren't the same.

I have tried importing using the following ways:
```Python
from albumentations import KeyPointType
```
```Python
from albumentations.core.transforms_interface import KeypointType
```

Both which landed me right where I was at the beginning.

### To Reproduce

1. Ubuntu 22.04.5 LTS
2. Using Albumentations 1.4.18

### Additional context

- I have tried to downgrade to 1.4.14 to no avail
- I have tried to remake my virtual environment about thrice, removing and rebuilding my lock file with poetry to ensure that it wasn't a dependency issue.

**Comment by ternaus** [comment]
Albumentations moved to a vectorized processing for Keyplints => no more KeypointType in the database.

What is the use case that requires `KeypointType`?

**Comment by VincentPelletier1** [comment]
It was used as a type hinting. I think our codebase will be able to live on without it ;)
