### ISSUE TITLE
[RandomShadow] shadow_dimension does not affect the polygon dimensions

### ISSUE THREAD

**Issue by clementlemon8** [albumentations-team/albumentations#1994]
## Describe the bug

I tried playing around in the playground provided, https://explore.albumentations.ai/transform/RandomShadow, noticed that changing `shadow_dimension` does not affect the polygon shape. Did a bit of digging in the codes 

### To Reproduce

1. Environment: Albumentations version v1.4.18
2. Edit RandomShadow `shadow_dimension` variable, does not affect the number of edges of shadow polygon

### Expected behavior

Changing `shadow_dimension` should affect shape of shadow polygon

### Actual behavior

`shadow_dimension` seem to be hardcoded as 5

### Screenshots
Proof that changing `shadow_dimension` is 5 no matter what value set
![image](https://github.com/user-attachments/assets/f9a622ff-6fe4-48bc-b4f5-80067a978a48)

In my understanding, `vertices_list` variable of the `get_params_dependent_on_data` method is where the shadow is being set, it appears that the shadow_dimension is simply hardcoded as 5? I don't see anywhere where `self.shadow_dimension` is being utilised in the codes. 
![image](https://github.com/user-attachments/assets/c4c8b424-eab7-462a-838d-dde0fd0cc2dc)

### Additional context
Proposed changes:
1. Add validation checks for the param `shadow_dimension` under `validate_shadows` method, ensuring it is >=3 integer for a valid polygon
2. Use `self.shadow_dimension` under the `get_params_dependent_on_data` method to set the `vertices_list`.

Hope it helps!

**Comment by ternaus** [comment]
Thanks! Will look ASAP
