### ISSUE TITLE
[Solarize] single int threshold not working as described in docstring

### ISSUE THREAD

**Issue by clementlemon8** [albumentations-team/albumentations#1996]
## Describe the bug

For Solarize, single int threshold does not work as what was written in the docstring
```
 Args:
        threshold (float | tuple[float, float]): Range for solarizing threshold.
            If threshold is a single int, the range will be [threshold, threshold].
            If it's a tuple of (min, max), the range will be [min, max].
```
For single int, it appears to be `[1, threshold]` instead of `[threshold, threshold]`

### To Reproduce

1. Environment: Albumentations version v1.4.18
2. Tested in the playground https://explore.albumentations.ai/transform/Solarize and local codes

### Expected behavior

Example use case: expect that `threshold=128`, will provide exact same output as `threshold=(128,128)` everytime

### Actual behavior

threshold=128 has behaviour similar to `threshold=(1,128)`

### Screenshots
`threshold=(128,128)` gives the same image output everytime
![image](https://github.com/user-attachments/assets/b4276705-5caa-4a09-ab0a-7ace2f4a0775)

`threshold=128` gives varying image output each time
![image](https://github.com/user-attachments/assets/d2700a8f-2de3-462a-8572-d4fac20a698e)
![image](https://github.com/user-attachments/assets/6bce3c6d-f315-4f36-8245-48f39c7c4569)

**Comment by ternaus** [comment]
Thanks.

Updated UI tool with the latest state of the repo.
