### ISSUE TITLE
[Affine] Unable to run Scale = 1.0 without raising error

### ISSUE THREAD

**Issue by clementlemon8** [albumentations-team/albumentations#2004]
## Describe the bug

I'm unable to run the Affine transform with scale=1.0 as it raises error with `balanced_scale = True`. Lines of code causing this issue: **[Link](https://github.com/albumentations-team/albumentations/blob/651d64cd2e11c397592efa82cc708ec5d41eff72/albumentations/augmentations/geometric/transforms.py#L766-L776)**

### To Reproduce

1. Environment (Windows, Python version = 3.8.10, Albumentations version=1.4.18)
2. Calling the Affine transform with scale set as 1.0

### Expected behavior
Expect no error to be raised when `scale = 1.0` & `balanced_scale = True`, as it is just no changes 

### Actual behavior

ValueError is raised as seen in screenshots, Reason being, there are cases where i just want to run Shear transform from this Affine class with no changes to the scale (scale = 1.0)
Oddly enough, when i put scale = 1.0 in the explore UI https://explore.albumentations.ai/transform/Affine, no error is raised. But error is raised when i set Scale = 1.0 in the codes

### Screenshots

![image](https://github.com/user-attachments/assets/0e7d88a9-98cc-4a26-b74e-bb115e23014f)
![image](https://github.com/user-attachments/assets/f206df87-e32a-4686-8706-539c04ace07f)

### Additional context

Not sure if this is intended behaviour, but it limits users from running one of the few transforms in Affine without changing the scale (=1.0)

**Comment by ternaus** [comment]
Thanks, will look ASAP.

**Comment by ternaus** [comment]
@clementlemon8 Fixed.
