### ISSUE TITLE
[OpticalDistortion] Inaccurate Bbox output when distort_limit is high 

### ISSUE THREAD

**Issue by clementlemon8** [albumentations-team/albumentations#2007]
## Describe the bug

For `OpticalDistortion`, when i attempt to set `distort_limit` with high magnitude (>=0.55), the resulting bbox appears inaccurate, but the mask and keypoints are accurate.

### To Reproduce

1. Environment (Windows, Python 3.8, Albumentations version v1.4.18)
2. Replicable in the **[UI](https://explore.albumentations.ai/transform/OpticalDistortion)** and also by code, by setting `distort_limit` >= (0.55,0.55)

### Expected behavior

Even with high `distort_limit`, bbox output should remain within the object of interest without excess background area covered.

### Actual behavior
With high `distort_limit`, Bbox output became larger encompassing excess background area.

### Screenshots
Code output with `OpticalDistortion(distort_limit=(0.55, 0.55), shift_limit=(-0.5, -0.5))`:
![image](https://github.com/user-attachments/assets/da862995-a0c1-4147-b4c2-a030473e8064)

In UI, setting `distort_limit = (0.55, 0.55)`
![image](https://github.com/user-attachments/assets/7bff571c-7566-4a3e-9087-ebb6c718daf8)

**Comment by ternaus** [comment]
Thanks, will take a look.

**Comment by ternaus** [comment]
@clementlemon8 Thanks, fixed.
