### ISSUE TITLE
[Perspective] keep_size=True in codes results in inaccurate bbox, keypoints and mask

### ISSUE THREAD

**Issue by clementlemon8** [albumentations-team/albumentations#2017]
## Describe the bug

For Perspective Transform, i use these parameters in my code, and the output annotations appear inaccurate: 
scale=(0.05, 0.1), `keep_size=True`, pad_mode=0, pad_val=0, mask_pad_val=0, fit_output=True, interpolation=1, always_apply=False, p=1):

but with same parameters and I change `keep_size = False`, the annotations are accurate

happens in my code, but not with the UI page

### To Reproduce

1. Environment (Windows, Python version =3.8.10, Albumentations version = v1.4.18)
2. compare set `keep_size = True` vs `keep_Size = False`

### Expected behavior

keep_size = True  returns accurate transformed annotations (bbox, keypoints, mask)

### Actual behavior

keep_size = True returns wrongly transformed annotations (bbox, keypoints, mask)

### Screenshots
keep_size = True (inaccurate)
![image](https://github.com/user-attachments/assets/eedf8f02-e8d9-4371-a55f-83f99e3cf6ce)
![image](https://github.com/user-attachments/assets/c3f25647-63b4-45ec-970e-12b7bd273f1a)

keep_size = False (accurate)
![image](https://github.com/user-attachments/assets/7f31d2b6-04ec-4f00-acc1-f14915c1aeac)
![image](https://github.com/user-attachments/assets/66db6176-9782-4664-adc6-0b26c87328db)

**Comment by ternaus** [comment]
Fixed
