### ISSUE TITLE
[RandomResizedCrop] inaccurate keypoints

### ISSUE THREAD

**Issue by clementlemon8** [albumentations-team/albumentations#2018]
## Describe the bug

bbox and mask seemed accurate, but keypoints are inaccurate after transformation

### To Reproduce

may test it out in the UI https://explore.albumentations.ai/transform/RandomResizedCrop
happens in codes as well (v1.4.18)

### Expected behavior

keypoints should look accurate.

### Actual behavior

keypoints are quite off after transformation, deferring away from the features in the image that are supposed to be labelled with keypoints

### Screenshots
UI
![image](https://github.com/user-attachments/assets/0f89ee7d-350c-41a3-b7e4-da984d0ca0e0)

Code output:
![image](https://github.com/user-attachments/assets/70a80e68-efcc-42d8-bc73-9c3cdcb82d9e)

**Comment by ternaus** [comment]
Thanks! WIll look ASAP
