### ISSUE TITLE
[RandomSizedBBoxSafeCrop] inaccurate keypoints AND UI bug: image is not resized to user specified height and width

### ISSUE THREAD

**Issue by clementlemon8** [albumentations-team/albumentations#2019]
## Describe the bug
**Bug 1:**
(in UI and codes) RandomSizedBBoxSafeCrop returns inaccurate keypoints after transform, suspect it might relate to [this issue of RandomResizedCrop](https://github.com/albumentations-team/albumentations/issues/2018) earlier, where crop transforms with any type of resizing will return inaccurate keypoints. 
Because I do not face this issue with BBoxSafeRandomCrop, and i know RandomSizedBBoxSafeCrop inherits that class and adds resizing.

**Bug 2:** 
(ONLY in UI, no problem in codes) for RandomSizedBBoxSafeCrop, image is not resized to user specified height and width (refer to Screenshots). suspect UI of RandomSizedBBoxSafeCrop is hardcoded to the default size values of RandomResizedCrop

### To Reproduce

Tested in UI: https://explore.albumentations.ai/transform/RandomSizedBBoxSafeCrop
Code: v1.4.18, python 3.8.10, i resize 1920x1080 img -> 500x500

### Expected behavior

Bug 1: keypoints should look accurate after transform.
Bug 2: in UI, output image should be resized to specified height and width as described in the docstring.

### Actual behavior

Bug 1: keypoints looks off and inaccurate after transform.
Bug 2: in UI, output image is alway resized to 512 x 320 no matter the user input height and width

### Screenshots
Bug 1:
UI:
![image](https://github.com/user-attachments/assets/3e9ac89b-973d-42a5-97f6-5815d6b553bb)
Code: 
![image](https://github.com/user-attachments/assets/11e2caf2-0c97-4502-8430-c2fcb882ef14)

Bug 2 (only in UI):
![image](https://github.com/user-attachments/assets/5bbc4675-9f6a-4d7f-93af-a989ad37f2f4)

**Comment by ternaus** [comment]
Thanks, will look asap.

**Comment by ternaus** [comment]
Fixed

**Comment by clementlemon8** [comment]
hi @ternaus, appreciate your swift response, can see the fix for accurate keypoints now 😁

> Bug 2:
(ONLY in UI, no problem in codes) for RandomSizedBBoxSafeCrop, image is not resized to user specified height and width (refer to Screenshots). suspect UI of RandomSizedBBoxSafeCrop is hardcoded to the default size values of RandomResizedCrop

however this UI seems to persists, would be great if this is fixed too for users to visualize changes with specified height and width (rather than the hardcoded 512 x 320 output img size)
![image](https://github.com/user-attachments/assets/6528c5d7-f4b5-440f-ab22-df64d1e86a39)

**Comment by ternaus** [comment]
Thanks, will fix tomorrow.

**Comment by ternaus** [comment]
Fixed.

@clementlemon8 If you have any issues or feature requests about UI tool, feel free to create issues.

The library is more or less polished, but UI tool is not. Your feedback will help.
