### ISSUE TITLE
[Normalize] normalization="inception shown in docstring of Normalize, but no actual implementations and support yet

### ISSUE THREAD

**Issue by clementlemon8** [albumentations-team/albumentations#2027]
## Describe the bug

`normalization="inception"` is shown in the docstring of class Normalize, but it is actually not supported yet with no implementations found within the repo.

### To Reproduce

1. Environment (e.g., Windows, Python 3.8.10, Albumentations version v1.4.18)
2. In codes, set `normalization="inception"` -> throws ValidationError

### Expected behavior

Expected to be able to run Normalize with normalization="inception" as written in docstring.

### Actual behavior

Normalize with normalization="inception" throws ValidationError

### Screenshots
**Code console error msg:**
![image](https://github.com/user-attachments/assets/41f05d3a-e5fa-4157-a4df-fab945b74911)
**Albumentations library class Normalize does not have the "inception" option in normalization parameter**
![image](https://github.com/user-attachments/assets/58394fb3-729f-47a2-a4a0-62fa5f4448ba)
![image](https://github.com/user-attachments/assets/ec35e2df-7d47-48f6-ba13-85579bf0d977)
**Albucore library doesn't have any implementations for "inception" for `normalize_per_image`**
![image](https://github.com/user-attachments/assets/c59e23e2-4d33-469d-a5fb-2e9909fb7009)
![image](https://github.com/user-attachments/assets/5baae933-fa8f-4135-8635-9a92b116fc34)
![image](https://github.com/user-attachments/assets/bd3c12fd-2441-4388-9ba8-577e25126f90)

**Comment by ternaus** [comment]
@clementlemon8 

Thank you.

Cleaned up docstring. For inception, we shuould just pass (0.5, 0.5, 0.5) for std and main in the standard normalization

**Comment by clementlemon8** [comment]
@ternaus I see now, thanks for the fixes too!
