### ISSUE TITLE
1.4.21 breaks `ElasticTransform` (in `generate_displacement_fields`)

### ISSUE THREAD

**Issue by RuRo** [albumentations-team/albumentations#2046]
`A.ElasticTransform` had a significant change in behavior between `1.4.20` and `1.4.21`. I was able to track the difference to the changes in `generate_displacement_fields`.

### To Reproduce

```python
import albumentations as A
import numpy as np

dx, dy = A.augmentations.geometric.functional.generate_displacement_fields(
    (3, 4),
    20.0,
    500.0,
    same_dxdy=False,
    kernel_size=(17, 17),
    random_generator=np.random.default_rng(42),
)
print(A.__version__)
print(dx)
print(dy)
```

In `1.4.20` this produces
```
1.4.20
[[5.5182104 5.7420244 5.7509494 6.6734114]
 [5.6253014 5.8748746 5.796039  6.8868446]
 [4.9180765 5.2411366 5.1809683 6.194394 ]]
[[2.7223685 2.3128772 3.23717   2.5941987]
 [2.486079  2.0793862 3.1618743 2.4262364]
 [3.0031323 2.6128216 3.674878  2.9513078]]
```

But in `1.4.21` the output is instead
```
1.4.21
[[-33.33009  -33.746403 -29.965046 -30.64001 ]
 [-35.34924  -35.85331  -32.12183  -32.52092 ]
 [-33.246334 -33.70301  -29.929686 -30.534288]]
[[-12.529673 -15.237955 -12.606472 -13.616659]
 [-13.570969 -16.224113 -13.247079 -14.587833]
 [-13.313246 -16.02848  -13.042294 -14.267974]]
```

### Additional context

It seems, that this regression was caused by #2031 in commit ad51312f6f6dd6a9729f17292a7aa3d5114a1b00, which changed
```diff
diff --git a/albumentations/augmentations/geometric/functional.py b/albumentations/augmentations/geometric/functional.py
index be9a647e9..d3eb3f45a 100644
--- a/albumentations/augmentations/geometric/functional.py
+++ b/albumentations/augmentations/geometric/functional.py
@@ -1487,19 +1486,17 @@ def generate_displacement_fields(
     sigma: float,
     same_dxdy: bool,
     kernel_size: tuple[int, int],
-    random_generator: np.random.Generator | None = None,
+    random_generator: np.random.Generator,
 ) -> tuple[np.ndarray, np.ndarray]:
     """Generate displacement fields for elastic transform."""
-    height, width = image_shape[:2]
-
-    dx = random_utils.rand(height, width, random_generator=random_generator).astype(np.float32) * 2 - 1
+    dx = random_generator.standard_normal(size=image_shape[:2]).astype(np.float32) * 2 - 1
     cv2.GaussianBlur(dx, kernel_size, sigma, dst=dx)
     dx *= alpha
  
     if same_dxdy:
         dy = dx
     else:
-        dy = random_utils.rand(height, width, random_generator=random_generator).astype(np.float32) * 2 - 1
+        dy = random_generator.standard_normal(size=image_shape[:2]).astype(np.float32) * 2 - 1
         cv2.GaussianBlur(dy, kernel_size, sigma, dst=dy)
         dy *= alpha
```

However, `rand` and `standard_normal` are not equivalent. `rand` samples from Uniform[0; 1] and `standard_normal` samples from Normal(0, 1).

**Comment by ternaus** [comment]
Thanks, will look ASAP.

**Comment by ternaus** [comment]
It is not a bug, but an unexpected breaking change.

Added parameter to Elastic for uniform Sampling.

Feel free to check: https://explore.albumentations.ai/transform/ElasticTransform

**Comment by RuRo** [comment]
I still think that the current implementation is wrong.

Unlike the Uniform sampling code path,
```python
random_generator.standard_normal(size=image_shape[:2]).astype(np.float32) * 2 - 1
```
produces values with a non-zero mean resulting in a shifted image.

The `* 2 - 1` was originally needed to transform the [0;1] uniform distribution into a [-1;1] uniform distribution. Applying it to the normal distribution doesn't make sense.

Also, even without this bug, introducing a breaking change in a patch version is not a great look. You can add a new mode without changing the default. Otherwise, augmentation parameters that worked great in `1.4.20` may produce nonsense results in `1.4.21` and vice versa.

**Comment by ternaus** [comment]
Good point. Will fix.

**Comment by ternaus** [comment]
Removed scaling and shift in https://github.com/albumentations-team/albumentations/pull/2049

**Comment by ternaus** [comment]
About breaking change.

Not happy about it, but somehow not excited to go through the long cycle of throwing warnings about the future change of the behavior.

I believe, linear sampling was introduced not that long ago and by accident, when used `random_utils.rand` instead of `random_utils.randn`

it is unfortunate and if there was more resorces, meaning $$$ in the https://github.com/sponsors/albumentations-team tab - I would be more careful with changes.
