### ISSUE TITLE
UserWarning: Try to use ``ElasticTransformation`` instead. However, there is no API for ElasticTransformation.

### ISSUE THREAD

**Issue by deanflaviano** [albumentations-team/albumentations#2051]
## Describe the bug

The file albumentations/augmentations/geometric/transforms.py triggers a warning:

 warn(
            "This augmenter is very slow. Try to use ``ElasticTransformation`` instead, which is at least 10x faster.",
            stacklevel=2,
        )

But ElasticTransformation does not exist in the library.

### To Reproduce

1. Pip package: albumentations 1.4.21

When I use:
```
augmentations = [
 A.PiecewiseAffine(scale=(0.01, 0.05), nb_rows=4, nb_cols=4, interpolation=3, p=0.5),
]

```
**I get the message:** "This augmenter is very slow. Try to use ``ElasticTransformation`` instead, which is at least 10x faster."

When I use:
```
import albumentations as A
augmentations = [
 A.ElasticTransformation(p=0.5),
]

```
**I get the error:** AttributeError: module 'albumentations' has no attribute 'ElasticTransformation'

### Expected behavior

Since the UserWarning recommends ElasticTransformation, I expect it to exist. I thought ElasticTransformation was a refactored version of ElasticTransform.

**Comment by deanflaviano** [comment]
I assume there is a typo in the UserWarning, and it suggests to use ElasticTransform instead of PiecewiseAffine?

**Comment by ternaus** [comment]
@deanflaviano Thank you, fixed
