### ISSUE TITLE
Extra keypoints when using Rotate with keypoints

### ISSUE THREAD

**Issue by Chxresubles** [albumentations-team/albumentations#2055]
## Describe the bug

Using `A.Rotate` in `A.Compose` with `remove_invisible=False` returns 9 times more keypoints than the input number of keypoints.

### To Reproduce

```
import numpy as np
import albumentations as A

image = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)
keypoints = np.random.randint(0, 100, (50, 2), dtype=np.uint8)

# Check shape
print(keypoints.shape)  # (50, 2)

result = A.Compose([A.Rotate(limit=45, p=1.0)], keypoint_params=A.KeypointParams(format='yx', remove_invisible=False))(image=image, keypoints=keypoints)

# Check shape
print(result['keypoints'].shape)  # (450, 2)
```

### Expected behavior

`result['keypoints']` should have the same shape as the input keypoints. (50, 2)

### Actual behavior

`result['keypoints']` has 9 times more keypoints than the input keypoints. (9 * 50, 2)

### Additional context

The bug was not present in albumentations==1.4.18 and was introduced since albumentations==1.4.19

**Comment by ternaus** [comment]
It is not a bug, but a feature.

When you use `border_mode=cv2.BORDER_REFLECT_101` which is the default, you get new keypoints in the reflected regions.

If you change `border_mode` to `cv2.BORDER_CONSTANT`, no new keypoints will be added.
