### ISSUE TITLE
[RandomSunFlare] Add transparency to RandomSunFlare

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#2067]
![image](https://github.com/user-attachments/assets/2c1a7dec-77db-4150-86df-d484da5e2e31)

Sunflare obscures the object

**Comment by momincks** [comment]
Can I assume explore.albumentations.ai hosts latest commit on main?

**Comment by ternaus** [comment]
Typically yes, unless I forget to update the explore.albumentations.ai 

Right now it is the latest.
