### ISSUE TITLE
[Bug] RandomSunFlare generates only one bright spot regardless of the input

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#2069]

**Comment by momincks** [comment]
There are no input parameters for RandomSunFlare to adjust the number of bright spots but flare spots (those with larger areas and different colors). There will only be one bright spot with num_times of circles stacked together:

https://github.com/albumentations-team/albumentations/blob/8e30be082eb18df6b68285a15a95f3ece788dbf1/albumentations/augmentations/functional.py#L940

Or you mean something else?

**Comment by ternaus** [comment]
bweing honest, I do not remember what did I mean. Let's just close it.
