### ISSUE TITLE
[New transform] Add RandomAutoContrast

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#2086]
Add RandomContrast that has the same API as RandomAutoContrast from Kornia

https://kornia.readthedocs.io/en/latest/augmentation.module.html#kornia.augmentation.RandomAutoContrast

**Comment by vectorvp** [comment]
Hey @ternaus, I want to work on some tasks connected with new transforms. Can I take any of them or should you assign me to some to prevent double work?

**Comment by ternaus** [comment]
@vectorvp You may pick any of them, but write in comments that you started working on them.

**Comment by ternaus** [comment]
Added in https://github.com/albumentations-team/albumentations/pull/2158
