### ISSUE TITLE
bbox_utils.convert_bboxes_to_albumentations() not working 

### ISSUE THREAD

**Issue by cami-tc** [albumentations-team/albumentations#2133]
## Describe the bug

Hello, 
I recently updated to the latest version of albumentations. My existing code no longer works, specifiically I get a type error `TypeError: convert_bboxes_to_albumentations() missing 1 required positional argument: 'array'`. It looks like the function wants an input argument `array` but when I go to the function definition it only has 
 ```    Args:
        bboxes: A numpy array of bounding boxes with shape (num_bboxes, 4+).
        source_format: Format of the input bounding boxes. Should be 'coco', 'pascal_voc', or 'yolo'.
        image_shape: Image shape (height, width).
        check_validity: Check if all boxes are valid boxes.
``` 
        
I might be missing something, but it seems that this function is wrapped in `@handle_empty_array` which is expecting an input array, whereas I explicitly assign bboxes. If I don't explicitly assign bboxes it works, if this is the desired behavior then no issue. 

### To Reproduce

```
from albumentations.core import bbox_utils
import numpy as np

input_boxes = np.array([[0, 0, 100, 100], [50, 50, 150, 150]])

bboxes = bbox_utils.convert_bboxes_to_albumentations(
    bboxes=input_boxes, source_format="coco", image_shape=(256, 256)
)
```
### Actual Behavior 

`TypeError: convert_bboxes_to_albumentations() missing 1 required positional argument: 'array'`

### Environment 
Python: 3.12.7
Albumentations:  1.4.21

### Expected behavior

No TypeError with  `bbox_utils.convert_bboxes_to_albumentations(
    bboxes=input_boxes, source_format="coco", image_shape=(256, 256)
)`

**Comment by ternaus** [comment]
@cami-tc Thank you. Fixed.
