### ISSUE TITLE
Is it possible to perform data enhancement on yolov8-obb txt files?

### ISSUE THREAD

**Issue by omaiyiwa** [albumentations-team/albumentations#2163]
## Your Question

I marked the rotated target box, but my dataset sample is a bit small, I want to do data enhancement, what parameters should be set, if it can be achieved, can you give me a simple example?

I have processed the annotation data into the styles supported by yolov8: class_index x1 y1 x2 y2 x3 y3 x4 y4

like: 1 0.8840979548345007 0.4897240259441924 0.8998242251018332 0.5123324301046271 0.9639363193590478 0.3713870851669188 0.9482100490917155 0.348778681006484

**Comment by ternaus** [comment]
@omaiyiwa I think, it is better to ask at https://github.com/ultralytics/ultralytics/issues
