### ISSUE TITLE
Please remove dependencies of imgaug

### ISSUE THREAD

**Issue by MonolithFoundation** [albumentations-team/albumentations#2182]
This lib is no longer maintained: imgaug

- You are not list it as dependencies in setup.py or anythingwhere but just import it;
- imgaug this lib is no longer compatible with numpy 2.0 API;
- imgaug this lib just breaks for numpy 2.0

Please consider remove it. or just use the code from it with reference but maintain inside .

**Comment by ternaus** [comment]
It was removed a long time ago.

**Comment by MonolithFoundation** [comment]
No, it still imported in your code, albumcore...

**Comment by ternaus** [comment]
Could you please show me the line?
