### ISSUE TITLE
Parameter not updated in CoarseDropout documentation?

### ISSUE THREAD

**Issue by gbernstein-inari** [albumentations-team/albumentations#2186]
https://github.com/albumentations-team/albumentations/blob/f83b98e793210b204efee8f4126f40739836d984/albumentations/augmentations/dropout/coarse_dropout.py#L43

Looking at the code, this should be `fill_mask`?

**Comment by ternaus** [comment]
@gbernstein-inari Thanks, will fix.

**Comment by ternaus** [comment]
Fixed.
