### ISSUE TITLE
How to know if a transform has been applied

### ISSUE THREAD

**Issue by Pabloferex** [albumentations-team/albumentations#2193]
So I'm trying to apply multiple transforms to the same original set of images.

However, I see that even with probability 0 the library just outputs the original image, ending up with the same image n times copied. I see that his behavior is described in the documentation.

Is there a way to know if the transform has been applied or not?

Thanks!

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the BasicTransform class to add an attribute that tracks whether the transform was applied, and a method to retrieve this information. This change allows users to determine if a transform was applied, even when the probability is 0.

You can review changes in this commit: https://github.com/kkpo4553/albumentations-team-albumentations-2193/commit/a823c36f455cdcbf417715b61d1e6f583b86ea83.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ternaus** [comment]
@kkpo4553 If you have a Compose and a set of transforms in it, how do you pass infor from transform being applied to the Compose?

**Comment by ternaus** [comment]
@Pabloferex you may try to use flag `save_applied_params=True` in compose. 

```python
import albumentations as A

# Create a transform with save_applied_params=True
transform = A.Compose([
    A.RandomCrop(width=256, height=256),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
], save_applied_params=True)

# Apply the transform
result = transform(image=image)

# Access the applied transforms and their parameters
applied_transforms = result['applied_transforms']

# Print the transforms that were actually applied and their parameters
for transform_name, params in applied_transforms:
    print(f"Transform: {transform_name}")
    print(f"Parameters: {params}")
```
