### ISSUE TITLE
ToTensorV2 support for a list of masks

### ISSUE THREAD

**Issue by matejpekar** [albumentations-team/albumentations#2212]
## Describe the bug

Pull Request #2196 modified the implementation of `apply_to_masks` in `ToTensorV2`, requiring the input to be a NumPy array of stacked masks instead of a list. This change restricts use cases where the masks dimensions don't match. I would suggest to support both stacked NumPy arrays and list of arrays.

### System Information

Albumentations version: 1.4.23
OS: MacOS: 15.1.1
Python version: 3.12.7

### Steps to reproduce
```python
import numpy as np
from albumentations.pytorch import ToTensorV2

to_tensor = ToTensorV2(transpose_mask=True)

img = np.zeros((256, 256, 3))
mask1 = np.zeros((10, 256, 256))
mask2 = np.zeros((20, 256, 256))

to_tensor(image=img, masks=[mask1, mask2])
```

**Comment by ternaus** [comment]
I do not think about transforms outside of the Compose pipeline, and in Compose we convert lists to arrays, process and convert back.

But I can wee that ToTensor could have use cases outside of the Compose.

Thank you for the Pull Request
