### ISSUE TITLE
Unexpected behavior of transforms  for multi-label masks

### ISSUE THREAD

**Issue by adizhol** [albumentations-team/albumentations#280]
Hi,

I have a multi-channel mask, where each channel is a binary mask, for multi-label segmentation.
For example, mask = 256 x 256 x 10
I apply a ShiftScaleRotate transform, with border value set to 255.
The result warped mask has the the border value only on the first channel. I expect it to be on all channel.

Edit:
Also, after Resize(), the last channel of the mask is all zeros although there was information there.
Also, Flip() changes transposes the third and second channels.
## Environment

 - Albumentations version: 0.2.3
 - Python version: 3.6
 - OS : Windows

**Comment by adizhol** [comment]
This is how I changed albumentations\core\transforms_interface.py:
line 54:
```
...
            for key, arg in kwargs.items():
                if arg is not None:
                    target_function = self._get_target_function(key)
                    target_dependencies = {k: kwargs[k] for k in self.target_dependence.get(key, [])}
                    if key == 'mask':
                        res[key] = []
                        for i in range(arg.shape[-1]):
                            res[key].append(target_function(arg[:,:,i], **dict(params, **target_dependencies)))

                        res[key] = numpy.dstack(res[key])
                    else:
                        res[key] = target_function(arg, **dict(params, **target_dependencies))
                else:
                    res[key] = None

```

**Comment by albu** [comment]
hi @adizhol looks like multi channel masks are not officially supported. if your classes don't intersect you can try to encode them into single-channel long mask. hope that helps

**Comment by snakers4** [comment]
@albu 
Is it still the case?

Interestingly enough, I forked your augs back when you posted them for carvana challenge (and used them for several satellite competitions) and they worked for multi-channel masks ...

**Comment by albu** [comment]
in 0.4.3 it should work

**Comment by snakers4** [comment]
I tested
I works
