### ISSUE TITLE
module 'albumentations' has no attribute 'RandomSnow'

### ISSUE THREAD

**Issue by HananRosenthal** [albumentations-team/albumentations#281]
## 🐛 Bug

Installed on windows 10 using Conda.
However, not all methods are recognized, e.g. 'RandomRain'.

**Comment by ternaus** [comment]
What is the library version do you use?

**Comment by HananRosenthal** [comment]
albumentations  0.3.0

**Comment by ternaus** [comment]
Could you please share an example of the code that will allow reproducing?

**Comment by ternaus** [comment]
```python
In [1]: import albumentations as A


In [2]:

In [2]: from albumentations import RandomSnow

In [3]: A.__version__
Out[3]: '1.4.8'
```
