### ISSUE TITLE
KeyError: 'cropping_bbox' when using RandomCropNearBBox

### ISSUE THREAD

**Issue by Susia00** [albumentations-team/albumentations#288]
I  use this method:
aug = get_aug([RandomCropNearBBox(max_part_shift=0.3,p=1)])
augmented = aug(**annotations)

but a keyError happened: 
albumentations-0.3.0-py3.5.egg/albumentations/core/composition.py", line 194, in __call__
albumentations-0.3.0-py3.5.egg/albumentations/core/transforms_interface.py", line 57, in __call__
albumentations-0.3.0-py3.5.egg/albumentations/core/transforms_interface.py", line 57, in <dictcomp>
KeyError: 'cropping_bbox'
 Does someone can solve it?

**Comment by albu** [comment]
this method is a little unstable. you need to pass bounding box to crop by as argument "cropping_bbox" and run cropping before all other augmentations.

**Comment by Susia00** [comment]
> this method is a little unstable. you need to pass bounding box to crop by as argument "cropping_bbox" and run cropping before all other augmentations.

Could you give me an example in code?   It still has some running errors. Thx.

**Comment by vfdev-5** [comment]
Any updates on this ?

**Comment by zhaonat** [comment]
also hoping for an update on this?

**Comment by NOxDriver** [comment]
I'm having the same error

**Comment by fadamsyah** [comment]
I have the same problem. Hope to see an update on this issue

**Comment by Dipet** [comment]
Fixed in #993
