### ISSUE TITLE
Repeat transformation many times

### ISSUE THREAD

**Issue by MichaelMonashev** [albumentations-team/albumentations#307]
Подумалось, не хватает одного подхода: генерации из одного изображения нескольких.

Практически это решается добавлением к Compose() и OneOf() ещё одного метода: Repeat(n=1234). Тогда все функции внутри блока репита будут повторяться несколько раз и после каждого создавать отдельное изображение. И далее по цепочке трансформаций будет уже идти не одно изображение, а батч изображений.

Так, например, можно будет потом на этих изображениях делать MixUp или получать батч из случайных кропов одной картинки...

**Comment by BloodAxe** [comment]
А что мешает сделать это извне:
```
batch = []
for i in range(16):
    batch.append(transform(image=image))
```
Мне кажется такой подход более гибок и не требует никаких изменений в коде библиотеки.

**Comment by MichaelMonashev** [comment]
Так и делаю сейчас: сначала общая аугментация всей картинки, потом отдельная аугментация для каждого кропа. 

Пример моего текущего кода:
```
def aug_train1(p=1.0):
    return Compose([
        LongestMaxSize(max_size=768, always_apply=True),
        PadIfNeeded(min_height=768, min_width=768, always_apply=True), 
        RandomBrightnessContrast(),
        GaussNoise(),
        VerticalFlip(p=0.5),
        RandomScale(scale_limit=(0.5,2.0), always_apply=True),
    ], p=p)

def aug_train2(p=1.0):
    return Compose([
        RandomCrop(224, 224, always_apply=True), 
        RandomRotate90(always_apply=True),
        Normalize(),
    ], p=p)

```
Плюс код, который обрабатывает одну картинку несколько раз на подобие Вашего.

Всё это могло бы быть переписано так:
```
def aug_train1(p=1.0):
    return Compose([
        LongestMaxSize(max_size=768, always_apply=True),
        PadIfNeeded(min_height=768, min_width=768, always_apply=True), 
        RandomBrightnessContrast(),
        GaussNoise(),
        VerticalFlip(p=0.5),
        RandomScale(scale_limit=(0.5,2.0), always_apply=True),
        Repeat([
                RandomCrop(224, 224, always_apply=True), 
                RandomRotate90(always_apply=True),
        ], n=8),
        Normalize(),
    ], p=p)
```
ИМХО, нагляднее и удобнее аугментацию картинок полностью сосредоточить в одном месте.

Хотя согласен, что подобное изменение потребует возможно сильных изменений в коде библиотеки.

**Comment by MichaelMonashev** [comment]
Вот, кстати схожий тикет: https://github.com/albu/albumentations/issues/300 . Там тоже речь о том, чтобы обрабатывать НЕСКОЛЬКО изображений. Только в виде отдельных каналов.

Возможно стоит подумать над тем, как сделать подобную обработку простой и универсальной.

**Comment by ternaus** [comment]
В цикле все-таки удобнее применить сколько надо раз. Перегружать Compose не хочется.
