### ISSUE TITLE
ValueError: y_max is less than or equal to y_min

### ISSUE THREAD

**Issue by vadik6666** [albumentations-team/albumentations#353]
During training in MMDetection using [this](https://github.com/open-mmlab/mmdetection/pull/1354) PR I got following error:
```
augmentations/bbox_utils.py", line 247, in check_bbox
    bbox=bbox,
ValueError: y_max is less than or equal to y_min for bbox [0.5390625, 0.6067708333333334, 0.541015625, 0.6067708333333334, 17].
```
I use only `ShiftScaleRotate` augmentation for bboxes:
```
type='ShiftScaleRotate',
        shift_limit=0.15,
        scale_limit=(0.0, 0.45),
        rotate_limit=10,
        interpolation=1,
        border_mode=0,
        p=0.5
```
```
bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_visibility=0.6,
            filter_lost_elements=True),
```
Version: 0.3.3

My original annotation of bboxes is correct. I think such `ValueError `can occur after `ShiftScaleRotate` when it modifies some of bboxes too much. 

Can you please give some advice how to avoid such error?

**Comment by vadik6666** [comment]
Hmm, when remove all albumentations except HFlip, I still get such Error, but without any albumentations everything is OK.

**Comment by vadik6666** [comment]
Currently fixed it by changing [this](https://github.com/albu/albumentations/blob/master/albumentations/core/composition.py#L156) line from
`p.preprocess(data)`
to
```
try:
    p.preprocess(data)
except:
    print('data:', data)
```
This is костыль, and it doesn't augment some amount of images, but it works :crab:.

**Comment by albu** [comment]
seems like a problem is in your data format. please send us few data points (boxes for one failing image should be enough)

**Comment by whuhangzhang** [comment]
@albu Hi.albu, thanks for your great work! I also have the same problem. I output the intermediate results for your reference：
``
'bboxes': [[478.1674, 278.39395, 686.9629, 418.23538, 0], [435.63498, 469.1454, 477.52298, 525.2108, 1], [397.6136, 536.16614, 441.43488, 590.94275, 2], [462.70108, 572.8987, 505.2335, 625.742, 3], [498.78918, 507.166     78, 541.3216, 559.36566, 4], [401.48016, 68.30963, 423.3908, 85.06482, 5], [389.88043, 73.46507, 426.61298, 97.309, 6], [386.01385, 80.55381, 422.74637, 103.7533, 7], [381.50284, 86.998116, 418.8798, 110.84204, 8], [374.4141, 93.44241, 415.65765, 118.5752, 9], [370.54752, 389.88043, 417.59094, 422.74637, 10],      [376.34738, 409.85776, 408.5689, 432.41284, 11], [359.5922, 419.52423, 366.0365, 426.61298, 12], [366.0365, 420.16867, 382.14725, 435.63498, 13], [380.21396, 431.12396, 399.54688, 445.30145, 14], [352.50345, 429.19067, 376.34738, 447.23474, 15], [378.28067, 444.657, 393.10257, 456.90118, 16], [392.45816, 449.8     1247, 392.45816, 449.81247, 17], [347.99246, 440.146, 366.68094, 454.3235, 18], [332.52612, 397.6136, 364.74765, 431.7684, 19], [318.99307, 438.85715, 380.8584, 478.1674, 20], [315.1265, 445.9459, 340.25928, 463.98993, 21], [345.41473, 463.98993, 376.99182, 485.25613, 22], [606.40906, 542.6105, 657.9635, 579.3     4296, 23], [552.9213, 641.8527, 574.18756, 659.8968, 24], [581.27625, 658.6079, 605.1202, 676.652, 25], [599.9648, 558.7212, 655.3858, 593.52045, 26], [589.6539, 578.69855, 645.0749, 612.8534, 27]]
``

**Comment by albu** [comment]
please ensure that you are on the latest version of albumentation and that your bounding box format is correct. https://albumentations.readthedocs.io/en/latest/api/core.html#albumentations.core.composition.BboxParams
also bounding boxes coordinates must not exceed image dimensions.

**Comment by averyehorvath** [comment]
Before you normalize your boxes do:

width = 1 if width < 1 else width
height = 1 if height < 1 else height

worked for me

**Comment by yzbx** [comment]
try to remove bbox with width/height=0, just set `min_area=1` in BboxParams
view https://albumentations.ai/docs/api_reference/core/composition/#albumentations.core.composition.BboxParams for detail
