### ISSUE TITLE
Propose to save used parameters and was transform applied or not as a parameter

### ISSUE THREAD

**Issue by IlyaOvodov** [albumentations-team/albumentations#381]
Sometimes it is nesessary to know was a particular transform applied or not and with what randomly chosen parameters.
For instance, flips can be an acceptable transform for classification or detection task provided that labels would be changed in a proper way (say, "left turn" road sign should be changed to "right turn" if hflip was applied).
I dont thing it is worth handling all such cases by the Albumentations library itself and sometimes it is better to leave it for user side.

**Comment by IlyaOvodov** [comment]
Properties `was_applied` and `params` were added to all transforms to keep an information about was this transform applied and with what parameters.
Usage examle:
```python
aug_res = self.albumentations(image=img, bboxes=rects)
aug_bboxes = aug_res['bboxes']
for t in self.albumentations.transforms:
    if isinstance(t, T.VerticalFlip) and t.was_applied:
        aug_bboxes = [vflip_rect_label(b) for b in aug_bboxes]
    if isinstance(t, T.HorizontalFlip) and t.was_applied:
        aug_bboxes = [hflip_rect_label(b) for b in aug_bboxes]
```

**Comment by IlyaOvodov** [comment]
See discussion under PR #382 
Probably required functionality will be available after merge of PR #350

**Comment by albu** [comment]
I've added an example how new replay mode works. https://github.com/albu/albumentations/blob/deterministic_poc/notebooks/replay.ipynb 

As for 
> For instance, flips can be an acceptable transform for classification or detection task provided that labels would be changed in a proper way (say, "left turn" road sign should be changed to "right turn" if hflip was applied).
You can use `get_params_dependent_on_targets` and write your own flip which flips only applicable signs.

Something like this:
```
class SignHorFlip(HorizontalFlip):
    def __init__(self, ignored_labels=[], always_apply=False, p=1.):
        super(SignHorFlip, self).__init__(always_apply=always_apply, p=p)
        self.ignored_labels = ignored_labels

    def get_params_dependent_on_targets(self, params):
        label = params['label']
        if label in self.ignored_labels:
            return {'apply': False}
        return {'apply': True}

    def targets_as_params(self):
        return ['label']

    def apply(self, img, apply=True):
        if not apply:
            return img
        if img.ndim == 3 and img.shape[2] > 1 and img.dtype == np.uint8:
            return F.hflip_cv2(img)
        else:
            return F.hflip(img)
```

Hope that helps

**Comment by albu** [comment]
```
class SignHorFlip(HorizontalFlip):
    def __init__(self, label_flipping={'turn_left': 'turn_right', 'turn_right': 'turn_left'}, always_apply=False, p=1.):
        super(SignHorFlip, self).__init__(always_apply=always_apply, p=p)
        self.label_flipping = label_flipping

    def apply_to_label(self, label, **params):
        return self.label_flipping.get(label, label)

    @property
    def targets(self):
        return {
            **self.targets,
            'label': self.apply_to_label
        }
```

**Comment by IlyaOvodov** [comment]
I suppose  #350 closes needs proposed here. If one needs postmortem information about what augmentations were applied (and with what params), he can replace `Compose` class with `ReplayCompose` and then write somthing like:
```
       aug_res = self.albumentations(image=aug_img, bboxes=rects)
       aug_bboxes = aug_res['bboxes']
       for t in aug_res['replay']['transforms']:
             if t['__class_fullname__'].endswith('.HorizontalFlip') and t['applied']:
                    aug_bboxes = [rect_hflip(b) for b in aug_bboxes]
```
Also approach with inheritance of HorizontalFlip class proposed above solves the problem.
So I close an issue.
