### ISSUE TITLE
Benchmarks against Nvidia DALI

### ISSUE THREAD

**Issue by mratsim** [albumentations-team/albumentations#408]
Nvidia DALI is currently probably the fastest data augmentation library all around, especially for jpeg's image as those can be directly decompressed on GPU.

All their augmentations are implemented using either C++/Cuda C++ or the C++ OpenCV API so without any Python overhead as well.

Benches against DALI CPU and DALI GPU for the relevant augmentations would be nice:
https://github.com/NVIDIA/DALI

**Comment by vdaita** [comment]
It really helps if you are augmenting large dataset in something like Google Colab, and you are able to use this with the GPU to accelerate your augmentations, it really helps.

**Comment by ismael-elatifi** [comment]
+1 for this very good suggestion !
Would be interesting to see the speed comparaison between albumentation and DALI at least for the most common augmentations.

**Comment by ternaus** [comment]
No plans to add DALI
