### ISSUE TITLE
AttributeError: module 'albumentations' has no attribute 'Lambda'

### ISSUE THREAD

**Issue by bluesky314** [albumentations-team/albumentations#414]
Am getting `AttributeError: module 'albumentations' has no attribute 'Lambda'` when I try to use albumentations.Lambda even though it is clearly listed in documentation. I am using 0.1.12 on Colab. How to fix? ( If I have to upgrade please let me know how, I did pip upgrade before)

**Comment by Dipet** [comment]
Try this command:
`!pip install git+https://github.com/albu/albumentations.git --no-cache-dir`

**Comment by KDcx35** [comment]
> Try this command to upgrade library:
> `!pip install -U git+https://github.com/albu/albumentations --no-cache-dir`

Thank you!

**Comment by sagar-m** [comment]
Hi, were you able to solve? I am getting a very similar error. Thank you.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-44-cc5622792842> in <module>
      2     return tuple(zip(*batch))
      3 
----> 4 train_dataset = WheatDataset(train_df, DIR_TRAIN, get_train_transform())
      5 valid_dataset = WheatDataset(valid_df, DIR_TRAIN, get_valid_transform())
      6 

<ipython-input-39-6bc9f86d57ba> in get_train_transform()
      2 
      3 def get_train_transform():
----> 4     return A.compose([
      5         A.Flip(0.5),
      6         ToTensorV2(p=0.1)

AttributeError: module 'albumentations' has no attribute 'compose'

**Comment by Dipet** [comment]
Python code case sensitive. `A.Compose` not `A.compose`

**Comment by amenevatanparast** [comment]
hi 
I have this problem "module 'albumentations' has no attribute 'Lambda"
I test 
!pip install -U albumentations>=0.3.0 --user 
!pip install -U git+https://github.com/albu/albumentations --no-cache-dir
pip install --upgrade albumentations
pip install --upgrade git+https://github.com/albumentations-team/albumentations

but the error  is still 
please help me

**Comment by Dipet** [comment]
Check that albumentations upgraded correctly and you use correct interpreter and environment.
Try to print library version `print(albumentations.__version__)`

**Comment by SunAriesCN** [comment]
Hi
I get problem as this
```
AttributeError: module 'albumentations' has no attribute 'MediaBlur'

print(A.__version__)
1.0.0
```

**Comment by mouni13r** [comment]
!pip install --force-reinstall albumentations==1.0.3
this solveed my error

**Comment by niyazikaracalar** [comment]
I try everything u said But I can't solve the problem.
![image](https://user-images.githubusercontent.com/83755124/164872572-134b696c-c3b8-4d63-a323-b7bf198656b0.png)

**Comment by niyazikaracalar** [comment]
Thanks, it s work!!
