### ISSUE TITLE
Cutout does nothing

### ISSUE THREAD

**Issue by igriffer** [albumentations-team/albumentations#418]
## 🐛 Bug

Cutout with max_h_size == 1 or max_w_size == 1 does nothing

## To Reproduce

aug = Cutout(max_h_size=1, max_w_size=80, p=1) 
augment_and_show(aug, image)

## Expected behavior

8 black lines with height 1px

## Environment

 - Albumentations version (e.g., 0.1.8): 0.3.3
 - Python version (e.g., 3.7): 3.6.8
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by skmatz** [comment]
First, `albumentations.Cutout` has been deprecated.
Use `albumentations.CoarseDropout` as in the warning.

**Comment by skmatz** [comment]
I also found the cause of the bug.
The bug occurs not only when `max_h_size == 1` or `max_w_size == 1`, but also when they are odd.

**Comment by Dipet** [comment]
Do not use Cutout it is deprecated. Use [CoarseDropout](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.CoarseDropout)
