### ISSUE TITLE
Unexpected behavior of CoarseDropout

### ISSUE THREAD

**Issue by igriffer** [albumentations-team/albumentations#419]
## 🐛 Bug

CoarseDropout with width or height in [1, 1] generates lines with width, height in [1, 3]

## To Reproduce

aug = CoarseDropout(max_height=1, max_width=100, min_height=1, min_width=100, p=1)
augment_and_show(aug, image)

## Expected behavior

Black horizontal lines with height == 1

## Environment

 - Albumentations version (e.g., 0.1.8): 0.3.3
 - Python version (e.g., 3.7): 3.6.8
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by ternaus** [comment]
@igriffer Cannot reproduce it
