### ISSUE TITLE
Mark deprecated transforms in README and docs

### ISSUE THREAD

**Issue by Dipet** [albumentations-team/albumentations#427]
1. Update docstrings for deprecated transforms.
**Related files:** `albumentations/augmentations/transforms.py`
2. Mark deprecated functions in README using ` [Depricated]` suffix.
**Related files:** `tools/make_transforms_docs.py`

**Comment by Soniyanayak51** [comment]
Hi, I would like to work on this. How do you want the docstrings to be updated?

**Comment by Dipet** [comment]
See #596

**Comment by ternaus** [comment]
Fixed
