### ISSUE TITLE
Feature request: add hypothesis library to tests

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#442]
https://hypothesis.readthedocs.io/en/latest/ works pretty well for finding corner cases.

I propose to extend the existing unit test functionality with the tests based on the Hypothesis library.

**Comment by gsvalgreen** [comment]
Do you mind if I try? I used hypothesis recently to test rules for a policy system.

**Comment by ternaus** [comment]
Go ahead :)
