### ISSUE TITLE
kornia collaboration

### ISSUE THREAD

**Issue by edgarriba** [albumentations-team/albumentations#452]
hi, I'm maintaining [kornia](www.kornia.org) an opencv like vision library for PyTorch.

We are discussing to provide some low level operators that could be useful for data augmentation using raw tensors. I believe that high level libraries like albumentations (and like others, see fastai ;) could be potential consumers of our low level operators. Would you be interested in starting a collaboration to integrate kornia into your backend stack ?

Cheers,
Edgar

**Comment by BloodAxe** [comment]
@edgarriba greetings Edgar!

Definitely! Having GPU-accelerated image augmentation is one of our areas of interest and is pretty often asked by our users. There is already some study has been done by @Dipet (using PyTorch API) and myself (for OpenCL) and we really would appreciate your input on this. 

We do have slack channel in `ods.ai`, where we can have more interactive discussion or you can drop me an email `ekhvedchenya@gmail.com` to schedule a call :)

**Comment by edgarriba** [comment]
hi @BloodAxe and @Dipet . Great! so we had an internal meeting and we decided that we will implement some of the existing functionalities using raw pytorch operators to leverage differentiable data augmentation. We will try to align with albumentations API and potentially with torchvision too.

Do you have any public roadmap so that we can join efforts ? I've seen that @Dipet already started to dig into kornia.

Would be great to brainstorm between frameworks so that both we can coexist instead of mutual excluding ourselves :D

Please check our updates: https://github.com/kornia/kornia/issues/312
Board meeting notes: https://github.com/kornia/kornia/wiki/2019#2019-10-31
