### ISSUE TITLE
CropNonEmptyMaskIfExists with Bounding Boxes

### ISSUE THREAD

**Issue by johanneskpp** [albumentations-team/albumentations#461]
Hello,

i tried to use the CropNonEmptyMaskIfExists-method with bounding boxes but it always says that it needs a mask-parameter. Is there a way to crop images to use this method with bounding boxes?

**Comment by Dipet** [comment]
Hi!
Is simplest way to use CropNonEmptyMaskIfExists for bboxes it is create mask from your bboxes like this:
```
mask = np.zeros(image.shape[:2], dtype=np.uint8)
for x1, y1, x2, y2 in bboxes:
    mask[y1:y2, x1:x2] = 1

result = transforms(image=image, mask=mask, bboxes=bboxes)
image = result['image']
bboxes = result['bboxes']
```

**Comment by Palushok** [comment]
Hello, this problem is still relevant. 
![Screenshot from 2020-10-12 16-52-32](https://user-images.githubusercontent.com/16117657/95754236-664a0500-0cab-11eb-9552-fabbe77f1dd9.png) The readme data is misleading.

**Comment by ternaus** [comment]
Works as expected https://explore.albumentations.ai/transform/CropNonEmptyMaskIfExists
