### ISSUE TITLE
Video Albumentations

### ISSUE THREAD

**Issue by rsomani95** [albumentations-team/albumentations#465]
Thank you for this library!

I was wondering if you plan on adding albumentations for videos?
For single frames (without bbox, etc.), this is fairly straightforward. An example, extracted from [this Jupyter notebook](https://github.com/rsomani95/video-classification/blob/master/notebooks/02_tfms_albumentations.ipynb):

```python
tfms = A.Compose([
        A.HorizontalFlip(p=0.5),
        A.ShiftScaleRotate(rotate_limit=15, p=0.3),
        A.ChannelDropout(p=0.1),
        A.RandomRain(p=0.1),
        A.GridDistortion(p=0.3)
    ], p=0.5)


def aug_video(vid, tfms):
    seed = random.randint(0,99999)
    aug_vid = []
    for x in vid:
        random.seed(seed)
        aug_vid.append((tfms(image = np.asarray(x)))['image'])
    return torch.from_numpy(np.stack(aug_vid))
```
![Screenshot 2019-11-08 at 1 59 53 PM](https://user-images.githubusercontent.com/17111474/68461354-0ee81d00-0230-11ea-8863-5ad5e5ed67fe.png)

**Comment by ternaus** [comment]
You may apply the same transform to a set of videos through the additional targets functionality: 

https://albumentations.ai/docs/examples/example_multi_target/

**Comment by ternaus** [comment]
@rsomani95 You may apply transform to a target "images" which is a list of frame like:


```python

tfms = A.Compose([
        A.HorizontalFlip(p=0.5),
        A.ShiftScaleRotate(rotate_limit=15, p=0.3),
        A.ChannelDropout(p=0.1),
        A.RandomRain(p=0.1),
        A.GridDistortion(p=0.3)
    ], p=0.5)


def aug_video(vid, tfms):      
    
    transformed = tfms(images=vid)
    
    aug_vid = transformed["images"]
    return torch.from_numpy(np.stack(aug_vid))

```
