### ISSUE TITLE
ToTensorV2 assumes image dimension as 3

### ISSUE THREAD

**Issue by selimarikan** [albumentations-team/albumentations#470]
## 🐛 Bug

albumentations.pytorch.ToTensorV2 assumes that input image has 3 dimensions since it calls

`torch.from_numpy(img.transpose(2, 0, 1))`

The transpose operation throws a ValueError axes don't match array when any image other than 3 dimensional is provided.

## To Reproduce

1. Create a PyTorch loader, similar like here: https://github.com/albu/albumentations/blob/master/notebooks/migrating_from_torchvision_to_albumentations.ipynb
2. Apply the transformation in __getitem__ self._transforms(image=image)['image']

## Expected behavior

Transpose and ToTensor calls should be separated. It blocks users from using grayscale or any high dimensional input data.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.3
 - Python version (e.g., 3.7): 3.6.8
 - OS (e.g., Linux): CentOS 7
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by vfdev-5** [comment]
@selimarikan what format of images you have ?

Well, in the readme of the library it also says "The library works with images in HWC format." :)

**Comment by Dipet** [comment]
This error will be fixed for grayscale images in #528

**Comment by Dipet** [comment]
Also library works only with grayscale images in `HW` or RGB images in `HWC` format. So we have 2 or 3 dimensions

**Comment by selimarikan** [comment]
> @selimarikan what format of images you have ?
> 
> Well, in the readme of the library it also says "The library works with images in HWC format." :)

I have greyscale images and I would say this is a common use case.
It is also good to keep in mind that TIFF images can have much more layers (>3) and some CNN-based detectors can make use of these multilayer TIFFs.

Best thing would be to handle this dynamically based on layer/channel count.

**Comment by AntixK** [comment]
Hi,
May I know what is the rationale behind transposing? What if my dataset has the correct form already like CWH?
For example, I have some preprocessed dataset in which the channel was the first dimension and now, to call ToTensorV2, I have to transpose the data before passing it. 

Can we at least have a flag that indicated if we need to transpose? Thanks!

**Comment by Dipet** [comment]
Library works on images in HWC format, so if you use library with images in CWH format, something wrong.

**Comment by AntixK** [comment]
Yes, I get that but a function named `ToTensor` must do.. just that.. convert to tensor. Adding extra (undocumented) functionality only leads to confusion.

I already have a pre-processed dataset in CHW format and I would like to use that for TTA. Using the current `ToTensorV2` unnecessarily requires me to transpose the channels just to pass to the function. 
Of course, I can have a workaround by having my own ToTensor, but doesn't that forego the idea of `ToTensorV2` in the first place?

**Comment by Dipet** [comment]
If you need only to convert image to tensor you has function `torch.from_numpy`. This transform is necessary to convert images from the library format to the torch image format. And torch work with images in `CHW`, but library works in `HWC`, so we need transpose.

**Comment by nmaffe** [comment]
```x = np.random.rand(256, 256)```
```tr = A.Compose([ToTensorV2()])```
```z = tr(image=x)['image']```
```z.shape --> torch.Size([1, 256, 256])```

According to the official documentation: "If the image is in HW format (grayscale image), it will be converted to pytorch HW tensor." I think it should be corrected to "... to pytorch CHW, C=1".
