### ISSUE TITLE
bbox support for ElasticTransform, GridDistortion and OpticalDistortion

### ISSUE THREAD

**Issue by Dipet** [albumentations-team/albumentations#474]

**Comment by flyingmrwang** [comment]
add keypoints support since piecewiseAffine is pretty slow and recommended elasticTransform does not support keypoints.

**Comment by ternaus** [comment]
@flyingmrwang Keypoints added to [ElasticTransform](https://explore.albumentations.ai/transform/ElasticTransform)

**Comment by ternaus** [comment]
@flyingmrwang 

bboxes and keypoints are now supported by ElasticTransform, GridDistortion and OpticalDistortion

You may check at:

https://explore.albumentations.ai/transform/ElasticTransform

https://explore.albumentations.ai/transform/GridDistortion

https://explore.albumentations.ai/transform/OpticalDistortion
