### ISSUE TITLE
Add new transforms from https://arxiv.org/abs/1903.12261

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations#477]
There is a set of Pixel Level transforms that is used in the work `Benchmarking Neural Network Robustness to Common Corruptions and Perturbations`

The authors also share the code => we can absorb some transforms that they have into the library.

https://github.com/hendrycks/robustness/blob/master/ImageNet-C/create_c/make_imagenet_c.py

 - [x] ShotNoise
 - [x] Defocus
 - [x] GlassBlur
 - [x] Zoom Blur
 - [x] Pixelate
 - [ ] Frost
 - [x] Spatter

**Comment by ternaus** [comment]
Pixelate in the paper == Dowscale with `cv2.INTER_NEAREST`

**Comment by ternaus** [comment]
ShotNoise in paper == ISONoise in the Library

**Comment by akarsakov** [comment]
@ternaus I'd like to take up this enhancement.

**Comment by akarsakov** [comment]
Hi @ternaus,

Frost transform requires precalculated images with ice crystals. 
What's the best way of storing this images in albumentations code (all images require ~2MB)?

**Comment by Dipet** [comment]
It seems that in this transformation we can use any image templates..  I think it's best to name this transformation as a `TemplateTranform`. And give the opportunity to set any image as a template.

**Comment by akarsakov** [comment]
That's great point! 
Moreover looks like it would be better to allow setting list of desired images as template and pick the random one.

**Comment by p4rallax** [comment]
Has this been finished?

**Comment by akarsakov** [comment]
@p4rallax The code is finished (please see PRs mentioned in this issue) but it haven't merged to master yet.

**Comment by zetyquickly** [comment]
Based on the PRs seems like the implementation is actually missing Frost only

**Comment by ternaus** [comment]
It looks like it was decided that Frost is the same as Template but with frost images.

Although this non-obvious fast should obviously covered in the blog post / tutorial.
