### ISSUE TITLE
stacked images augmentation (4,256,256,3)

### ISSUE THREAD

**Issue by ninjakx** [albumentations-team/albumentations#481]
I have stacked 4 brain MRI t1, t1c, t2, flair together to create (2,256,256,3)
How to perform augmentation?

**Comment by albu** [comment]
you need to stack on last dimension or pass masks separately. https://github.com/albu/albumentations/blob/master/notebooks/example_multi_target.ipynb

**Comment by ninjakx** [comment]
@albu : But I want my stacked images to have the same augmentation.
