### ISSUE TITLE
Order of Execution

### ISSUE THREAD

**Issue by MentalGear** [albumentations-team/albumentations#484]
## 📚 Documentation

Is the order of execution for augmentations sequentially as provided by filter order, or is it applied at random ?

Example:
```
filters = [

           PadIfNeeded(
                min_height=biggestSide,
                min_width=biggestSide,
                border_mode=0,
                value=trimmedImage.getpixel( (0,0) ),
                always_apply=True,
                p=1.0),

            RandomShadow( p=0.5, shadow_roi=(0, 0, 1, 1), num_shadows_lower=1, num_shadows_upper=2, shadow_dimension=random.randint(1,10) ),


          ]

augment = Compose ( filters )

```
Will this always apply the padding before the shadow overlay, or can it also happen that the shadow is applied before padding is done, resulting in an augmentation with white edges?

**Comment by albu** [comment]
order of execution is direct
