### ISSUE TITLE
Result error when augment with IAAPiecewiseAffine on detection task 

### ISSUE THREAD

**Issue by cswwp** [albumentations-team/albumentations#485]
Such as IAAPiecewiseAffine(p=1),
and the result follows:
![image](https://user-images.githubusercontent.com/11901683/70038790-cf74dc80-15f3-11ea-98cf-726cb498c138.png)

Absolutely, the bbox of dog is error, Is this method not implement correctly?

**Comment by ternaus** [comment]
IAAPiecewiseAffine deprecated, use [PiecewiseAffine](https://explore.albumentations.ai/transform/PiecewiseAffine) instead
