### ISSUE TITLE
How resize with adaptive h/w ration

### ISSUE THREAD

**Issue by cswwp** [albumentations-team/albumentations#486]
How resize with adaptive h/w ratio, just give height or width, the ALBU auto calculate the width or height with h/w ratio

**Comment by albu** [comment]
https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomSizedCrop
https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomResizedCrop
