### ISSUE TITLE
OverflowError in RandomSunFlare

### ISSUE THREAD

**Issue by wolterlw** [albumentations-team/albumentations#489]
## 🐛 Bug

An Overflow error randomly appears in 
`cv2.circle(overlay, (x, y), rad3, (r_color, g_color, b_color), -1)`
inside function add_sun_flare

## To Reproduce

1. add `A.RandomSunFlare(src_radius=100, p=0.2)` to the transforms sequence
2. wait for randomness to spit out this error

## Environment

 - Albumentations version 0.4.3:
 - Python 3.7:
 - OS Ubuntu 18.04
 - installed with pip

**Comment by tavein** [comment]
Had the same bug.

My code:
```
        RandomSunFlare(
            flare_roi=(0, 0, 1, 1), 
            src_radius=random.randint(10, 200),
            p=.25,
        )
```

Environment
- Albumentations version 0.4.4
- Python 3.5.3
- OS Debian GNU/Linux 9.11 (stretch)
- pip installation from repo (`pip install git+https://github.com/albu/albumentations`)

**Comment by ternaus** [comment]
Fixed
