### ISSUE TITLE
Add AdditiveNoise

### ISSUE THREAD

**Issue by Dipet** [albumentations-team/albumentations#501]
~~1. Add `AdditiveNoise` like `MultiplicativeNoise`.~~
2. Add warning message for `shift_hsv`: `Do not use shift_hsv for grayscale image. Use AdditiveNoise with argument elementwise=False.`

**Comment by akarsakov** [comment]
Hi, @Dipet !
I would like to take up this enhancement.

**Comment by Dipet** [comment]
Hmm, at this time I am not sure, that we need `AdditiveNoise`, bacause at this time the same way works `GaussNoise`

**Comment by Dipet** [comment]
A warning has also been added into `shift_hsv`. So this issue is outdated.

**Comment by akarsakov** [comment]
Ok, thank you!
