### ISSUE TITLE
 ImportError: cannot import name 'BboxParams' (in albumentations/notebooks/example_bboxes.ipynb)

### ISSUE THREAD

**Issue by kitarikes** [albumentations-team/albumentations#502]
## To Reproduce

1. !pip install -U git+https://github.com/albu/albumentations on google colab
2. from albumentations import BboxParams (like 1st cell in albumentations/notebooks/example_bboxes.ipynb)
3. error occured :(  but, run except BboxParams module
```
ImportError                               Traceback (most recent call last)
<ipython-input-5-374b6504bebe> in <module>()
----> 1 from albumentations import BboxParams

ImportError: cannot import name 'BboxParams'

NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```

## Environment

 - Albumentations version is latest
 - on Google colab
 - How you installed albumentations ( `pip`, source): !pip install -U git+https://github.com/albu/albumentations

**Comment by kitarikes** [comment]
! pip install -U git + https: //github.com/albu/albumentations
After that, I was able to import BboxParams !
I don't know why : (

**Comment by liangxiao05** [comment]
hi,do you know how to fix when use conda install ? I met the same error.
