### ISSUE TITLE
Segmentation fault hapening when applying augmentation

### ISSUE THREAD

**Issue by vmgustavo** [albumentations-team/albumentations#509]
## 🐛 Bug

Segmentation fault is hapening when I try to use GridDistortion and ElasticTransform augmentations. The problem does not happen in every execution.

## To Reproduce

Minimal reproducible example:
```python
import cv2
import numpy as np
from albumentations import ElasticTransform, GridDistortion, OneOf, Compose


class DataAug:
    @staticmethod
    def get_augs():
        grid = GridDistortion(
            distort_limit=0.2,
            interpolation=cv2.INTER_NEAREST,
            border_mode=cv2.BORDER_CONSTANT,
            value=0,
            always_apply=True
        )
        elast = ElasticTransform(
            alpha_affine=20,
            interpolation=cv2.INTER_NEAREST,
            border_mode=cv2.BORDER_CONSTANT,
            value=0,
            always_apply=True
        )
        return OneOf([
            OneOf([grid, elast], p=1),
            Compose([grid, elast], p=1)
        ], p=1)

    def apply(self, image, mask):
        aug = self.get_augs()
        res = aug(image=image.astype('uint8'), mask=mask.astype('uint8'))
        return res['image'], res['mask']


if __name__ == '__main__':
    input_a = np.zeros((1, 512, 512, 3))
    input_b = np.zeros((1, 512, 512, 1))

    image, mask = DataAug().apply(image=input_a[0, :, :, :], mask=input_b[0, :, :, 0])

    print(image.shape, mask.shape)
```

## Expected behavior

Code should execute without errors and print the shape of the augmented image and mask.

## Environment

 - Albumentations version: 0.4.3
 - Python version: 3.6.9
 - OS: Ubuntu 18.04.2 LTS
 - How you installed albumentations: Pip

---

EDIT:
Apparently it happens less frequently  when using python 3.6.8. I tried in 4 different machines (all ubuntu using conda virtual env) and this was the result:

* opencv 4.1.1 python 3.6.8 albu 0.4.3 > OK
* opencv 4.1.2 python 3.6.9 albu 0.4.3 > not OK
* opencv 4.1.2 python 3.6.8 albu 0.4.3 > OK
* opencv 4.1.2 python 3.6.9 albu 0.4.3 > not OK (but less frequent)

---
EDIT:
Using the trace method from this answer the last lines printed are:
```
line, /home/gustavomaia/miniconda3/envs/test/lib/python3.6/site-packages/albumentations/augmentations/functional.py:172
line, /home/gustavomaia/miniconda3/envs/test/lib/python3.6/site-packages/albumentations/augmentations/functional.py:180
Segmentation fault (core dumped)
```

**Comment by vmgustavo** [comment]
Apparently it happens less frequently  when using python 3.6.8. I tried in 4 different machines (all ubuntu using conda virtual env) and this was the result:

* opencv 4.1.1 python 3.6.8 albu 0.4.3 > OK
* opencv 4.1.2 python 3.6.9 albu 0.4.3 > not OK
* opencv 4.1.2 python 3.6.8 albu 0.4.3 > OK
* opencv 4.1.2 python 3.6.9 albu 0.4.3 > not OK (but less frequent)

**Comment by vmgustavo** [comment]
Using the trace method from [this answer](https://stackoverflow.com/a/2663863/6763224) the last lines printed are:
```
line, /home/gustavomaia/miniconda3/envs/test/lib/python3.6/site-packages/albumentations/augmentations/functional.py:172
line, /home/gustavomaia/miniconda3/envs/test/lib/python3.6/site-packages/albumentations/augmentations/functional.py:180
Segmentation fault (core dumped)
```

**Comment by lstefanou** [comment]
I had the same issue; using this config:
```opencv 4.1.2 python 3.6.8 albu 0.4.3```
solved it (only change in my case was downgrading Python).

So probably some weird interplay happening between Python/OpenCV?

**Comment by Gawajn** [comment]
I had a similar problem some time ago. In my case OpenCv caused the segmentation fault. Downgrading OpenCV got rid of the segmentation fault

**Comment by Dipet** [comment]
Problem in OpenCv 4.1.2. I am can not catch this error in 4.1.1 and 4.2.0
