### ISSUE TITLE
Reason for making ReplayCompose not serializable?

### ISSUE THREAD

**Issue by jmerkow** [albumentations-team/albumentations#534]
What is the reason that `ReplayCompose` specifically broke serialization?
Looking at the code, I do not see any reason why the ability to replay would mean that serialization doesn't work. Given the fact that `ReplayCompose` is used in the exact same way as `Compose`, only it allows you to call `replay` rather than `__call__`, this doesn't make sense.

Consider a (typical) example usage:
```
images = [
   cv2.imread('./images/image_1.jpg'), 
   cv2.imread('./images/image_2.jpg'), 
   cv2.imread('./images/image_3.jpg')
] # as many images as you want

transform = A.ReplayCompose([
    A.Resize(512, 512, always_apply=True),
    A.RandomCrop(200, 200, always_apply=True),
    A.OneOf([
        A.RGBShift(), 
        A.HueSaturationValue()
    ]),
])

replay = None
aug_images = []
for image in images:
    if replay is None:
        a = transform(image=image)
        replay = a.pop('replay')
    else:
       a = transform.replay(replay, image=image)
    aug_images.append(a)
```

The replay parameters aren't stored anywhere in `ReplayCompose` the only addition is that it adds the `'replay'` dictionary to the output, which is typically popped or ignored (it will mess with torch.utils.data.Dataloader collation).  Since the state is not stored on the object, there is no real difference with `ReplayCompose` and `Compose` from a serialization/de-serialization standpoint.
In fact, the only parameter missing is `save_key` which can easily be added.  I've been using this in my code and it all works fine. 
It looks like the code to break serialization added [here](https://github.com/albumentations-team/albumentations/pull/350/commits/7febf9f9f33a70832a7c8033cb48a903c8bc4772), possibly with the intention of returning to it later?

I was considering contributing the changes to make `ReplayCompose` serializable. However, since it was specifically prevented and given the low hurdle to make it serializable, I wanted to check why this was before moving forward.

**Comment by albu** [comment]
hi @jmerkow I don't really remember reasons why `ReplayCompose` is not serializable so you can try to fix it.
