### ISSUE TITLE
RandomScale, ShiftScaleRotate bug

### ISSUE THREAD

**Issue by dselivanov** [albumentations-team/albumentations#548]
## 🐛 Bug

The logic in the `RandomScale`, `ShiftScaleRotate` is flawed - scale has a bias towards upscale. As can be seen from the [code](https://github.com/albumentations-team/albumentations/blob/bd2c655bc753a72cb48b49eceeabc8dbbc22b9d8/albumentations/augmentations/transforms.py#L568), scale is defined as `scale = uniform([1 - scale_limit + bias, 1 + scale_limit + bias]) - bias`. 

Let's take an example of `scale_limit =(0.5, 2)`:

1. formula above means that we will uniformly sample from [1.5, 3]. which means 2/3 of the sample will be within the range [2, 3] and 1/3 will be within the range [1.5, 2]. With the subtraction of bias this translates into 2/3 chance to upscale and 1/3 chance to downscale.
1. it is unclear what is the purpose of `bias` here, looks pointless (attempt to mitigate the issue above?).

**Comment by Dipet** [comment]
The initial assumption is incorrect.
Look how work `to_tuple` [method](https://github.com/albumentations-team/albumentations/blob/bd2c655bc753a72cb48b49eceeabc8dbbc22b9d8/albumentations/core/transforms_interface.py#L16): 
Scale defined as: `scale = uniform([-scale_limit, scale_limit]) + bias`

**Comment by dselivanov** [comment]
> The initial assumption is incorrect.

What assumption, could you elaborate please? 

Say I want a random downscale or upscale within 2x of the image size. With the current logic:
- if `scale_limit = 1`. Then `scale` is a value within `[0, 2]`. And this is not what a user would expect. Will it work for values > 1? (what if I want augment within 3x of the image size?
- if `scale_limit = (-0.5, 1)` then `scale` is drawn as uniform `[-0.5, 1]` and result is a uniform `[0.5, 2]`. Which has a 2/3 chance to upscale and 1/3 to downscale. Which is not what user would expect.

Solution for a single `scale_limit` might be following:
```
scale = uniform(1, scale_limit) # upscale by default
if uniform(0, 1) < 0.5: # downscale 50%
  scale = 1 / scale
return scale
```

For two values we might need to sample 2 times - from upscale interval and from downscale interval. And then draw another binary value to choose whether to upscale or downscale.

**Comment by BloodAxe** [comment]
Thanks for your PR. Balanced upscale and downscale is important improvement. We may need some time to review your PR and end up with a solution that fixes this imbalance while keeping backward compatibility.

**Comment by aliab3d** [comment]
@BloodAxe I appreciate the team efforts for putting up such a great library for augmentations. I just want to re-raise the problem with **RandomScale** augmentation behaviour, since this still remains unresolved and can cause a silent bug in deep learning codebases, significantly harming training processes. 

As previously raised by others, with the current implementation, using a scale_limit =(0.5, 1.5), counter-intuitively scales data by a factor of (1.5, 2.5), thus always resulting in upsampled images. Reading the docs, one would expect this augmentation to uniformly pick a random value x in range (0.5,1.5) on the fly and resize the data according to the random scale selected.

**Comment by ogencoglu** [comment]
4 years and still this unintuitive behaviour is there.

**Comment by ternaus** [comment]
You can get the desired functionality by splitting overall sampling interval into pieces and applying `OneOf`

```python
balanced_scale_transform = A.OneOf([
  A.Affine(scale=(0.5, 1), p=0.5),
  A.Affine(scale=(1, 2), p=0.5)])
```

Added to the FAQ: https://albumentations.ai/docs/faq/#how-to-perform-balanced-scaling
