### ISSUE TITLE
HorizontalFlip and VerticalFlip inconsistent with multilabel masks

### ISSUE THREAD

**Issue by Geeks-Sid** [albumentations-team/albumentations#549]
## 🐛 Bug
Given a pair of image and its corresponding mask, the generated output for the augmented mask through augmentation is not the same as the image.(it is inconsistent) when HorizontalFlip() and VerticalFlip() are included in the augmentations.

## To Reproduce
The following snippet is a small dataloader that i usually use. Can't share code.

        self.aug = Compose([
                            RandomBrightnessContrast(),
                            HueSaturationValue(),
                            RandomGamma(),
                            GaussNoise(),
                            GaussianBlur(),
                            # HorizontalFlip(),
                            # VerticalFlip(),
                            ])
    def __getitem__(self, patient_id):
        image_path = os.path.join(self.df.iloc[patient_id, 0])
        z = np.load(image_path)
        image = z['patch']
        gt_data = z['patch_gt']
        # print("Pre : ", image.shape, gt_data.shape)
        gt_data = gt_data.swapaxes(0, 2)
        # print("Pre swapped: ", image.shape, gt_data.shape)
        # gt_data = gt_data[:4, :, :]
        if not self.valid:
            augmented = self.aug(image=image, mask=gt_data)
            image = augmented['image']
            gt_data = augmented['mask']
        image = (image/255).astype(np.float32)
        # print("Post Augment :", image.shape, gt_data.shape)
        image = image.swapaxes(0, 2)
        gt_data = gt_data.swapaxes(0, 2)
        # print("Post Augment Swapped: ", image.shape, gt_data.shape)
        image = torch.FloatTensor(image)
        gt_data = torch.FloatTensor(gt_data)
        #mask.shape = (5, 256, 256)
        #image.shape = (256, 256, 3)
        return image, gt_data

## Expected behavior
The augmentation over the images for horizontal and vertical flip should be working fine for both the mask and the image, but for some reason, there are errors in mask augmentations during horizontal and vertical flips.

Image shape : 256, 256, 3
Mask Shape : 5, 256, 256

## Environment

 - Albumentations version : 0.43.
 - Python version : 3.6
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

**Comment by BloodAxe** [comment]
Please provide a minimal reproducible case. From provided code snippet it is unclear what shape `image` and `gt_data` objects have. Since flip operation is working identically to image and mask targets, I don't see any reason why it would provide this behavior. Please, double check the shape of your input data.

**Comment by Dipet** [comment]
Masks format must be `HW` or `HWC`, but you use `CHW` format.
Do not use `swapaxes` before augmentations.

**Comment by Geeks-Sid** [comment]
Mask and Image dimensions have been mentioned as :

> Image shape : 256, 256, 3
> Mask Shape : 5, 256, 256

I have previously tried HWC instead of CHW but for some reasons the channels get swapped when using HWC in masks.

**Comment by Dipet** [comment]
As @BloodAxe said, please, give a minimal example to reproduce the problem.

**Comment by Geeks-Sid** [comment]
I shall post pictures
![Figure_1](https://user-images.githubusercontent.com/20500704/76113008-55e0f600-6009-11ea-87b5-ae8459700c77.png)
![Figure_2](https://user-images.githubusercontent.com/20500704/76113011-57122300-6009-11ea-8421-1262e047eb45.png)

In the first one, I have turned off the horizontalflip and the verticalflip, but in the second one, I have turned it on and you can see the results, the masks dont correspond to the cells.

`
        class TumorSegDataset(Dataset):
            def __init__(self, csv_file, params, valid=False):
            self.df = pd.read_csv(csv_file, header=0)
            self.params = params
            self.valid = valid
            self.aug = Compose([
                            RandomBrightnessContrast(),
                            HueSaturationValue(),
                            RandomGamma(),
                            GaussNoise(),
                            GaussianBlur(),
                            HorizontalFlip(),
                            VerticalFlip()
                            ])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, patient_id):
        image_path = os.path.join(self.df.iloc[patient_id, 0])
        z = np.load(image_path)
        image = z['patch']
        gt_data = z['patch_gt']
        # print("Pre : ", image.shape, gt_data.shape)
        gt_data = gt_data.swapaxes(0, 2)
        # print("Pre swapped: ", image.shape, gt_data.shape)
        # gt_data = gt_data[:4, :, :]
        if not self.valid:
            augmented = self.aug(image=image, mask=gt_data)
            image = augmented['image']
            gt_data = augmented['mask']
        image = (image/255).astype(np.float32)
        # print("Post Augment :", image.shape, gt_data.shape)
        image = image.swapaxes(0, 2)
        gt_data = gt_data.swapaxes(0, 2)
        # print("Post Augment Swapped: ", image.shape, gt_data.shape)
        image = torch.FloatTensor(image)
        gt_data = torch.FloatTensor(gt_data)

        return image, gt_data`

Sorry, but i dont know how to post code properly

**Comment by Dipet** [comment]
I am can not reproduce problem or I misunderstand the problem.
Before:
![image](https://user-images.githubusercontent.com/7512250/76153011-37493080-60d7-11ea-8d18-eeb2b750a1c3.png)
After:
![image](https://user-images.githubusercontent.com/7512250/76152896-09afb780-60d6-11ea-9a8e-9d4bcec4ed4e.png)

```
import numpy as np
import cv2 as cv
import json
from albumentations import *
import matplotlib.pyplot as plt
from pathlib import Path
import random

random.seed(0)
np.random.seed(0)


def polygon_to_mask(poly, image_shape):
    mask = np.zeros(image_shape[:2], dtype=np.uint8)
    poly = np.array(poly).reshape((1, -1, 2)).astype(np.int32)
    cv.drawContours(mask, poly, 0, 255, -1)
    return mask


def get_image(image_id, data, images_dir):
    image_data = None
    for sub_data in data['images']:
        if sub_data['id'] == image_id:
            image_data = sub_data
            break

    file_path = Path(images_dir).joinpath(image_data['file_name'])
    image = cv.imread(str(file_path), cv.IMREAD_COLOR)
    image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
    return image


def get_masks(image_id, anno, image_shape):
    masks = []
    for item in anno['annotations']:
        if item['image_id'] == image_id:
            segm = item['segmentation']
            if not isinstance(segm, list):
                continue
            masks.append(polygon_to_mask(segm, image_shape))
    return np.stack(masks, axis=-1)


def show_image_masks(image, masks):
    plt.subplot(231)
    plt.imshow(image)

    for i in range(5):
        mask = masks[..., i]
        mask *= 255
        plt.subplot(2, 3, 2 + i)
        plt.imshow(mask, cmap='gray')
    plt.show()

with open(r'D:\coco\annotations\instances_val2017.json', 'r') as file:
    coco = json.load(file)

image_id = 494869
images_dir = Path(r"D:\coco\val2017")
image = get_image(image_id, coco, images_dir)
masks = get_masks(image_id, coco, image.shape)

show_image_masks(image, masks)

augs = Compose([
    RandomBrightnessContrast(p=1),
    HueSaturationValue(p=1),
    RandomGamma(p=1),
    GaussNoise(p=1),
    GaussianBlur(p=1),
    HorizontalFlip(p=1),
    VerticalFlip(p=1),
    ])
res = augs(image=image, mask=masks)
show_image_masks(res['image'], res['mask'])
```

**Comment by Geeks-Sid** [comment]
Hey @Dipet  You are close.
can you just change the p=1 to p=0.5 and give it a try.
When you do p=1, it forces the probability to be 1 which in turn forces augmentation.

Let me know if you have trouble.

**Comment by Dipet** [comment]
With `p=0.5` all also is good. `p` does not used directly in transforms, this parameter works equal for all transforms inherited from `BasicTransform`.

**Comment by Dipet** [comment]
Can you experiment with my code and your data using different seeds and `p`?
Would be great if you can give to us 1 image with it is mask to reproduce problem using this code.

**Comment by Geeks-Sid** [comment]
[sample_patch.zip](https://github.com/albumentations-team/albumentations/files/4303789/sample_patch.zip)

Here is a sample patch, its a compressed npz, feel free to refer to m code and follow through me code to extract stuff.

Thanks for your help,
Siddhesh

**Comment by Dipet** [comment]
Problem with `swapaxes` use `np.transpose(gt_data, [1, 2, 0])`
