### ISSUE TITLE
Obsolete conda dependencies

### ISSUE THREAD

**Issue by fcakyon** [albumentations-team/albumentations#550]
Hello team albumentations, thank you so much for this awesome tool, I have been using it for all my computer vision trainings. 

When are you planning to publish the next stable release for pypi/conda? I'm currently pulling the latest version of this repo in my projects but it causes some inconsistencies as you can imagine :)

I couldn't find anything similar in the issues about this, so submitting it here as a new bug report.

Bests

**Comment by albu** [comment]
https://github.com/albumentations-team/albumentations/pull/552 done, thanks for noting!

**Comment by fcakyon** [comment]
Thanks a lot for the package release, especially for conda!

When I install the package with "conda install -c albumentations albumentations=0.4.5" and then run "from albumentations import Compose", I got an error:

File "/home/x/miniconda3/envs/x/lib/python3.6/site-packages/albumentations/__init__.py", line 8, in <module>
    from .augmentations.transforms import *
  File "/home/x/miniconda3/envs/x/lib/python3.6/site-packages/albumentations/augmentations/transforms.py", line 8, in <module>
    from skimage.measure import label
ModuleNotFoundError: No module named 'skimage'

Is "skimage" package missing in the conda package dependencies?

**Comment by albu** [comment]
@creafz do you have an idea what's happened?

**Comment by Dipet** [comment]
pip get scikit-image from when resolves imgaug dependencies.

**Comment by fcakyon** [comment]
are there any plans to fix this issue?

**Comment by ternaus** [comment]
ImgAug dependency removed
