### ISSUE TITLE
docs(benchmark): add keypoints-augmentation benchmark

### ISSUE THREAD

**Issue by AmitMY** [albumentations-team/albumentations#554]
## 📚 Documentation

In your documentation, you include the speed of image augmentations.
As you support keypoints augmentations as well, I think you are missing a benchmark on that type of data specifically.

`imgaug` for example, augments keypoints really slowly compared to how they augment images - see https://github.com/aleju/imgaug/issues/635 for benchmarks

In order for people (myself included) to know if it is worth to learn a new library, it is important to show how well you can handle this type of data (just keypoints, without images)

**Comment by Dipet** [comment]
Interesting. Before I did not think about bboxes and keypoints as bottleneck in transforms.

**Comment by mys007** [comment]
I haven't done any hard measurements but keypoints in albumentations are horribly slow because the operations are not vectorized at all. Would the maintainers be interested in changing this (i.e. to allow accepting numpy arrays, instead of lists of tuples)?

**Comment by Dipet** [comment]
I also thought to change the logic and change the default data type for keypoints and bboxes to `np.ndarray` and use vectorized operations. But I don't have enough time now to make it my own. I think it would be great if we will speed up this part of the code.
