### ISSUE TITLE
solt library version 0.1.9 has very different speed benchmark results vs. albumentations

### ISSUE THREAD

**Issue by ogencoglu** [albumentations-team/albumentations#557]
Can you update your speed benchmarks with newer version of solt (https://github.com/MIPT-Oulu/solt) and eloborate a bit more on the differences of benchmark pipelines in terms of fairness, comparability and ability to resemble real use?

**Comment by BloodAxe** [comment]
Maybe it some points it will be added. However as of now it's on low-priority list.
As usual, we are more than happy to see pull-requests that adds different benchmark strategies.

**Comment by ternaus** [comment]
Solt is not supported anymore.

Closing the issue.
