### ISSUE TITLE
Facing issue while applying Albumentations 0.4.5 with CIFAR10

### ISSUE THREAD

**Issue by Sanket-DataEnt** [albumentations-team/albumentations#562]
Have you started supporting integer datatype in albumentation 0.4.5. I am facing the issue while working on CIFAR 10 dataset.

data_transforms = albumentations.Compose([
albumentations.HorizontalFlip(),
albumentations.RandomBrightness(),
albumentations.ShiftScaleRotate(rotate_limit=15, scale_limit=0.10),
albumentations.JpegCompression(80),
albumentations.HueSaturationValue(),
albumentations.Normalize(),
ToTensor()
])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
download=True, transform=data_transforms)

SEED = 1
cuda = torch.cuda.is_available()
print("CUDA Available?", cuda)
torch.manual_seed(SEED)

if cuda:
torch.cuda.manual_seed(SEED)
dataloader_args = dict(shuffle=True, batch_size=128, num_workers=4, pin_memory=True) if cuda else dict(shuffle=True, batch_size=64
train dataloader

train_loader = torch.utils.data.DataLoader(trainset, **dataloader_args)

classes = ('plane', 'car', 'bird', 'cat',
'deer', 'dog', 'frog', 'horse', 'ship', 'truck')
functions to show an image

def imshow(img):
img = img / 2 + 0.5 # unnormalize
npimg = img.numpy()
plt.imshow(np.transpose(npimg, (1, 2, 0)))
get some random training images

dataiter = iter(train_loader)
images, labels = dataiter.next()
show images

imshow(torchvision.utils.make_grid(images))
print labels

print(' '.join('%5s' % classes[labels[j]] for j in range(4)))
-------------ERROR------------------

TypeError Traceback (most recent call last)

in ()
7 # get some random training images
8 dataiter = iter(train_loader)
----> 9 images, labels = dataiter.next()
10
11 # show images

3 frames

/usr/local/lib/python3.6/dist-packages/torch/_utils.py in reraise(self)
392 # (https://bugs.python.org/issue2651), so we work around it.
393 msg = KeyErrorMessage(msg)
--> 394 raise self.exc_type(msg)

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
data = fetcher.fetch(index)
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/cifar.py", line 125, in getitem
img = self.transform(img)
TypeError: call() takes 1 positional argument but 2 were given

**Comment by Dipet** [comment]
Pass data into augmentations as named arguments. Examples: https://github.com/albumentations-team/albumentations_examples/blob/master/notebooks/showcase.ipynb

**Comment by Dipet** [comment]
In your case you can try wrap augs like this:
`augs = lambda image: data_transforms(image=image)['image']`

**Comment by Sanket-DataEnt** [comment]
Can I use this in augment and show function?

**Comment by Sanket-DataEnt** [comment]
n

**Comment by Dipet** [comment]
Torchvision works with Pillow images, we are use numpy arrays. So you can try to wrap transforms like this:
```
transfroms = lambda x: data_transforms(image=np.array(x))['image']
```
