### ISSUE TITLE
Not able to import CoarseDropout

### ISSUE THREAD

**Issue by shan18** [albumentations-team/albumentations#564]
## 🐛 Bug

The documentation specifies that the CoarseDropout method is present in the `albumentations.augmentations.transforms` module but no such method is found on importing.

## To Reproduce

1. `from albumentations import CoarseDropout`
1. `from albumentations.augmentations.transforms import CoarseDropout`
1. `dir(albumentations)`, no CoarseDropout method is present in the list

The first two lines give the following error:
```[python]
ImportError: cannot import name 'CoarseDropout'
```

## Expected behavior

There shouldn't have been any errors.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.1.8
 - Python version (e.g., 3.7): 3.6.10
 - OS (e.g., Linux): Linux Ubuntu 18.04 64-bit
 - How you installed albumentations (`conda`, `pip`, source): Tried with both conda and pip

**Comment by Dipet** [comment]
Update albumentations to the latest version: `pip install --upgrade albumentations`
Also you can install latest version from git: `pip install git+https://github.com/albumentations-team/albumentations.git`

**Comment by shan18** [comment]
Thank you, the issue was resolved.

I installed the package via conda as mentioned in README
```
conda install -c conda-forge imgaug
conda install albumentations -c albumentations
```
It installed the version 0.1.12
