### ISSUE TITLE
bug for Special enhancement

### ISSUE THREAD

**Issue by hhaAndroid** [albumentations-team/albumentations#565]
Enhance the demo image as follows, a bug will appear
![image](https://user-images.githubusercontent.com/17425982/76735991-05a02b80-67a1-11ea-8caa-5f660e89a08b.png)

![image](https://user-images.githubusercontent.com/17425982/76736021-118bed80-67a1-11ea-8ecb-9e3d9de568b4.png)

The reason is obvious. There is no filter operation for each enhancement function.

The code that should be modified is：
![image](https://user-images.githubusercontent.com/17425982/76736169-47c96d00-67a1-11ea-9c43-04d9f69d75ae.png)

**Comment by Dipet** [comment]
Please do not use screenshots for code, copy past it into issue as text and wrap it into code specifiers.

**Comment by BloodAxe** [comment]
Please, use the suggested issue template. By explaining the issue in a structured way, you are helping maintainers to understand and address your issue faster. 

More specifically, there is parameter to `A.Compose` that controls how keypoints are removed during augmentations. It is not clear what parameter value you are using, therefore as it is now, the issue cannot be reproduced.
