### ISSUE TITLE
always_apply=True v/s p=1.0

### ISSUE THREAD

**Issue by arunmallya** [albumentations-team/albumentations#575]
## 📚 Documentation

The library is amazing and great to use, but I couldn't find this answer anywhere in the documentation: What is the difference between setting `always_apply=True, p=0.5` v/s `always_apply=True, p=1.0` v/s `always_apply=False, p=1.0` for a transform?

Does using `always_apply=True` mean `p=1.0` implicitly, or does using `p=1.0` mean `always_apply=True`, or neither?

It would be great if you could clarify what the differences between `always_apply` and `p` exactly are.

**Comment by albu** [comment]
neither. `always_apply` forces a transform to be applied even in case when top-level containers are not applied. for example if you have compose with probability `p=0.9` and underlying `Resize` which you want to apply all the time - you have to pass `always_apply=True` to this resize.

**Comment by IlyaOvodov** [comment]
Hm... Rather strange undocumented behaviour. It is a surprize.
At last, if you need som part of Compose to be executed always, why not to do it in a strict way:
```
Compose([SomeStuffToBeDoneAlways(...),
                 Compose([OptionalStuff1(...),
                                   OptionalStuff2(...)], p=0.5),
                 AnotherStuffToBeDoneAlways(...)])
```
instead of 
```
Compose(SomeStuffToBeDoneAlways(some  parameters, more parameters, etc, always_done=True),
                 OptionalStuff1(some  parameters, more parameters, etc, ),
                 OptionalStuff2(some  parameters, more parameters, etc, ),
                 AnotherStuffToBeDoneAlways(some  parameters, more parameters, etc, always_done=True)],
                 p=0.5)
```
From my oppinion the 2nd options is much more misleading.

**Comment by lollows** [comment]
Maybe you want to see [this](https://albumentations.ai/docs/faq/#augmentations-have-a-parameter-named-p-that-sets-the-probability-of-applying-that-augmentation-but-they-also-have-the-always_apply-parameter-that-can-either-be-true-or-false-what-is-the-difference-between-p-and-always_apply-is-always_applytrue-equals-to-p10). The document gives a good explanation.

**Comment by ternaus** [comment]
`alway_apply` was deprecated. Use `p=1` if you want to apply the transform in 100% of situations.
