### ISSUE TITLE
The explanation of probabilities of OneOf is confusing.

### ISSUE THREAD

**Issue by WaterKnight1998** [albumentations-team/albumentations#586]
## 📚 Documentation

For example:

```
OneOf([
                                Flip(p=0.6),
                                Rotate(p=0.2,limit=20),
                                Transpose(p=0.2)
                            ],p=0.5)
```

The previous OneOf will be applied to 50% of images.
For selecting, which operation will be applied is based on the normalized probabilities.

Si, in the previous example. For half of the images OneOf will be applied. If OneOf is applied 60% of the times will be a Flip, 20% will be a Rotate and 20% will be a Transpose.

Is this correct?

**Comment by albu** [comment]
correct
