### ISSUE TITLE
Feature request : mosaic augmentation

### ISSUE THREAD

**Issue by pfeatherstone** [albumentations-team/albumentations#587]
Feature request : mosaic augmenter.
For example, the mosaic augmenter could take 4 images say, and transform them into 4 mixed mosaics.

**Comment by BloodAxe** [comment]
This augmentation has quite narrow use-case and somewhat similar to mixup/mix-match/aug-mix training tricks, which is naturally done quite effectively on GPU. Therefore, duplicating this functionality in Albumentations is doubtful.

**Comment by ogencoglu** [comment]
> This augmentation has quite narrow use-case

That is quite a bold statement considering current state-of-the-art object detection YOLOv4 utilizes _mosaic augmentation_: https://arxiv.org/abs/2004.10934

**Comment by pfeatherstone** [comment]
Ultralytics yolov3 repo uses it too. I think this type of augmentation is one of the key reasons why their model is so good compared to the original yolov3-spp weights

**Comment by BloodAxe** [comment]
Let me clarify my statement.

To start, I'm not arguing that Mosaic augmentation is useless. Indeed, there are use case scenarios, where it brings value to model accuracy. Applying it to object detection is quite natural. But it's not so straightforward to apply it to image classification (e.g this would require to change objective function to multi-label classification). 

Second, API design of Albumentations assumes **single entity augmentation** (By entity I mean image and optionally corresponding mask, keypoints and bboxes). That is the main blocker from my perspective. And I'm not convinced that we should change our API to support training augmentations that goes above the single-entity scope. 

Third, mosaic augmentation seems can be implemented quite easy aside albumentations:

```
def __getitem(self, index):
  indexes = random.choice(np.arange(len(self)), 4)
  images = self.images[indexes]
  bboxes = self.bboxes[indexes]
  labels = self.labels[indexes]
  
  augmented_data = [self.augment(image=i, bboxes=b, labels=l) for (i,b,l) in zip(image, bboxes, labels)]
  
  image, bboxes, labels = grid_stack_images(augmented_data )


```

Hope this clarifies my line of thinking.
