### ISSUE TITLE
ColorJitter Equivalent

### ISSUE THREAD

**Issue by kailasdayanandan** [albumentations-team/albumentations#589]
## 🐛 Bug

There is a transform in ColorJitter in torchvision.transforms. Can you add an equivalent. 
Or is there an equivalent way to reproduce the same.

Having transform of same name can help in easy migration to Albumentations from PyTorch.

**Comment by ternaus** [comment]
You can use the combination of `RandomBrightnessContrast` and `HueSaturationValue` to get the behavior of the CollorJitter from torchvision.

Ex:
```
import albumentations as albu

color_jitter_transform = albu.Compose([
   albu.RandomBrightnessContrast(),
   albu.HueSaturationValue(),
], p=p)
```

**Comment by kailasdayanandan** [comment]
Can you also give details about these values
transforms.ColorJitter(0.3, 0.3, 0.3)

**Comment by kailasdayanandan** [comment]
The suggestion did not give any accuracy increase where as the below gave good increase in score.
transforms.ColorJitter(0.3, 0.3, 0.3)

**Comment by zhaw** [comment]
I think the difference is that transform.ColorJitter random scale the contrast/brightness/saturation/hue value, while HueSaturationValue random shift. In other words, multiply vs add.
It would be nice to have an equivalent implementation.
