### ISSUE TITLE
GridDistortion artifacts at left and bottom margins

### ISSUE THREAD

**Issue by stepelu** [albumentations-team/albumentations#592]
The `GridDistortion` transformation results in artifacts at left and bottom margins.
See example (watch carefully and notice that this happens also at the bottom of the image, where there is no padding):
<img width="565" alt="Screen Shot 2020-04-20 at 17 15 35" src="https://user-images.githubusercontent.com/6617696/79729575-9fbc3c00-832a-11ea-984f-bba468fd4c08.png">
Tested with albumentations head.

**Comment by BloodAxe** [comment]
Could you please share a minimal code example to reproduce?

**Comment by Attrezzi** [comment]
Sorry to intrude, I've just experienced the same problem!
I've been able to replicate the problem with this code, by using the example images from the TGS salt challenge. 

```
import albumentations as A
import cv2
from matplotlib import pyplot as plt
%matplotlib inline

def visualize(image, mask, original_image=None, original_mask=None):
    fontsize = 18
    
    if original_image is None and original_mask is None:
        f, ax = plt.subplots(2, 1, figsize=(8, 8))

        ax[0].imshow(image)
        ax[1].imshow(mask)
    else:
        f, ax = plt.subplots(2, 2, figsize=(8, 8))

        ax[0, 0].imshow(original_image)
        ax[0, 0].set_title('Original image', fontsize=fontsize)
        
        ax[1, 0].imshow(original_mask)
        ax[1, 0].set_title('Original mask', fontsize=fontsize)
        
        ax[0, 1].imshow(image)
        ax[0, 1].set_title('Transformed image', fontsize=fontsize)
        
        ax[1, 1].imshow(mask)
        ax[1, 1].set_title('Transformed mask', fontsize=fontsize)
        

image = cv2.imread('0fea4b5049_image.png')
mask = cv2.imread('0fea4b5049.png', 0)

aug = A.Compose([
            A.GridDistortion(always_apply=True),
        ])

result = aug(image=image, mask=mask)
visualize(result["image"], result["mask"])
```
![grid_distortion](https://user-images.githubusercontent.com/26741549/79748691-231b6480-830e-11ea-98ce-d95aa2078dc9.png)

**Comment by Dipet** [comment]
Fixed at last commit. Try to install latest version from github
```
pip install git+https://github.com/albumentations-team/albumentations.git
```
