### ISSUE TITLE
Modify Resize after Compose

### ISSUE THREAD

**Issue by tienthegainz** [albumentations-team/albumentations#593]
Hi, I want to do multi-size training for object detection task with albumentations.
For example:
```
tfms = Compose([Resize(height=512, width=512), ToTensorV2()], bbox_params=BboxParams(format='pascal_voc', label_fields=['category_id']))
```
Is there any way to change `height` and `width` in `Resize` after calling `Compose`?
Thanks.

**Comment by BloodAxe** [comment]
You can modify parameters of `Resize` instance after you've created compose to fit your needs:

`tfms.transforms[0].width = 256`
