### ISSUE TITLE
Resize - parameters per target

### ISSUE THREAD

**Issue by millerjv** [albumentations-team/albumentations#595]
Is it possible to specify either 

1. Which targets are to be transformed?
2. Different parameters for each target?

Specific to the Resize transform (not a random transformation), I have a use case where my image and masks each need to be resized but they need to be resized to different sizes.  Is this possible? Or do I need to write my own transform?

Features like this would allow me to use Albumentations for many data prep steps, not just for generating augmented data.

**Comment by Dipet** [comment]
No, library does not provide interface to set different parameters for each target and choose which target to be transformed.
