### ISSUE TITLE
rotation augmentations apply method uses angle=0 and not a random angle within provided limit

### ISSUE THREAD

**Issue by AbdullahAly** [albumentations-team/albumentations#598]
## 🐛 Bug

The apply method for `albumentations.augmentations.transforms.Rotate` has an `angle` parameter that has a default of 0. This is in contrast to the `limit` initialization parameter. Using the apply method without supplying an angle will return the original method.

## To Reproduce

Create the transform object. Apply the transformation to an image using the .apply method of the transform object without supplying the angle parameter. The returned image is just the original image.

```
import nibabel as nib
transformation = albumentations.augmentations.transforms.Rotate(limit=180, interpolation=2, border_mode=1, p=0.5)
nib_file = nib.load('path/to/image/img19.nii.gz')
img = nib_file.get_fdata()
affine = nib_file.affine

new_img = transformation.apply(img)
nib.save(nib.Nifti1Image(new_img.astype('float64'), affine), 'path/to/image/test_transform.nii.gz')
```

## Expected behavior
I would expect that the .apply would rotate the image by a random angle that is within the limit provided during initialization instead the .apply method has angle=0 as a default which would mean that the user has to supply the random angle (which is not intuitive in the context of the documentation and initialization parameters);

## Environment

 - Albumentations version: 0.4.5
 - Python version: 3.7.4
 - Linux
 - pip install albumentations

**Comment by BloodAxe** [comment]
There is a problem with how you apply augmentations to your image. The right way to apply augmentations is the following:

```
data = transformation(image=img)
augmented_image = data["image"]
```

Please, follow examples & tutorials at https://github.com/albumentations-team/albumentations_examples.
