### ISSUE TITLE
Error in export GaussNoise(): AttributeError: 'GaussNoise' object has no attribute 'var_limit'

### ISSUE THREAD

**Issue by Hekrdla** [albumentations-team/albumentations#599]
## 🐛 Bug

It seems that there is a problem in export of GaussNoise().
## To Reproduce
This is a minimal example:

import albumentations as alb
trans = alb.GaussNoise()
path = '/tmp/trans.json'
alb.save(trans, path)
loaded_trans = alb.load(path)
loaded_trans

with error: 
AttributeError: 'GaussNoise' object has no attribute 'var_limit'

1.
1.
1.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.5
 - Python version (e.g., 3.7): 3.7.7
 - OS (e.g., Linux): linux
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

**Comment by Dipet** [comment]
Can you show full traceback of error?

**Comment by Hekrdla** [comment]
> Can you show full traceback of error?

 AttributeError: 'GaussNoise' object has no attribute 'var_limit' 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/local/hekrdmir/Applications/miniconda3/envs/smp_v0/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/local/hekrdmir/Applications/miniconda3/envs/smp_v0/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/local/hekrdmir/Applications/miniconda3/envs/smp_v0/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    682     """A pprint that just redirects to the normal repr function."""
    683     # Find newlines and replace them with p.break_()
--> 684     output = repr(obj)
    685     lines = output.splitlines()
    686     with p.group():

/local/hekrdmir/Applications/miniconda3/envs/smp_v0/lib/python3.7/site-packages/albumentations/core/transforms_interface.py in __repr__(self)
    111     def __repr__(self):
    112         state = self.get_base_init_args()
--> 113         state.update(self.get_transform_init_args())
    114         return "{name}({args})".format(name=self.__class__.__name__, args=format_args(state))
    115 

/local/hekrdmir/Applications/miniconda3/envs/smp_v0/lib/python3.7/site-packages/albumentations/core/transforms_interface.py in get_transform_init_args(self)
    181 
    182     def get_transform_init_args(self):
--> 183         return {k: getattr(self, k) for k in self.get_transform_init_args_names()}
    184 
    185     def _to_dict(self):

/local/hekrdmir/Applications/miniconda3/envs/smp_v0/lib/python3.7/site-packages/albumentations/core/transforms_interface.py in <dictcomp>(.0)
    181 
    182     def get_transform_init_args(self):
--> 183         return {k: getattr(self, k) for k in self.get_transform_init_args_names()}
    184 
    185     def _to_dict(self):

AttributeError: 'GaussNoise' object has no attribute 'var_limit'

**Comment by BloodAxe** [comment]
This issue is already fixed in master branch. There was a missing `list` type, but it's been recently fixed. 
https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/transforms.py#L2540
