### ISSUE TITLE
Feature request: Denormalize

### ISSUE THREAD

**Issue by bsridatta** [albumentations-team/albumentations#601]
## :rocket: Feature Request
Inverse normalization for generative models. Training on normalized images and de-normalizing in test time to visually inspect the generated images.
Quite easy to implement but maybe it's nice to have, would come in handy for generative models

**Comment by ternaus** [comment]
@bsridatta 

A bit unclear what do you have in mind. Do you have a link, reference or example of the code?

P.S. Closing for now, will be happy to reopen with more info.
