### ISSUE TITLE
Issue on cv2.cvtColor() when using Albumentation

### ISSUE THREAD

**Issue by Bai426** [albumentations-team/albumentations#603]
## 🐛 Bug
When I used Albumentation to augment my data, the function cv2.cvtColor is incorrect, so there is problem, I adjusted like this according to official guideline on how to use cv2.cvtColor.

The original one in line 39 of normalize.py:
**cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)** 
The revised one:
**img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)**
and it works after revising, my python version is 3.7.2.

**Comment by BloodAxe** [comment]
We do not have file normalize.py in our code-base for current release and many previous versions. Maybe you have some really old version of albumentations. Therefore I strongly encourage you to double-check what version do you have installed and update if necessary. If you still think the issue exists in current release - please re-open this issue and attach a link to exact place in the code, where you think the error is.
