### ISSUE TITLE
module 'albumentations' has no attribute 'KeypointParams'

### ISSUE THREAD

**Issue by ashwath98** [albumentations-team/albumentations#606]
## 🐛 Bug

there seems to be no KeypointParams module in the library
I was trying out the code from the example_keypoints notebook when I ran into this issue
## CODE From notebook

albu.Compose(transformations, p=1, 
                        keypoint_params=albu.KeypointParams(format='xy'))(image=image, keypoints=landmarks)

## Error that arises 
module 'albumentations' has no attribute 'KeypointParams'

## Additional context

I have also tried executing it individually using 
albu.KeypointParams(format='xy')
and I get the same error

Environment :
Google Colab

Installation : 
PIP

**Comment by BloodAxe** [comment]
Please specify version of albumentations that you have installed.

**Comment by ashwath98** [comment]
0.1.12

**Comment by BloodAxe** [comment]
You have installed very old version. Please update to latest, which is 0.4.5.
