### ISSUE TITLE
Check with Black (3.8) fails on PR with no descriptive message

### ISSUE THREAD

**Issue by IlyaOvodov** [albumentations-team/albumentations#621]
CI / Check code formatting with Black (3.8) fails but produces no descriptive message.
See example here: https://github.com/albumentations-team/albumentations/pull/618/checks?check_run_id=642536352
Only information I found there is:
```
Run black --config=black.toml --check .
would reformat /home/runner/work/albumentations/albumentations/albumentations/augmentations/bbox_utils.py
would reformat /home/runner/work/albumentations/albumentations/albumentations/core/composition.py
All done! 💥 💔 💥
2 files would be reformatted, 32 files would be left unchanged.
##[error]Process completed with exit code 1.
```
How to find what is wrong?

**Comment by Dipet** [comment]
To avoid this problems you can install pre-commit hook, like described here https://github.com/albumentations-team/albumentations/blob/master/docs/contributing.rst
Or you can format code directly using the command `black --config=black.toml` inside the project root.
