### ISSUE TITLE
Bounding box resize?

### ISSUE THREAD

**Issue by tienthegainz** [albumentations-team/albumentations#625]
Hi, I want to resize bounding boxes back to image size after doing `Resize()` for evaluation purpose.
I tried to scale by:
```
# width is the image original width
# height is the image original height
# s is the resize shape, let say 512
# bbox is in voc style.
boxes[:, 0] *= (width/s)
boxes[:, 1] *= (height/s)
boxes[:, 2] *= (width/s)
boxes[:, 3] *= (height/s)
```
Some cases are correct, but some are not. Can you tell me the correct way to do it?
Thank you.

**Comment by Dipet** [comment]
Looks correct. Can you give some example where this operations are wrong?

**Comment by tienthegainz** [comment]
Sorry, mistake in my code caused it. This is correct.
