### ISSUE TITLE
Test Time Dropout

### ISSUE THREAD

**Issue by luistelmocosta** [albumentations-team/albumentations#629]
Hello, I was looking for a test time dropout to include it on my project and I was wondering if this amazing library has something like that. I did a quick research and I could not find anything. However, I would like to know if you plan to add it or if something has escaped me.

Kind Regards

**Comment by BloodAxe** [comment]
Hi,

Short answer is no. 

Long version:
You can easily achieve desired functionality by writing custom prediction function:

```
image = YOUR_INPUT_IMAGE
input = torch.from_numpy(image).permute(2,0,1).unsqueeze(0)
output = model(input)

augment = A.CoarseDropout(p=1)
for _ in range(10):
   augmented = augmentation(image=image)
   input = torch.from_numpy(augmented ["image"]).permute(2,0,1).unsqueeze(0)
   output += model(input)

output /= 11
```

This snippet is sub-optimal in terms of performance, but it's goal to illustrate an idea.  Hope it helps.
