### ISSUE TITLE
How to resize images annotated with Labelimg?

### ISSUE THREAD

**Issue by abdou31** [albumentations-team/albumentations#633]
## Environment

 - Albumentations version (e.g., 0.1.8): Last version
 - Python version (e.g., 3.7):3.6
 - OS (e.g., Linux):Windows 10 x64
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

Hello, I would like to know is it a guide of how to use albumentations to resize dataset ( images annotated with bounding box using Labelimg )?
Thanks.

**Comment by Dipet** [comment]
You need convert them to one of supported bbox formats: https://albumentations.readthedocs.io/en/latest/api/core.html#albumentations.core.composition.BboxParams
Look to example https://github.com/albumentations-team/albumentations_examples/blob/master/notebooks/example_bboxes.ipynb
More examples here https://github.com/albumentations-team/albumentations_examples/tree/master/notebooks
