### ISSUE TITLE
RandomBrightnessContrast or HueSaturationValue on Synthetic MNIST display black image

### ISSUE THREAD

**Issue by rao208** [albumentations-team/albumentations#635]
## 🐛 Bug

When I try to apply RandomBrightnessContrast or HueSaturationValue **on Synthetic MNIST** and plot the augmented image, it returns nothing but just a plain black canvas

## To Reproduce

```
import numpy as np
import matplotlib.pyplot as plt
from albumentations import (Compose, HorizontalFlip, CLAHE, HueSaturationValue,
                            RandomBrightness, RandomContrast, Rotate, VerticalFlip,
                            HueSaturationValue, Normalize, RandomGamma, ToFloat, RandomBrightnessContrast)

AUGMENTATIONS_TRAIN = Compose([HorizontalFlip(p=0.5),
                               VerticalFlip(p=0.5),
                               Rotate(20),
                               RandomGamma(gamma_limit=(80, 120), p=0.5),
                               HueSaturationValue(hue_shift_limit=5, sat_shift_limit=20,
                                                   val_shift_limit=10),
                               ToFloat(max_value=255),
                               ])

test_x = np.load('./data/test_x.npy')
test_y = np.load('./data/test_y.npy')

train_x = np.load('./data/train_x.npy')
train_y = np.load('./data/train_y.npy')

# train_x = train_x.astype('float32')
# test_x = test_x.astype('float32')
 

fig = plt.figure(figsize=(5,4))

for i in range(3):
    for j in range(3):
        ax = fig.add_subplot(3, 3, i * 3 + j + 1)
        ax.imshow(train_x[i * 3 + j]/255)

fig = plt.figure(figsize=(5,4))
for i in range(3):
    for j in range(3):
        ax = fig.add_subplot(3, 3, i * 3 + j + 1)
        img = (AUGMENTATIONS_TRAIN(image=train_x[8])["image"]).astype(np.float32)
        ax.imshow(img)

```
displays

![error](https://user-images.githubusercontent.com/44291384/82621356-30f92980-9bdb-11ea-9f08-21d4734411bf.png)

It is the same with RandomBrightnessContrast

However, when I comment` HueSaturationValue(hue_shift_limit=5, sat_shift_limit=20, val_shift_limit=10), `, the images are displayed correctly.

![correct](https://user-images.githubusercontent.com/44291384/82621571-c3013200-9bdb-11ea-8683-da4a4f2059fd.png)

I tried 'np.uint8' datatype as well. The above code seems to work fine in the link below, but it is not giving me the desired output.

[https://colab.research.google.com/drive/1zTYNJ3xtPeNsa5ARBw4Ufj8crPZJx-cp#scrollTo=EajrUBCS0TnW](CIFAR10)

## Environment

 - Albumentations version: 0.4.5
 - Python version: 3.7
 - OS: Windows (Anaconda)
 - How you installed albumentations: conda install -c conda-forge albumentations
 - Any other relevant information:

Please help

Best Regards,

**Comment by BloodAxe** [comment]
Greetings,

What is the range of values in images in `train_x.npy`? Expected image intensity range for `float32 `dtype is [0..1]. It the value is outside this range, you may get clipped values.

**Comment by stvogel** [comment]
I got the same problem. The image is a usual image-numpy array with dtype=float32 and pixel-values ranging [0..1].
I'm using 
```
A.HueSaturationValue(hue_shift_limit=10, sat_shift_limit=25, val_shift_limit=5)
```

Doh ... while typing this, the error gets obvious, for pixel-values ranging from 0 to 1 you should also use the limits [0, 1].
Might be worth mentioning in the docs.
