### ISSUE TITLE
Rotation induced mirroring doesnt mirror boxes

### ISSUE THREAD

**Issue by julled** [albumentations-team/albumentations#636]
## 🐛 Bug

I encountered a problem when rotation fills the gaps at the image border by mirroring (default cv2 bordermode is cv2.BORDER_REFLECT_101). If a rotation is applied, the box of the object isnt mirrored. Thus there is a new object in the image created, but without a corresponding box.
Example:
![rotation](https://user-images.githubusercontent.com/8696195/82719299-8996f800-9ca9-11ea-896b-d98cdc22419a.png)

## To Reproduce

1. Rotate a image with a box next to the image border

## Expected behavior

I expect to have a new box created which encloses the mirrored objects/parts.

## Environment

 - Albumentations version (e.g., 0.1.8): albumentations     0.4.3
 - Python version (e.g., 3.7): 3.7

**Comment by BloodAxe** [comment]
Hi,

unfortunately, adding extra bounding boxes to reflected regions of the image is not supported. 
You can change border mode to `cv2.BORDER_CONSTANT` if this causes significant impact on the training of your model.

**Comment by julled** [comment]
Okay good to know!
I think it might be a good idea to actually point that out in the documentation, otherwise the trainingdata gets corrupted if there is not extra caution for this topic.
Or did i missed this info in the docu somewhere?

**Comment by BloodAxe** [comment]
No, you didn't miss anything. This is definitely a place where we can improve our documentation.
I will close this issue for now and in next release we will include more clear description on mirroring to docs. Thanks for highlighting this issue.
