### ISSUE TITLE
CUDA backend support

### ISSUE THREAD

**Issue by briankosw** [albumentations-team/albumentations#645]
Are there plans to add CUDA backend support? It seems natural that image augmentation and preprocessing would have GPU acceleration.

**Comment by ternaus** [comment]
Feel free to check https://github.com/kornia/kornia

**Comment by imneonizer** [comment]
> Feel free to check https://github.com/kornia/kornia

Does it allows to transform annotations at the same time ?

**Comment by Dipet** [comment]
As I know kornia works only with images.
