### ISSUE TITLE
Question -- add data or just transform data?

### ISSUE THREAD

**Issue by aamster** [albumentations-team/albumentations#646]
My understanding of data augmentation is that we should take whatever data we have, and then to this dataset _add_ augmented images. However with albumentations, my understanding is that with the `p` argument, we can control whether the augmentation gets applied or not, but the amount of data that we have is still the same. Shouldn't albumentations work by _adding_ augmented images to the dataset instead of just applying transformations to the existing dataset or am I wrong?

**Comment by aravindveluri** [comment]
Hey, I am confused about the same. Did you find any explanation for this?

**Comment by aamster** [comment]
When we train using SGD for example we sample the dataset over and over, each time applying a random transformation to the data, so that the dataset grows. Or you can apply the transformation randomly ahead of time to the data and then sample that; either way the dataset size gets bigger

**Comment by aravindveluri** [comment]
Oh, now it makes sense! Essentially, it performs an online augmentation on the dataset, instead of an offline augmentation, if I'm getting it right.
Thank you!
