### ISSUE TITLE
Adding documentation to use Albumentations with TensorFlow

### ISSUE THREAD

**Issue by benihime91** [albumentations-team/albumentations#651]
## 📚 Documentation

I have searched everywhere but nowhere did i find any docs or notebooks that describe how to integrate albumentations with TensorFlow data pipeline. 
I have was able to apply this i.e., use albumentations transforms with the  `tf.data`.
How do i contribute to the docs?

**Comment by BloodAxe** [comment]
Greetings! It would be great if you can contribute by generating a PR to https://github.com/albumentations-team/albumentations_examples with example of using Albumentations in Tensorflow for some toy example (CIFAR/MNIST).
Also, if you prefer writing docs, consider making a new page under https://github.com/albumentations-team/albumentations/tree/master/docs.
