### ISSUE TITLE
GridDistortion is not centered

### ISSUE THREAD

**Issue by jacekpoplawski** [albumentations-team/albumentations#652]
## 🐛 Bug

After doing some experiments with GridDistortion I found out that it is not centered, instead it is glued to top/left side of the image. 

## To Reproduce

Please try generating images with following transforms:

transforms = Compose( [
                        GridDistortion(num_steps=5, distort_limit=0.5, border_mode=cv2.BORDER_CONSTANT, p=1),    
                        ToTensor()
                      ], p = 1.0)

Please observe where are black rectangles in the results.

## Expected behavior

I would expect the black space will be on each edge of images, instead we can see black rectangles only on right and bottom side of the generated images.

I believe the problem is that GridDistorion can increase or decrease size of the image, but it is always anchored to the top left corner, so the right and bottom parts are more modified that the left/top. 

I think the neutral zone should be center of the image, so each side of the image will be affected with same probability.

## Versions

I use albumentations in DataGenerator in pytorch in Windows.

Windows 10, Python 3.8.2
torch                         1.5.1
albumentations                0.4.5

**Comment by ternaus** [comment]
Should be fixed now.

Could you please verify at: https://explore.albumentations.ai/transform/GridDistortion
