### ISSUE TITLE
Index Error when importing albumentations.pytorch.transforms

### ISSUE THREAD

**Issue by hpschrei** [albumentations-team/albumentations#653]
## 🐛 Bug

When importing albumentations.pytorch.transforms I get an "IndexError: list index out of range" error.

## To Reproduce

1. import albumentations.pytorch.transforms

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-5bbab2123c88> in <module>
----> 1 import albumentations.pytorch.transforms

~/anaconda3/lib/python3.7/site-packages/albumentations/pytorch/__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from .transforms import *

~/anaconda3/lib/python3.7/site-packages/albumentations/pytorch/transforms.py in <module>
      5 import numpy as np
      6 import torch
----> 7 from torchvision.transforms import functional as F
      8 
      9 from ..core.transforms_interface import BasicTransform

~/anaconda3/lib/python3.7/site-packages/torchvision/__init__.py in <module>
      1 import warnings
      2 
----> 3 from torchvision import models
      4 from torchvision import datasets
      5 from torchvision import ops

~/anaconda3/lib/python3.7/site-packages/torchvision/models/__init__.py in <module>
     10 from .shufflenetv2 import *
     11 from . import segmentation
---> 12 from . import detection
     13 from . import video
     14 from . import quantization

~/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/__init__.py in <module>
----> 1 from .faster_rcnn import *
      2 from .mask_rcnn import *
      3 from .keypoint_rcnn import *

~/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py in <module>
     12 from .generalized_rcnn import GeneralizedRCNN
     13 from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
---> 14 from .roi_heads import RoIHeads
     15 from .transform import GeneralizedRCNNTransform
     16 from .backbone_utils import resnet_fpn_backbone

~/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/roi_heads.py in <module>
    209 
    210 
--> 211 @torch.jit.script
    212 def _onnx_heatmaps_to_keypoints_loop(maps, rois, widths_ceil, heights_ceil,
    213                                      widths, heights, offset_x, offset_y, num_keypoints):

~/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)
   1288         raise RuntimeError("interface must be applied to a class")
   1289     if not _is_new_style_class(obj):
-> 1290         raise RuntimeError("TorchScript interfaces must inherit from 'object'")
   1291 
   1292     is_module_interface = issubclass(obj, torch.nn.Module) and len(obj.mro()) == 3

~/anaconda3/lib/python3.7/site-packages/torch/jit/_recursive.py in try_compile_fn(fn, loc)
    566 
    567 def compile_unbound_method(concrete_type, fn):
--> 568     if _jit_internal.is_ignored_fn(fn):
    569         return None
    570     stub = make_stub(fn)

~/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)
   1288         raise RuntimeError("interface must be applied to a class")
   1289     if not _is_new_style_class(obj):
-> 1290         raise RuntimeError("TorchScript interfaces must inherit from 'object'")
   1291 
   1292     is_module_interface = issubclass(obj, torch.nn.Module) and len(obj.mro()) == 3

~/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in _get_overloads(obj)
   2028 _compiled_overloaded_fns = {}
   2029 
-> 2030 def _compile_function_with_overload(qual_name, impl_fn, overload_decl, overload_defaults):
   2031     impl_ast = torch.jit.get_jit_def(impl_fn)
   2032     _rcb = _jit_internal.createResolutionCallbackFromClosure(impl_fn)

~/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in _compile_function_with_overload(overload_fn, qual_name, impl_fn)
   2015 
   2016 
-> 2017 def _get_script_class(name):
   2018     global _script_classes
   2019     if name not in _script_classes:

~/anaconda3/lib/python3.7/site-packages/torch/jit/_recursive.py in try_compile_fn(fn, loc)
    566 
    567 def compile_unbound_method(concrete_type, fn):
--> 568     if _jit_internal.is_ignored_fn(fn):
    569         return None
    570     stub = make_stub(fn)

~/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)
   1285 
   1286 def interface(obj):
-> 1287     if not inspect.isclass(obj):
   1288         raise RuntimeError("interface must be applied to a class")
   1289     if not _is_new_style_class(obj):

~/anaconda3/lib/python3.7/site-packages/torch/jit/frontend.py in get_jit_def(fn, self_name)
    162     sourcelines, file_lineno, filename = get_source_lines_and_file(fn)
    163     source = ''.join(sourcelines)
--> 164     dedent_src = dedent(source)
    165     py_ast = ast.parse(dedent_src)
    166     if len(py_ast.body) != 1 or not isinstance(py_ast.body[0], ast.FunctionDef):

~/anaconda3/lib/python3.7/site-packages/torch/_utils_internal.py in get_source_lines_and_file(obj, error_msg)
     44     try:
     45         filename = inspect.getsourcefile(obj)
---> 46         sourcelines, file_lineno = inspect.getsourcelines(obj)
     47     except OSError as e:
     48         raise OSError((

~/anaconda3/lib/python3.7/inspect.py in getsourcelines(object)
    953     raised if the source code cannot be retrieved."""
    954     object = unwrap(object)
--> 955     lines, lnum = findsource(object)
    956 
    957     if istraceback(object):

~/anaconda3/lib/python3.7/inspect.py in findsource(object)
    826         pat = re.compile(r'^(\s*def\s)|(\s*async\s+def\s)|(.*(?<!\w)lambda(:|\s))|^(\s*@)')
    827         while lnum > 0:
--> 828             if pat.match(lines[lnum]): break
    829             lnum = lnum - 1
    830         return lines, lnum

IndexError: list index out of range

## Expected behavior

Import of albumentations.pytorch.transforms without an index error.

## Environment

<details>
  <summary>'conda info'</summary>
<pre>     active environment : base
    active env location : /home/hps/anaconda3
            shell level : 1
       user config file : /home/hps/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.31
       base environment : /home/hps/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/hps/anaconda3/pkgs
                          /home/hps/.conda/pkgs
       envs directories : /home/hps/anaconda3/envs
                          /home/hps/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.7.4 Linux/5.4.0-050400rc5-generic pop/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
</pre>
</details>
<details>
<summary>'conda list --show-channel-url'</summary>
<pre># packages in environment at /home/hps/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.02                  py37_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
_libgcc_mutex             0.1                        main    defaults
_pytorch_select           0.2                       gpu_0    defaults
alabaster                 0.7.12                   py37_0    defaults
albumentations            0.4.5                    pypi_0    pypi
anaconda                  custom                   py37_1    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.4                      py_0    defaults
argh                      0.26.2                   py37_0    defaults
arviz                     0.6.1                      py_0    defaults
asn1crypto                1.3.0                    py37_0    defaults
astroid                   2.4.2                    py37_0    defaults
astropy                   4.0.1.post1      py37h7b6447c_1    defaults
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.4.0                      py_0    defaults
attrs                     19.3.0                     py_0    defaults
autograd                  1.3                      pypi_0    pypi
autopep8                  1.5.3                      py_0    defaults
babel                     2.8.0                      py_0    defaults
backcall                  0.2.0                      py_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.6.1                      py_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.9.1                    py37_0    defaults
binutils_impl_linux-64    2.33.1               he6710b0_7    defaults
binutils_linux-64         2.33.1              h9595d00_15    defaults
bitarray                  1.2.2            py37h7b6447c_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.5                      py_0    defaults
blosc                     1.19.0               hd408876_0    defaults
bokeh                     2.1.1                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.3.2            py37heb32a55_1    defaults
brotlipy                  0.7.0           py37h7b6447c_1000    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2020.1.1                      0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2020.6.20                py37_0    defaults
cffi                      1.14.0           py37h2e261b9_0    defaults
cftime                    1.1.2            py37heb32a55_0    defaults
chardet                   3.0.4                 py37_1003    defaults
click                     7.1.2                      py_0    defaults
cloudpickle               1.4.1                      py_0    defaults
clyent                    1.2.2                    py37_1    defaults
cmdstanpy                 0.4.0                    pypi_0    pypi
colorama                  0.4.3                      py_0    defaults
conda                     4.8.3                    py37_0    defaults
conda-build               3.18.9                   py37_3    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.1            py37h7b6447c_0    defaults
conda-verify              3.4.2                      py_1    defaults
confuse                   1.0.0                    pypi_0    pypi
contextlib2               0.6.0.post1                py_0    defaults
convertdate               2.2.1                    pypi_0    pypi
crayons                   0.3.1                    pypi_0    pypi
cryptography              2.9.2            py37h1ba5d50_0    defaults
cudatoolkit               10.1.243             h6bb024c_0    defaults
cudnn                     7.6.5                cuda10.1_0    defaults
curl                      7.69.1               hbc83047_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.20          py37he6710b0_0    defaults
cytoolz                   0.10.1           py37h7b6447c_0    defaults
dask                      2.19.0                     py_0    defaults
dask-core                 2.19.0                     py_0    defaults
dbus                      1.13.16              hb2f20db_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
diff-match-patch          20181111                   py_0    defaults
dill                      0.3.1.1                  pypi_0    pypi
distributed               2.19.0                   py37_0    defaults
docutils                  0.16                     py37_1    defaults
efficientnet-pytorch      0.6.3                    pypi_0    pypi
entrypoints               0.3                      py37_0    defaults
ephem                     3.7.7.1                  pypi_0    pypi
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.9                he6710b0_2    defaults
fastcache                 1.1.0            py37h7b6447c_0    defaults
fbprophet                 0.6                      pypi_0    pypi
ffmpeg                    4.0                  hcdf2ecd_0    defaults
filelock                  3.0.12                     py_0    defaults
fix-yahoo-finance         0.1.37                   pypi_0    pypi
flake8                    3.8.2                    pypi_0    pypi
flask                     1.1.2                      py_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freeglut                  3.0.0                hf484d3e_5    defaults
freetype                  2.10.2               h5ab3b9f_0    defaults
fribidi                   1.0.9                h7b6447c_0    defaults
fsspec                    0.7.4                      py_0    defaults
future                    0.18.2                   py37_1    defaults
gcc_impl_linux-64         7.3.0                habb00fd_1    defaults
gcc_linux-64              7.3.0               h553295d_15    defaults
geojson                   2.5.0                    pypi_0    pypi
geos                      3.8.0                he6710b0_0    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    20.6.2           py37h7b6447c_0    defaults
glib                      2.63.1               h5a9c865_0    defaults
glob2                     0.7                        py_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py37h10f8cd9_2    defaults
graphite2                 1.3.14               h23475e2_0    defaults
greenlet                  0.4.16           py37h7b6447c_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
gxx_impl_linux-64         7.3.0                hdf63c60_1    defaults
gxx_linux-64              7.3.0               h553295d_15    defaults
h5py                      2.8.0            py37h989c5e5_3    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
hdf4                      4.2.13               h3ca952b_2    defaults
hdf5                      1.10.2               hba1933b_1    defaults
heapdict                  1.0.1                      py_0    defaults
holidays                  0.10.2                   pypi_0    pypi
html5lib                  1.0.1                    py37_0    defaults
htmlmin                   0.1.12                   pypi_0    pypi
hypothesis                5.16.1                     py_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.9                        py_1    defaults
imageio                   2.8.0                      py_0    defaults
imagesize                 1.2.0                      py_0    defaults
imgaug                    0.2.6                    pypi_0    pypi
importlib-metadata        1.6.1                    py37_0    defaults
importlib_metadata        1.6.1                         0    defaults
inflection                0.3.1                    py37_1    defaults
intel-openmp              2020.1                      217    defaults
intervaltree              3.0.2                      py_0    defaults
ipykernel                 5.3.0            py37h5ca1d4c_0    defaults
ipython                   7.15.0                   py37_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.1                      py_0    defaults
isort                     4.3.21                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jasper                    2.0.14               h07fcdf6_1    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.15.2                   py37_0    defaults
jeepney                   0.4.3                      py_0    defaults
jinja2                    2.11.2                     py_0    defaults
joblib                    0.15.1                     py_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
json5                     0.9.5                      py_0    defaults
jsonschema                3.2.0                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            6.1.3                      py_0    defaults
jupyter_console           6.1.0                      py_0    defaults
jupyter_core              4.6.3                    py37_0    defaults
jupyterlab                2.1.4                      py_1    defaults
jupyterlab_server         1.1.5                      py_0    defaults
keyring                   21.2.1                   py37_0    defaults
kiwisolver                1.2.0            py37hfd86e86_0    defaults
korean-lunar-calendar     0.2.1                    pypi_0    pypi
krb5                      1.17.1               h173b8e3_0    defaults
lazy-object-proxy         1.4.3            py37h7b6447c_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libarchive                3.4.2                h62408e4_0    defaults
libcurl                   7.69.1               h20c2e04_0    defaults
libedit                   3.1.20191231         h7b6447c_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libglu                    9.0.0                hf484d3e_1    defaults
libgpuarray               0.7.6                h14c3975_0    defaults
liblief                   0.10.1               he6710b0_0    defaults
libnetcdf                 4.6.1                h10edf3e_2    defaults
libopencv                 3.4.2                hb342d67_1    defaults
libopus                   1.3.1                h7b6447c_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libspatialindex           1.9.3                he6710b0_0    defaults
libssh2                   1.9.0                h1ba5d50_1    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
libtool                   2.4.6                h7b6447c_5    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libvpx                    1.7.0                h439df22_0    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.10               he19cac6_1    defaults
libxslt                   1.1.34               hc22bd24_0    defaults
lifetimes                 0.11.1                   pypi_0    pypi
lightgbm                  2.3.0            py37he6710b0_0    defaults
llvmlite                  0.32.1           py37hd408876_0    defaults
locket                    0.2.0                    py37_1    defaults
lunarcalendar             0.0.9                    pypi_0    pypi
lxml                      4.5.1            py37hefd8a0e_0    defaults
lz4-c                     1.9.2                he6710b0_0    defaults
lzo                       2.10                 h7b6447c_2    defaults
mako                      1.1.3                      py_0    defaults
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1            py37h7b6447c_0    defaults
matplotlib                1.5.1                    pypi_0    pypi
matplotlib-base           3.2.2            py37hef1b27d_0    defaults
mccabe                    0.6.1                    py37_1    defaults
missingno                 0.4.2                    pypi_0    pypi
mistune                   0.8.4            py37h7b6447c_0    defaults
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.1.0            py37h23d657b_0    defaults
mkl_random                1.1.1            py37h0573a6f_0    defaults
mock                      4.0.2                      py_0    defaults
more-itertools            8.4.0                      py_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.2                hb69a4c5_1    defaults
mpld3                     0.5.1                    pypi_0    pypi
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            1.0.0            py37hfd86e86_1    defaults
multipledispatch          0.6.0                    py37_0    defaults
multitasking              0.0.9                    pypi_0    pypi
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.6.1                    py37_0    defaults
nbformat                  5.0.7                      py_0    defaults
nbopen                    0.6                      pypi_0    pypi
ncurses                   6.2                  he6710b0_1    defaults
netcdf4                   1.4.2            py37h4b4f87f_0    defaults
networkx                  2.4                        py_0    defaults
ninja                     1.9.0            py37hfd86e86_0    defaults
nltk                      3.5                        py_0    defaults
nonlinshrink              0.6                       dev_0    &lt;develop&gt;
nose                      1.3.7                    py37_2    defaults
notebook                  6.0.3                    py37_0    defaults
numba                     0.49.1           py37h0573a6f_0    defaults
numexpr                   2.7.1            py37h423224d_0    defaults
numpy                     1.18.5           py37ha1c710e_0    defaults
numpy-base                1.18.5           py37hde5b4d6_0    defaults
numpydoc                  1.0.0                      py_0    defaults
olefile                   0.46                     py37_0    defaults
opencv                    3.4.2            py37h6fd60c2_1    defaults
opencv-python             4.2.0.34                 pypi_0    pypi
opencv-python-headless    4.2.0.34                 pypi_0    pypi
openpyxl                  3.0.3                      py_0    defaults
openssl                   1.1.1g               h7b6447c_0    defaults
packaging                 20.4                       py_0    defaults
pandas                    1.0.5            py37h0573a6f_0    defaults
pandas-datareader         0.8.1                    pypi_0    pypi
pandas-profiling          2.3.0                    pypi_0    pypi
pandoc                    2.9.2.1                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
pango                     1.42.4               h049681c_0    defaults
parso                     0.5.2                      py_0    defaults
partd                     1.1.0                      py_0    defaults
patchelf                  0.11                 he6710b0_0    defaults
path                      14.0.1                   py37_0    defaults
path.py                   12.0.2                     py_0    defaults
pathlib2                  2.3.5                    py37_0    defaults
pathtools                 0.1.2                      py_1    defaults
patsy                     0.5.1                    py37_0    defaults
pcre                      8.44                 he6710b0_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.8.0                    py37_0    defaults
phik                      0.9.8                    pypi_0    pypi
pickleshare               0.7.5                    py37_0    defaults
piexif                    1.1.3                    pypi_0    pypi
pillow                    6.2.2                    pypi_0    pypi
pip                       19.3.1                   pypi_0    pypi
pixiedust                 1.1.18                   pypi_0    pypi
pixman                    0.40.0               h7b6447c_0    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
plotly                    4.6.0                      py_0    defaults
pluggy                    0.13.1                   py37_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.8.0                      py_0    defaults
prompt-toolkit            3.0.5                      py_0    defaults
prompt_toolkit            3.0.5                         0    defaults
psutil                    5.7.0            py37h7b6447c_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
py                        1.8.2                      py_0    defaults
py-lief                   0.10.1           py37h403a769_0    defaults
py-opencv                 3.4.2            py37hb342d67_1    defaults
pycodestyle               2.6.0                      py_0    defaults
pycosat                   0.6.3            py37h7b6447c_0    defaults
pycparser                 2.20                       py_0    defaults
pycrypto                  2.6.1           py37h7b6447c_10    defaults
pycurl                    7.43.0.5         py37h1ba5d50_0    defaults
pydocstyle                5.0.2                      py_0    defaults
pyflakes                  2.2.0                      py_0    defaults
pygments                  2.6.1                      py_0    defaults
pygpu                     0.7.6            py37heb32a55_0    defaults
pylint                    2.5.3                    py37_0    defaults
pymc3                     3.8                        py_0    defaults
pymeeus                   0.3.7                    pypi_0    pypi
pyodbc                    4.0.30           py37he6710b0_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pyreadline                2.1                      pypi_0    pypi
pyrsistent                0.16.0           py37h7b6447c_0    defaults
pysocks                   1.7.1                    py37_0    defaults
pystan                    2.19.1.1                 pypi_0    pypi
pytables                  3.4.4            py37ha205bf6_0    defaults
pytest                    5.4.3                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.8.0                      py_0    defaults
pytest-astropy-header     0.1.2                      py_0    defaults
pytest-doctestplus        0.7.0                      py_0    defaults
pytest-openfiles          0.5.0                      py_0    defaults
pytest-pylint             0.14.1                   pypi_0    pypi
pytest-remotedata         0.3.2                    py37_0    defaults
python                    3.7.4                h265db76_1    defaults
python-dateutil           2.8.1                      py_0    defaults
python-jsonrpc-server     0.3.4                      py_0    defaults
python-language-server    0.31.9                   py37_0    defaults
python-libarchive-c       2.9                        py_0    defaults
pytorch                   1.4.0           cuda101py37h02f0884_0    defaults
pytz                      2020.1                     py_0    defaults
pywavelets                1.1.1            py37h7b6447c_0    defaults
pyxdg                     0.26                       py_0    defaults
pyyaml                    5.3.1            py37h7b6447c_1    defaults
pyzmq                     19.0.1           py37he6710b0_1    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtawesome                 0.7.2                      py_0    defaults
qtconsole                 4.7.5                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
quandl                    3.4.8                    py37_0    defaults
readline                  7.0                  h7b6447c_5    defaults
regex                     2020.5.14        py37h7b6447c_0    defaults
requests                  2.24.0                     py_0    defaults
retrying                  1.3.3                    py37_2    defaults
ripgrep                   11.0.2               he32d670_0    defaults
rope                      0.17.0                     py_0    defaults
rtree                     0.9.4                    py37_1    defaults
ruamel_yaml               0.15.87          py37h7b6447c_1    defaults
scikit-image              0.16.2           py37h0573a6f_0    defaults
scikit-learn              0.23.1           py37h423224d_0    defaults
scipy                     1.5.0            py37h0b6359f_0    defaults
seaborn                   0.10.1                     py_0    defaults
secretstorage             3.1.2                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                47.3.1                   py37_0    defaults
setuptools-git            1.2                      pypi_0    pypi
shapely                   1.7.0            py37h98ec03d_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.15.0                     py_0    defaults
snappy                    1.1.8                he6710b0_0    defaults
snowballstemmer           2.0.0                      py_0    defaults
sortedcollections         1.2.1                      py_0    defaults
sortedcontainers          2.2.2                      py_0    defaults
soupsieve                 2.0.1                      py_0    defaults
sphinx                    3.1.1                      py_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-applehelp   1.0.2                      py_0    defaults
sphinxcontrib-devhelp     1.0.2                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.3                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.3                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.4                      py_0    defaults
sphinxcontrib-websupport  1.2.2                      py_0    defaults
spyder                    4.1.3                    py37_0    defaults
spyder-kernels            1.9.1                    py37_0    defaults
sqlalchemy                1.3.17           py37h7b6447c_0    defaults
sqlite                    3.32.3               h62c20be_0    defaults
start_jupyter_cm          2.1.0                      py_0    conda-forge
statsmodels               0.11.1           py37h7b6447c_0    defaults
stegano                   0.9.8                    pypi_0    pypi
sympy                     1.6                      py37_0    defaults
tbb                       2020.0               hfd86e86_0    defaults
tblib                     1.6.0                      py_0    defaults
terminado                 0.8.3                    py37_0    defaults
testpath                  0.4.4                      py_0    defaults
theano                    0.8.2                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
tk                        8.6.10               hbc83047_0    defaults
toml                      0.10.1                     py_0    defaults
toolz                     0.10.0                     py_0    defaults
torch                     1.5.1                    pypi_0    pypi
torchvision               0.5.0                py37_cu101    pytorch
tornado                   6.0.4            py37h7b6447c_1    defaults
tqdm                      4.46.1                     py_0    defaults
traitlets                 4.3.3                    py37_0    defaults
typed-ast                 1.4.0                    pypi_0    pypi
typing_extensions         3.7.4.2                    py_0    defaults
ujson                     1.35             py37h14c3975_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h14c3975_0    defaults
urllib3                   1.25.9                     py_0    defaults
watchdog                  0.10.2                   py37_0    defaults
wcwidth                   0.2.4                      py_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  1.0.1                      py_0    defaults
wheel                     0.34.2                   py37_0    defaults
widgetsnbextension        3.5.1                    py37_0    defaults
wrapt                     1.11.2           py37h7b6447c_0    defaults
wurlitzer                 2.0.0                    py37_0    defaults
xarray                    0.15.1                     py_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.2.9                      py_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yapf                      0.29.0                     py_0    defaults
yfinance                  0.1.54                   pypi_0    pypi
zeromq                    4.3.2                he6710b0_2    defaults
zict                      2.0.0                      py_0    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zope                      1.0                      py37_1    defaults
zope.event                4.4                      py37_0    defaults
zope.interface            4.7.1            py37h7b6447c_0    defaults
zstd                      1.4.4                h0b5b093_3    defaults
</pre>
</details>

## Additional context

Given that the error occurs immediately at import, it seems likely to me that it is a versioning issue, possibly caused by a particular version configuration on my side.

**Comment by BloodAxe** [comment]
Hi. I could not reproduce this issues locally and on CI. Therefore it's hard to provide any help at this point.
Also, it seems your environment has two versions of pytorch installed:
```
torch                     1.5.1                    pypi_0    pypi
torchvision               0.5.0                py37_cu101    pytorch
pytorch                   1.4.0           cuda101py37h02f0884_0    defaults
```

My suggestion is to go with fresh environment and one pytorch version to see whether the issue is still happens.
But my bet - it will go away once you tidy up packages in your working environment.
