### ISSUE TITLE
mask is not corresponting with images after augmentation

### ISSUE THREAD

**Issue by bozhenhhu** [albumentations-team/albumentations#655]
## 📚 Documentation

My codes are as follows: 
def get_transforms(phase='train', p=1):
    if phase == "train":
        list_transforms = []
        list_transforms.extend(
            [
                HorizontalFlip(), VerticalFlip(),
                # OneOf([
                #     IAAAdditiveGaussianNoise(),
                #     GaussNoise(),
                # ], p=0.1),
                # OneOf([
                #     MotionBlur(p=.2),
                #     MedianBlur(blur_limit=3, p=.1),
                #     Blur(blur_limit=3, p=.1),
                # ], p=0.1),
                # OneOf([
                #     GridDistortion(p=.1),
                #     IAAPiecewiseAffine(p=0.2),
                # ], p=0.3),
                # OneOf([
                #     CLAHE(clip_limit=2),
                #     IAASharpen(),
                #     IAAEmboss(),
                #     RandomBrightnessContrast(),
                # ], p=0.2),
                HueSaturationValue(p=0.3),
            ]
        )
        list_trfms = Compose(list_transforms,p=p)
        return list_trfms

transforms = get_transforms(phase='train')
heigth = 256
width = 256
img = cv2.imread(label_path, 0)
for i in range(0, data.shape[2], 2):
       pre_frame = np.tile(np.expand_dims(data[:, :, i], axis=-1), (1, 1, 3))
       pre_frame = pre_frame.astype(np.uint8)
       aug_data = {"image":pre_frame, "mask":img}
       augmented = transforms(**aug_data)
       pre_frame, img = augmented['image'][:, :, 0], augmented['mask']
       pre_frame = cv2.resize(pre_frame, (height, width))
       if img.shape != (height, width):
            img = cv2.resize(img, (height, width))
       scipy.misc.imsave('./ims/im_{}.png'.format(i), pre_frame)
       scipy.misc.imsave('./ims_label/label_{}.png'.format(i), img)

However, when I checked the augmented images and labels, I found that the transformed images are different with corresponding transformed masks,for example, one image is rotated 90 degree while its mask is not rotated correctly , I don't know why and how to revise the codes???

**Comment by bozhenhhu** [comment]
I have already found the problem, My codes exist a bug.

**Comment by LAUBENicolas** [comment]
I have the same issue. Ref= #713
