### ISSUE TITLE
Request to bump the imgaug dependency to latest version

### ISSUE THREAD

**Issue by GokulNC** [albumentations-team/albumentations#657]
When installing `albumentations`, I saw the following:

```
Installing collected packages: imgaug, albumentations
  Attempting uninstall: imgaug
    Found existing installation: imgaug 0.4.0
    Uninstalling imgaug-0.4.0:
      Successfully uninstalled imgaug-0.4.0
Successfully installed albumentations-0.4.5 imgaug-0.2.6
```

It basically downgraded my `imgaug` version, because of which I face the following error in that library:
https://github.com/aleju/imgaug/issues/490

Please modify your `setup.py` to support the latest `imgaug` after testing if the latest one works.
Cheers!

**Comment by ternaus** [comment]
Fixed in https://github.com/albumentations-team/albumentations/pull/658.
