### ISSUE TITLE
[Feature Request] Add Bbox support to CoarseDropout

### ISSUE THREAD

**Issue by cswwp** [albumentations-team/albumentations#666]
I try to use random block dropout with albu, but it seems some bbox with Occluded not remove, Does albu's CoarseDropout support object detection augment?

![image](https://user-images.githubusercontent.com/11901683/88254314-7cb57580-cce7-11ea-8c97-fa5275a7e30c.png)
and my code is followed
![image](https://user-images.githubusercontent.com/11901683/88254337-98b91700-cce7-11ea-8188-6e84fe87f3b8.png)

**Comment by Dipet** [comment]
Hi!
At this time CoarseDropout does not support targets. It is works only on pixel level.
All transforms, that supports targets, you can see here: https://github.com/albumentations-team/albumentations#spatial-level-transforms

**Comment by cswwp** [comment]
> https://github.com/albumentations-team/albumentations#spatial-level-transforms

Yes, i find it, and i just rewrite a method with numpy to achieve

**Comment by cswwp** [comment]
look forward albu will support this method, it will boost the result especially in Scenes with Occlude

**Comment by msat59** [comment]
still not supported?

**Comment by folkien** [comment]
Is it supported now?

**Comment by ternaus** [comment]
As there is demand, let's reopen this as a Feature request

**Comment by ternaus** [comment]
@cswwp @msat59 @folkien 

Added in https://github.com/albumentations-team/albumentations/pull/1953

You can check in the UI tool at https://explore.albumentations.ai/transform/CoarseDropout
