### ISSUE TITLE
How to make an equivalent migration from torchvision.transforms.ColorJitter to  albumentations

### ISSUE THREAD

**Issue by yaox12** [albumentations-team/albumentations#672]
`torchvision.transforms.ColorJitter` randomly changes the brightness, contrast and saturation of an image.

I find that `albumentations.augmentations.transforms.RandomBrightnessContrast` provides similar api for changing brightness and constrast, while `albumentations.augmentations.transforms.HueSaturationValue` seems to have very different args. 

In `ColorJitter`, saturation and hue accept small float numbers, e.g., 0.2. Then the saturation_factor is chosen uniformly from [max(0, 1 - saturation), 1 + saturation] or the given [min, max] and hue_factor is chosen uniformly from [-hue, hue] or the given [min, max].
While in `HueSaturationValue`, hue_shift_limit and sat_shift_limit accept large int numbers. So how can I make an equivalent migration from `torchvision.transforms.ColorJitter` to `albumentations` without much domain knowledge about image processing?

**Comment by Dipet** [comment]
In `HueSaturationValue` arguments is absolute value, so if your image has `float` data type you do not need change anything, because values in in float images in range `[0, 1]`. If image has `uint8` data type you need multiply torchvision factor value to 255.
For example this transforms get similar results:
```python
torchvision.transforms.ColorJitter(brightness=0, contrast=0, saturation=0.6, hue=0.8)
A.HueSaturationValue(hue_shift_limit=int(0.8 * 255), sat_shift_limit=int(0.6 * 255), val_shift_limit=0)
```

**Comment by yaox12** [comment]
@Dipet Thank you very much!

**Comment by Dipet** [comment]
A little fix, `hue` in range `[0, 180]` for `uint8` data type, so we need change this values `hue_shift_limit=int(0.8 * 180)`
And hue in range `[0, 360]` for `float32` data type. So hue limit changes to `hue_shift_limit=int(0.8 * 360)`
