### ISSUE TITLE
Support passing 'sigma' as an argument for GaussianBlur

### ISSUE THREAD

**Issue by yaox12** [albumentations-team/albumentations#673]
In recent self-supervised learning papers, they usually adopt the `GaussianBlur` augmentation with a random standard
deviation `sigma`. For example, in SimCLR [[code]](https://github.com/google-research/simclr) [[paper]](https://arxiv.org/abs/2002.05709), they randomly sample sigma in [0.1, 2.0]. I hope you can support this feature.

**Comment by Dipet** [comment]
Unfortunately at this time you can not set range for sigma value. In current implementation sigma value computes from kernel size.
For example:
- `ksize=3, sigma=0.8`
- `ksize=5, sigma=1.1`
- `ksize=7, sigma=1.4`

**Comment by yaox12** [comment]
@Dipet Thank you for your fast response!
I have read the updated code and I'm wondering whether we can use a **fixed kernel size** while **random sigma** with the new code? For example, in SimCLR, they use a fixed kernel size of 23 with sigma uniformly sampled from [0.1, 2.0].

**Comment by Dipet** [comment]
Yes, you can set fixed kernel size like `blur_limit=[23, 23]`, it is docs issue.

**Comment by Dipet** [comment]
The changes are merged.
