### ISSUE TITLE
Equivalent of `imgaug.augmenters.Resize` 

### ISSUE THREAD

**Issue by tengerye** [albumentations-team/albumentations#675]
Hi, in `imgaug`, we can randomly change the size of an image (NOT keeping the ratio). May I ask how can I do that in `albumentations`? It seems if I want to resize the image, I have to provide the destination height and width? But that's not reasonable if my images have different sizes.

**Comment by Dipet** [comment]
Hello.
Library does not have transform, that can resize without keeping the ratio.
You can use RandomScale, but transform will keep ratio.
Also you can write your own transform, like this:
```python
import albumentations as A
import numpy as np
import cv2 as cv


class RandomResize(A.Resize):
    def __init__(self, height_limit=(100, 500), width_limit=(100, 500), interpolation=cv.INTER_LINEAR, always_apply=False, p=1):
        super(RandomResize, self).__init__(0, 0, interpolation, always_apply, p=p)
        self.height_limit = height_limit
        self.width_limit = width_limit

    def get_params(self):
        # This function will be called before each transformation.

        # Set result height and width
        self.height = np.random.randint(*self.height_limit)
        self.width = np.random.randint(*self.width_limit)

        return {}

    def get_transform_init_args_names(self):
        # Need for serialization and correct string representation
        return ("height_limit", "width_limit", "interpolation")


image = np.zeros([1000, 1000, 3], dtype=np.uint8)
transform = A.Compose([RandomResize()])

for i in range(10):
    print(transform(image=image)['image'].shape)
```

**Comment by tengerye** [comment]
Hi @Dipet , thank you for your kind reply. I strongly recommend adding the feature that can randomly scale the image with random ratio of height and width with PADDING. Random pyramid scaling is so common in computer vision.

**Comment by Dipet** [comment]
If you need padding use `albumentations.PadIfNeeded` combined with resize transform: `A.Compose([A.RandomScale(), A.PadIfNeeded()])`.
For random scaling we have `albumentations.RansomScale`.
I do not think that randomly changing aspect ratio is good idea. I think this approach will give many false positive results in real world.

**Comment by tengerye** [comment]
Hi @Dipet , I see your point. There are two reasons hope you would kindly consider. The first is if randomness is restricted to a limit, there will be no false positive (it is similar as other augments methods). The second is it will help attracting more users from other tools, like me.  It will be easier for user to choose use a method or not than implementing one himself.
