### ISSUE TITLE
Cutout and CoarseDropout should be setting height/width based on percentage not absolute pixel value

### ISSUE THREAD

**Issue by bfeeny** [albumentations-team/albumentations#676]
In Cutout and CoarseDropout you should be allowing the height/width to be set by percentage of the image not just absolute pixels.  example height=.2

**Comment by ternaus** [comment]
@bfeeny 

`CutOut` was deprecated in favor of `CoarseDropout`

As of today, `CoarseDroput` could pick holes bases on pixel values and percentage of height, width.

Would you consider becoming a sponsor for the project to make work being peformed faster?

https://github.com/sponsors/albumentations-team
