### ISSUE TITLE
Equivalent of 'imgaug.augmenters.size.PadToSquare' in albumentations

### ISSUE THREAD

**Issue by akum04** [albumentations-team/albumentations#678]
I'm new to albumentations, I'm trying to pad the image with different aspect ratios to square one, the input image sizes are different for each image. RESIZE option changes the geometry of the object within the image. How to implement the 'pad to square' (helps keeping the original geometry of the target object). Also, want to transform the  associated keypoints as well.

**Comment by ternaus** [comment]
[PadIfNeeded](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.PadIfNeeded) will pad to the desired square. Associated key points will be transformed as well.

**Comment by akum04** [comment]
PadIfNeeded requires min_height and min_width parameters to be defined. But what if the input sizes are different for each image in the list of images and would like to pad them to square before preforming RESIZE to desired input size.

**Comment by Dipet** [comment]
You can use different approach: resize with keep ratio and than pad to square
```python
Compose([
    LongestMaxSize(512),
    PadIfNeeded(512, 512)
])
```

**Comment by akum04** [comment]
@Dipet Thanks. It solves the problem.

**Comment by aparico** [comment]
Hi @Dipet. How to do black padding instead of mirroring?

**Comment by Dipet** [comment]
@aparico 
```python
import cv2
A.PadIfNeeded(512, 512, border_mode=cv2.BORDER_CONSTANT, value=0)
```
