### ISSUE TITLE
AssertionError: force_apply must have bool or int type

### ISSUE THREAD

**Issue by adriangrepo** [albumentations-team/albumentations#680]
Sample code to reproduce error:

```
from PIL import Image
import albumentations as A
from albumentations.pytorch import ToTensorV2

image= Image.open('some_image.png').convert('RGB')

albu_image_transform = A.Compose(
    [
        A.Resize(224, 224),
        ToTensorV2()
    ]
)

def visualize(image):
    plt.figure(figsize=(10, 10))
    plt.axis('off')
    plt.imshow(image)
    
print(type(image))
#PIL to cv2
image=np.array(image)
image[...,[0,2]]=image[...,[2,0]]   
print(image.shape)
augmented_image = albu_image_transform(image) #error here
                          
visualize(augmented_image)
```
>>
<class 'PIL.Image.Image'>
(400, 265, 3)

AssertionError                            Traceback (most recent call last)
<ipython-input-27-01d25b293057> in <module>
     29 image[...,[0,2]]=image[...,[2,0]]
     30 print(image.shape)
---> 31 augmented_image = albu_image_transform(image)
     32 
     33 visualize(augmented_image)

~/env/lib/python3.8/site-packages/albumentations/core/composition.py in __call__(self, force_apply, **data)
    162 
    163     def __call__(self, force_apply=False, **data):
--> 164         assert isinstance(force_apply, (bool, int)), "force_apply must have bool or int type"
    165         need_to_run = force_apply or random.random() < self.p
    166         for p in self.processors.values():AssertionError: force_apply must have bool or int type

Not sure what I'm doing wrongly

**Comment by Dipet** [comment]
Use named arguments:
```
albu_image_transform(image=image)
````
