### ISSUE TITLE
CLAHE not deterministic

### ISSUE THREAD

**Issue by a1302z** [albumentations-team/albumentations#682]
## 🐛 Bug

If you apply CLAHE multiple times to the same image you get different results each time. Doesn't matter if image or clahe are reinitialized every time or not, never the exact same result.

## To Reproduce

```
import albumentations as a
import numpy as np
from PIL import Image
c = a.CLAHE(always_apply=True, p=1.0)
img = Image.open(_path_to_img_)
img = np.array(img)
c(image=img)["image"].mean()
```
gives different results every time its executed. For my application it would be crucial to be deterministic.

## Expected behavior

Everytime the code above is executed you get the exact same result.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.6
 - Python version (e.g., 3.7): 3.7.1
 - OS (e.g., Linux): Kubuntu 20.04
 - How you installed albumentations (`conda`, `pip`, source): conda
 - Any other relevant information: None

**Comment by Dipet** [comment]
If you need same result set fixed `clip_limit` by default it is in range `[1, 4]`
For example:
```python
A.CLAHE(clip_limit=(4, 4), always_apply=True, p=1.0)]
```

**Comment by a1302z** [comment]
Thanks, sorry I missed that.
