### ISSUE TITLE
can I use it for video?

### ISSUE THREAD

**Issue by seyeeet** [albumentations-team/albumentations#683]
Im following the example [here](https://github.com/albumentations-team/albumentations_examples/blob/master/notebooks/example.ipynb) regarding how to apply it on images.
Can I use it on video data? or I have to apply it frame by frame?
for example if I have a 3xTxWxH data, should I apply augmentation of each frame separately or there is a way to do it on all T frames at once?
Thanks

**Comment by Dipet** [comment]
At this time you can provide [additional_targets](https://albumentations.ai/docs/examples/example_multi_target/) to work with sequences of images.
We will try to add more clear API for work with images, but we can not tell how many time it's need.

**Comment by dav-ell** [comment]
Also interested in support for this feature.

**Comment by ternaus** [comment]
@dav-ell @seyeeet @jah456 

You may use images target to pass a list of frames.



```python
transformed = transform(images=[image1, imag2, image3])
transformed_images = transformed["images"]
```
