### ISSUE TITLE
A suggestion about `ToTensorV2`.

### ISSUE THREAD

**Issue by lartpang** [albumentations-team/albumentations#687]
https://github.com/albumentations-team/albumentations/blob/73cac2f5e56284d5ad06647356edcb134e141af8/albumentations/pytorch/transforms.py#L96-L97

A suggestion. 

If mask is a grayscale image, is it worthwhile to consider inserting a separate channel dimension here to avoid the need for users to execute `mask = mask.unsqueeze(0) ` after `ToTensorV2`.

Here is my code demo:

```python
        transformed = self.joint_transform(image=curr_img, flow=curr_flow, mask=curr_mask)
        curr_img = transformed["image"]
        curr_flow = transformed["flow"]
        curr_mask = transformed["mask"]
        curr_mask = curr_mask.unsqueeze(0)
        return curr_img, curr_flow, curr_mask
```

**Comment by GuillaumeTong** [comment]
I would like to add that for images with 3 dimensions (in my case just a single color channel just to sync up the dimensions with the image), it is very unnatural how only the image's dimensions are transposed:
`
    def apply(self, img, **params):  # skipcq: PYL-W0613
        return torch.from_numpy(img.transpose(2, 0, 1))

    def apply_to_mask(self, mask, **params):  # skipcq: PYL-W0613
        return torch.from_numpy(mask)`
I had to manually squeeze the mask to get rid of the dimension, then unsqueeze it after transformation like @lartpang above.

**Comment by JVGD** [comment]
Yes! I had to write a custom TensorV2 transform! I really think this Issue is necessary, my contribution:

```python
 def apply_to_mask(self, mask, **params):
        """Mask from numpy [H, W] to tensor [1, H, W]"""
        # Adding channel to first dim if mask has no channel
        if mask.ndim == 2:
            mask = np.expand_dims(mask, axis=0)
        # Transposing channel to channel first if mask has channel
        elif mask.ndim == 3:
            # [H, W, C] to tensor [C, H, W] in case mask has C > 1
            mask = mask.transpose(2, 0, 1)
        else:
            raise ValueError('Mask should have shape [H, W] without, '
                             'channel however provided mask shape was: '
                             '{}'.format(mask.shape))
        # To numpy
        return torch.from_numpy(mask)
```

**Comment by kielnino** [comment]
In the [documentation](https://albumentations.ai/docs/getting_started/mask_augmentation/), the use of multiple masks is mentioned. At the moment I have to use `additional_targets` for `ToTensorV2` to work. Is there a chance to get it working with the `masks` parameter?

**Comment by JVGD** [comment]
Yes yes, but that is a very basic usage. Say you want to do this simple feature: create a transform that given a tuple of (image, boxes, mask) in numpy it transforms it to torch.Tensor... How would you do it? Well, I come up with this, but to the best of my knowledge, how to do more advanced  stuff is not documented.

```python
class ToTensorCustom(A.BasicTransform):
    """Convert image and mask to `torch.Tensor`
    * Image numpy: [H, W, C] -> Image tensor: [C, H, W]
    * Mask numpy: [H, W, 1] -> Mask tensor: [1, H, W]
    """
    def __init__(self, always_apply=True, p=1.0):
        super().__init__(always_apply=always_apply, p=p)

    @property
    def targets(self):
        return {"image": self.apply, "mask": self.apply_to_mask}

    def apply(self, img, **params):
        """Image from numpy [H, W, C] to tensor [C, H, W]"""
        return torch.from_numpy(img.transpose(2, 0, 1))

    def apply_to_mask(self, mask, **params):
        """Mask from numpy [H, W] to tensor [1, H, W]"""
        # Adding channel to first dim if mask has no channel
        if mask.ndim == 2:
            mask = np.expand_dims(mask, axis=0)
        # Transposing channel to channel first if mask has channel
        elif mask.ndim == 3:
            # [H, W, C] to tensor [C, H, W] in case mask has C > 1
            mask = mask.transpose(2, 0, 1)
        else:
            raise ValueError('Mask should have shape [H, W] without, '
                             'channel however provided mask shape was: '
                             '{}'.format(mask.shape))
        # To numpy
        return torch.from_numpy(mask)
```

So far so good. But I have not been able to do the same for bounding boxes. I know you have to add it to the targets (which is just slightly mentioned in the docstring from the core.py...) but I tried everything (including using a DualTrasnform) and could not get it working. So I think this should be better documented, what is the flow of the albumentations lib, I went through it with the debugger but it is not very clear (specially the argument passing to the functions transforms)
