### ISSUE TITLE
Can't send several masks

### ISSUE THREAD

**Issue by Khoa-NT** [albumentations-team/albumentations#691]
## 🐛 Bug

I can't input several masks to target following this tutorial  [One image and several masks](https://medium.com/pytorch/multi-target-in-albumentations-16a777e9006e) or this [tutorial](https://albumentations.ai/docs/getting_started/mask_augmentation/).

## To Reproduce

```python
import numpy as np
import albumentations as A

transform = A.Compose([
    A.RandomCrop(width=5, height=5),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
])

image = np.arange(100, dtype="uint8").reshape([10,10])
target = np.arange(100, dtype="uint8").reshape([10,10])

masks = [target, target, target]
transformed = transform(image=image, mask=masks)
```

**Error messages**
```
AttributeError: 'list' object has no attribute 'shape'
```
## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.6
 - Python version (e.g., 3.7): 3.7
 - OS (e.g., Linux): Linux 
 - How you installed albumentations (`conda`, `pip`, source):  **pip**
 - Any other relevant information:

**Comment by BloodAxe** [comment]
Try masks=... and not mask=

пн, 31 авг. 2020 г. в 5:22 PM, Khoa Nguyen-Tuan <notifications@github.com>:
