### ISSUE TITLE
module 'albumentations' has no attribute 'pytorch'

### ISSUE THREAD

**Issue by chasimyeong** [albumentations-team/albumentations#692]
## 🐛 Bug

I want to use albumentations.pytorch library. but I get an error that there is no library.

## To Reproduce

```
import albumentations
import torch
print(albumentations.__version__)
```
`'0.4.6'`

```
albumentations.pytorch.transforms.ToTensor()
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-79-76ed98043096> in <module>()
----> 1 albumentations.pytorch.transforms.ToTensor()

AttributeError: module 'albumentations' has no attribute 'pytorch'
```

## Environment
 - Albumentations version (e.g., 0.4.6):
 - Python version (e.g., 3.6.9):
 - OS (e.g., Linux): google colaboratory
 - How you installed albumentations (`conda`, `pip`, source): 
!pip install -U git+https://github.com/albumentations-team/albumentations

**Comment by Dipet** [comment]
If you need to use `albumentations.pytorch` you need it import directly `import albumentations.pytorch`.
