### ISSUE TITLE
How can i keep the keypoint_params result which is out of bound?

### ISSUE THREAD

**Issue by sierenavg** [albumentations-team/albumentations#694]
I tried to use this fuction . 

 transform = A.Compose(
        [A.ShiftScaleRotate(shift_limit=translate, scale_limit=scale, rotate_limit=degrees, interpolation=1, 
                          border_mode=cv2.BORDER_CONSTANT, value=None, mask_value=None, always_apply=False, p=1),
         A.imgaug.transforms.IAAAffine(shear=shear) ,
        ], 
        keypoint_params=A.KeypointParams(format='xy')
    ) 
transformed = transform(image=img, keypoints=tmpkeypoints)
resultLabel=transformed['keypoints']

This function works perfect but the "keypoint_params" always remove the points outside of the image .

What can i do if i want to keep all points? 

Please help me , thank you very much.

**Comment by Dipet** [comment]
Set `keypoint_params=A.KeypointParams(format='xy', remove_invisible=False)`

**Comment by sierenavg** [comment]
thank you very much for your help. You save the day 👍
