### ISSUE TITLE
Is there a HueSaturationLightness (to recreate torchvision.transforms.ColorJitter)?

### ISSUE THREAD

**Issue by cgebbe** [albumentations-team/albumentations#698]
I wanted to reproduce the behavior of torchvision.transforms.ColorJitter, similar to these existing threads
- https://github.com/albumentations-team/albumentations/issues/693
- https://github.com/albumentations-team/albumentations/issues/672
- https://github.com/albumentations-team/albumentations/issues/589

For now, I am only focusing on adjusting the **saturation** using albumentations in (nearly) the same way as using torchvision:
```
sat_shift = 0.5
torch_aug = torchvision.transforms.ColorJitter.get_params(saturation=sat_shift)
album_aug = A.HueSaturationValue(hue_shift_limit=0,
                                 sat_shift_limit=int(sat_shift * 255),
                                 val_shift_limit=0,
                                 p=1.0,
                                 ),
```
# Expected result
Augmented images are more or less the same

# Actual result
![test_aug_5](https://user-images.githubusercontent.com/4158176/92602131-05936b00-f2ae-11ea-92d7-ffb96e36e1a2.png)

- Torchvision seems to apply saturation shift in something like HSL space (they actually convert to black-white 'L' space and then blend using PIL, so not 100% sure whether it is really HSL space). Anyhow, white stays white
- In contrast, albumentations applies saturation shift in HSV space. Thereby, white can become a color (e.g. red)! I was actually quite surprised to see this. It does make total sense, since we are using HSV space. But this behavior is definitely different than changing the saturation slider in photoshop/GIMP.

# Conclusion
Is there any other transformation which changes saturation in the HSL space or HL-Chroma space similar to photoshop/GIMP?

**Comment by Dipet** [comment]
We now have our version of `ColorJitter`, look to PR #705 fo details

**Comment by Dipet** [comment]
Ooops, my fault, PR is not merged....

**Comment by Dipet** [comment]
Finally we are added our implementation of `CollorJitter` that equal to torchvision transform.
