### ISSUE TITLE
Add dependency to `opencv-contrib-python` and `opencv-contrib-python-headless`

### ISSUE THREAD

**Issue by tastelessjolt** [albumentations-team/albumentations#707]
## 🐛 Add dependency to `opencv-contrib-python` and `opencv-contrib-python-headless`

Not exactly a bug. If other parts of the code use extra modules provided by the contrib module, but also want to use `albumentations`. 

## To Reproduce

1. Install `albumentations` in an environment where `cv2` is provided by `opencv-contrib-python` or `opencv-contrib-python-headless`

## Expected behavior

Can take the `opencv-contrib-python` or `opencv-contrib-python-headless` as dependencies while installing

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.6
 - Python version (e.g., 3.7): 3.7
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

## Additional context

Reference for what these packages provide: https://github.com/skvark/opencv-python#installation-and-usage

Maybe you can add these entries in here. 
https://github.com/albumentations-team/albumentations/blob/7f099adbb3ee1a88f6f0fc284cecfc68acec8cae/setup.py#L11

**Comment by agchang-cgl** [comment]
+1, this makes it a pain to use in a production system that needs the `opencv-contrib-*` dependency.

**Comment by Dipet** [comment]
Fixed in #837
