### ISSUE TITLE
Return crop info x_start, y_start, w, h, scale etc.

### ISSUE THREAD

**Issue by Antsypc** [albumentations-team/albumentations#712]
After processing below, I want to get actually crop information such as cropped image x coordinate starts from the original image, y_start, scale size, width and height of cropped information, etc. 

```python
transforms = A.Compose(
    [A.RandomResizedCrop(), A.RandomCrop()],
    bbox_params=xx,
    keypoint_params=xx
)
```

So that, I can map bounding boxes and keypoints to original image, it's userful for object detection and landmark detection in predict/test stage. If there is no crop info, i cannot use any random transforms.

I'm a beginner of albumentations, maybe there is another way to do this, thanks for your help.

**Comment by BloodAxe** [comment]
Greetings. Maintainer here. Can you please elaborate more on what you're trying to achieve?
Albumentations supports boxes & keypoints augmentations as first-class citizens - https://github.com/albumentations-team/albumentations_examples/blob/master/notebooks/example_bboxes.ipynb and you can also trace what augmentation has been applied using `A.ReplayCompose` mechanism. Demo: https://github.com/albumentations-team/albumentations_examples/blob/master/notebooks/replay.ipynb
Hope it helps.
