### ISSUE TITLE
Masks not placed correctly after augmentation

### ISSUE THREAD

**Issue by LAUBENicolas** [albumentations-team/albumentations#713]
## 🐛 Bug

Hello, I'm currently doing augmentation for my segmentation model to avoid overfitting.
For that purpose, I created a class ```Augmentator```.
The problem I'm facing is that after the augmentation process, the masks aren't at the correct place.

![image](https://user-images.githubusercontent.com/51950336/94779468-4a02ba00-03c7-11eb-8143-22dbcfe7dc26.png)
*original image comes from the NSCLC Radiomics Lungs dataset: Aerts, H. J. W. L., Wee, L., Rios Velazquez, E., Leijenaar, R. T. H., Parmar, C., Grossmann, P., … Lambin, P. (2019). Data From NSCLC-Radiomics [Data set]. The Cancer Imaging Archive. https://doi.org/10.7937/K9/TCIA.2015.PF0M9REI

My input images range between 0 and 255 (integers) and my input masks range between 0 and 1 (interger).

## To Reproduce

Here is my augmentation class:

```
class Augmentator():
    def __init__(self, augmentation_type: str):
        self.augmentation_type = augmentation_type
        self.image_size = None

    def augment_data(self, image: NDArray[(Any, Any), np.uint8], mask: NDArray[(Any, Any), np.uint8]) -> Tuple[NDArray[(Any, Any), np.uint8], NDArray[(Any, Any), np.uint8]]:
        data = {"image": image, "mask": mask}
        print("max first image: ", np.max(image))
        print("min first image: ", np.min(image))
        print("max first mask: ", np.max(mask))
        print("min first mask: ", np.min(mask))
        self.image_size = [image.shape[0], image.shape[1]]
        augmentation = self.transformations()
        augmented = augmentation(**data)
        augmented_image, augmented_mask = augmented["image"], augmented["mask"]
        return augmented_image, augmented_mask

    def transformations(self, proba=0.7):
        """
        Applies the transformations to the data.
        ---
        Lambda can be added to use custom functions
        """
        if self.augmentation_type == "train":
            transforms = [
                HorizontalFlip(p=0.5),
                ShiftScaleRotate(scale_limit=0.5, rotate_limit=45, shift_limit=0.1, p=1, border_mode=0),
                PadIfNeeded(min_height=self.image_size[0], min_width=self.image_size[1], always_apply=True, border_mode=0),
                # use crandom crop to be sure that the image has the same size
                RandomCrop(height=self.image_size[0], width=self.image_size[1], always_apply=True),
                IAAAdditiveGaussianNoise(p=0.2),
                OneOf([
                    CLAHE(p=1),
                    RandomBrightness(p=1),
                    RandomGamma(p=1)
                ], p=0.9),
                OneOf([
                    RandomContrast(p=1),
                    Blur(blur_limit=3, p=1)
                ], p=0.9),
                OneOf([
                    GridDistortion(num_steps=10, p=1, interpolation=0, border_mode=0),
                    ElasticTransform(alpha=1, sigma=50, alpha_affine=50, interpolation=1,\
                        border_mode=4, value=None, mask_value=None, always_apply=True, approximate=False, p=1)
                ], p=0.9)
            ]
        elif self.augmentation_type == "test":
            print("ndfvojvofdjvofj")
            transforms = []
        else:
            raise ValueError("augmentation type is not recognized. Values should be in ['train', 'test'].")
        return Compose(transforms, p=proba)
```

Afterwards, I call the class and the augmented mask and image thanks to:
```image, mask = self.augmentator.augment_data(image, mask)```

**Comment by BloodAxe** [comment]
Can you please attach original image and mask?

**Comment by Dipet** [comment]
I can not reproduce problem with example image.
Can you show problem on the image? Also would be great if you get example with fixed random seeds to reproduce problem.
![image](https://user-images.githubusercontent.com/7512250/94783529-7de4dc00-03d5-11eb-9e11-e5ffcfd5ae2b.png)
![image](https://user-images.githubusercontent.com/7512250/94783539-82a99000-03d5-11eb-8e24-78a563d013d1.png)

**Comment by LAUBENicolas** [comment]
Thank you for your answers.

I tried to visualize the results launching my ```augment_data()``` function directly on the images and it worked correctly.
So it seems that the problem is coming from my ```batchloader```.

All is ok.
