### ISSUE TITLE
[QUESTION] What is the expected input ? 

### ISSUE THREAD

**Issue by LAUBENicolas** [albumentations-team/albumentations#714]
I have a few questions about the accepted inputs.

Is it possible to enter an input image in gray levels i.e. of shape ```(width, height)```, or should I always specify a channel (i.e. ```(width, height, 1)```) ?
Which transforms still work afterwards ?

I have the same question for the masks, should the masks be of dimension ```(width, height)``` or ```(width, height, 1)``` ?

Besides, is it possible to enter multiple images at the same time ?

Last but not least, is there an expected range of values ?
If understood well, the image and mask should be ```uint8```, but is it better/equal to input a mask ranging from 0->1 or 0-> 255.0
I suppose that it doesn't matter but if someone can confirm it for me.

Thanks in advance.

**Comment by Dipet** [comment]
You can provide images in both formats: `(height, width)` and `(height, width, 1)`.
Most of transforms will work fine with grayscale images. But for obvious reasons some transforms doesn't work like `RGBShift`.
For mask same rules as for images.

With current API you can provide multiple mask using keyword `mask` like this: `transforms(image=image, masks=[mask1, mask2])`. You also can provide multiple images, but you need describe `additional_targets` for this puprose. More info about `additional_targets` here: https://albumentations.ai/docs/examples/example_multi_target/

For images the following ranges:
- `uint8` - `[0, 255]`
- `float32` - `[0, 1]`

For masks you can use full diapason of values, but is customary to use range `[0, 1]`

But I advise you to check pipeline before using it to avoid problems.

**Comment by LAUBENicolas** [comment]
Thanks a lot for your answer ! What do you mean by check pipeline ?

**Comment by Dipet** [comment]
Just take few images from your dataset and see how they look after transforms.
