### ISSUE TITLE
Working with keras-ocr: float32 errors, non-square bounding boxes, and speed

### ISSUE THREAD

**Issue by fingoldo** [albumentations-team/albumentations#717]
I am trying to extend keras-ocr with albumentations by wrapping its native image generator with custom one:

```python
def get_image_generator(**args):
    import albumentations as A
    
    p=0.9
    pipe=A.Compose([
        ### Weather
        A.OneOf([
            A.RandomRain(p=p),
            A.RandomSunFlare(flare_roi=(0, 0, 1, 0.5), angle_lower=0.5, p=p),
            A.RandomShadow(num_shadows_lower=1, num_shadows_upper=3, shadow_dimension=7, shadow_roi=(0, 0.5, 1, 1), p=p),
        ],p=p),
        ### Colors, channels
        A.OneOf([
            A.RGBShift(r_shift_limit=15, g_shift_limit=15, b_shift_limit=15,p=p),
            A.ToGray(p=p,),
            A.ToSepia(p=p,),
            A.RandomBrightnessContrast(p=p),
            A.RandomGamma(p=p)    ,
            A.HueSaturationValue(hue_shift_limit=20, sat_shift_limit=50, val_shift_limit=50, p=p),
            A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225),p=p),
            A.Equalize(p=p,),
            A.ChannelShuffle(p=p),
            A.ChannelDropout(p=p),        
        ],p=p),
        
        ### Blurring/sharpening
        A.OneOf([
            A.Blur(p=p,blur_limit=30),   
            A.GlassBlur(p=p,),
            A.MotionBlur(p=p,blur_limit=20),
            A.MedianBlur(blur_limit=9, p=p),   
            A.IAASharpen(p=p,),        
        ],p=p),
        ### Noise
        A.OneOf([
            A.IAAAdditiveGaussianNoise(p=p,),
            A.GaussNoise(p=p,),   
            A.CoarseDropout (p=p,max_height=40,max_width=40),
            A.Downscale(p=p,),
            A.MultiplicativeNoise(p=p,multiplier=(1.1,8)),
            A.IAASuperpixels(p=p),        
        ],p=p),
        ],p=0.5)
    inner_gen=keras_ocr.data_generation.get_image_generator(**args)
    for image,lines in inner_gen:
        new_image=pipe(image=image)['image']
        new_lines=lines
        yield new_image, new_lines
```
**1) I am randomly getting several kinds of errors when running this pipeline:**

> ~/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/imgaug/dtypes.py in gate_dtypes(dtypes, allowed, disallowed, augmenter)
>     330                     augmenter.name,
>     331                     augmenter.__class__.__name__,
> --> 332                     ", ".join(disallowed)
>     333                 ))
>     334         else:
> 
> ValueError: Got dtype 'float32' in augmenter 'UnnamedSuperpixels' (class 'Superpixels'), which is a forbidden dtype (uint128, uint256, int128, int256, float16, float32, float64, float96, float128, float256).

and 

>   File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 759, in median_blur
>     "Invalid ksize value {}. For a float32 image the only valid ksize values are 3 and 5".format(ksize)
> 
> ValueError: Invalid ksize value 7. For a float32 image the only valid ksize values are 3 and 5

Is this a know behaviour of IAASuperpixelsand MedianBlur transforms in a pipeline? How can I assure they always get input of uint8 format, if it's obviously previous transforms in my pipeline which return float32 ('cause keras-ocr returns image = (alpha * text_image[..., :3] + (1 - alpha) * current_background).astype('uint8'))? Also, as I'm feeding outputs to a neural network, is there a way to guarantee a pipeline to always return rescaled images?

**2) Speed consideration:**

Abovementioned pipeline has average generation speed of 3.81 im/sec on 800x600 size images, compared with 4.26 im/s native performance of the keras-ocr generator. CPU is 100% busy. Is ~0.5 sec/image albumentations overhead normal to expect?

**3) Bounding boxes**

I can't use spatial transformations, because albumentations seems to only support 2-points, 4 coordinates notation for bounding boxes, and they are expected to be rectangular and strictly parallel to the x,y axes. Which is not the case with 
 [keras-ocr](https://freeimage.host/i/2XEyjR), which uses 4 points, 8 coordinates to store its bounding boxes. Are there any plans to support such extended format of bounding boxes in albumentations? Do you have any advice for my use case?

**My system info:**

_Albumentations: 0.4.6
Tensorflow: 2.3.0
System Platform: linux
System Platform: linux
System Version: 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
Machine: x86_64
Platform: Linux-5.3.0-1035-aws-x86_64-with-debian-buster-sid
Pocessor: x86_64
System OS: Linux
Release: 5.3.0-1035-aws
Version: #37-Ubuntu SMP Sun Sep 6 01:17:09 UTC 2020
Number of CPUs: 8
Number of Physical CPUs: 4_

**Comment by BloodAxe** [comment]
Greetings.

1)
Usually all augmentation transforms i. Albumentations has docs, which
states what image types are supported. For sake speed it’s recommended to
stay within uint8 style as it could be up to 4 times faster than float32.

Usually you want A.Normaize to be a last operation in your pipeline.

 2)
When we compare speed, it’s always to measure apples to apples. Could you
show augmentation pipeline in keras that you comparing to?


3) 4-corner polygons is a different kind of targets, which is good to have.
Yet it is not on the roadmap. However we are very open to PR with new
features

пн, 5 окт. 2020 г. в 8:34 AM, fingoldo <notifications@github.com>:

**Comment by fingoldo** [comment]
Oh. So, errors happen due to Normalize call, I did not realize that from start, thank you! I removed Normalize entirely, because actually for training a Detector it's not needed, and for training a Recognizer keras-ocr does scaling to 0..1 on its own. Now all my images are uint8 throughout whole pipeline, errors are gone, however, there is no visible speed improvement.

Regarding 2), ~0.5 sec per image is pure overhead of Albumentations, compared to a "clean" keras-ocr pipeline. Is it normal? Seems a bit high for a modern CPU, or not?

Also, I forgot to mention, are there any plans to move at least some of transforms to GPU? As it's not utilized at all, while CPU is struggling and is an obvious bottleneck in the ML pipeline.

**Comment by Dipet** [comment]
Can you provide keras pipeline that is faster, than Albumentations?
I will be very grateful to see it and trying to improve Albumentations results.
Maybe albumentations used single thread? Many our transforms by default used single thread, but keras can use more than 1 thread for some functions.

About GPU augmentations it is complex problem.
In many cases we can not have enough memory and GPU power to do augmentations on GPU. For this reason current strategy to delegate part of work to CPU. When CPU do augmentations GPU do inference on another batch.
At this time I recommend to use [kornia](https://github.com/kornia/kornia) or [DALI](https://github.com/NVIDIA/DALI) if you need GPU augmentations.

**Comment by fingoldo** [comment]
> Can you provide keras pipeline that is faster, than Albumentations?
> I will be very grateful to see it and trying to improve Albumentations results.
> Maybe albumentations used single thread? Many our transforms by default used single thread, but keras can use more than 1 thread for some functions.
> 
> About GPU augmentations it is complex problem.
> In many cases we can not have enough memory and GPU power to do augmentations on GPU. For this reason current strategy to delegate part of work to CPU. When CPU do augmentations GPU do inference on another batch.
> At this time I recommend to use [kornia](https://github.com/kornia/kornia) or [DALI](https://github.com/NVIDIA/DALI) if you need GPU augmentations.

I did not mean keras pipeline was faster than Albumentations... Albumentations pipepline had much more different possible transformations to. I was just wondering if 0.5 sec is acceptable for a 800x600 image and the above mentioned pipeline. Thanks for pointing at Dali!

**Comment by Dipet** [comment]
Some of your transforms need expensive computations.
For example in your pipeline I see `GlassBlur`, this transform repeats `GaussianBlur` several times and do many substitutions on image.
If you will remove `GlassBlur` you will see high speed increase.

**Comment by fingoldo** [comment]
I just had another project with similar bottelneck. In my understanding, problem is that augmented images are used only once in a training cycle of a model, not even across several epochs. So it's a huge waste of GPU cycles while CPU is struggling. I considered DALI, but it is not keras-friendly, and my goal was to stay with Keras.
I found following solution: 
1) I generate as many augmentations in RAM as I can
2) I use them for training across a frame of epochs, 10 to 30, whatever it takes to get a noticeable convergence
3) after that I generate new batch of augmented images (by implementing on_epoch_end) and process goes on automatically.

This approach most of the time keeps GPU busy, while being able to benefit from data augmentation. I use custom Sequence subclass to generate augmentation and fix classes imbalance at the same time.

**Comment by fingoldo** [comment]
Do you guys have a recommended way to run many images through an albumentation pipeline so as to utilize all CPU cores available?

**Comment by Dipet** [comment]
All transforms are optimized to work in single thread.
Library assumes that you will manage with threads by himself, for example using multithreaded data loader from [pytorch](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader).
