### ISSUE TITLE
Resize image while maintaing the aspect ratio

### ISSUE THREAD

**Issue by misads** [albumentations-team/albumentations#718]
I want to resize image to a given longer edge (e.g. longer edge=416) while keeping the original aspect ratio. But I don't know what API to use.

I find `albumentations.augmentations.transforms.Resize()` must specify width and height parameter so that all the images will be resized to exactly the same size. 

https://github.com/albumentations-team/albumentations/blob/97b640fe1fcdc6d991a86bd44ec56cf3c02aae4e/albumentations/augmentations/transforms.py#L460-L461

How I must change the code so that I can resize image when keeping its original aspect ratio?

**Comment by misads** [comment]
I have found the API I needed `albumentations.augmentations.transforms.LongestMaxSize()`

**Comment by aparico** [comment]
> I have found the API I needed `albumentations.augmentations.transforms.LongestMaxSize()`

Hi @misads. Does it use black padding to keep the aspect ratio or does it crop the image?

**Comment by notmatthancock** [comment]
@aparico By itself, `LongestMaxSize` will resize the image and preserve aspect ratio. For example, if my image is `(2100, 3200)` and I use `LongestMaxSize(max_size=512)` then the result will be `(336, 512)`.

However, you can add additional transforms to your composition pipeline after `LongestMaxSize` to apply cropping or padding. E.g., you could use [`PadIfNeeded`](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.PadIfNeeded) to ensure the result is square `(512, 512)` using the padding mode of your choice.

**Comment by a-arbabian** [comment]
For future references to this thread, if you want to resize an image to NxN (while preserving aspect ratio) then 0/black pad the short side:
```   
A.LongestMaxSize(max_size=N, interpolation=1),
A.PadIfNeeded(min_height=N, min_width=N, border_mode=0, value=(0,0,0)),
```

By default `PadIfNeeded()` will mirror pad the border
