### ISSUE TITLE
Problem with Rotate for keypoints having the xysa format

### ISSUE THREAD

**Issue by sayantanauddy** [albumentations-team/albumentations#720]
## 🐛 Bug

I am working on a problem which involves predicting the location, scale, and orientation of keypoints in an image and hence I use Albumentations for image augmentation. When I use the different transforms for cropping, scaling, flipping, rotating by 90 degrees, etc. (location, scale and angle of the transformed keypoints look correct). However, when I use `Rotate`, only the location and scale of the transformed keypoints look correct, but the angle does not. I am using `xysa` as the format in A.KeypointParams, and have also specified `angle_in_degrees=False`. Could this be a problem in how the keypoint angles are handled?

## To Reproduce
To reproduce the issue, I made some minor changes to the example provided at https://albumentations.ai/docs/examples/example_keypoints/. I changed this notebook to use the `xysa` keypoint format instead of `xy`. As expected, everything except `Rotate` seems to work correctly for the keypoint angles.

1. Please view the notebook at https://colab.research.google.com/drive/1_9yp05aC1jLTRNQ2_c9HScnb69yMFj64?usp=sharing
2. All the modified code cells have the tag <font color="red">**Modified**</font> above them
3. The incorrect angles for `Rotate` can be seen in the displayed images

## Expected behavior

The angles of the keypoints should also rotate by the same angle as the image.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.6
 - Python version (e.g., 3.7): 3.6.9
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information: Ran in a Google colab notebook

**Comment by Dipet** [comment]
Hello. Problem with your visualization. To visualize point use this function: 
```python
def vis_keypoints(image, keypoints, diameter=15):
    image = image.copy()
    h, w = image.shape[:2]

    for (x, y, s, a) in keypoints:
        cv2.circle(image, (int(x), int(y)), diameter, KEYPOINT_COLOR, -1)

        # (x0,y0) is a point at an angle of `a` from (x,y) and at a distance of `s`
        x0 = x + s * np.cos(a)
        y0 = h - y + s * np.sin(a)
        y0 = h - y0
        cv2.arrowedLine(image, (int(x), int(y)), (int(x0), int(y0)), KEYPOINT_COLOR, 2)

    plt.axis('off')
    plt.imshow(image)
```
`np.pi / 2.0` it is equal to 90 degree, so arrow must look at the top of image. Positive angle means counter-clockwise rotation. It is common interpretations of angles.

**Comment by Dipet** [comment]
Use this function to visualize angles:
```python
def vis_keypoints(image, keypoints, diameter=15):
    image = image.copy()

    for (x, y, s, a) in keypoints:
        cv2.circle(image, (int(x), int(y)), diameter, KEYPOINT_COLOR, -1)

        # (x0,y0) is a point at an angle of `a` from (x,y) and at a distance of `s`
        x0 = x + s * np.cos(a)
        y0 = y - s * np.sin(a)
        cv2.arrowedLine(image, (int(x), int(y)), (int(x0), int(y0)), KEYPOINT_COLOR, 2)

    plt.axis('off')
    plt.imshow(image)
```
`np.pi / 2.0` equal to 90 degree, so arrow must look to the top of image. Positive angle means counter-clockwise rotation. Is is common interpretation of angles.
