### ISSUE TITLE
Transform on keypoints

### ISSUE THREAD

**Issue by JiayiLy** [albumentations-team/albumentations#728]
The content about keypoints is not as much in the documentation. Generally the 'keypoints' is a list containing fixed number of points. Does the transform change the order of  points in the input 'keypoints' list?

**Comment by Dipet** [comment]
Keypoints list may change in situations where we need to remove invisible keypoints. Otherwise, the order of the keypoints will be the same.
To ensure that the order hasn't  changed, you can add the keypoint index to the tail of the keypoint.

**Comment by JiayiLy** [comment]
Do you mean pass the keypoint index as a filed of label_fields to the transform?

**Comment by Dipet** [comment]
Yes, as an option.

**Comment by JiayiLy** [comment]
Another question. My keypoints is a nested list of (x, y) tuples like this:
```
[
 [(923, 517), (914, 526)], 
 [(1133, 553), (1156, 562), (1179, 571)], 
 [(147, 661), (105, 670), (62, 679), (20, 688)], 
 [(1000, 526), (1010, 535)],
]
```
That is I have keypoints of four faces. Each face has different keypoints. When I passed this nested list to transform, I got an error. So I flat the nested list, but this op will not make sense because some keypoints will lie out of image after one transform in a compose. Do you have any idea on how to process this question? Thank you

**Comment by JiayiLy** [comment]
It seems that I can use a filed of label_fields contains face id. Thank you
