### ISSUE TITLE
super(type, obj): obj must be an instance or subtype of type using Resize

### ISSUE THREAD

**Issue by WenfeiShen** [albumentations-team/albumentations#733]
## 🐛 Bug

Code:
import albumentations as A
from albumentations.pytorch import ToTensorV2
from albumentations import DualTransform
train_transform = A.Compose(
    [   A.Resize(512, 512),
        A.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1, always_apply=False, p=0.5),
        A.Blur (blur_limit=7, always_apply=False, p=0.5),
        A.Rotate(limit=90, interpolation=1, border_mode=4, value=None, mask_value=None, always_apply=False, p=0.5),
        A.ShiftScaleRotate(shift_limit=0.2, scale_limit=0.2, rotate_limit=15, p=0.5),
        A.RandomCrop(height=512, width=512),
        A.RandomBrightnessContrast(p=0.5),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ])

By then, show me the error:
A.Resize(512,512)
Traceback (most recent call last):

  File "<ipython-input-172-fcbc15f8a409>", line 1, in <module>
    A.Resize(512,512)

  File "/home/swenfei1/anaconda3/lib/python3.8/site-packages/albumentations/augmentations/transforms.py", line 463, in __init__
    super(Resize, self).__init__(always_apply, p)

TypeError: super(type, obj): obj must be an instance or subtype of type

## Environment

 - Albumentations version (0.5):
 - Python version (3.7):
 - OS (Linux):
 - How you installed albumentations (`pip`, source):pip install -U git+https://github.com/albumentations-team/albumentations

**Comment by Dipet** [comment]
It is very strange error, I can't reproduce it.
Try to print albumentations version and check that it is correct: `print(A.__version__)`

**Comment by BloodAxe** [comment]
Please double check your pipeline and/or environment since it cannot be
reproduced by me too.

чт, 22 окт. 2020 г. в 10:57 AM, Mikhail Druzhinin <notifications@github.com

**Comment by WenfeiShen** [comment]
print(A.__version__)
0.5.0
Os is Ubuntu
Python is 3.8
