### ISSUE TITLE
RandomSizedBBoxSafeCrop can yield image with height or width = 0

### ISSUE THREAD

**Issue by dsalathe** [albumentations-team/albumentations#742]
## 🐛 Bug
Sometimes, RandomSizedBBoxSafeCrop yields a negative width or height, which then might crop an area of length 0. Then I get an OpenCV error saying that the image is ill-conditioned.

I printed many things, so I can explain exactly why it happens: let's say the problem occurs with width: we can observe that bw can be negative (line 1002 in transforms.py). This is because bx2 can be smaller than bx. This is because x2 is computed as follow: _x2 + (1 - x2) * random.random()_. My guess is that BBox coordinates seems to be rescaled around [-0.5, 1.5] (values I could read when printing) and sometimes x2 is bigger than 1., so we are actually not adding quantity but removing some.
By the way, I am curious to know why in the call of _union_of_bboxes_, width and height of image are given unnormalized while Bbox coordinates are given normalized.

A dirty fix I did in the meantime is to change line 1001 from bx2, by2 = x2 + (1 - x2) * random.random(), y2 + (1 - y2) * random.random() to bx2, by2 = x2 + max(0, 1 - x2) * random.random(), y2 + max(0, 1 - y2) * random.random(). That is, I clamp the value in parenthesis, but I don't understand yet if the bounding boxes are actually normalized or if it is something else.

I am using albumentations indirectly, via the icevision library. I don't know how to help to reproduce the behavior, I am using private datasets and this bug is very rare, it doesn't happen in all of them.
I attached a stacktrace screenshot.

![albumentationsStacktrace](https://user-images.githubusercontent.com/26025133/97971567-8c9f2400-1dc3-11eb-8bd6-0148ea66f799.png)

## Environment

 - Albumentations version == 0.4.6
 - Python version == 3.8
 - OS Linux Ubuntu
 - icevision 0.1.4
 - Installed when installing icevision

**Comment by Dipet** [comment]
Can you provide image shape and bboxes to reproduce this problem?

**Comment by dsalathe** [comment]
### In the record format

All images are of shape 512x512.
I can provide you the list of Bounding boxes as a pth file.
To upload it here, I renamed it bboxes.zip, I guess you can rename it back to bboxes.pth and it should work.

Then you can do:
bboxes = torch.load('bboxes.pth')
to check all of them.
[bboxes.zip](https://github.com/albumentations-team/albumentations/files/5488130/bboxes.zip)

### In the dataset format
Then I am using transformation via the icevision library on those records. The one used is called aug_transforms and is called like this line:
train_tfms = tfms.A.Adapter([*tfms.A.aug_tfms(size=size, presize=presize), tfms.A.Normalize()])
with size=512, presize=1050.
aug_tfms is documented [here](https://airctic.com/albumentations/).
I also joined the bouding boxes after transformations, called bboxes_dataset.zip (that should be renamed as bboxes_dataset.pth)
[bboxes_datasets.zip](https://github.com/albumentations-team/albumentations/files/5488168/bboxes_datasets.zip)
