### ISSUE TITLE
Pip installation stuck on `Building wheel for opencv-python-headless`

### ISSUE THREAD

**Issue by alexander-soare** [albumentations-team/albumentations#743]
## 🐛 Bug

Description is as explained in title. Been waiting for 5 minutes as of writing this.

## To Reproduce

`pip install albumentations`

## Expected behavior

Installation goes through as normal

## Environment

On Google Colab, or on MacOS 10.15.7. I have not tested other platforms.
This has started happening very recently. Last time I installed Albumentations without an issue was several days ago.
Albumentations version is whatever is in Pypi at the time of writing this.

**Comment by akatasonov** [comment]
+1,  I'm having the same issue

**Comment by akatasonov** [comment]
I think the problem is in opencv 
![image](https://user-images.githubusercontent.com/6917547/97975179-62546300-1dd1-11eb-9bcd-67f7d12e6f62.png)

**Comment by akatasonov** [comment]
Fixed it by installing !pip install -U opencv-python-headless==4.4.0.44 *before* installing albumentations

**Comment by creafz** [comment]
It looks like the problem is related to uploading a new release of OpenCV to PyPI and should be resolved automatically when all wheels with the latest version of OpenCV will be uploaded - https://github.com/skvark/opencv-python/issues/411. In the meantime, a workaround from @akatasonov should help.

**Comment by ternaus** [comment]
Worked for me: `pip install -U pip` before installing albumentations.

**Comment by creafz** [comment]
Now the installation of the latest version correctly works in Google Colab and on macOS. Closing the issue.
