### ISSUE TITLE
Why does the bounding box become so loose after rotation data aug? Is there a better way?

### ISSUE THREAD

**Issue by rra94** [albumentations-team/albumentations#746]
## 🐛 Bug

Loose bounding boxes after rotation data augmentation:

![image](https://user-images.githubusercontent.com/5424122/98274612-a1192300-1f61-11eb-8ceb-008435a53460.png)

after rotation

Notice the gap in the segmentation adn the bounding box

![image](https://user-images.githubusercontent.com/5424122/98274640-aa09f480-1f61-11eb-8b3d-94deee694b18.png)

## To Reproduce

Steps to reproduce the behaviour:

transform = A.Compose(
    [A.Rotate(limit=120, p=1)],
    bbox_params=A.BboxParams(format='coco', label_fields=['category_ids']),
)
transformed = transform(image=image, bboxes=bboxes, category_ids=category_ids)

## Expected behaviour

Tight box around the objects.  Is there a way to get better boxes?

## Environment

 - Albumentations-0.5.1
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations ( `pip`):

**Comment by BloodAxe** [comment]
This is not a bug at all. If you have only bounding boxes (not instance masks), you don't have information of the shape of the object inside. Therefore when you rotate an image, you cannot guess what the new shape of the object is.  All augmentations that support augmentation of bounding boxes works in a similar way - they augment 4 corners and make a new bounding box. In case of rotation it will lead to possibly inflated boxes. This is a known behavior and not a bug.

**Comment by Leci37** [comment]
Original:
![igor_2_00391_](https://github.com/albumentations-team/albumentations/assets/110530848/6403e044-5208-4fc4-b3ed-7d67ace37894)

Results after rotate90 and do other augmentation:

![igor_1_00001_Y](https://github.com/albumentations-team/albumentations/assets/110530848/b5e1130d-0075-4a59-9fb1-13a0d269b0d6)
![igor_1_00001_V](https://github.com/albumentations-team/albumentations/assets/110530848/f5926485-322f-4223-92d0-7ad087f174ce)
