### ISSUE TITLE
Rotating with default settings (cv2.BORDER_REFLECT_101) does not reflect bounding boxes

### ISSUE THREAD

**Issue by felixgravila** [albumentations-team/albumentations#748]
## 🐛 Bug

When creating a transform pipeline on images with bounding box data, rotating the images with REFLECT mode does not reflect the bounding boxes. This can be problematic for training models that would be confused by the lack of boxes there. This is especially problematic since the default mode is cv2.BORDER_REFLECT_101.

## To Reproduce

1. Create a simple transform pipeline on images with bounding box data containing a Rotate operation
2. Execute the transformation on an image with objects that reside around the corners, which will be reflected after the rotation
3. Observe, by visualising the output, that the returned bboxes do not contain the duplicate objects

Code is mostly from https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/

```python
transform = A.Compose([
            A.Rotate(limit=23, p=0.3),
            A.RandomBrightness(limit=0.2, p=1.0),
            A.JpegCompression(quality_lower=85, quality_upper=100, p=1.0),
            A.HueSaturationValue(hue_shift_limit=10, sat_shift_limit=20, val_shift_limit=10, p=0.5),
            A.RandomContrast(limit=0.2, p=1.0),
            A.HorizontalFlip(p=0.5),
        ],
        bbox_params=A.BboxParams(format='pascal_voc', min_visibility=0.3, label_fields=['labels'])
        )

transformed = transform(image=image, bboxes=bboxes, labels=labels)
visualize(
    transformed['image'],
    transformed['bboxes'],
    transformed['labels'],
)
```
## Expected behavior

When the mirrored data contains objects, the returned list of objects should be updated to contain them.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.5.1
 - Python version (e.g., 3.7): 3.7.6
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

## Additional context

My quick fix: change mode

```python
(...)
           A.Rotate(limit=23, border_mode=cv2.BORDER_CONSTANT, value=0, p=0.3),
(...)
```

**Comment by b02202050** [comment]
Is there any response to this problem?

I think this is quite critical because it may produce background training patches which should be positive samples!
btw, I encounter this problem at using ShiftScaleRotate.

**Comment by Dipet** [comment]
Unfortunately at this time we have no quick solution how to implement bboxes reflection.
We recommend to do not use reflection mode for borders in any transformations if you apply these transforms to bboxes.
We will add information about this problem to all transformations documentation that uses border mode as soon as possible.

**Comment by ternaus** [comment]
Fixed.
