### ISSUE TITLE
Augmenting multiple keypoints per image

### ISSUE THREAD

**Issue by FraPochetti** [albumentations-team/albumentations#749]
Hello team,
first of all, thanks a lot for your work! 
Such a great tool you are building!

I have a question about `keypoints`.
As far as I can tell, `transform` does not support multiple` keypoints` to be passed under a single argument
I am referring to the same behavior we have for `bboxes` and `masks`, which can be a list of lists (e.g. multiple `bboxes` per image).
Am I missing anything basic here?
What if my image contains multiple persons each annotated with `keypoints`?
How can I deal with that with the current API?

Thanks again!

**Comment by Dipet** [comment]
You can add person id to tail of each keypoint or use additional target for different persons.
https://albumentations.ai/docs/examples/example_multi_target/

**Comment by FraPochetti** [comment]
Thanks for the link @Dipet
