### ISSUE TITLE
Use key points augmentation option for polygons augmentation

### ISSUE THREAD

**Issue by xmba15** [albumentations-team/albumentations#750]
Hi, I would like to ask a question related to using albumentations for polygons augmentation.
As also pointed out in [this issue](https://github.com/albumentations-team/albumentations/issues/702), polygons augmentation can be done by augmentation of keypoints.
However, for polygons (that are used for instance segmentation), the order of the vertex points are important, I wonder if keypoints augmentation will preserve this order all the time?

**Comment by Dipet** [comment]
Order of keypoints does not changed, but this is not guaranteed. You can add additional data to the tail of your keypoint to restore order order.
For example:
```python
keypoints = [val + [i] for i, val in enumerate(keypoints)]
res = transform(image=image, keypoints=keypoints)
keypoints = [i[:-1] for i in sorted(res['keypoints'])]
```

**Comment by wangwei880403** [comment]
you cannot do that， the keypoints augmentation is total different from polygons，the number of polygon vertex points maybe increase or decrease while some part of polygon is outside the new image

**Comment by Felipecordeiiro** [comment]
How would to i did this (augmentation from scratch) for segmentation task in yolo format. <class id> <x> <y>. I looking for albumentations, but i dont find nothing about this, annotations following polygon yolo format

**Comment by XZLancer** [comment]
Is there a solution for horizontal&vertical flip? These augmentations change point order after transformation, and the trick above does not work
