### ISSUE TITLE
Spatial-level transforms 

### ISSUE THREAD

**Issue by Auth0rM0rgan** [albumentations-team/albumentations#751]
Hello, 

I'm trying to implement data augmentation in my model pipeline but I'm cannot manage it to work! I can easily apply pixel-level transforms but my main problem is when I want to apply Spatial level transform on the Bboxes.

This is my Bbox information which the first elements are the class_id
`
 [[          2      388.13      19.346      412.38      39.594]
 [          2      388.15      8.5168         416      38.972]
 [          0      223.14      156.21      317.91      193.46]]
`
Any help would be appreciated!

**Comment by Dipet** [comment]
Read documentation https://albumentations.ai/docs/examples/example_bboxes/
All additional data must be at the end of bbox.

**Comment by Auth0rM0rgan** [comment]
Thanks, Solved the problem :)
