### ISSUE TITLE
Get error mask after CoarseDropout

### ISSUE THREAD

**Issue by cswwp** [albumentations-team/albumentations#753]
![image](https://user-images.githubusercontent.com/11901683/99155896-25546e80-26f7-11eb-9f77-3b379e04049d.png)
have installed albu with the newest github albu version

**Comment by BloodAxe** [comment]
You need to set `mask_fill_value` when creating `A.CoarseDropout` to apply this augmentation to mask too. By default, dropout to mask is not applied.
