### ISSUE TITLE
CropNonEmptyMaskIfExists with multiple masks not working

### ISSUE THREAD

**Issue by gatordevin** [albumentations-team/albumentations#760]
Hi all,
I ran into an interesting issue. I was originally using RandomCrop to crop my images for instance segmentation with mask rcnn but, I ran into problems where I had images that lacked any instances after cropping. I saw the CropNonEmptyMaskIfExists and it seems to do what I want, correct me if I am wrong but it crops the image and guarantees there will be a mask present. Well, I used this and it gave me this error.
`AssertionError: CropNonEmptyMaskIfExists requires ['mask']`

My current lien of code that runs the composed transform function is as follows.
`transformed = self.__transformations(image=np.array(image, dtype=np.uint8), masks=masks)`
Since I am doing instance segmentation I have multiple masks and have to use the masks parameter instead of a mask. I believe the CropNonEmptyMaskIfExists has a problem with this that won't allow it to run on more than one mask. Or I could be missing something. Please let me know.

Here is my transform
`transformations = A.Compose([
    A.CropNonEmptyMaskIfExists(height=2000, width=2000),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
])`
Thank you

**Comment by Dipet** [comment]
Thanks for information. We will try to resolve this problem us soon us possible.
At this time you may try to concatenate your mask along last axis to create single mask with shape `[Height, Width, NumMasks]` and provide it with keyword `mask`

**Comment by Dipet** [comment]
Try latest version from repository `pip install git+https://github.com/albumentations-team/albumentations`. I think we fixed this problem
