### ISSUE TITLE
what‘s the difference between albumentations and torchvision?

### ISSUE THREAD

**Issue by rOtking** [albumentations-team/albumentations#765]
## 📚 Documentation

Thanks for your works!   I have tried to use it and it performs well.  But i wonder what‘s the difference between albumentations and torchvision?  Compared to torchvision, what are its advantages?    Speed?Or anything else?

**Comment by BloodAxe** [comment]
Lot of things makes Albumentations unique. To start, we offer the largest number of image augmentations than any other image augmentations library. This includes color augmentations, spatial transformations, style transfers, various dropout techniques and may others.

Secondly, Albumentations is battle-tested. Meaning it has been widely adopted in the ML industry (https://github.com/albumentations-team/albumentations#used-by) and in competitive ML, being a part of winning many solutions (https://github.com/albumentations-team/albumentations#competitions-won-with-the-library).

Third, we offer native support for augmentation of image & mask, keypoints & bounding boxes, which covers the most use cases for image classification, image segmentation, object detection and instance segmentation. 

Lastly, unlike torchvision, Albumentations is not pytorch-only library. It can be used together with any DL framework of your choice or even without it. 

And yes, it is much faster, than torchvision - https://github.com/albumentations-team/albumentations#benchmarking-results.
