### ISSUE TITLE
semantic segmentation

### ISSUE THREAD

**Issue by Ciaran1981** [albumentations-team/albumentations#766]
## 📚 Documentation

Hello,

This is  a question/request rather than an issue. 
How does one alter the binary segmentation example workflow to do a multi-class semantic segmentation? 

I have attempted this for a long time to no avail and it'd be great to see how albumentations can be used for a multi class semantic segmentation.

https://albumentations.ai/docs/examples/pytorch_semantic_segmentation/

**Comment by adbcode** [comment]
@Ciaran1981 were you able to figure something that worked in your case?

**Comment by Dipet** [comment]
Just specify a mask for each class and use `masks` instead of `mask`
