### ISSUE TITLE
multi band images

### ISSUE THREAD

**Issue by Ciaran1981** [albumentations-team/albumentations#767]
## 🐛 Bug

Does albumentations support multi-spectral images? I appear to hit this problem using 4-band imagery, which would suggest it does not. 

`augmentations/functional.py", line 141, in normalize
    img -= mean
ValueError: operands could not be broadcast together with shapes (256,256,4) (3,) (256,256,4) `

**Comment by Dipet** [comment]
Library supports  4 channels image. Change default values for `Normalize` transform. They are must be single value or their length must equal to image channels count.
