### ISSUE TITLE
Add a flag to allow missing input data field

### ISSUE THREAD

**Issue by MultiLi** [albumentations-team/albumentations#769]
For multitask training, if there are some data that are not fully annotated (for example, keypoints are missing) presented, the transforms then raise corresponding exceptions.

Can we add a flag somewhere (like Compose) to allow the skipping of missing data field? Or if that has been already handled, can anyone show me how? Thanks.

**Comment by Dipet** [comment]
I think that better to resolve this problem on dataloder side. As an example, ff your targets are empty you can provide empty lists for bboxes and keypoints.
