### ISSUE TITLE
Bounding boxes with negative coordinates cause an exception when cropping

### ISSUE THREAD

**Issue by ronif** [albumentations-team/albumentations#772]
## 🐛 Bug

Hey!

Bounding boxes with negative coordinates cause an exception when cropping.

Please note that negative coordinates are valid in general, for example in cases where part of an object is visible in the image, and it's possible to deduce the bounding box of the entire object just from the visible part.

## To Reproduce

```
import numpy as np
import albumentations as A                                                                                                                                                                               

cropper = A.Crop(0, 0, 10, 10)                                                                                                                                                                           
cropper = A.Compose([A.Crop(0, 0, 10, 10)], bbox_params=A.BboxParams(format='pascal_voc', label_fields=['bbox_labels'], min_area=0, min_visibility=0))
bboxes = [(-5, -5, 5, 5)]
cropper(image=np.zeros((10,10)), bboxes=bboxes, bbox_labels=[1])
```

## Expected behavior

Returned bounding box should be `[(0, 0, 5, 5)]`

## Environment

 - Albumentations version: 0.5.1
 - Python version: 3.7
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by ternaus** [comment]
It is not a bug. It is done on purpose.

It is much better to do label cleaning at the data preparation step rather than during training.

I would recommend fixing bounding box coordinates before augmentations.
