### ISSUE TITLE
RandomCrop and ShiftScaleRotate only returns 1 channel from 3 channels input

### ISSUE THREAD

**Issue by leocd91** [albumentations-team/albumentations#774]
Hi, I have an input in 3 channel but after using RandomCrop  and/or ShiftScaleRotate, it only return 1 channel. 
my input shape is [height, weigth, channel]
Where resize is work just fine.

**Comment by BloodAxe** [comment]
Hi,

I'm really doubt this is caused by an error on our side. Please double-check your pipeline and if the problem persist, re-open this issue with the minimal example to reproduce unexpected behavior. It would also help if you follow issue template, to provide us all the relevant information.
