### ISSUE TITLE
ToTensorV2

### ISSUE THREAD

**Issue by sriharsha0806** [albumentations-team/albumentations#776]
## 🐛 Bug

I ran the following line after installing albumentations in Colab
```python
from albumentations.pytorch import ToTensorV2
ImportError: cannot import name 'ToTensorV2'
```
I tried the solutions provided in the [link](https://stackoverflow.com/questions/62872413/cant-import-totensorv2-in-colab). But the issue still remains the same. 

## To Reproduce

1. Go to colab, Install albumentations library 
```
!pip install albumentations
```
2. run the following line:
```from albumentations.pytorch import ToTensorV2```

3. I tried for the three Hardwares settings 1. None 2. GPU 3. TPU

## Expected behavior

It should run without any error
## Environment

 - Albumentations version (e.g., 0.1.8): 0.1.12
 - Python version (e.g., 3.7): 3.6.9
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

**Comment by Dipet** [comment]
Try to install directly from github: `!pip install git+https://github.com/albumentations-team/albumentations.git`

**Comment by sriharsha0806** [comment]
Thank you, It resolved the issue.
