### ISSUE TITLE
get rid off imgaug dependency

### ISSUE THREAD

**Issue by vvv-tech** [albumentations-team/albumentations#783]
There is page with transforms that albu don't do herself, need to fix that
https://albumentations.ai/docs/api_reference/imgaug/transforms/

**Comment by Dipet** [comment]
As I see we need to rewrite only this transforms:
```
    "IAAEmboss",
    "IAASuperpixels",
    "IAASharpen",
    "IAAAffine",
    "IAAPiecewiseAffine",
    "IAAPerspective",
```

**Comment by sjeffry-o** [comment]
#785 
gotcha superpixels augmentation

**Comment by KiriLev** [comment]
I'd take Emboss if you don't mind

**Comment by sjeffry-o** [comment]
sure
