### ISSUE TITLE
Scikit-image dependency error

### ISSUE THREAD

**Issue by ozen** [albumentations-team/albumentations#795]
Starting from scikit-image 0.18.0 which was released 3 days ago, using skimage.data requires pooch 1.3.0.
But if you don't install skimage with `pip install scikit-image[data]`, pooch is not installed.
Related change: https://github.com/scikit-image/scikit-image/pull/5105/files

Albumentations uses skimage.data through `from skimage.measure import label` and the following error is raised if you don't have pooch 1.3.0

```
  File "/opt/conda/lib/python3.8/site-packages/albumentations/augmentations/transforms.py", line 13, in <module>
    from skimage.measure import label
  File "/opt/conda/lib/python3.8/site-packages/skimage/__init__.py", line 135, in <module>
    from .data import data_dir
  File "/opt/conda/lib/python3.8/site-packages/skimage/data/__init__.py", line 156, in <module>
    image_fetcher, data_dir = create_image_fetcher()
  File "/opt/conda/lib/python3.8/site-packages/skimage/data/__init__.py", line 136, in create_image_fetcher
    image_fetcher = pooch.create(
TypeError: create() got an unexpected keyword argument 'retry_if_failed'
```

This may be a scikit-image issue in general but I think the above error can be prevented in albumentations.

**Comment by ozen** [comment]
Related scikit-image issue: https://github.com/scikit-image/scikit-image/issues/5146

**Comment by ozen** [comment]
This is fixed in scikit-image 0.18.1. You should only avoid 0.18.0.

**Comment by taomanwai** [comment]
Or better use the v0.19.0 mentioned in https://github.com/scikit-image/scikit-image/issues/5146 ?

**Comment by Dipet** [comment]
Does this problem still exist? Tests work correctly
