### ISSUE TITLE
can we directly apply albumentation transforms on torch tensors or variable?

### ISSUE THREAD

**Issue by soumochatterjee** [albumentations-team/albumentations#799]
Is there any way by which we can directly apply albumentation transforms on torch tensors or variable , not by converting torch tensor into numpy array and then applying albumentation transforms? I know it can be a lame question to put but as I am unable to find this out on google that why I thought to put this thing here directly.

**Comment by BloodAxe** [comment]
The short answer is no.



Сб, 19 дек. 2020 г. в 17:05, soumochatterjee <notifications@github.com>:
