### ISSUE TITLE
Missing docs of geometric transformations

### ISSUE THREAD

**Issue by jwitos** [albumentations-team/albumentations#800]
## 📚 Documentation

Documentation of geometric transformations are missing from all docs, e.g. [Resize](https://albumentations.ai/docs/api_reference/augmentations/geometric/resize/#albumentations.augmentations.geometric.resize.Resize), [ShiftScaleRotate](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.ShiftScaleRotate) and more. I was wondering if those functions somehow got deprecated recently as I wasn't following the updates, but all links pointing to geometric transformations - including the ones in readme - don't work.

**Comment by creafz** [comment]
Fixed. Now docs for these transformations are correctly displayed on albumentations.ai.
