### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (433,326,3) (433,328,3) when using additional_targets to apply same transformations

### ISSUE THREAD

**Issue by AugustasMacys** [albumentations-team/albumentations#801]
I have this pipeline and I can see that with GaussNoise it gets an error on return image + gauss:

```
def augmentation_pipeline(size=224):
        return Compose([
        ImageCompression(quality_lower=60, quality_upper=100, p=0.5),
        GaussNoise(p=0.1),
        GaussianBlur(blur_limit=3, p=0.05),
        HorizontalFlip(),
        PadIfNeeded(min_height=size, min_width=size, border_mode=cv2.BORDER_CONSTANT),
        OneOf([RandomBrightnessContrast(), FancyPCA(), HueSaturationValue()], p=0.7),
        ToGray(p=0.2),
        ShiftScaleRotate(shift_limit=0.1, scale_limit=0.2, rotate_limit=10, border_mode=cv2.BORDER_CONSTANT, p=0.5)],
        additional_targets={'image2': 'image'}
    )
```

## To Reproduce

1.  Call function like transformed_images = self.augmentate(image=img_real, image2=img_fake) (images have different dimensions)

Does anyone know how I should fix this so that I could use the same or very similar pipeline and to get same augmentations for both images?

**Comment by BloodAxe** [comment]
Would you mind adding shapes & dtypes of both targets?

**Comment by AugustasMacys** [comment]
@BloodAxe Yes, I read more about GaussNoise and now I understand that both images need to be the same size, I will try to resize them before applying this transformation. Thanks for your reply.
