### ISSUE TITLE
Inability to set different shear in x and y for Affine transformation

### ISSUE THREAD

**Issue by vishal733** [albumentations-team/albumentations#806]
## 🐛 Bug

- Albumentations uses imgaug for doing an image shear.
- imgaug typically allows for a different shear in x and y, by passing shear as: `shear={"x":(-16, 16), "y": (-16, 16)}`
- But albumentations allows only tuple values for shears. And doesn't allow for different shear in x and y (which kind of limits the shear functionality to more like a rotation)

## Environment

 - Albumentations version: 0.5.2
 - Python version: 3.7.9
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by ternaus** [comment]
@vishal733 

Affine in version 1.4.13+ supports shear for both x and y direction, exactly as you desscribe.
