### ISSUE TITLE
Demo for GaussNoise misplaces decimal and produces too much noise

### ISSUE THREAD

**Issue by lidless-vision** [albumentations-team/albumentations#809]
## 📚 Documentation

when using the demo thing at https://albumentations-demo.herokuapp.com/ for the gaussNoise function
the demo provides code like 
`GaussNoise(always_apply=False, p=1.0, var_limit=(10.0, 50.0))`

and on the demo that seems to work fine, but on my system, when i apply this to my cv2 float32 images, i get images that are 100% noise.

i have found a workaround! moving the decimal over twice, gets the desired behavior.

`GaussNoise(always_apply=False, p=1.0, var_limit=(0.10, 0.50))`

I am using albumentations==0.5.2

**Comment by ternaus** [comment]
@lidless-vision 

Works correctly now: https://explore.albumentations.ai/transform/GaussNoise
