### ISSUE TITLE
AttributeError: module 'albumentations' has no attribute 'Compose'

### ISSUE THREAD

**Issue by erdemunal35** [albumentations-team/albumentations#810]
Freshly installed albumentations through anaconda. This error pops up even when I try to run the [simple example](https://pypi.org/project/albumentations/#a-simple-example) in your website.

**Comment by BloodAxe** [comment]
What the exact version of Albumebtations did you install from conda?

**Comment by erdemunal35** [comment]
I installed Version 0.5.2 via `conda install -c conda-forge albumentations`
``` shell
$ conda list
# packages in environment at D:\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
alabaster                 0.7.12                     py_0
albumentations            0.5.2              pyhd8ed1ab_0    conda-forge
anaconda                  2020.11                  py38_0
....                                   .....                          ......
```

**Comment by erdemunal35** [comment]
Totally my mistake. I had another file "albumentations.py" in the same folder. Problem solved!
