### ISSUE TITLE
Does this library support PIL?

### ISSUE THREAD

**Issue by somebodyus** [albumentations-team/albumentations#817]
Does this library support PIL?
PIL comes with TorchVision, so it will be more convenient to use PIL.

**Comment by BloodAxe** [comment]
Hi. Albumentations does not support images in PIL format. We work with numpy arrays, which provide faster access to underlying memory and better performance when doing interop with native libraries (such as OpenCV).

**Comment by somebodyus** [comment]
I think using PIL needs a little modifications to your example:

`import albumentations as A
import numpy as np
import PIL

# Declare an augmentation pipeline
transform = A.Compose([
    A.RandomCrop(width=256, height=256),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
])

# Read an image with PIL  
image = np.asarray(PIL.Image.open("image.jpg"))

# Augment an image
transformed = transform(image=image)
transformed_image = transformed["image"]`
