### ISSUE TITLE
Better to mention `ReplayCompose` in multi-target docs

### ISSUE THREAD

**Issue by irvingzhang0512** [albumentations-team/albumentations#818]
Thank you very much for your work! It's very useful!

## 📚 Documentation

I want to augment images with the same augmenters, just like `to_deterministic` in imgaug, and find this [multi-target docs](https://albumentations.ai/docs/examples/example_multi_target/). `additional_targets` works fine but `ReplayCompose` is exactly what I need. This docs may be a little bit misleading. I thought `additional_targets` was the ONLY WAY to support deterministic mode.

I think both `ReplayCompose` and `additional_targets` could support `Applying the same augmentation with the same parameters to multiple images...` Maybe we could mention `ReplayCompose` in the above docs.

**Comment by creafz** [comment]
Hey, @irvingzhang0512, thanks for creating an issue. I have updated an example for multi-target augmentations. Now the example has a note about ReplayCompose - https://albumentations.ai/docs/examples/example_multi_target/
