### ISSUE TITLE
Add Option to wipe bounding box content if bounding boxes are invalid after Random Croping

### ISSUE THREAD

**Issue by tenggyut** [albumentations-team/albumentations#824]
## 🐛 Bug

this is not a bug but a enhencement. 

Random crop may change the label of a bounding box

e.g. after random crop,  a head with a helmet may result in no helmet, and its label changes from `with a helmet` to `without a helmet`.

In this case, just drop the bouding box may not enough, I think a more safer way is to wipe the remaining content.

**Comment by Dipet** [comment]
I have no idea how to implement this request, because the library doesn't know such specific information about your data.
If you have independent boxes for helmet and head you can check labels after transformations.
Also if you have some ideas how to implement this changes for your data you can inherit from `RandomCrop` and implement your own `apply_to_bbox` method.

**Comment by tenggyut** [comment]
> I have no idea how to implement this request, because the library doesn't know such specific information about your data.
> If you have independent boxes for helmet and head you can check labels after transformations.
> Also if you have some ideas how to implement this changes for your data you can inherit from `RandomCrop` and implement your own `apply_to_bbox` method.

the library dosen't need to know such info about the data, Just need a flag. if the flag is true, wipe the content of the invalid bounding boxes when dropping it. the flag is controlled by the user, not the library. Maybe add a extra option in BBoxParam ?

**Comment by Dipet** [comment]
Do you mean when we drop bbox by `min_area` or `min_visibility` conditions, we don't just simple remove it, but we remove and fill the bbox area by some values, for example zeros?

**Comment by tenggyut** [comment]
> Do you mean when we drop bbox by `min_area` or `min_visibility` conditions, we don't just simple remove it, but we remove and fill the bbox area by some values, for example zeros?

Yes! And this behavior is controlled by a flag or param, like `min_visibility`

**Comment by Dipet** [comment]
I think this is a good idea and doesn't require big code changes.
Looks like we need to add new arguments into [this](https://github.com/albumentations-team/albumentations/blob/13f44d1397f11cb371436715d50739a8c90b6abb/albumentations/augmentations/bbox_utils.py#L345) function and add function to replace pixels values

**Comment by tenggyut** [comment]
> I think this is a good idea and doesn't require big code changes.
> Looks like we need to add new arguments into [this](https://github.com/albumentations-team/albumentations/blob/13f44d1397f11cb371436715d50739a8c90b6abb/albumentations/augmentations/bbox_utils.py#L345) function and add function to replace pixels values

**Comment by tenggyut** [comment]
Thanks!
