### ISSUE TITLE
Keypoint augmentations not working for IAAAffine

### ISSUE THREAD

**Issue by mikkelmedm** [albumentations-team/albumentations#827]
## 🐛 Bug

As per the overview of transformations here: https://albumentations.ai/docs/getting_started/transforms_and_targets/
I try to run both pixel-wise and spatial augmentations on my dataset, however when using the IAAAffine transformation, it results in the following error: 
_ValueError: Expected x for keypoint (-9.433, 93.50725, 0.0, 0) to be in the range [0.0, 256], got -9.433._

Would like to perform different translations/scaling/shearing of my dataset. Is this not possible with keypoints also? Or are there other native albumentations transforms that would work instead?

## To Reproduce

    augment = albu.Compose(
        [
            albu.HueSaturationValue(p=0.5),
            albu.RGBShift(p=0.5),
            albu.RandomBrightnessContrast(p=0.5),
            albu.MotionBlur(p=0.5),
            albu.Cutout(num_holes=6, max_h_size=ranh, max_w_size=ranw, fill_value=ranc, always_apply=False, p=0.5),
            albu.IAAAffine(scale=1, translate_percent=0.0, translate_px=None, rotate=0.0, shear=[25,25], order=1, cval=0, mode='edge', always_apply=False, p=0.5),
            albu.GaussNoise(p=0.5),
            albu.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, always_apply=False, p=1.0),
        ],
        keypoint_params=albu.KeypointParams(format="xy")
    )

    augmented = augment(image=image, mask=mask, keypoints=keypoints)

## Environment

 - Albumentations version (e.g., 0.1.8): 0.5.2
 - Python version (e.g., 3.7): 3.7.9
 - OS (e.g., Linux): Windows
 - How you installed albumentations (`conda`, `pip`, source): conda

**Comment by Dipet** [comment]
I can not reproduce the problem. Can you provide reproducible example?
Unfortunately library does not have shear transformation. You may try `ShiftScaleRotate`

**Comment by mikkelmedm** [comment]
`im = np.random.rand(512,256,3) * 255
im = np.array(Image.open(image_path).convert('RGB'))
mask = np.random.choice([0, 1], size=(512,256), p=[1./3, 2./3])
locations = [[6.14975, 76.1165], [13.89175, 79.07975], [13.0165, 81.74075], [7.29775, 73.5655], [-9.433, 93.50725], [-0.8295, 95.27225], [-2.5525, 98.82875], [-7.417, 90.01375]]

# Organic color pallette:
colorpallete = {'black': (0,0,0), 'white': (255,255,255)}

ranh = int(image.shape[0]/randrange(4,10))
ranw = int(image.shape[1]/randrange(4,10))
ranc = random.choice(list(colorpallete.values()))

augment = albu.Compose(
    [
        albu.HueSaturationValue(p=0.5),
        albu.RGBShift(p=0.5),
        albu.RandomBrightnessContrast(p=0.5),
        albu.MotionBlur(p=0.5),
        albu.Cutout(num_holes=6, max_h_size=ranh, max_w_size=ranw, fill_value=ranc, always_apply=False, p=0.5),
        # TODO: shearing/translation/rotation doesnt work - issues with the keypoints
        albu.IAAAffine(scale=1, translate_percent=0.0, translate_px=None, rotate=0.0, shear=[25,25], order=1, cval=0, mode='edge', always_apply=False, p=0.5),
        albu.GaussNoise(p=0.5),
        albu.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, always_apply=False, p=1.0),
    ],
    keypoint_params=albu.KeypointParams(format="xy")
)

augmented = augment(image=im, mask=mask, keypoints=locations)`

I suspect it's because some of my keypoints are "outside" the image. This is part of the task of the model. Would I need to pad to circumvent this?

**Comment by Dipet** [comment]
The problem is not in imagaug augmentations. You have keypoints outside of image. If you want to use and save them set `remove_invisible=False`
```python
keypoint_params=albu.KeypointParams(format="xy", remove_invisible=False)
```

**Comment by mikkelmedm** [comment]
Ahh, my bad. Thanks for your help! :)

**Comment by wind-surfer** [comment]
@Dipet Is there a way to pad the image such that keypoints (which are beyond the image region) background is not white?

**Comment by Dipet** [comment]
I didn't quite understand what you want. Could you give me a small example?

**Comment by wind-surfer** [comment]
Hello @Dipet 
I meant, if after applying keypoint transformation, if the keypoint is going beyond the original image dimension, then the background of the image region (corresponding to that exact keypoint which has gone beyond the image dimension) is white. 

_Question/Confusion_: Is there a way to pad the image such that all the keypoints (even after transformation) has real image background, not white.

For example, please see that the image background is white when the keypoint has gone beyond the image.

![output_outpoint](https://user-images.githubusercontent.com/53333216/143848801-a397e7ca-edd6-484b-943a-8d35d3b0e261.png)

I have pasted my code [here ](https://pastecode.io/s/evxohojb)which I used to generate the scenario. Thank you

`

`

**Comment by Dipet** [comment]
Sorry for the delay. How did you get this white background? I can not reproduce the problem. By default set `border_mode=cv2.BORDER_REFLECT_101`, which means that all pixels outside the image will be reflected starting from the image edge.
