### ISSUE TITLE
Install albumentations in Apple Silicon M1

### ISSUE THREAD

**Issue by ismaproco** [albumentations-team/albumentations#829]
Hi, I been trying to install albumentations on a MacBook Air with Apple silicon, and haven't been able to do it, because the `opencv-python-headless` dependency is not available.

## more details
I have a working tensorflow environment with numpy and standard opencv I followed this tutorial: http://iphonesdkdev.blogspot.com/2020/11/202011.html
albumentations is not available in the conda repos for arm64, so I have to install it through `pip`, but then it complains about the `opencv-python-headless` dependency, I'm able to compile opencv on the M1 with the HEADLESS option but still something is off (it might be that I have done something wrong) http://iphonesdkdev.blogspot.com/2020/11/202011.html

**Comment by BloodAxe** [comment]
Can you try with `pip install --no-deps albumentations`?

**Comment by Dipet** [comment]
This command `pip install git+https://github.com/albumentations-team/albumentations.git` also needs `opencv-python-headless`?
Are you sure that you install `albumentations` in same envirornment? You may check that OpenCV installed with this command `pip freeze | grep opencv`

**Comment by ismaproco** [comment]
thank you @BloodAxe I was able to install it using the no deps.
@Dipet yes I installed py-opencv from the mini-conda environment but the pip install couldn't check the existence of it, but it did work with @BloodAxe suggestion of omitting the dependencies, I did have to install the other dependencies manually one by one but it worked.
