### ISSUE TITLE
apply_to_keypoint() does not work for Rotation augumentation

### ISSUE THREAD

**Issue by PawelFaron** [albumentations-team/albumentations#832]
## 🐛 Bug

I'm doing several transformations like shift, scale, rotate etc. For most of them when using apply_to_keypoint() to transform keypoints it works good. The keypoints are where they should be after transformation. But this is not the case for Rotation. The points are scattered all around the image.

## To Reproduce

1. Create Rotate transformation:
`rotate = Rotate(10, p=1.0)`
2. Apply this transformation to image:
`rotate.apply(image, **params)`
3. Apply this transformation to some points:
`rotate.apply_to_keypoint([x_coordinate, y_coordinate, 0, 0], **params)`

## Expected behavior

The points should be in the same place (taking into account transformation) as before rotation.

## Environment

 - Albumentations 0.5.2
 - Python 3.7
 - Linux
 - How you installed albumentations: pip

**Comment by Dipet** [comment]
As I see, all works fine
```python
import numpy as np
import albumentations as A
import random
import cv2 as cv


random.seed(0)
np.random.seed(0)

image = np.zeros([100, 100, 3], dtype=np.uint8)
keypoints = [
    [10, 10],
    [10, 90],
    [50, 50],
    [90, 10],
    [90, 90],
]

transforms = A.Compose([A.Rotate(10, p=10)], keypoint_params=A.KeypointParams(format="xy"))

res = transforms(image=image, keypoints=keypoints)

print(keypoints)            # [[10, 10], [10, 90], [50, 50], [90, 10], [90, 90]]
print(res["keypoints"])     # [(11, 9), (9, 89), (50, 50), (91, 11), (89, 91)]

```

**Comment by ternaus** [comment]
@PawelFaron Works now: https://explore.albumentations.ai/transform/Rotate
