### ISSUE TITLE
[Bug] Emboss and Sharpen transformations import

### ISSUE THREAD

**Issue by alexandreMayerowitz** [albumentations-team/albumentations#833]
## 🐛 Bug

I can't import **Emboss** and **Sharpen** transformations from main module.

## To Reproduce

1. Install albumentations
2. Open a Python interpreter
3. Run the following commands:

```
import albumentations as A

A.Emboss()
```

results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'albumentations' has no attribute 'Emboss'
```

Same behavior with **Shapen** transformation.

## Expected behavior

What we expect is to be able to import both transformations directly from main module.

## Environment

 - Albumentations version : `0.5.2`
 - Python version : `3.6.12`
 - OS : `Mac OS X`
 - How you installed albumentations : `pip`
 - Any other relevant information:

**Comment by BloodAxe** [comment]
Hi. `A.Emboss()` is not in pip package yet. To get the latest development version you can install albumentations via `pip install git+https://github.com/albumentations-team/albumentations.git`.

**Comment by alexandreMayerowitz** [comment]
Thanks for your quick answer. My bad!

**Comment by zlyin** [comment]
Hello there, could you also elaborate on the reason of failure of importing "Sharpen"?

**Comment by Xiaoyang-Rebecca** [comment]
fyi, need to ``pip uninstall albumentations`` then ``pip install git+https://github.com/albumentations-team/albumentations.git``
