### ISSUE TITLE
Wrong result of ColorJitter when the dtype of input image is float32 instead of uint8 

### ISSUE THREAD

**Issue by VVingerfly** [albumentations-team/albumentations#835]
## 🐛 Bug

When input image is of type float32, the augmented image of ColorJitter is a white image. Is this a bug, or the input image must be the type of uint8?

## To Reproduce

```python
# test ColorJitter 
print('albumentations versioin', A.__version__)
img_uint8 = cv2.imread('img/Macropus_rufogriseus_rufogriseus_Bruny.jpg')
img_uint8 = cv2.cvtColor(img_uint8, cv2.COLOR_BGR2RGB)
img_uint8 = cv2.resize(img_uint8, (259, 389))
transform = A.ReplayCompose([
    A.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.2, p=1.0),
])
# random.seed(7)
img_f32 = img_uint8.copy().astype('float32')
# img = img_uint8
img = img_f32
print(type(img), img.dtype, np.max(img), np.min(img))
data = transform(image=img)
print(data['image'].shape)
visualize(data['image'])
```

## Expected behavior

When input image is `img = img_f32` the result is as follows, just a white image

![image](https://user-images.githubusercontent.com/16233971/106684900-48116780-6602-11eb-94b0-667b3edfb7d9.png)

When input image is `img = img_uint8` the result below is correct

![image](https://user-images.githubusercontent.com/16233971/106684989-74c57f00-6602-11eb-80b7-5eef5af73b47.png)

## Environment

 - Albumentations version: 0.5.2
 - Python version: 3.7.7
 - OS: Linux
 - How you installed albumentations: pip
 - Any other relevant information:

**Comment by Dipet** [comment]
You are working with float32 images in the wrong order.
float32 image must be normalized in range `[0, 1]`.
```python
img_f32 = img_uint8.astype(np.float32) / 255.0
```

**Comment by VVingerfly** [comment]
Oh, it's my fault, thanks for your reply. 😃
