### ISSUE TITLE
Keypoints Example - HorizontalFlip misleading

### ISSUE THREAD

**Issue by cheind** [albumentations-team/albumentations#840]
## 📚 Documentation

Hey, I just came across your project yesterday and was browsing the documentation when I came across the following example: 

*Using Albumentations to augment keypoints*
https://albumentations.ai/docs/examples/example_keypoints/

which should be improved: it is misleading to use horizontal flips for side-sensitive keypoints, except one accounts for it (which I believe is not done in the example).

**Comment by creafz** [comment]
Hey @cheind , good catch, thanks. For now, I have updated the article and added a note about side-sensitive keypoints at the beginning.

**Comment by cheind** [comment]
@creafz thanks for the update! i wonder if albumentations/HorizontalFlip could automatically correct the ordering of the keypoints? I've seen the usage of `class_sides`, but I believe it does not affect the behaviour of HorizontalFlip.

**Comment by cheind** [comment]
Closing, because fixed.

**Comment by creafz** [comment]
@cheind No, `class_sides` is an example of how you can pass multiple sets of keypoints' labels to a transformation function, and it doesn't have any semantic meaning inside Albumentations. For now, the only way to pass information about side-sensitive keypoints to Albumentations is to use the symmetry-aware augmentations from `albumentations-experimental`.

**Comment by cheind** [comment]
Thanks, didn't know about the symmetry-aware transformations.
