### ISSUE TITLE
choose_requirement function from albumentations setup.py does not work properly from a clean enviroment installation. 

### ISSUE THREAD

**Issue by DanielAguileraGarcia** [albumentations-team/albumentations#841]
## 🐛 Bug

choose_requirement function from setup.py does not work properly from a clean enviroment installation. 

## To Reproduce

1. Create a setup.py that contains albumentations and opencv-python libraries
2. Create new virtual environment
3. pip install -e .

Having a clean environemnt (any opencv version) albumentations installs opencv-python and opencv-python-headless.

## Expected behavior

Expected behaviour would be to install opencv-python from setup.py and theorically albumentations does not need to install opencv-python-headless because as choose_requirements says, it won't install any dependency if opencv-python is already installed. I think opencv-python headless disables some basic functionalities of cv2 like for example "imshow". 

Making a brief summary, albumentations installs two different open-cv libraries and it is not what open cv recommends. 

To avoid this problem first I have to uninstall opencv-python, uninstall opencv-python-headless and install opencv-python again once the setup.py is installed. 

The same thing is happening to me as issue #697. 

## Environment

 - Albumentations version (0.5.2)
 - Python version (e.g., 3.7): 3.6
 - OS (e.g., Linux): windows
 - How you installed albumentations (`con`pip`, source): pip

**Comment by Dipet** [comment]
Try to look this issue to #697

**Comment by creafz** [comment]
Hey @DanielAguileraGarcia 

I have added a description of how to handle this case with pip to docs: https://albumentations.ai/docs/getting_started/installation/#note-on-opencv-dependencies.

In short, you need to use the `--no-binary imgaug,albumentations` argument to pip, e.g. `pip --no-binary imgaug,albumentations install -e .`
