### ISSUE TITLE
Augment RGB and Grayscale image

### ISSUE THREAD

**Issue by RGring** [albumentations-team/albumentations#845]
Hi,
Thanks for this nice library.

I couldn't find any information about how to augment a collection of different image types. In my case I would like to augment a RGB and grayscale image.
E.g. how can I apply Normalize() on those different types. Can I somehow set valid target identifier?

Thanks in advance!

**Comment by creafz** [comment]
Hey, @RGring 

You need to apply different normalization values (e.g., different mean or std) to RGB and Grayscale images. Do I understand the case correctly?

In such a situation, I think the simplest way is to define two separate augmentation pipelines and use the appropriate pipeline for an input image. For example:

```
transform_rgb = A.Compose([
    ...,
    A.Normalize(mean=..., std=...)
])

transform_grayscale = A.Compose([
    ...,
    A.Normalize(mean=..., std=...)
])

if is_rgb(image):
    transformed = transform_rgb(image=image)
else:
    transformed = transform_grayscale(image=image)
```

**Comment by RGring** [comment]
Thanks for the reply. I want to compose both images in the same way, except channel relevant augmentations like e.g. normalization. But your answer inspired me, splitting it in another way. Haven't thought about it. Thanks!
```
transform_both = A.Compose([
    ...,
    A.ShiftScaleRotate()
])

transform_grayscale = A.Compose([
    A.Normalize(mean=..., std=...)
])

transform_rgb = A.Compose([
    A.Normalize(mean=..., std=...)
])

transformed = transform_both(image=rgb_image, gray_image=gray_image)
normalized_grey = transform_grayscale(transformed["gray_image"])
normalized_rgb = transform_rgb(transformed["image"])
```

Have not yet tried it though.
