### ISSUE TITLE
Module 'albumentations' has no attribute 'Lambda'

### ISSUE THREAD

**Issue by Indhujamari** [albumentations-team/albumentations#851]
I am working on multi-class segmentation problem where I need to use Lambda function for serialization but it shows the following error as

![image](https://user-images.githubusercontent.com/53159366/110087894-3b775f00-7dba-11eb-8b4e-858805af2864.png)

can anyone help me..
Thanks in advance.

**Comment by Dipet** [comment]
Which version of the library are you using?
Try to update it:
`pip install --upgrade albumentations`
or
`pip install --upgrade git+https://github.com/albumentations-team/albumentations`

**Comment by Indhujamari** [comment]
It works. Thank you.

**Comment by amenevatanparast** [comment]
hi
I have this problem "module 'albumentations' has no attribute 'Lambda"
I test
!pip install -U albumentations>=0.3.0 --user
!pip install -U git+https://github.com/albu/albumentations --no-cache-dir
pip install --upgrade albumentations
pip install --upgrade git+https://github.com/albumentations-team/albumentations

but the error is still
please help me

**Comment by BloodAxe** [comment]
Please double-check you environment, since the sequence of commands that
you attach can easily mess the env. Clean uninstall and installation of
latest release should work

Ср, 14 апр. 2021 г. в 10:54, amenevatanparast ***@***.***>:
