### ISSUE TITLE
ReplayCompose ColorJitter params not correct

### ISSUE THREAD

**Issue by Trud09** [albumentations-team/albumentations#852]
## To Reproduce

1. Run replay compose with color jitter
2. Try to access the params

Example Outputs:
Wrong:
ColorJitter:{'transforms': [<function ColorJitter.get_params.<locals>.<lambda> at 0x000001E029835D90>, <function ColorJitter.get_params.<locals>.<lambda> at 0x000001E029835C80>, <function ColorJitter.get_params.<locals>.<lambda> at 0x000001DF92FF6378>, <function ColorJitter.get_params.<locals>.<lambda> at 0x000001E029835E18>]}

Right:
GaussianBlur:{'ksize': 3, 'sigma': 0.0}

## Environment

Albumentations version (e.g., 0.1.8): 0.5.2
Python version (e.g., 3.7): 3.6
OS (e.g., Linux): Windows
How you installed albumentations (conda, pip, source): pip

**Comment by Dipet** [comment]
I don't understand what's wrong. Replay compose does not work in your case or what?
For me it is works ok. And yes, parameters are list of lambdas https://github.com/albumentations-team/albumentations/blob/ae50578a46e5981eccaafee311a3ee0b4b7992b2/albumentations/augmentations/transforms.py#L2834

**Comment by Dipet** [comment]
Fixed in #1199
