### ISSUE TITLE
How to select some augmentations applying for medical image such as CT images(2D liver tumor image)?

### ISSUE THREAD

**Issue by ee-hash** [albumentations-team/albumentations#854]
Hello, I'm fairly new to Albumentations and it great! I have reviewed the documentation and I'm not sure which function is applicable to CT Image. Now I'm trying to select some operations to build a search space and augment the input data in liver tumor segmentation.  The examples you showed just contain 2 operations: GridDistortion and ElasticTransform. 

I have created 13 operations. Are there more functions working well in medical image processing?

List of opeartions:
`'GridDistortion',
    'RandomScale',
    'Rotate',
    'VerticalFlip',
    'RandomCrop',
    'RandomSizedCrop',
    'Blur',
    'CLAHE',
    'GaussNoise',
    'Transpose',
    'ElasticTransform',
    'Flip',
    'GridDropout',`

CT image example:
![0004](https://user-images.githubusercontent.com/57698625/110912971-83186080-834f-11eb-9cbd-6275741c869e.png)

Thanks!

**Comment by creafz** [comment]
Hey, @hwx10 

Generally speaking, there are no well-established rules of which augmentations you should apply to images from a particular domain (medical images in your case). There are two popular ways of applying augmentations. You could try them both and see which works better.

1. Apply a lot of strong augmentations that will heavily alter input images, and those images won't look like real images.
2. Apply only those augmentations that will make augmented images look like real images. 

Option 1 is more suitable if your dataset is small, while option 2 usually works the same or better than option 1 for large datasets.
