### ISSUE TITLE
How to not augment the image randomly?

### ISSUE THREAD

**Issue by ee-hash** [albumentations-team/albumentations#858]
For example, I wanna rotate a image, I just set the angle=90, the image will rotate 90.
But just like Elastictransform and GridDistortion will randomly augment images , though I set a constant value. I don't want this.
I don't know how to augment the image according to a constant. 
My purpose: the degree of image enhancement changes according to the value(I set).
Thanks!
`**value**= 1000
transform = A.Compose([
        A.ElasticTransform(alpha=1, sigma=50, alpha_affine=50, p=1),
    ])
augmented = transform(image=image, mask=mask, random_state=**value**)`

**Comment by creafz** [comment]
Hey @hwx10 

As a quick workaround, you can set a seed value before augmenting input data, e.g.:


```
import random
import albumentations as A

transform = A.Compose([ A.ElasticTransform(alpha=1, sigma=50, alpha_affine=50, p=1), ])

random.seed(1000)
augmented = transform(image=image, mask=mask)
```

**Comment by hwx10** [comment]
> Hey @hwx10
> 
> As a quick workaround, you can set a seed value before augmenting input data, e.g.:
> 
> ```
> import random
> import albumentations as A
> 
> transform = A.Compose([ A.ElasticTransform(alpha=1, sigma=50, alpha_affine=50, p=1), ])
> 
> random.seed(1000)
> augmented = transform(image=image, mask=mask)
> ```

Thanks! 
But I wanna augmenting input data by a determinded value. The value is the hyper-parameters. I wan to optimize it.
I have achieved it in this way. I inherit the class and reconstructed the function `get_params(self)`.
>    def get_params(self):
>          return {"random_state": 1000}

**Comment by hwx10** [comment]
@creafz 
Thanks!
But I wanna augmenting input data by a determinded value. The value is the hyper-parameters. I wan to optimize it.
I have achieved it in this way. I inherit the class and reconstructed the function `get_params(self).`
e.g.:
def get_params(self):
return {"random_state": 1000}
