### ISSUE TITLE
`fill_value` argument is missing from ver 0.1.12

### ISSUE THREAD

**Issue by sayakpaul** [albumentations-team/albumentations#872]
## 📚 Documentation

With respect to the documentation of [`Cutout`](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.Cutout) there should be one argument called `fill_value` but I found it to be missing in version 0.1.12 which happens to be the latest one.

**Comment by BloodAxe** [comment]
Last version is 0.5.2
