### ISSUE TITLE
albumentations to labelme json

### ISSUE THREAD

**Issue by monkeycc** [albumentations-team/albumentations#878]
{
  "version": "4.0.0",
  "flags": {},
  "shapes": [
    {
      "label": "person",
      "points": [
        [
          250.8142292490119,
          107.33596837944665
        ],
        [
          229.8142292490119,
          119.33596837944665
        ],
        [
          221.8142292490119,
          135.33596837944665
        ],
        [
          223.8142292490119,
          148.33596837944665
        ],

......

      "group_id": null,
      "shape_type": "polygon",
      "flags": {}
    },
  "imagePath": "2011_000003.jpg",
  "imageData": null,
  "imageHeight": 338,
  "imageWidth": 500
}

-------
labelme json

How to import JSON

Graphics processing of algorithms

Save new pictures and new JSON

**Comment by BloodAxe** [comment]
I don't see what to comment here. This request is not an issue, but rather request on how to transform one dict to another. We do not provide here support for such kind of requests. Please take a time to read our example notebooks.
