### ISSUE TITLE
Cannot instantiate augmentations with tuple parameters from Hydra config

### ISSUE THREAD

**Issue by senarvi** [albumentations-team/albumentations#884]
## 🐛 Bug

I'd like to use [Hydra](https://hydra.cc/) to configure and instantiate augmentations. It works nicely, unless I try to use a tuple as a parameter value. Hydra translates lists and tuples to an internal type that can be casted to a tuple, but Albumentations checks the parameter types and won't try to cast it if it's not a list.

## To Reproduce

It's convenient to define augmentations in a Hydra configuration like this:

```yaml
augmentations:
- _target_: albumentations.HorizontalFlip
  p: 0.5
- _target_: albumentations.HueSaturationValue
  sat_shift_limit:
  - -10
  - 20
```

One can then instantiate the augmentations like this:

```python
from omegaconf import DictConfig
import hydra
from hydra.utils import instantiate

@hydra.main(config_path='conf', config_name='config')
def my_app(cfg: DictConfig) -> None:
    augmentations = [instantiate(a) for a in cfg.augmentations]

if __name__ == "__main__":
    my_app()
```

If you run the above code, it will correctly instantiate the `HorizontalFlip` augmentation, but fails to instantiate the `HueSaturationValue`. The reason is that `instantiate()` translates the `sat_shift_limit` value [-10, 20] to an `omegaconf.ListConfig`. It would be possible to cast `omegaconf.ListConfig` to a tuple, but [to_tuple()](https://github.com/albumentations-team/albumentations/blob/95a048d342cbe748e5acf15cb1a28611a6303885/albumentations/core/transforms_interface.py#L36) checks that the type is either a list or a tuple before casting. It's not, so instead of casting it throws an exception:

    ValueError: Argument param must be either scalar (int, float) or tuple

## Expected behavior

`to_tuple()` should cast the `omegaconf.ListConfig` to a tuple, so that `instantiate()` would instantiate the `HueSaturationValue` transform.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.5.2
 - Python version (e.g., 3.7): 3.8.3
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): conda

## Additional context

I understand that it's impossible to check for `omegaconf.ListConfig` and all other possible cases that can be casted to a tuple. Actually it's common to use "duck typing" in Python, meaning that anything that acts like a list can be provided in place of a list, so it's problematic to check the exact type of parameters.

**Comment by BloodAxe** [comment]
I think you can easily solve this issue by calling `OmegaConf.to_container` while calling `instantiate(a)`: `instantiate(OmegaConf.to_container(a))`. I'm seriously against adding extra dependency to hydra (although I'm using hydra by myself as well) to Albumentations to fix this issue. To me, `tuple` and `list` are standard containers, while `ListConfig` and `DictConfig` are not. One should not expect compatibility with custom classes that "pretend" to be `tuple` or `dict`.

Please let us know whether `to_container` solve this issue.

**Comment by senarvi** [comment]
Thanks for the suggestion @BloodAxe! Calling `OmageConf.to_container()` before calling `instantiate()` won't solve the problem, because if you pass a tuple or list to `instantiate()`, it will convert it to `ListConfig`. The only way to work around the problem that I came up with is creating a function that converts the parameters before instantiating the augmentations:

```python
def instantiate_transform(transform, *args, **kwargs):
    kwargs = {k: tuple(v) if isinstance(v, ListConfig) else v
              for k, v in kwargs.items()}
    transform_class = getattr(albumentations, transform)
    return transform_class(*args, **kwargs)
```

The configuration then has to be changed slightly to use this function:

```yaml
augmentations:
- _target_: my_app.instantiate_transform
  transform: HorizontalFlip
  p: 0.5
- _target_: my_app.instantiate_transform
  transform: HueSaturationValue
  sat_shift_limit:
  - -10
  - 20
```

I wouldn't add a dependency to OmegaConf either, because it will only solve the problem in this particular case (users of Hydra). It's actually quite idiomatic in Python to rely on the fact that you can provide anything that acts like a list (be it a NumPy array or a PyTorch tensor) in place of a list, and that's why it's considered bad practice to check arguments for the exact type. (See what I wrote in "Additional context".)
The proper way would be to check whether the argument does what you want, for example check that param[0] and param[1] are scalars.

**Comment by Dipet** [comment]
It looks like we can replace check `isinstance(param, (list, tuple))` with `isinstance(param, Sequence)` and everything will work fine.

**Comment by BloodAxe** [comment]
It seems hydra (Tested on 1.1) `instantiate` has additional parameter `_convert_`:
```
   _convert_: Conversion strategy
        none    : Passed objects are DictConfig and ListConfig, default
        partial : Passed objects are converted to dict and list, with
                  the exception of Structured Configs (and their fields).
        all     : Passed objects are dicts, lists and primitives without
                  a trace of OmegaConf containers
```

So adding `_convert_` should do the job:
```
augmentations:
- _target_: albumentations.HorizontalFlip
  p: 0.5
- _target_: albumentations.HueSaturationValue
  _convert_: all
  sat_shift_limit:
  - [10, 20]
```

**Comment by BloodAxe** [comment]
> It looks like we can replace check `isinstance(param, (list, tuple))` with `isinstance(param, Sequence)` and everything will work fine. `Sequence` - is a standard type from typing module

Like the `Sequence` approach!

**Comment by senarvi** [comment]
I agree, it's probably the best approach.
