### ISSUE TITLE
KeyError: 'rows' in CropNonEmptyMaskIfExists if keypoints used.

### ISSUE THREAD

**Issue by MartSlaaf** [albumentations-team/albumentations#891]
## 🐛 Bug

If `CropNonEmptyMaskIfExists` is used in transformation pipeline with keypoint, it throws `KeyError: 'rows'` exception. Even though keypoints mentioned as a correct target. Being replaced with `RandomCrop` works without problems on the same data.

## To Reproduce

1. Instantiate  `CropNonEmptyMaskIfExists` transformation
2. Add it to composition which works with keypoints.
3. Try to actually run composed transformation.

```Python
import albumentations as A
import numpy as np

i = np.random.randint(0, 255, (256, 256), dtype=np.uint8) # image
m = np.zeros((256, 256), dtype=np.uint8) # mask
m[20:30, 20:40] = 1
m[120:130, 120:140] = 2
k = np.random.randint(0, 256, (10, 2)) # keypoints

# == This will throw an exception ==
transform = A.Compose([A.CropNonEmptyMaskIfExists(128, 128)], 
                      keypoint_params=A.KeypointParams(format='xy', remove_invisible=True))
transform(image=i, mask=m, keypoints=k)

# == This will work good ==
transform = A.Compose([A.RandomCrop(128, 128)], 
                      keypoint_params=A.KeypointParams(format='xy', remove_invisible=True))
transform(image=i, mask=m, keypoints=k)
```

## Expected behavior

I expect it to work similarly to the `RandomCrop`, but preserving the masked area if presented.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.5.2
 - Python version (e.g., 3.7): 3.7.3
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

## Additional context

It looks like the total row counter or something like that is just not created during processing, but is expected.

**Comment by MartSlaaf** [comment]
Looks like, it's because `CropNonEmptyMaskIfExists` overrided `update_params` method, which in parent class `BasicTransform` is coded to add height and width to params:

```Python
params.update({"cols": kwargs["image"].shape[1], "rows": kwargs["image"].shape[0]})
```

Should `CropNonEmptyMaskIfExists` then call to `super` or?

**Comment by Dipet** [comment]
I reproduced this problem only with `bboxes`
```python
import albumentations as A
import numpy as np

i = np.random.randint(0, 255, (256, 256), dtype=np.uint8) # image
m = np.zeros((256, 256), dtype=np.uint8) # mask
m[20:30, 20:40] = 1
m[120:130, 120:140] = 2
k = np.random.randint(0, 256, (10, 2)) # keypoints
bboxes = [
    [10, 10, 50, 70, 0],
]

# == This will throw an exception ==
transform = A.Compose([A.CropNonEmptyMaskIfExists(128, 128, p=1)],
                      keypoint_params=A.KeypointParams(format='xy', remove_invisible=True),
                      bbox_params=A.BboxParams(format="pascal_voc")
                      )
transform(image=i, mask=m, keypoints=k, bboxes=bboxes)

# == This will work good ==
transform = A.Compose([A.RandomCrop(128, 128, p=1)],
                      keypoint_params=A.KeypointParams(format='xy', remove_invisible=True))
transform(image=i, mask=m, keypoints=k, bboxes=bboxes)
```
