### ISSUE TITLE
SafeRotate: transfromed image is rotated however the bounding boxes are not rotated. 

### ISSUE THREAD

**Issue by Sehjbir** [albumentations-team/albumentations#896]
## To Reproduce

1.
1.
1.

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

**Comment by ternaus** [comment]
@Sehjbir Fixed: https://explore.albumentations.ai/transform/SafeRotate
