### ISSUE TITLE
Rotate with expand

### ISSUE THREAD

**Issue by thomas0809** [albumentations-team/albumentations#898]
SafeRotate compresses the rotated image to fit in the original size. Is it possible to add an option to skip the compression step? I.e. torchvision.transform.RandomRotation with expand=True

Same issue #642, but I don't think it's fixed.

**Comment by Dipet** [comment]
Try to use [Affine](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.Affine) with `fit_output` parameter
