### ISSUE TITLE
Erosion and Dilation feature without cropping an image

### ISSUE THREAD

**Issue by srdg** [albumentations-team/albumentations#904]
Is there a feature for eroding/dilating an image without having to crop it? The closest reference I found to this feature in the API was [this](https://albumentations.ai/docs/api_reference/augmentations/crops/transforms/#albumentations.augmentations.crops.transforms.RandomSizedBBoxSafeCrop), but it seems that apart from this, I would not be able to do any such transforms.

**Comment by Dipet** [comment]
I can not understand what you want. What the result you expect? For me [erosion](https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#gaeb1e0c1033e3f6b891a25d0511362aeb) and [dilation](https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#ga4ff0f3318642c4f469d0e11f242f3b6c) of image are morphological transforms

**Comment by srdg** [comment]
@Dipet , yes - this is where I am also a little confused. Does this library not include morphological transforms as part of image augmentation?

**Comment by srdg** [comment]
Okay, thank you @Dipet , I will close this issue.
