### ISSUE TITLE
 when to release A.Affine?

### ISSUE THREAD

**Issue by Xiaoyang-Rebecca** [albumentations-team/albumentations#914]
## 🐛 Bug

The Affine class is able to located in https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/geometric/transforms.py#L467
 but not available in the release package:

## To Reproduce

---> aug = A.Affine(p=1, shear = 1)
AttributeError: module 'albumentations' has no attribute 'Affine'

## Environment

 - Albumentations version 0.5.2
 - Python 3.7):
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

**Comment by Dipet** [comment]
We are working on a release. Hopefully we will release a new version in PyPi soon.

**Comment by Dipet** [comment]
Version [1.0.0](https://github.com/albumentations-team/albumentations/releases) has been released. Try to upgrade you package from [PyPi](https://pypi.org/project/albumentations/1.0.0/)
