### ISSUE TITLE
ValueError: Requested crop size is larger than the image size in RandomResizedCrop

### ISSUE THREAD

**Issue by claverru** [albumentations-team/albumentations#915]
## 🐛 Bug

`ValueError: Requested crop size is larger than the image size` when including RandomResizedCrop in my transforms pipeline:

```
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/ai_damages/parts/src/data_loading.py", line 64, in __getitem__
    transformed = self.transforms(image=img, mask=mask)
  File "/opt/conda/lib/python3.8/site-packages/albumentations/core/composition.py", line 182, in __call__
    data = t(force_apply=force_apply, **data)
  File "/opt/conda/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 89, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 102, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/opt/conda/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 227, in apply_to_mask
    return self.apply(img, **{k: cv2.INTER_NEAREST if k == "interpolation" else v for k, v in params.items()})
  File "/opt/conda/lib/python3.8/site-packages/albumentations/augmentations/transforms.py", line 857, in apply
    crop = F.random_crop(img, crop_height, crop_width, h_start, w_start)
  File "/opt/conda/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 331, in random_crop
    raise ValueError(
ValueError: Requested crop size (2131, 1636) is larger than the image size (1836, 3264)
```

## To Reproduce

I can't reproduce it deterministically, it just happens sometimes. 

## Environment

- Docker Image: pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime
- Albumentations version: 0.5.2 (by pip)

## Additional Context

Instantiated as:
`A.RandomResizedCrop(img_size, img_size, scale=(0.20, 1.))`

**Comment by Dipet** [comment]
> ValueError: Requested crop size (2131, 1636) is larger than the image size (1836, 3264)

As described in message - images size is less then requested crop size. Try to rotate or resize image before cropping.

**Comment by claverru** [comment]
@Dipet Wait what? New H and W are chosen randomly inside the buggy function. I'm reporting this bug just precisely because something must be wrong inside `albumentations.RandomResizedCrop`, which first crops and then resizes the image. It should be something around here https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/crops/transforms.py#L338, which I believe is the place where W and H crop parameters are being chosen.

**Comment by claverru** [comment]
@Dipet Even more, I'd say it triggers when it falls back to center crop, around line 360: https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/crops/transforms.py#L360.

**Comment by claverru** [comment]
Okay, it seems like the fall back part is okay. Steps:

```
import cv2
import albumentations as A

!wget https://image.api.playstation.com/vulcan/img/rnd/202010/2621/KvgbdmY6MvPdLaa3dyVNGOw1.png?w=440

img = cv2.imread('/content/KvgbdmY6MvPdLaa3dyVNGOw1.png?w=440')
# img = img.transpose(1, 0, 2)
print(img.shape)

ratio = (0.75, 1.3333333333333333)

in_ratio = img.shape[1] / img.shape[0]

if in_ratio < min(ratio):
    w = img.shape[1]
    h = int(round(w / min(ratio)))
elif in_ratio > max(ratio):
    h = img.shape[0]
    w = int(round(h * max(ratio)))
else:  # whole image
    w = img.shape[1]
    h = img.shape[0]

print(h, w)
```

**Comment by Dipet** [comment]
Hmm, strange. I can not reproduce the problem.
Could you give reproducible example with fixed seeds?
```python
import albumentations as A
import numpy as np
import random

seed = 0
random.seed(seed)
np.random.seed(seed)

img_size = 512
aug = A.Compose([A.RandomResizedCrop(img_size, img_size, scale=(0.20, 1.))])

img = np.zeros([1836, 3264, 3], dtype=np.uint8)
for i in range(1000):
    res= aug(image=img)["image"]

img = np.zeros([3264, 1836, 3], dtype=np.uint8)
for i in range(1000):
    res= aug(image=img)["image"]

```

**Comment by claverru** [comment]
I'm not able to reproduce the error on purpose. If I do, I will update asap.

**Comment by claverru** [comment]
I just found the error. It is a mix between an error from my part and a weird interaction from albumentations.

I'm applying these transforms to images and masks, and in one case I had my mask rotated for some reason. That's my fault. 

Though, I think albumentations should check if the images and the masks have the same shape (or the same aspect ratio.) In the latter case, it should resize the crop params to adequate them for the rest of the items.

**Comment by lucmos** [comment]
@claverru Thanks! I hit almost exactly the same problem :)

**Comment by Dipet** [comment]
Now we check that image and mask shapes are equal. More info in #1310
