### ISSUE TITLE
AttributeError: albumentation 'Compose' object has no attribute 'additional_targets'

### ISSUE THREAD

**Issue by deevyankar** [albumentations-team/albumentations#918]
## To Reproduce

1.
1.
1.

## Environment

 - Albumentations version (e.g., 0.1.8):
 - Python version (e.g., 3.7): google colab GPU
 - OS (e.g., Linux):
 - How you installed albumentations (`conda`, `pip`, source):
 - Any other relevant information:

## Additional context

aug=A.Compose([
        RandomRotate90(),
        Flip(),
        Transpose(),
        OneOf([
            IAAAdditiveGaussianNoise(),
            GaussNoise(),
            
        ], p=0.2),
        OneOf([
            MotionBlur(p=.2),
            MedianBlur(blur_limit=3, p=.1),
            Blur(blur_limit=3, p=.1),
        ], p=0.3),
        ShiftScaleRotate(shift_limit=0.0625, scale_limit=0.2, rotate_limit=45, p=.2),
        OneOf([
            OpticalDistortion(p=0.3),
            GridDistortion(p=.1),
            IAAPiecewiseAffine(p=0.3),
        ], p=0.3),
        OneOf([
            CLAHE(clip_limit=2),
            IAASharpen(),
            IAAEmboss(),
            RandomContrast(),
            RandomBrightness(),
        ], p=0.3),
        HueSaturationValue(p=0.3),
    ], p=0.8)

from ImageDataAugmentor.image_data_augmentor import *
data_gen= ImageDataAugmentor(
     rescale=1/255,
     augment=aug)

error :
AttributeError                            Traceback (most recent call last)
<ipython-input-27-3dc6ac5f445e> in <module>()
      2 data_gen= ImageDataAugmentor(
      3      rescale=1/255,
----> 4      augment=aug)

/usr/local/lib/python3.7/dist-packages/ImageDataAugmentor/image_data_augmentor.py in __init__(self, featurewise_center, samplewise_center, featurewise_std_normalization, samplewise_std_normalization, zca_whitening, augment, input_augment_mode, label_augment_mode, seed, rescale, preprocess_input, preprocess_output, data_format, validation_split, **kwargs)
     84         self.label_augment_mode = label_augment_mode
     85         if self.augment is not None:
---> 86             additional_targets = self.augment.additional_targets
     87             if self.input_augment_mode not in {'image','mask',}.union(additional_targets.keys()):
     88                 raise ValueError(f"Unknown `input_augment_mode='{self.input_augment_mode}'`")

AttributeError: 'Compose' object has no attribute 'additional_targets'

**Comment by BloodAxe** [comment]
Would you mind adding a version of the library you have?

**Comment by Satriosnjya** [comment]
What library that you mean ?

**Comment by deevyankar** [comment]
Requirement already satisfied: albumentations in
/usr/local/lib/python3.7/dist-packages (0.1.12) Requirement already
satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from
albumentations) (1.4.1) Collecting imgaug<0.2.7,>=0.2.5 Downloading
https://files.pythonhosted.org/packages/ad/2e/748dbb7bb52ec8667098bae9b585f448569ae520031932687761165419a2/imgaug-0.2.6.tar.gz
(631kB) |████████████████████████████████| 634kB 8.1MB/s Requirement
already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.7/dist-packages
(from albumentations) (1.19.5) Requirement already satisfied: opencv-python
in /usr/local/lib/python3.7/dist-packages (from albumentations) (4.1.2.30)
Requirement already satisfied: scikit-image>=0.11.0 in
/usr/local/lib/python3.7/dist-packages (from
imgaug<0.2.7,>=0.2.5->albumentations) (0.16.2) Requirement already
satisfied: six in /usr/local/lib/python3.7/dist-packages (from
imgaug<0.2.7,>=0.2.5->albumentations) (1.15.0) Requirement already
satisfied: networkx>=2.0 in /usr/local/lib/python3.7/dist-packages (from
scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations) (2.5.1)
Requirement already satisfied: PyWavelets>=0.4.0 in
/usr/local/lib/python3.7/dist-packages (from
scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations) (1.1.1)
Requirement already satisfied: imageio>=2.3.0 in
/usr/local/lib/python3.7/dist-packages (from
scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations) (2.4.1)
Requirement already satisfied: pillow>=4.3.0 in
/usr/local/lib/python3.7/dist-packages (from
scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations) (7.1.2)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in
/usr/local/lib/python3.7/dist-packages (from
scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations) (3.2.2)
Requirement already satisfied: decorator<5,>=4.3 in
/usr/local/lib/python3.7/dist-packages (from
networkx>=2.0->scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations)
(4.4.2) Requirement already satisfied:
pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in
/usr/local/lib/python3.7/dist-packages (from
matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations)
(2.4.7) Requirement already satisfied: cycler>=0.10 in
/usr/local/lib/python3.7/dist-packages (from
matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations)
(0.10.0) Requirement already satisfied: kiwisolver>=1.0.1 in
/usr/local/lib/python3.7/dist-packages (from
matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations)
(1.3.1) Requirement already satisfied: python-dateutil>=2.1 in
/usr/local/lib/python3.7/dist-packages (from
matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.11.0->imgaug<0.2.7,>=0.2.5->albumentations)
(2.8.1) Building wheels for collected packages: imgaug Building wheel for
imgaug (setup.py) ... done Created wheel for imgaug:
filename=imgaug-0.2.6-cp37-none-any.whl size=654019
sha256=8c01e192e46434466d8d883f9cc1f8b7338fff29c67a0d34907199571c6fc027
Stored in directory:
/root/.cache/pip/wheels/97/ec/48/0d25896c417b715af6236dbcef8f0bed136a1a5e52972fc6d0
Successfully built imgaug Installing collected packages: imgaug Found
existing installation: imgaug 0.2.9 Uninstalling imgaug-0.2.9: Successfully
uninstalled imgaug-0.2.9 Successfully installed imgaug-0.2.6

**Comment by Dipet** [comment]
Try to upgrade to latest library version `pip install --upgrade albumentations`

**Comment by deevyankar** [comment]
Still same.. I am using google colab.... Is it mandatory now to give
arguments for additional targets in new version of albumentation?

**Comment by saurabh8418** [comment]
Hey @deevyankar  Did you find out any solution for it?
I am facing the same issue.
