### ISSUE TITLE
Unexpected behavior for Rotate()

### ISSUE THREAD

**Issue by omri374** [albumentations-team/albumentations#923]
## 🐛 Bug

When using the `Rotate` augmentation on a simple example, unexpected results are returned.

## To Reproduce

```python
import numpy as np
import albumentations as A

random.seed(10)
np.random.seed(10)

rotate_transform = A.Rotate(p=1.0)

image = np.array([[1, 2], [3, 4]],dtype=np.uint8)

transformed_image = rotate_transform(image=image)
print(transformed_image['image'].tolist())

```
Returns
```
[[2, 2], [2, 4]]
```

Running it multiple times, I get different results:
```python
for _ in range(10):
    print(rotate_transform(image=image)['image'].tolist())
```
Returns

```
[[2, 2], [2, 4]]
[[2, 2], [2, 4]]
[[2, 2], [2, 4]]
[[1, 2], [3, 4]]
[[1, 2], [3, 4]]
[[1, 2], [3, 4]]
[[2, 2], [2, 4]]
[[3, 2], [2, 4]]
[[1, 3], [2, 4]]
[[1, 2], [3, 4]]
```

## Expected behavior

A few things aren't as expected:
1. Not sure how `Rotate` is expected to rotate the image, but it doesn't seem like the simple matrix is rotated by either 90 or -90 degrees.
2. I would expect to have the same pixel values in the output (1,2,3,4 and not 2,2,3,4)
3. I would expect to get the only two results (one for +90 and one for -90) as `p=1`

Is there an assumption on the shape of the input image? I couldn't find it on the documentation.

## Environment

 - Albumentations version: 1.0.0
 - Python version: 3.8.5
 - OS (e.g., Linux): WSL (Ubuntu 20.04 on Windows)
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by Dipet** [comment]
Transform `Rotate` rotate image to random angle between `[-90, 90]` degrees. If you want to rotate to 90 degrees only use `RandomRotate90`
