### ISSUE TITLE
Fancy PCA - is column_stack necessary (or even the right thing to do)?

### ISSUE THREAD

**Issue by mallyagirish** [albumentations-team/albumentations#925]
Referring to the relevant section in the AlexNet paper (screenshot below), the perturbation to be added to every pixel is a linear combination of the eigenvectors using the corresponding randomly-scaled eigenvalues as coefficients.

![image](https://user-images.githubusercontent.com/52492456/122373768-a90a5e00-cf59-11eb-8570-b34cdc49da75.png)

Now, in the code, the square array `eig_vecs` [already contains the eigenvectors in its columns](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html#numpy.linalg.eigh).
https://github.com/albumentations-team/albumentations/blob/d1082f32a64b2083ba84bcaee1274e42715050bb/albumentations/augmentations/functional.py#L1565-L1566

That is, `eig_vecs` is already _[**p**1, **p**2, **p**3]_. Why then is it necessary to [column_stack](https://numpy.org/doc/stable/reference/generated/numpy.column_stack.html) as below? In fact, this step actually has the effect of transposing `eig_vecs`. That is, `m1` ends up being _[**p**1, **p**2, **p**3]_<sup>T</sup>. This does not seem to be the intent.
https://github.com/albumentations-team/albumentations/blob/d1082f32a64b2083ba84bcaee1274e42715050bb/albumentations/augmentations/functional.py#L1573-L1574

I have also raised this issue in the original author's code (https://github.com/pixelatedbrian/fortnight-furniture/issues/1).

**Comment by jun2tong** [comment]
Hi, I have same question/issue as you raised. 

According to numpy's documentation, `np.linalg.eigh` returns eigenvectors in its column, i.e. `eig_vecs[:,i]` will contain the `i-th` eigenvector. This means, we should not `column_stack` later.

In addition to `column_stack` issue, we actually only need to reverse the `eig_vals` and corresponding `eig_vecs` as the eigenvalues are return in ascending order. From Numpy's [documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html), 

> The eigenvalues in ascending order, each repeated according to its multiplicity.

Any update from maintainer would be appreciated.
