### ISSUE TITLE
networkx vulnerability

### ISSUE THREAD

**Issue by scanner-ml** [albumentations-team/albumentations#929]
## Vulnerability
  ✗ Deserialization of Untrusted Data [High Severity][https://snyk.io/vuln/SNYK-PYTHON-NETWORKX-1062709] in networkx@2.5.1
    introduced by albumentations@1.0.0 > scikit-image@0.18.1 > networkx@2.5.1 and 2 other path(s)

Detected with snyk

**Comment by BloodAxe** [comment]
I feel the whole point of raising this issue is to add "Detected with snyk" PR footer.

**Comment by scanner-ml** [comment]
not affiliated with them.  edited the original post. we deploy for financial institution and that's why this was raised
