### ISSUE TITLE
Expected y_max for bbox to be in the range [0.0, 1.0], got 1.0006307061906432.

### ISSUE THREAD

**Issue by NishinoTSK** [albumentations-team/albumentations#937]
I know other people have reported this issue but has it been fixed?

This is my pipeline:

```python
transformRotate = A.Compose(
    [A.Rotate(always_apply=True,limit=30)],
    bbox_params=A.BboxParams(format='coco', label_fields=['category_ids']),
)
```
And this is the error:

```python
ValueError                                Traceback (most recent call last)
<ipython-input-148-5c907af81af2> in <module>()
     26   image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
     27   #Transformar
---> 28   transformed = transformRotate(image=image, bboxes=lbox, category_ids=categoryid)
     29   #Salvar
     30   img = Image.fromarray(transformed['image'], 'RGB')

7 frames
/usr/local/lib/python3.7/dist-packages/albumentations/augmentations/bbox_utils.py in check_bbox(bbox)
    327 
    328 
--> 329 def check_bbox(bbox):
    330     """Check if bbox boundaries are in range 0, 1 and minimums are lesser then maximums"""
    331     for name, value in zip(["x_min", "y_min", "x_max", "y_max"], bbox[:4]):

ValueError: Expected y_max for bbox (0.6064227035100822, 0.7198738170347003, 0.9656458192562561, 1.0006307061906432, 78) to be in the range [0.0, 1.0], got 1.0006307061906432.
```

**Comment by narain1** [comment]
Even I have a similar issue

>ValueError: Expected y_min for bbox (0.0087890625, -6.938893903907228e-18, 0.0625, 0.04882812499999992, 3) to be in the range [0.0, 1.0], got -6.938893903907228e-18.

but when I check the bounding boxes they seem to be completely normal and I am using PASCAL voc formating for input

`{'bboxes': array([[332.52173913, 503.7826087 , 458.52173913, 597.7826087 ]]),
 'labels': array([5])}`

#https://github.com/albumentations-team/albumentations/issues/459

and this has already been mentioned before but has'nt been solved yet I dont want to get into the mess of editing library files and importing them I would like to make a PR if the team is interested
