### ISSUE TITLE
RandomCrop with padding

### ISSUE THREAD

**Issue by hassiahk** [albumentations-team/albumentations#943]
I want to implement an equivalent of Torchvision's transforms (`transforms.RandomCrop(32, padding=4)`) in albumentations.

The only way I found till now is:

```
A.Sequential([
    A.PadIfNeeded(
        min_height=32+8,
        min_width=32+8,
    ),
    A.RandomCrop(
        height=32,
        width=32
    )
], p=1.0)
```

What are the different ways we can do this? And what is an efficient or recommended way?

Thanks in advance!! :)

Already asked in the Discussions forum but I don't think anyone is using that actively.

**Comment by creafz** [comment]
Hey, @hassiahk 

Your way looks totally fine and efficient for me. 

As an alternative, we have the [`CropAndPad`](https://albumentations.ai/docs/api_reference/augmentations/crops/transforms/#albumentations.augmentations.crops.transforms.CropAndPad) transform which does cropping and padding, but in the reverse order (first cropping, then padding).

**Comment by hassiahk** [comment]
> As an alternative, we have the [`CropAndPad`](https://albumentations.ai/docs/api_reference/augmentations/crops/transforms/#albumentations.augmentations.crops.transforms.CropAndPad) transform which does cropping and padding, but in the reverse order (first cropping, then padding).

Yes. I need to do padding and then cropping :)

**Comment by ternaus** [comment]
@hassiahk Added option to pad if needed [Crop](https://explore.albumentations.ai/transform/Crop), [RandomCrop](https://explore.albumentations.ai/transform/RandomCrop) and [CenterCrop](https://explore.albumentations.ai/transform/CenterCrop)
