### ISSUE TITLE
RandomShadow and RandomSunFlare does not work for grayscale images

### ISSUE THREAD

**Issue by wosiu** [albumentations-team/albumentations#957]
## To Reproduce
Call any of those transforms on 1-channel image to get:

```
ValueError: This transformation expects 3-channel images
You can convert your grayscale image to RGB using cv2.cvtColor(image, cv2.COLOR_GRAY2RGB))
``` 

from e.g.:
https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/functional.py#L848

## Expected behavior

IMO it makes sense to make those transforms to work with grayscale images too, as in my case. I can try to improve it that way if it makes sense to you. Also I'd appreciate any advice.

## Environment
 - Albumentations version 1.0.1:
 - Python version 3.6:
 - OS - MacOS
 - How you installed albumentations - `pip`

**Comment by wosiu** [comment]
FYI I did a quick hack locally to handle 1-channel images, which works fine for me.
It basically detects if it's grayscale and if so converts to rgb first. At the end convert back from rgb to grayscale.

So to give you a taste, I put here: https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/functional.py#L909

lines:
```
    is_single_channel = (len(img.shape) == 2)
    if is_single_channel:
        # this is a quick hack to handle grayscale, faster implementation would have a separate logic for 1 channel images
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
```

and then I replaced: 
https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/functional.py#L921-L924

with:
```
    image_out = cv2.cvtColor(image_hls, cv2.COLOR_HLS2RGB)
   
    if is_single_channel:
        image_out = cv2.cvtColor(image_hls, cv2.COLOR_RGB2GRAY)
        
    if needs_float:
        image_out = to_float(image_out, max_value=255)
```

I guess it could be handled better by implementing completly separate logic for adding shadows (other than using HLS channels), but I'm too lazy :P Let me know if the proposal above sounds acceptable to you and I can make a PR.

**Comment by wosiu** [comment]
# RandomSunFlare

Works straight away for 1-channel, the check:
https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/functional.py#L848
could be just removed

I guess it could be a separate issue and PR.

**Comment by ternaus** [comment]
Fixed. Both work on any number of channels.
