### ISSUE TITLE
RandomBrightnessContrast turns all images black

### ISSUE THREAD

**Issue by Edenzzzz** [albumentations-team/albumentations#964]
## 🐛 Bug

RandomBrightnessContrast always produce all-black images

## To Reproduce
 RandomBrightnessContrast(brightness_limit=0.15,contrast_limit=0.1,p=1)
Whatever value I set contrast_limit at,this function constantly produce all-black images.
Even setting it to 0. does not solve this problem. If I delete this function  from Compose(), the problem is solved.
![image](https://user-images.githubusercontent.com/87317405/125759304-3b752769-851d-44da-8496-adf84b51b546.png)

## Expected behavior

The code is intended to change the brightness of images instead of changing the contrast.

## Environment

 - Albumentations version (e.g., 0.1.8):1.0.0
 - Python version (e.g., 3.7):3.7
 - OS (e.g., Linux):win10
 - How you installed albumentations (`conda`, `pip`, source):pip
 - Any other relevant information:

## Additional context

Nope

**Comment by blaine141** [comment]
What is the data type of your input image?

**Comment by Edenzzzz** [comment]
> What is the data type of your input image?
Thanks for your attention. It turned out that this function was not built for float32 data and casting them to 'uint8' solved it perfectly.

**Comment by RafayAK** [comment]
This should not be closed. The documentation does suggest that RandomBrightnessContrast works on both `uint8` and `float32`

**Comment by BloodAxe** [comment]
RandomBrightnessContrast supports fp32. However, the range of float32 images assumed to stay in [0..1] range, which is stated in the docs. For values outside this range, a clamping to [0...1] range will occur.

**Comment by RafayAK** [comment]
@BloodAxe Just for my sanity, I checked the docs again. It does not state clamping to [0...1]:

https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.RandomBrightnessContrast

```
class albumentations.augmentations.transforms.RandomBrightnessContrast (brightness_limit=0.2, contrast_limit=0.2, brightness_by_max=True, always_apply=False, p=0.5) [view source on GitHub] ¶
Randomly change brightness and contrast of the input image.

Parameters:

Name	Type	Description
brightness_limit	[float, float] or float	
factor range for changing brightness. If limit is a single float, the range will be (-limit, limit). Default: (-0.2, 0.2).

contrast_limit	[float, float] or float	
factor range for changing contrast. If limit is a single float, the range will be (-limit, limit). Default: (-0.2, 0.2).

brightness_by_max	Boolean	
If True adjust contrast by image dtype maximum, else adjust contrast by image mean.

p	float	
probability of applying the transform. Default: 0.5.

Targets: image

Image types: uint8, float32
```

**Comment by zlyin** [comment]
> . However, the range of float32 images assumed to stay in [0..1] range, which is stated in the docs. For values outside this range, a clamping to [0...1] range will occur.

I didn't find what you mentioned either!
