### ISSUE TITLE
ValueError: Expected x_min for bbox (2.4285714285714284, 3.15625, 2.705357142857143, 3.2142857142857144, 0) to be in the range [0.0, 1.0], got 2.4285714285714284.

### ISSUE THREAD

**Issue by tensorAI** [albumentations-team/albumentations#965]
## 🐛 Bug

There is a bug in the code while processing images along with the bounding boxes, and keypoints together.  I am using `tf.data.Dataset` input pipeline to process bound boxes along with the keypoints for a detection task. 

## To Reproduce

Here is how my code looks like. 

        
        class Pipeline:
               def __init__(self, ...)
                      ...
                   self.transform = A.Compose([
                   A.LongestMaxSize(max_size=self.image_width, interpolation=cv2.INTER_AREA),
                   A.PadIfNeeded(min_height=self.image_height,
                              min_width=self.image_width,
                              border_mode=cv2.BORDER_CONSTANT,
                              p=1.0),
                   # A.RandomRotate90(p=0.49),
                   # A.RandomScale(scale_limit=0.2, interpolation=cv2.INTER_AREA),
                   A.HorizontalFlip(p=self.horizontal_flip_prob),
                   A.VerticalFlip(p=self.vertical_flip_prob),
                   A.GaussianBlur(blur_limit=3, p=0.3),
                   A.MotionBlur(blur_limit=3),
                   A.ChannelShuffle(p=0.49),
                   A.ChannelDropout(channel_drop_range=(1, 1), p=0.49),
                   A.ToGray(p=0.49),
                   A.RandomBrightnessContrast(brightness_limit=self.max_brightness_adjustment,
                                                             contrast_limit=self.max_contrast_adjustment,
                                                             p=self.brightness_contrast_adjustment_prob),
                    ],
                    bbox_params=A.BboxParams(format='pascal_voc', min_area=0.2, min_visibility=0.3),
                    keypoint_params=A.KeypointParams(format='xy', remove_invisible=False),
                    )
                     ....
                    # it will load images along with annotations
                    dataset = dataset.map(self._load_images_and_annotations,
                                 num_parallel_calls=NUM_PARALLEL_CALLS)
                    # augmentations
                    dataset = dataset.map(self._process_data,
                                num_parallel_calls=NUM_PARALLEL_CALLS)
                    ...
                    ...
                   self.dataset = dataset
       ` 
        def aug_function(self,
                     image: np.ndarray,
                     bboxes: np.ndarray,
                     keypoints: np.ndarray,
                     keypoints_valid: np.ndarray,
                     num_boxes: np.ndarray):
            """ image augmentations """
            # reshape keypoints
            keypoints_reshaped = np.reshape(keypoints, (-1, 2))

            data = {"image": image,
                        "bboxes": bboxes[:num_boxes],
                        "keypoints": keypoints_reshaped}
            transformed = self.transform(**data)
            # denormalize image
            transformed_image = transformed['image'] * 255.0
            # pad the heights of bboxes and denormalize
            _bboxes = np.array(transformed['bboxes']).astype(np.int32)
            transformed_bboxes = np.zeros((self.max_num_annotations, 5), dtype=np.int32)
            if _bboxes.shape[0] > 0:
                transformed_bboxes[:_bboxes.shape[0], :] = _bboxes
            transformed_keypoints = np.reshape(np.array(transformed['keypoints'], dtype=np.int32), keypoints.shape)
            return transformed_image, transformed_bboxes, transformed_keypoints, \
                keypoints_valid, np.int32(_bboxes.shape[0])

        def _process_data(self,
                      image: tf.Tensor,
                      bboxes: tf.Tensor,
                      keypoints: tf.Tensor,
                      keypoints_valid: tf.Tensor,
                      num_boxes: tf.Tensor):

            transformed_image, transformed_bboxes, transformed_keypoints, keypoints_valid, num_boxes = \
                tf.numpy_function(func=self.aug_function,
                                  inp=[image, bboxes, keypoints, keypoints_valid, num_boxes],
                                  Tout=[tf.float32, tf.int32, tf.int32, tf.bool, tf.int32])
            # set shapes of all the tensors
            transformed_image.set_shape((self.image_width, self.image_height, 3))
            transformed_bboxes.set_shape(bboxes.get_shape())
            transformed_keypoints.set_shape(keypoints.get_shape())
            return transformed_image, transformed_bboxes, transformed_keypoints, keypoints_valid, num_boxes

Error Message: 
```

            2021-07-15 12:54:33.382104: W tensorflow/core/framework/op_kernel.cc:1639] Invalid argument: ValueError: Expected x_min for bbox (2.4285714285714284, 3.15625, 2.705357142857143, 3.2142857142857144, 0) to be in the range [0.0, 1.0], got 2.4285714285714284.
Traceback (most recent call last):

      File "/home/user/anaconda3/envs/zippin/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

      File "/home/user/zippin/code-base/rgb_person_detection/dataloader/dataloader_test.py", line 268, in aug_function
    transformed = self.transform(**data)

      File "/home/user/anaconda3/envs/zippin/lib/python3.6/site-packages/albumentations/core/composition.py", line 188, in __call__
    p.preprocess(data)

      File "/home/user/anaconda3/envs/zippin/lib/python3.6/site-packages/albumentations/core/utils.py", line 62, in preprocess
    data[data_name] = self.check_and_convert(data[data_name], rows, cols, direction="to")

      File "/home/user/anaconda3/envs/zippin/lib/python3.6/site-packages/albumentations/core/utils.py", line 70, in check_and_convert
    return self.convert_to_albumentations(data, rows, cols)

      File "/home/user/anaconda3/envs/zippin/lib/python3.6/site-packages/albumentations/augmentations/bbox_utils.py", line 51, in convert_to_albumentations
    return convert_bboxes_to_albumentations(data, self.params.format, rows, cols, check_validity=True)

      File "/home/user/anaconda3/envs/zippin/lib/python3.6/site-packages/albumentations/augmentations/bbox_utils.py", line 306, in convert_bboxes_to_albumentations
    return [convert_bbox_to_albumentations(bbox, source_format, rows, cols, check_validity) for bbox in bboxes]

      File "/home/user/anaconda3/envs/zippin/lib/python3.6/site-packages/albumentations/augmentations/bbox_utils.py", line 306, in <listcomp>
    return [convert_bbox_to_albumentations(bbox, source_format, rows, cols, check_validity) for bbox in bboxes]

      File "/home/user/anaconda3/envs/zippin/lib/python3.6/site-packages/albumentations/augmentations/bbox_utils.py", line 254, in convert_bbox_to_albumentations
    check_bbox(bbox)

      File "/home/user/anaconda3/envs/zippin/lib/python3.6/site-packages/albumentations/augmentations/bbox_utils.py", line 333, in check_bbox
    "to be in the range [0.0, 1.0], got {value}.".format(bbox=bbox, name=name, value=value)

    ValueError: Expected x_min for bbox (2.4285714285714284, 3.15625, 2.705357142857143, 3.2142857142857144, 0) to be in the range [0.0, 1.0], got 2.4285714285714284.
```

##  Behavior

What is happening here, 
there is a queue of images with different sizes, 
..
image1 (224,224,3)
...
image5 (720, 1080, 3)
...

I see sometimes image5 picks a shape of an image (224, 224, 3). Sometimes, it is the reason bbox coordinate go above 1.0. To overcome that I did resizing operations in tensorflow itself. And found out that `a.preprocess` in `composition.py` causes this issue.   
Interestingly, this behaviour is random and not specific to a particular sized images. 

## Environment
 - tensorflow version : 1.15.0
 - Albumentations version 1.0.2
 - Python version 3.6
 - OS : Linux 20.04
 - Installation: `conda install -c conda-forge albumentations`

**Comment by Dipet** [comment]
Are you sure that you are using the correct bboxes?
Could you please provide a minimal reproducible example or at least the shape of the image and bbxoxes you caught this error on?

**Comment by tensorAI** [comment]
I did little analysis of a code and found this. 

I changed `albumentations/albumentations/bbox_utils.py` line 253-256 this way. 
```
    ....
    bbox_final = (x_min, y_min, x_max, y_max) + tail

    if source_format != "yolo":
        bbox_final = normalize_bbox(bbox_final, rows, cols)
    if check_validity:
        try:
            check_bbox(bbox_final)
        except Exception as ex:
            print(f"Original Bbox: {bbox} Transformed Bbox : {bbox_final} cols: {cols} rows: {rows}")
            raise ValueError(f"Error: {ex}")
    return bbox_final
```
What I got is this, 
```
    Original Bbox: [670, 0, 842, 114, 0] Transformed Bbox : (2.9910714285714284, 0.0, 3.7589285714285716, 0.5089285714285714, 0) cols: 224 rows: 224
```
Now I found an coordinates belongs to an image with a size `"width": 1280, "height": 720 `

**Comment by Dipet** [comment]
Just print image shape and bboxes before sending them into albumentations pipeline.
It looks like you are using the wrong bboxes

**Comment by tensorAI** [comment]
Yeah there is an issue in the bbox coordinates. There are variations in the image size and bboxes are drawn at a particular resolution. So there was a mismatch and that was causing an issue. Closing this issue!
