### ISSUE TITLE
Albumentations for black and white drawing images like Quickdraw and Fashion MNIST datasets

### ISSUE THREAD

**Issue by cgnorthcutt** [albumentations-team/albumentations#966]
Thank you for this great package. I'm trying to use Albumentations for augmenting black and white drawing images like Quickdraw and Fashion MNIST datasets, but most of the examples seem focused on color images. What do you recommend?

**Comment by ternaus** [comment]
I would say that the majority, if not all of the augmentations will work for grayscale images if your treat them as RGB with 3 channels obtained from the grayscale image, say with `rgb_image = cv2.cvtColor(grayscale_image, cv2.COLOR_GRAY2RRGB)`

You may also check machine learning competitions at Kaggle where participants worked with the medical or other grayscale images.

P.S. I would guess, that you may get more detailed advice at Stackoverflow.
