### ISSUE TITLE
problem with pytorch_classification example

### ISSUE THREAD

**Issue by lollows** [albumentations-team/albumentations#967]
## 📚 Documentation

In the section-[Use Albumentations to define transformation functions for the train and validation datasets](https://albumentations.ai/docs/examples/pytorch_classification/#use-albumentations-to-define-transformation-functions-for-the-train-and-validation-datasets), the doc tells me 

> Next, we will normalize an image. We first divide all pixel values of an image by 255, so each pixel's value will lie in a range [0.0, 1.0]. Then we will subtract mean pixel values and divide values by the standard deviation.

Howerver, I don't see any operation related with `divide all pixel values of an image by 255`. And following the [Normalize doc](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.Normalize) , it's not true to say `we will subtract mean pixel values and divide values by the standard deviation.` Please fix this (noted in the following picture)
![image](https://user-images.githubusercontent.com/31273965/126128257-e116a061-713b-4893-838c-39277649bc41.png)

If I missing something, please let me konw. Thank you very much.

**Comment by Dipet** [comment]
String from docs:

> Normalization is applied by the formula: img = (img - mean * max_pixel_value) / (std * max_pixel_value)

Just open the parentheses:
`(img - mean * max_pixel_value) / (std * max_pixel_value) = (img / max_pixel_value - mean) / std`
