### ISSUE TITLE
Update Torchvision alternatives

### ISSUE THREAD

**Issue by Dipet** [albumentations-team/albumentations#969]
## 📚 Documentation

Need update torchvision alternatives, because now we have some transforms that work better than old.

 For example `ShiftScaleRotate` as an alternative for `RandomAffine`, but now we have `Affine` transform. #719

**Comment by creafz** [comment]
I have updated torchvision alternatives in https://github.com/albumentations-team/albumentations_examples/commit/24f3bf740ffda010dd5ceda743d4cb41899b7d22

![Screenshot 2021-08-19 at 18 25 24](https://user-images.githubusercontent.com/681989/130096342-47496c4a-f702-4755-885b-38477510f992.png)
