### ISSUE TITLE
PyTorch Example Inquiry

### ISSUE THREAD

**Issue by ankandrew** [albumentations-team/albumentations#970]
I have a small doubt in the _[PyTorch and Albumentations for image classification](https://github.com/albumentations-team/albumentations_examples/blob/master/notebooks/pytorch_classification.ipynb)_ example, in the [part](https://albumentations.ai/docs/examples/pytorch_classification/#use-albumentations-to-define-transformation-functions-for-the-train-and-validation-datasets):

> ...  **We first divide all pixel values of an image by 255, so each pixel's value will lie in a range [0.0, 1.0]**. ...

then comes the transform:

```python
train_transform = A.Compose(
    [
        A.SmallestMaxSize(max_size=160),
        A.ShiftScaleRotate(shift_limit=0.05, scale_limit=0.05, rotate_limit=15, p=0.5),
        A.RandomCrop(height=128, width=128),
        A.RGBShift(r_shift_limit=15, g_shift_limit=15, b_shift_limit=15, p=0.5),
        A.RandomBrightnessContrast(p=0.5),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ]
)
```

I am somehow confused, where are the pixels getting **scaled** between [0, 1] in this example? Was this referring to the old `ToTensor`?

**Comment by Dipet** [comment]
These operations work at [Normalize](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.Normalize) transform.

**Comment by ankandrew** [comment]
@Dipet When trying the transform I don't see the pixels in range [0, 1]. How could achieve this?

**Comment by Dipet** [comment]
Just read the entire text, not one sentence: 

> We first divide all pixel values of an image by 255, so each pixel's value will lie in a range [0.0, 1.0]. **Then we will subtract mean pixel values and divide values by the standard deviation.**

Normalization does these operations: 
```
img = (img - mean * max_pixel_value) / (std * max_pixel_value)
```

That's equivalent to this:
```
img = (img / max_pixel_value - mean) / std
```
