### ISSUE TITLE
transformation function that only divide the number by 255

### ISSUE THREAD

**Issue by wanburana** [albumentations-team/albumentations#973]
## 🐛 Bug

I can't seem to find the function that used to divided the pixel to [0, 1]. It seems like the original ToTensor (which is deprecated) will do that, but ToTensorV2 does not, I know that it is not a big deal and we can divide the pixel manually using 'img /= 255' but I wonder if there is a proper way to do it in transform pipeline

## Expected behavior

A proper function to turn 8 bit image (0-255) to (0-1)

**Comment by Dipet** [comment]
Just use [Normalize](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.Normalize) transform:
```python
A.Normalize(mean=0, std=1)
```
