### ISSUE TITLE
Docs builder can not work with enum types

### ISSUE THREAD

**Issue by Dipet** [albumentations-team/albumentations#977]
Docs builder shows an empty line for enum types.
As an example `compression_type` in [ImageCompression](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.ImageCompression)

**Comment by creafz** [comment]
Should be fixed in https://github.com/albumentations-team/albumentations.ai/commit/3deac49be141ccf2ead25badc68c53e53f1e74c3

![Screenshot 2021-08-18 at 19 38 06](https://user-images.githubusercontent.com/681989/129937518-03ed3b70-3038-478c-ada2-daccee6c80cc.png)
