### ISSUE TITLE
The docs for ElasticTransform are out of date

### ISSUE THREAD

**Issue by InCogNiTo124** [albumentations-team/albumentations#981]
## 📚 Documentation

The `ElasticTransform` references https://gist.github.com/erniejunior/601cdf56d2b424757de5

This is unavailable, and has become
https://gist.github.com/ernestum/601cdf56d2b424757de5

**Comment by InCogNiTo124** [comment]
Can I be assigned to this?

**Comment by BloodAxe** [comment]
Please feel free to contribute!

Пн, 9 авг. 2021 г. в 23:07, Marijan Smetko ***@***.***>:
