### ISSUE TITLE
how to convert the augmented bbox into xml file?

### ISSUE THREAD

**Issue by IamExperimenting** [albumentations-team/albumentations#982]
## 🐛 Bug

 Is there any method to convert the boxes to XML file format, after the image augmentation

## To Reproduce

1. load image
2. do transformation (eg: horizontal flip)
3. after flipping how to regenerate the XML file for the augmented data? for training the model?

## Environment

 - Albumentations version (e.g., 0.1.8): 1.0.0
 - Python version (e.g., 3.7): 3.7.6
 - OS (e.g., Linux): Linux
 - How you installed albumentations (`conda`, `pip`, source): pip
 - Any other relevant information:

**Comment by Dipet** [comment]
It is based on your xml data format. Library returns a common list of boxes in described format. You could write them by yourself to any format that you want using another libraries.
