### ISSUE TITLE
How to apply a transformation based on image size

### ISSUE THREAD

**Issue by NOxDriver** [albumentations-team/albumentations#989]
Hi

I'm running a pipeline of quite a few augmentations per image. 
One of the transformations I'm using is to random crop the image to 468x468. But, some of the images are not big enough, so an error is thrown.
 
Is there a simple way to apply that crop function only to images bigger than 468x468. 
Similar to albumentations.OneOf(), is there a albumentations.Try()? 

Then, if the image isn't big enough, or would throw an error, it moves onto the next one?

**Comment by Dipet** [comment]
No, we have no these functionality. Try to add `PadIfNeeded(468, 468, border_mode=cv2.BORDER_CONSTANT, value=0)` before copping, for example.
