### ISSUE TITLE
CoarseDropout throws NotImplementedError: Method apply_to_bbox is not implemented in class CoarseDropout

### ISSUE THREAD

**Issue by claudiu-decean** [albumentations-team/albumentations#995]
## 🐛 Bug

CoarseDropout throws NotImplementedError: Method apply_to_bbox is not implemented in class CoarseDropout

## To Reproduce

1. Add CoarseDropout augmentation to augmentation pipeline
2. Pass an image and bounding boxes to the augmentation pipeline

## Expected behavior

CoarseDropout should not modify bounding boxes, as Cutout augmentation does

## Environment

 - Albumentations version 0.5.2
 - Python version 3.7
 - OS Ubuntu 20.04
 - Albumentations  installed via`conda`

**Comment by raulsenaferreira** [comment]
The same happens for the method GridDropout

**Comment by Dipet** [comment]
This is because these transforms do not yet support bboxes  https://github.com/albumentations-team/albumentations#spatial-level-transforms

**Comment by claudiu-decean** [comment]
> This is because these transforms do not yet support bboxes https://github.com/albumentations-team/albumentations#spatial-level-transforms

Thank you for answering! For clarification, how would supporting bboxes look like? I imagine that CoarseDropout should keep the bboxes unmodified

**Comment by Dipet** [comment]
Hmm, this is a real problem, looks like we need to add flag to not modify bboxes and keypoints.
Just now you could try `Cutout`, it is deprecated, but it is change only the image

**Comment by BloodAxe** [comment]
I have implemented a partial solution which is:
- if the box entirely masked by dropout it is removed
- if only one side of box is affected by cutout mask, box is trimmed to reflect the actual non-masked area
- we can also think to have an overlap-based threshold when the 90%+ of box is masked out while it's bbox still remains the same and drop such instances as well

This should land as a PR in a next few days

**Comment by claudiu-decean** [comment]
> I have implemented a partial solution which is:
> 
>     * if the box entirely masked by dropout it is removed
> 
>     * if only one side of box is affected by cutout mask, box is trimmed to reflect the actual non-masked area
> 
>     * we can also think to have an overlap-based threshold when the 90%+ of box is masked out while it's bbox still remains the same and drop such instances as well
> 
> 
> This should land as a PR in a next few days

Thank you for detailing your plans!
An occlusion threshold would be useful.
Regarding the trimming feature:
-  How would it behave for the case when the visible part of the object is L shaped?
- If not already planned, please consider adding the possibility of deactivating this feature; for ex., in the case of an object detection model that uses anchors, the trimming may cause problems by creating bboxes that don't match any of the anchors

**Comment by berceanbogdan** [comment]
Any update on this?

**Comment by ternaus** [comment]
@claudiu-decean @raulsenaferreira @berceanbogdan 

Added in https://github.com/albumentations-team/albumentations/pull/1953

You can check in the UI tool at https://explore.albumentations.ai/transform/CoarseDropout
