### ISSUE TITLE
RandomFog bug

### ISSUE THREAD

**Issue by Inkln** [albumentations-team/albumentations#996]
https://github.com/albumentations-team/albumentations/blob/300ee99386ad27f482387047dac4f6dddff11ac2/albumentations/augmentations/transforms.py#L1168

In case width > height value of ( 3 * hw * width // sum(imshape) ) or of ( 3 * hw * height // sum(imshape) ) can be equal to zero, that leads to absolutly unlimited "while" cycle

**Comment by opeide** [comment]
I've also had this issue!

**Comment by ternaus** [comment]
Fixed: https://explore.albumentations.ai/transform/RandomFog
