### ISSUE TITLE
Cropping and multi-label classification

### ISSUE THREAD

**Issue by Mordokkai** [albumentations-team/albumentations#999]
Hi!

I used albumentations for multi-target segmentation before without problems. Now I'm moving to multi-label classification, but I don't get the result that I want. From what I understood of albumentations, when you do augmentations for classification, only the input image is modified and not the target vector. This may be a problem for certain transform like Cropping, that may remove a target class from the image, while keeping the target vector intact. Did I miss something or is it a normal behavior ?

**Comment by BloodAxe** [comment]
Yes, you assumptions are correct.
If you do cropping, some information can get lost and multi-label targets
may become invalid. There is no way to get correct labels using only
image-level targets as input.

Пн, 30 авг. 2021 г. в 19:09, Mordokkai ***@***.***>:

**Comment by Mordokkai** [comment]
Yeah you're right, it's just that in my case I also have segmentation masks so I know if some targets are removed or not. I didn't realize that my situation was very particular. 
Thanks !
